### ISSUE TITLE
TechDraw: Drawing auxiliary lines without reference points

### ISSUE THREAD

**Issue by Dirk-M** [FreeCAD/FreeCAD#18144] opened 2024-11-26 16:05 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When creating drawings, not only one object is shown on a sheet, but also several different ones.
These different components are separated from one another using a guide line on the drawing.
Currently, no free lines can be created on the drawing sheet.
As an "emergency solution", I am currently using the editor and underlined spaces. But that only works horizontally and cannot be the solution.
The creation of free straight guide lines with adjustable thickness and shape, both horizontally and vertically, would be a wish.
![image](https://github.com/user-attachments/assets/669802e1-f6e0-484c-a131-ef78ccb2458d)

### Full version info

```shell
OS: Windows 11 build 26100
Architecture: x86_64
Version: 1.1.0dev.39315 (Git) Conda
Build type: Release
Branch: main
Hash: 710542d121c2cabce05561591cfb00ef3b6e745c
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: German/Germany (de_DE)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * 3DfindIT 1.2.0
  * 3D_Printing_Tools
  * A2plus 0.4.68
  * boltsfc 2022.11.5
  * btl 0.9.9
  * CADExchanger
  * dxf-library
  * fasteners 0.5.30
  * Help 1.0.3
  * InventorLoader 1.4.0
  * sheetmetal 0.5.5
  * symbols_library
```

### Subproject(s) affected?

TechDraw

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment] 2024-11-26 17:54
Duplicate of https://github.com/FreeCAD/FreeCAD/issues/5693

**Closed by maxwxyz** 2024-11-26 17:54 UTC
Labels: Status: Needs confirmation, Status: Needs triage
