### ISSUE TITLE
[Problem] Feature or Bug? Worksheet Toolbars not context switching

### ISSUE THREAD

**Issue by iAmVaeVictus** [FreeCAD/FreeCAD#12514] opened 2024-02-19 22:16 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Toolbars don't context switch when changing tiled windows. 
1. Open spreadsheet
2. Open Sketch
3. Tile windows
4. Click spreadsheet - tool bars and worksheet selection in dropdown do not change

### Full version info

```shell
OS: macOS 13.6.4
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35994 (Git)
Build type: Release
Branch: main
Hash: 69097667df47b2cc86d8688d2dbb545319e33e68
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: C/Default (C)
```

### Subproject(s) affected?

None

### Anything else?

Not clear if this is a feature but it seems to slow down my work as I have to keep changing to spreadsheet tools when working in the spreadsheet. Seems like context switching to the active windows would make sense, then allowing us to change the context in the dropdown if needed. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment] 2024-02-20 07:14
Not sure if this is a desired behavior. Currently no toolbars switch if you change documents.

**Comment by maxwxyz** [comment] 2024-02-20 07:16
@obelisk79 is this a wanted feature or not in line with UX?

**Comment by obelisk79** [comment] 2024-02-20 09:10
This really highlights a limitation of the workbench paradigm. I'm not entirely sure initially what the behavior should be. I'll have to engage with the rest of the DWG and have a conversation about it.

**Comment by maxwxyz** [comment] 2024-06-13 08:54
I'll close this issue for now as it works as intended and more objects now enable a WB / toolbar switch by double clicking on the tree icon (e.g. Spreadsheet, TechDraw Page, PartDesign Body, FEM,...)

**Closed by maxwxyz** 2024-06-13 08:54 UTC
Labels: UI/UX, Feature, Missing: feedback
