### ISSUE TITLE
Preferences need cosmetic fix

### ISSUE THREAD

**Issue by Kuzma30** [FreeCAD/FreeCAD#14760] opened 2024-06-18 09:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

![Знімок екрана з 2024-06-18 09-43-21](https://github.com/FreeCAD/FreeCAD/assets/1382812/2cff10d1-3818-4a5e-9beb-b0da68ece46a)
![Знімок екрана з 2024-06-18 09-42-03](https://github.com/FreeCAD/FreeCAD/assets/1382812/b6dba111-f871-4286-9d10-476b9ea22afd)

### Full version info

```shell
latest dev
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by furgo16** [comment] 2024-06-18 11:32
@Kuzma30 could you include your full version info? I believe you are using [OpenTheme Light](https://github.com/obelisk79/OpenTheme), which is a 3rd party theme. The built-in Classic theme looks like this:

![image](https://github.com/FreeCAD/FreeCAD/assets/148809153/a5903a10-d441-41b0-b8d8-8fc39a0e1888)

If that is the case, you might need to file the bug against the OpenTheme project.

I have also noticed the horizontal scrollbar on that screen. It seems it's there as the default width of the window is not wide enough to contain all widgets.

**Comment by furgo16** [comment] 2024-06-18 11:36
The invalid height mentioned on this issue is, I believe https://github.com/obelisk79/OpenTheme/issues/60. It should have been fixed by now, but I've not checked, as I no longer use OpenTheme.

**Comment by Kuzma30** [comment] 2024-06-18 13:37
Same on Classic
![Знімок екрана з 2024-06-18 13-34-50](https://github.com/FreeCAD/FreeCAD/assets/1382812/088911e4-68ad-4a79-85d5-f49b681db326)

```
OS: Ubuntu 24.04 LTS (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37817 (Git)
Build type: Debug
Branch: master
Hash: 4a11652263c8635da0be55e41c0a5a9d04767dcf
Python 3.12.3, Qt 5.15.13, Coin 4.0.2, Vtk 9.1.0, OCC 7.8.2.dev
Locale: Ukrainian/Ukraine (uk_UA)
Installed mods: 
  * sheetmetal 0.4.18
  * ose-piping
  * dodo 1.0.1
  * fasteners 0.5.22
  * FeedsAndSpeeds 0.5.0
  * ose-3d-printer-workbench 0.1.0
  * OpenTheme 2024.5.16
  * Assembly3 0.12.2
  * addFC 0.3.1
  * ose-workbench-core

```

**Comment by furgo16** [comment] 2024-06-18 17:08
Of all the issues reported, I can only reproduce the one about the horizontal scrollbar:

![image](https://github.com/FreeCAD/FreeCAD/assets/148809153/7eb94c84-08f7-4fb6-ab34-4011e8143f01)

```
OS: Ubuntu 22.04.4 LTS (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37821 (Git)
Build type: Unknown
Branch: main
Hash: 1ccb74f141ec4d1276b39d18fb99f276d09e007e
Python 3.10.12, Qt 5.15.3, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
```
Have you tried with clean configuration files? I've found out that once you've had the OpenTheme applied, switching back to Classic does not reset all changes: https://forum.freecad.org/viewtopic.php?t=87293

**Comment by Kuzma30** [comment] 2024-06-18 17:15
Just remove all config files and get same error with height.
I have Display with 1920*1080 resolutions.

**Comment by maxwxyz** [comment] 2024-06-18 19:10
@kadet1090 FYI

**Comment by kadet1090** [comment] 2024-06-26 22:44
@maxwxyz can you assign me? Also this should be considered a bug

**Comment by maxwxyz** [comment] 2024-07-30 18:46
@kadet, the scrollbar on the preferences is still there, so seems not to be fixed.
@Kuzma30 could you confirm?

**Comment by kadet1090** [comment] 2024-07-30 18:53
I am no longer able to reproduce - so I'll need more info.

**Comment by maxwxyz** [comment] 2024-11-08 07:10
closing for no feedback, I cannot reproduce either.

**Closed by maxwxyz** 2024-11-08 07:10 UTC
Labels: Type: Bug, Mod: Core, Topic: User Interface, Status: Needs feedback, Topic: Preferences
