### ISSUE TITLE
Can't use Measure Tool in a file containing linked objects only

### ISSUE THREAD

**Issue by chronos1970** [FreeCAD/FreeCAD#18071] opened 2024-11-22 14:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Before v1.0 I used to create a file with links of bodies from different files as a simple assembly. The old measurement tool used to work there.

To reproduce:
1. Create file1 with two bodies in PartDesign
2. Create file2
3. Link file1's bodies to file2
4. Observe how the Measure Tool is grayed out only in file2

I have attached two simple files that demonstrate the issue

### Full version info

```shell
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.0.0.39109 (Git) Conda
Build type: Release
Branch: (HEAD detached at 1.0.0)
Hash: 2fcc5317fe3aee96ca73475986a577719fc78e20
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Fusion
```

### Subproject(s) affected?

PartDesign

### Anything else?

[Test.zip](https://github.com/user-attachments/files/17871214/Test.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment] 2024-11-22 14:14
Duplicate of https://github.com/FreeCAD/FreeCAD/issues/14332

**Closed by maxwxyz** 2024-11-22 14:14 UTC
Labels: Status: Needs confirmation, Status: Needs triage
