### ISSUE TITLE
Changing a part feature causes Assembly references and constraints to change

### ISSUE THREAD

**Issue by nallyn1972** [FreeCAD/FreeCAD#18023] opened 2024-11-20 23:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

There is a part with a number of features  that is added to an assembly. If the part is modified, the references change. E.g. if a part is constrained using a cylindrical joint and another feature is added to the base part, then the references for the constraints is modified and the assembly breaks.

![image](https://github.com/user-attachments/assets/d84ededc-4872-4c05-821e-1561c9f78bec)

Remove one boss on the base (not associated with the assembly references) and the assembly breaks:
![image](https://github.com/user-attachments/assets/577f7e24-d93d-4f95-8cc3-c29a7ec8b5c5)

Note that the reference faces are still the same but the names now have a ? in them. Before: base.Face7, after: base.?Face7

### Full version info

```shell
OS: Windows 11 build 22635
Architecture: x86_64
Version: 1.0.0.39109 (Git) Conda
Build type: Release
Branch: (HEAD detached at 1.0.0)
Hash: 2fcc5317fe3aee96ca73475986a577719fc78e20
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: English/Canada (en_CA)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Fusion
Installed mods: 
  * A2plus 0.4.65
  * Assembly3 0.12.2
  * Assembly4 0.50.15
  * fasteners 0.5.26
  * freecad.gears 1.2.0
  * Help 1.0.3
  * kicadStepUpMod 11.2.7
  * parts_library
```

### Subproject(s) affected?

Assembly

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment] 2024-11-21 08:09
Duplicate of https://github.com/FreeCAD/FreeCAD/issues/17776

**Closed by maxwxyz** 2024-11-21 08:09 UTC
Labels: Status: Needs triage
