### ISSUE TITLE
[macOS] Editing item by double-clicking opens other project window

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5849] opened 2022-02-07 17:53 UTC
Issue imported from https://tracker.freecad.org/view.php?id=3740

* **Reporter:** HardyW
* **Date submitted:** 12/18/2018
* **FreeCAD version:** 0.17
* **Category:** Bug
* **Status:** confirmed
* **Tags:** 

# Original report text

When editing an item by double clicking onto the item in the tree structure always the first project window, respectively the start page, is activated.

# Steps to reproduce

Open FreeCAD and create a new document without closing the start page. Switch to draft mode and draw something. Finish drawing.
Double click onto an item in the element tree to start editing. The start page is being activated. A mouse click on the document page (to switch pages) reveals that the "double clicked" element is in edit mode.

# Other bug information

* **Priority:** normal
* **Severity:** tweak
* **Category:** Bug
* **OS: macOS Mojave**
* **Platform:** iMac
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by Kunda1 2018-12-19 09:33
~12306

---

### Comment by chrisb 2018-12-19 09:58
With the setup as described above I have drawn a line. Don't know what "finish editing" means in the error report.
Double clicking enters editing mode as it should.

OP: please try on a non retina display and don't flood the bug tracker without discussions in the forum.

OS: Mac OS X
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.17.13541 (Git)
Build type: Release
Branch: releases/FreeCAD-0-17
Hash: 9948ee4f1570df9216862a79705afb367b2c6ffb
Python version: 2.7.14
Qt version: 5.10.1
Coin version: 4.0.0a
OCC version: 7.2.0
Locale: German/Germany (de_DE)

---

### Comment by HardyW 2018-12-19 21:34
This bug is independent from the type of display. It occurs on either display (checked on a non Retina display again and before submitting this bug).

PS: "Finish editing" means that a line is drawn (at the beginning the I observed the bug by drawing a polyline / dwire). I still had this example in my mind.
PPS: Which forum do you like to use for the discussion? "Open discussion"?

OS: Mac OS X
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.17.13541 (Git)
Build type: Release
Branch: releases/FreeCAD-0-17
Hash: 9948ee4f1570df9216862a79705afb367b2c6ffb
Python version: 2.7.14
Qt version: 5.10.1
Coin version: 4.0.0a
OCC version: 7.2.0
Locale: English/Germany (en_DE)

---

### Comment by Kunda1 2018-12-24 12:35
[quote=HardyW]PPS: Which forum do you like to use for the discussion? "Open discussion"?
[/quote]
Yes, please.

---

### Comment by Kunda1 2019-01-04 18:39
HardyW please link the forum thread in to this ticket. thank you

---

### Comment by Kunda1 2019-02-10 16:05
Forum discussion thread: https://forum.freecadweb.org/viewtopic.php?f=8&t=34125

**Comment by luzpaz** [comment] 2022-04-11 04:11
Closing as @PLChris couldn't reproduce

**Closed by luzpaz** 2022-04-11 04:11 UTC
Labels: Bug, core, OS: macOS
