### ISSUE TITLE
1.0.0 RC2 crashes (segmentation fault) when clicking an axis

### ISSUE THREAD

**Issue by Kashouryo** [FreeCAD/FreeCAD#17391] opened 2024-10-21 18:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When clicking an axis in 1.0.0 RC2 it crashes the entire editor instantly.

1. Launch 1.0.0 RC2
2. Create a new parametric part
3. Expand `Origin`
4. Click on `X-axis`
5. Crash

```
Program received signal SIGSEGV, Segmentation fault.
#0  /lib/x86_64-linux-gnu/libc.so.6(+0x45320) [0x73cc63845320]
#1  0x73cc2e151fc6 in BRep_Tool::Curve(TopoDS_Edge const&, TopLoc_Location&, double&, double&) from /tmp/.mount_FreeCAzMHVA4/usr/lib/./libTKBRep.so.7.7+0x26
#2  0x73cc2e163b21 in BRepAdaptor_Curve::Initialize(TopoDS_Edge const&) from /tmp/.mount_FreeCAzMHVA4/usr/lib/./libTKBRep.so.7.7+0xd1
#3  0x73cc2e164d35 in BRepAdaptor_Curve::BRepAdaptor_Curve(TopoDS_Edge const&) from /tmp/.mount_FreeCAzMHVA4/usr/lib/./libTKBRep.so.7.7+0xd5
#4  0x73cc47ed5dce in Measure::Measurement::length() const from /tmp/.mount_FreeCAzMHVA4/usr/lib/Measure.so+0x15e
#5  0x73cc38cd0de7 in MeasureGui::QuickMeasure::printResult() from /tmp/.mount_FreeCAzMHVA4/usr/lib/MeasureGui.so+0x947
#6  0x73cc38cd19ee in MeasureGui::QuickMeasure::processSelection() from /tmp/.mount_FreeCAzMHVA4/usr/lib/MeasureGui.so+0x1e
#7  /tmp/.mount_FreeCAzMHVA4/usr/bin/../lib/libQt5Core.so.5(+0x2eb6f2) [0x73cc63eeb6f2]
#8  0x73cc63eef34a in QTimer::timeout(QTimer::QPrivateSignal) from /tmp/.mount_FreeCAzMHVA4/usr/bin/../lib/libQt5Core.so.5+0x2a
#9  0x73cc63ee064d in QObject::event(QEvent*) from /tmp/.mount_FreeCAzMHVA4/usr/bin/../lib/libQt5Core.so.5+0x7d
#10  0x73cc64d703ae in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /tmp/.mount_FreeCAzMHVA4/usr/bin/../lib/libQt5Widgets.so.5+0x7e
#11  0x73cc66b69079 in Gui::GUIApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAzMHVA4/usr/bin/../lib/libFreeCADGui.so+0x99
#12  0x73cc63eb6b28 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /tmp/.mount_FreeCAzMHVA4/usr/bin/../lib/libQt5Core.so.5+0x108
#13  0x73cc63f09f51 in QTimerInfoList::activateTimers() from /tmp/.mount_FreeCAzMHVA4/usr/bin/../lib/libQt5Core.so.5+0x381
#14  /tmp/.mount_FreeCAzMHVA4/usr/bin/../lib/libQt5Core.so.5(+0x30a724) [0x73cc63f0a724]
#15  /tmp/.mount_FreeCAzMHVA4/usr/bin/../lib/./libglib-2.0.so.0(+0x5bad7) [0x73cc62510ad7]
#16  /tmp/.mount_FreeCAzMHVA4/usr/bin/../lib/./libglib-2.0.so.0(+0x5eac7) [0x73cc62513ac7]
#17  /tmp/.mount_FreeCAzMHVA4/usr/bin/../lib/./libglib-2.0.so.0(g_main_context_iteration+0x2e) [0x73cc625140ce]
#18  0x73cc63f0aa36 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCAzMHVA4/usr/bin/../lib/libQt5Core.so.5+0x66
#19  0x73cc63eb570b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCAzMHVA4/usr/bin/../lib/libQt5Core.so.5+0x11b
#20  0x73cc63ebd212 in QCoreApplication::exec() from /tmp/.mount_FreeCAzMHVA4/usr/bin/../lib/libQt5Core.so.5+0x82
#21  0x73cc66ac84e1 in Gui::Application::runApplication() from /tmp/.mount_FreeCAzMHVA4/usr/bin/../lib/libFreeCADGui.so+0xa41
#22  /tmp/.mount_FreeCAzMHVA4/usr/bin/freecad(+0x789f) [0x630c721a089f]
#23  /lib/x86_64-linux-gnu/libc.so.6(+0x2a1ca) [0x73cc6382a1ca]
#24  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x8b) [0x73cc6382a28b]
#25  /tmp/.mount_FreeCAzMHVA4/usr/bin/freecad(+0x7c12) [0x630c721a0c12]
```

### Full version info

```shell
OS: Linux Mint 21.2 (X-Cinnamon/cinnamon) <-- Actual version 22, upgraded from 21.2
Word size of FreeCAD: 64-bit
Version: 1.0.0RC2.38806 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 1.0rc2)
Hash: 3d63fc6c2f665a8d5e6468845a419bcac80756c7
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: unset/unset/Qt default
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment] 2024-10-21 19:31
Duplicate of https://github.com/FreeCAD/FreeCAD/issues/17355

**Closed by maxwxyz** 2024-10-21 19:31 UTC
Labels: Status: Needs triage
