### ISSUE TITLE
Sketcher: cannot use reference constraints in other constraints

### ISSUE THREAD

**Issue by alfrix** [FreeCAD/FreeCAD#16592] opened 2024-09-16 21:59 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

in versions 0.22+ it's no longer possible to use a reference constraint as the value of another constraint in the same sketch, 
this seems to be a regression to me unless it's expected but it should at least be added into the known limitations

![Screenshot_20240916_180529](https://github.com/user-attachments/assets/6ed685dc-a75e-4028-922f-59cb16873a84)

![Screenshot_20240916_180646](https://github.com/user-attachments/assets/6bee0d02-bacf-49c7-9ffb-3095a10c8ecc)

![Screenshot_20240916_180749](https://github.com/user-attachments/assets/613a1672-3499-495c-afbd-660cca339a94)

i just realized this while doing a frame for a monitor, and i wanted the height to be calculated from the width, but the width was a reference.
i can workaround this limitation without issues, but i wanted to raise the attention to at least document this change somewhere if it's known

### Full version info

```shell
OS: Debian GNU/Linux trixie/sid (KDE/plasmawayland)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38738 (Git)
Build type: Unknown
Branch: main
Hash: 5fb2361d63a76920687d19418006c4bd18a809af
Python 3.12.6, Qt 5.15.13, Coin 4.0.2, Vtk , OCC 7.8.1
Locale: Spanish/Argentina (es_AR)
Stylesheet/Theme/QtStyle: unset/FreeCAD Dark/Fusion
Installed mods: 
  * CurvedShapes 1.0.9
```

### Subproject(s) affected?

Sketcher

### Anything else?

for reference this already happened before:
https://forum.freecad.org/viewtopic.php?t=24574

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kaiwas** [comment] 2024-09-17 05:26
I confirm. This is a clear regression.
Sometimes you need to make a measurement using an auxiliary constraint and use this number to calculate some element. This is an important opportunity.

**Comment by FlachyJoe** [comment] 2024-09-17 11:11
Duplicate #12655
It's seems a claimed feature added by #11716

**Comment by FlachyJoe** [comment] 2024-09-17 14:02
If really needed, references can still be hidden for circular detector with the `href()` function.

**Comment by kaiwas** [comment] 2024-09-17 14:03
I don't know why exactly the cyclic dependency is not solvable in Freakada. But for example, "web engines" have the ability to receive information in two directions.
A parent can receive data from a child, and a child can receive data from a parent.

Perhaps this is really difficult to implement, but if it were done, it would greatly expand the possibilities.
For example, it would be possible to specify "Take the height from the parent" in the child (without specifying its specific parent name). And the parameter would be received.

The same is true for this example - the reference as data exists, and it would be useful to be able to use this data to calculate something, but it seems that now there is no such possibility.

If we proceed from logical reflections on this limitation, then perhaps it would be possible to create some "data layer" that would process information (a kind of buffer not subject to the problem of cyclic dependency) and would give this information upon request.

**Comment by FlachyJoe** [comment] 2024-09-17 14:18
@kaiwas the problem is with logic:
_Length = Height + 10
Height = Length + 20_
Can you tell me _Height_ and _Length_ values?


By the way, in FreeCAD you can do this:
![image](https://github.com/user-attachments/assets/9c5c0015-6027-4096-ae80-2d5be17f62a8)

The expression value is calculated only at recompute.

**Comment by maxwxyz** [comment] 2024-09-17 14:40
I'm closing this in favor of https://github.com/FreeCAD/FreeCAD/issues/12655

**Closed by maxwxyz** 2024-09-17 14:40 UTC
Labels: Mod: Sketcher, Blocker, Type: Regression

**Comment by kaiwas** [comment] 2024-09-17 15:03
hahaha.
this is a great solution to the problem - just take away the ability to do something (even though it was possible before) without an alternative.
you'll forgive me, of course, but this is ridiculous.

**Comment by kaiwas** [comment] 2024-09-17 16:58
> the problem is with logic: _Length = Height + 10 Height = Length + 20_ Can you tell me _Height_ and _Length_ values?
> 
> By the way, in FreeCAD you can do this:

In your example there are two unknowns. And it is very easy to identify such a case.

But if instead of length (or height) there is a specific number entered by the user - the example turns into a regular ratio of sides (this is used everywhere in geometry).

Pythagoras would turn over in his grave from this discussion.

**Comment by frank-trampe** [comment] 2024-09-17 18:25
@Syres916, breaking the feature was a very clumsy way to solve the circular dependency problem. There are a lot of other ways to do it.

**Comment by frank-trampe** [comment] 2024-09-17 18:35
@bgbsww, Wikipedia uses the following definition of a regression.

[A software regression](https://en.wikipedia.org/wiki/Software_regression) is a type of [software bug](https://en.wikipedia.org/wiki/Software_bug) where a feature that has worked before stops working.

This feature (intra-sketch reference constraints) worked before and now does not work. That is a regression. It is no solace to people who built their models on that feature that there is a piece of documentation somewhere that suggests that the feature ought not to have existed in the first place. I am now running my own patched fork of FreeCAD to support a project that used the feature, and I cannot benefit from new features in FreeCAD without patching each new set of binaries.

I have proposed a simple fix in #12655 that safely allows intra-sketch references and even stable circular references by checking for stable convergence of the sketch solution. Look at it and tell me what you think.

**Comment by bgbsww** [comment] 2024-09-17 18:40
I am done with this issue, please stop pinging me.  If you want to submit a fix, great.  I won't be working on it.

**Comment by kaiwas** [comment] 2024-09-18 12:03
> By the way, in FreeCAD you can do this:

I have a question unrelated to this topic.
And was the "length" inscription visible in the picture made in an image editor? Or did Frecad add the ability to display names in a sketch? )
