### ISSUE TITLE
PartDesign: Helix breaks over certain length

### ISSUE THREAD

**Issue by chopsywa** [FreeCAD/FreeCAD#14309] opened 2024-05-27 09:04 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I create a cylinder. Then I sketch a thread profile alongside the cylinder. When I create an additive helix, it works as expected, but only up to an arbitrary length. The diagram below shows a drawing of a bolt. The extruded shaft section is 5.5mm x 25mm. The thread is 0.8mm high at the connection point and 0.2mm at the outer edge. The pitch is 1mm. 
The first picture is setting the helix to 22mm. At this point it is perfect. The next picture is when I set it to 23mm and it fails on the regeneration.
![image](https://github.com/FreeCAD/FreeCAD/assets/109642777/94313ad0-edf3-466d-b3ec-8b671c4f0a07)
![image](https://github.com/FreeCAD/FreeCAD/assets/109642777/9e988baa-a91f-425f-a274-a8f843f0ed8a)

### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37464 (Git)
Build type: Release
Branch: main
Hash: db48a78d5a545bb21a5c80a9fa4b4c983fbbe951
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/Australia (en_AU)
Installed mods: 
  * Curves.backup1706353084.2536438 0.6.13
  * OpenDark 2024.3.13
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment] 2024-05-27 09:32
Could this be related: https://github.com/FreeCAD/FreeCAD/issues/12185https://github.com/FreeCAD/FreeCAD/issues/12185 
Does it work in the stable 0.21.2 version and can you provide a demo file?

**Comment by chopsywa** [comment] 2024-05-27 09:56
Perhaps it's related to 12185, but definitely a different scenario.
It works fine in 21.2. In both versions it is slow, but faster in the production version. Also, in dev version, no additional operations can be done on the helix, whereas they work fine on the production version. I also noticed that the direction is back to front in the dev version. Finally, after opening it in the production version it opens fine in the dev, but as soon as you do any operation, it breaks. How can I upload the test model? Github only seems to accept images.

**Comment by maxwxyz** [comment] 2024-05-27 10:43
@FlachyJoe didn't you work on helix? There seems to be a regression here.

**Comment by FlachyJoe** [comment] 2024-05-27 11:47
@maxwxyz I have a fix in progress: #13205 but I'm not sure it changes anything about this problem.
I'll take a look.

**Comment by FlachyJoe** [comment] 2024-05-27 12:04
@chopsywa You can send a zip (or simply add `.zip` after the`.FCStd` extension).

**Comment by chopsywa** [comment] 2024-05-27 12:16
Oh, OK. I was sure I tried that on another issue earlier. File is now attached. Opens in both production and dev, but you will see how it all goes pear shaped in dev if you try to do anything with it.

[testthread.zip](https://github.com/FreeCAD/FreeCAD/files/15455712/testthread.zip)

**Comment by bgbsww** [comment] 2024-08-25 02:31
Oh my, that's interesting:
![image](https://github.com/user-attachments/assets/531e17df-934f-42ce-9bea-b4511327b03d)

Just a really tall cylinder and a lot of additive helix turns, and in three places, it doesn't render correctly.  I dunno if the model behind it is broken.  The cylinder and the helix interfere with each other.

When I reduce the radius of the cylinder so that it doesn't touch the helix, all apparent problems go away.

**Comment by FlachyJoe** [comment] 2024-08-25 09:49
@bgbsww could you share a file please?

**Comment by bgbsww** [comment] 2024-08-25 13:32
I should have saved that test file!  I'm a bad bug reported.  I thought it was a common occurrence, but it's a little harder to replicate.  As far as I can tell, you need:
1) A self intersecting helix
2) A cylinder that intersects the helix
3) A pitch and height that stress the computer ( >10 second recompute delay)

Along the way to recreating this, when I made a self intersecting helix, I found I could not make a cylinder without "09:08:11  <Part> ViewProviderExt.cpp(1299): Cannot compute Inventor representation for the shape of Unnamed#Body: Bnd_Box is void" error

That's BadHelix1.FCStd.  BadHelix2.FCStd just shows a glimpse of the rendering problem if you look at the very top, you can see the cylinder between the first helix coils, but (correctly) cannot see it at all lower down.

[BadHelixes.zip](https://github.com/user-attachments/files/16740419/BadHelixes.zip)

**Comment by maxwxyz** [comment] 2024-08-26 08:00
@FlachyJoe @bgbsww this wasn't fixed by https://github.com/FreeCAD/FreeCAD/pull/16009?

**Comment by bgbsww** [comment] 2024-08-26 14:07
I don't know; I just observed some strangeness.  I'll try again in a bit.

**Comment by bgbsww** [comment] 2024-09-16 18:26
So, those pictures don't appear to match the attached file when I open this in 1.0pre.

There is an additional pocket at the end of the tree, with a diameter of 8.5 which is way too big; if you drop it to 4mm the model starts working.

At 22 and 23 mm the thread stops short of meeting the bolt head, but still work fine:
![image](https://github.com/user-attachments/assets/f50649e2-9c01-4a3d-b594-c0aec5b570d3)

Is this still causing a problem, and if so, can we see either pictures matching the file or a file that matches the pictures?

Note that the second picture is consistent with having a way oversize pocket attached at the TestPlaneAlternativePocketSketchProfile Datum plane that is cutting away the screw, threads and all in that region.

**Comment by chopsywa** [comment] 2024-09-17 13:00
I can't check until next week as I am away at present. I have build 38459 on my Macbook at present (not my usual computer) and I get similar, but not same errors. When I set the ThreadHelix as tip, all I get is a thread. The bolt disappears. I removed the pocket altogether so as not to interfere which makes no difference. If I try to reduce the length of the thread from 25mm, i get an error ThreadHelix: removing splitter failed.

**Comment by chopsywa** [comment] 2024-09-17 13:41
UPDATE: I updated my Macbook to the latest weekly build.
OS: macOS 14.6.1
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38768 (Git)
Build type: Release
Branch: main
Hash: 758674d40be45e365f4148fb2a5ea6bd6f93bc74
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C)
Stylesheet/Theme/QtStyle: OpenDark.qss/OpenDark/Qt default
Installed mods: 
  * OpenTheme 2024.8.10

Different issue again. Now I can draw the thread full length, so long as it does not touch the head of the bold. I.E. I can do it 24.9mm and it works. If I try to go to 25mm, touching the bold head I get a "Threadhelix:bnd box is void" error.

I then try to pocket the top. It fails with the same error. "Pocket: bnd box is void". I also tried to pad the "TestPocketSketch" and I got the same error "Pad: bnd box is void".

Hope this helps.

**Comment by bgbsww** [comment] 2024-09-17 15:00
I think the choices here are to move back to a single helix approach to this ala Part; presumably there were some bugs with that, or to live with this set of failure modes for objects with matching edges that aren't actually matching in OpenCascade.

I would guess that fewer helixes ( fewer objects ) would reduce the likelihood of hitting this failure without completely eliminating it.  I admit that I can't follow the history of the helix mess any more, it confuses me.

**Comment by chopsywa** [comment] 2024-09-21 04:23
Running latest build 387984

Helixes are working better and as @bgbsww stated, you can run a helix along a cylinder and it will work up to a point near the end, or a distance past it, but it will fail at the point of intersection. Another issue I have found is that working with the body that has a helix is very difficult. In the attached file, I have created a bolt. I then created a cap to clean the end of the bolt. I cannot boolean the two bodies. In my case I would want to use 
the  "cleanTop" body as the cut tool, but I can't even union the parts. 
[testthread.zip](https://github.com/user-attachments/files/17082807/testthread.zip)

**Comment by bgbsww** [comment] 2024-09-21 13:10
Same solution category:  push the bolt shaft up from 5.5 to 5.52mm to force enough interference, and all starts working fine.  We might want to add some documentation about this recommendation, if my wiki edit request ever gets looked at I'd add this to the page.  (Gentle nudge @yorikvanhavre )

**Comment by chennes** [comment] 2024-09-25 20:36
I'm going to close this as "not going to fix" because we're really just picking which edge cases we want to fail at this point (and that decision has changed in 1.0). I'll get @bgbsww wiki edit permissions so we can get this documented appropriately.

**Closed by chennes** 2024-09-25 20:36 UTC
Labels: Type: Bug, Mod: Part Design, Type: Regression, Topic: Helix
