### ISSUE TITLE
[Feature Request][Part Design WB] Merge the "Internal Geometry" feature of RealThunder's Link Branch if and when multiple solids in Part Design becomes the standard

### ISSUE THREAD

**Issue by RaphaelNunes10** [FreeCAD/FreeCAD#14281] opened 2024-05-25 19:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

In [RealThunder's Link Branch fork](https://github.com/realthunder/FreeCAD) there's this feature called "Internal Geometry" in the form of a property section with a property called "Make Internals" that, when set to "true", automatically detects and divides a sketch with many closed shapes (intersecting or not) into selectable zones that allow for multiple operations per sketch:

![image](https://github.com/FreeCAD/FreeCAD/assets/43423924/c261e6e7-c89b-48a9-b6d7-3c4bbb1d5dbf)

I always thought the Part Design workbench was meant for creating a single solid per body object, so this feature would break the paradigm. But since this might change with the recent inclusion of the experimental setting for allowing multiple solids per body, this feature could turn out to be really useful.

### Full version info

```shell
Last main Freecad version used:

OS: Windows 11 build 22635
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37464 (Git)
Build type: Release
Branch: main
Hash: db48a78d5a545bb21a5c80a9fa4b4c983fbbe951
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US) [ OS: Portuguese/Brazil (pt_BR) ]
Installed mods: 
  * fasteners 0.5.20
  * freecad.gears 1.2.0
  * Glass
  * Ondsel-Lens 2024.4.16.01
  * OpenTheme 2024.4.20
  * ThreadProfile 1.89.0

Last RealtThunder's Freecad Link Branch version used:

OS: Windows 11 build 22635
Word size of FreeCAD: 64-bit
Version: 2024.408.0.14555 (Git shallow)
Build type: Release
Branch: (HEAD detached at 20240407stable)
Hash: 973e4821bcd19a5a1af9ae3e1d2ed961aad0a8ab
Python 3.11.8, Qt 5.15.6, Coin 4.0.1, Vtk 9.2.5, OCC 7.7.1
Locale: English/United States (en_US) [ OS: Portuguese/Brazil (pt_BR) ]
Installed mods: 
  * fasteners 0.5.20
  * freecad.gears 1.2.0
  * Glass
  * Ondsel-Lens 2024.4.16.01
  * OpenTheme 2024.4.20
  * ThreadProfile 1.89.0
```

### Subproject(s) affected?

PartDesign

### Anything else?

Discussions can be found in these Reddit posts, where people seem to show some interest in the topic:

https://www.reddit.com/r/FreeCAD/comments/1bvyac9/found_out_about_the_internal_geometry_properties/

https://www.reddit.com/r/FreeCAD/comments/1czrh5a/whats_new_in_freecad_multiple_solids_in/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment] 2024-05-26 06:27
Duplicate of https://github.com/FreeCAD/FreeCAD/issues/12820

**Closed by maxwxyz** 2024-05-26 06:27 UTC
