### ISSUE TITLE
Bugs in 0.21.2

### ISSUE THREAD

**Issue by colinconey** [FreeCAD/FreeCAD#17858] opened 2024-11-14 14:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

It dose not work all the time

### Full version info

```shell
When I'm following some one on you tube using all the same numbers as they do, My work dose not come out the same. and some times trying to put in some measurement manually it dose not work and I have to start all over again. I hope that you can help Colin
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment] 2024-11-14 16:16
Please check out how to [report issues](https://github.com/FreeCAD/FreeCAD?tab=readme-ov-file#reporting-issues) which could help us diagnose and fix it.

- Test if the issue is still present in the dev version: https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds or 1.0 RC4
- add full [About](https://wiki.freecad.org/About) info to the issue (`Help > About FreeCAD > Copy to clipboard`).
- share an example file with the issue present. You can upload a zipped file to the original issue.
- add steps to reproduce the issue. Ideally, provide a macro of the issue: `Macro > Macro recording...` and repeat all steps until the issue occurs.

I'll close this issue as the old measurement tool is not available in 1.0

**Closed by maxwxyz** 2024-11-14 16:16 UTC
Labels: Status: Needs triage
