### ISSUE TITLE
[Issue] Bold text is somewhat blurry/pixelated (Qt related)

### ISSUE THREAD

**Issue by K4LCIFER** [FreeCAD/FreeCAD#8250] opened 2023-01-24 01:04 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
[code]
OS: KDE Flatpak runtime (GNOME/gnome)
Word size of FreeCAD: 64-bit
Version: 0.20.2.29603 (Git)
Build type: Release
Branch: (HEAD detached at 0.20.2)
Hash: 930dd9a76203a3260b1e6256c70c1c3cad8c5cb8
Python 3.10.6, Qt 5.15.7, Coin 4.0.0, Vtk 8.2.0, OCC 7.6.3
Locale: English/Canada (en_CA)
Installed mods: 
  * ProDarkThemePreferencePack 1.0.0
[/code]
```

### Subproject(s) affected?

None

### Issue description

Bold text is somewhat distorted/blurry.
![image](https://user-images.githubusercontent.com/7829231/214191816-ea912433-c41e-41d4-acf3-0775f8767e94.png)
![image](https://user-images.githubusercontent.com/7829231/214191839-bf169bbf-acd4-495c-ba77-fa19ca5ae8d3.png)

Could be an issue with how anti-aliasing is being handled on bold text.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment] 2023-01-24 11:28
Is this theme related?  (If you switch themes does this issue persist?)

**Comment by K4LCIFER** [comment] 2023-01-26 00:42
Ah it may be a theme issue with ProDark.

Here is no stylesheet:

![image](https://user-images.githubusercontent.com/7829231/214727807-e869d69c-e1d8-43ff-8bf6-d44d81ac557f.png)


Darker Blue theme:

![image](https://user-images.githubusercontent.com/7829231/214728204-82d12a29-3a5e-4bb9-9dd2-5dff6b9180a6.png)

**Comment by K4LCIFER** [comment] 2023-01-26 00:44
However, the tree view is still somewhat distorted, I am noticing:

Darker Blue theme:

![image](https://user-images.githubusercontent.com/7829231/214728649-e21cc987-e1b7-4f3f-95d1-bdc75dad6503.png)


No style sheet:

![image](https://user-images.githubusercontent.com/7829231/214728714-dbd735a7-94fc-4324-9c77-dfce921cddbf.png)

**Comment by luzpaz** [comment] 2023-03-15 14:23
@MisterMakerNL can you have a look when you get a chance ?

**Comment by MisterMakerNL** [comment] 2023-03-15 18:15
ProDark is one of the only one that use bold fonts, looks like that is the issue.
Found similar issue here but no solution:
https://forum.qt.io/topic/114649/why-fonts-in-qt-are-appearing-blurry-or-pixelated

**Comment by luzpaz** [comment] 2023-03-18 22:15
Thanks mistermaker. 

CC @turn211 FYI

**Comment by luzpaz** [comment] 2023-04-15 21:11
Can anyone locate an upstream Qt ticket for this pixelated issue ?

**Comment by chennes** [comment] 2023-04-15 21:55
Does the font being used there have a real bold variant, or is it being faked by the renderer?

**Comment by adrianinsaval** [comment] 2023-04-28 22:43
sounds like a font configuration problem, @luzpaz I don't think we can target this for 0.21 since it's most likely a system/packaging problem not something on freecad's code.

**Comment by turn211** [comment] 2023-04-29 16:49
I took a look at my theme and the bold text is crisp and perfect on Windows. So Linux related.

**Comment by adrianinsaval** [comment] 2023-04-29 16:53
Check your font settings on qt5ct, my first suspicion is that gnome doesn't properly configure Qt applications. What distro are you using?

**Comment by turn211** [comment] 2023-04-29 19:26
I’m only on windows but I did test on Manjaro KDE live iso and fonts displayed properly.

**Comment by xtemp09** [comment] 2023-04-30 18:39
@K4LCIFER, could you run FreeCAD with the following command:
```ruby
QT_SCALE_FACTOR=1.3 FreeCAD
```
varying the scale factor from 1.0 to 2.0?

**Comment by adrianinsaval** [comment] 2023-05-23 15:09
@K4LCIFER please provide feedback, otherwise I think we should close the issue since it's not actionable as is

**Comment by luzpaz** [comment] 2024-07-27 01:18
bump @K4LCIFER

**Comment by obelisk79** [comment] 2024-08-17 20:55
@luzpaz @maxwxyz I am unable to reproduce this text rendering issue on linux. Everything bold is crisp as reported by others. I suggest this issue be closed as it hasn't really be reproducible and the originator has seemingly abandoned this report.

**Closed** 2024-08-18 05:50 UTC
Labels: Topic: User Interface, OS: Linux, Status: Needs feedback, Topic: Stylesheets, 3rd party: Qt
