### ISSUE TITLE
Loses reference to external geometry

### ISSUE THREAD

**Issue by Beep6581** [FreeCAD/FreeCAD#17672] opened 2024-11-04 18:12 UTC
### Problem description

Changing the sub-shape binder's offset a few times makes FreeCAD lose reference to external geometry.

[issue17672.zip](https://github.com/user-attachments/files/17622286/issue17672.zip)

https://github.com/user-attachments/assets/0739f5b8-23da-45d1-97ed-c48bfe571248

### Full version info

```shell
OS: Manjaro Linux (KDE/plasma/xcb)
Architecture: x86_64
Version: 1.1.0dev.39126 (Git)
Build type: Release
Branch: main
Hash: 1b35d8b0f18867b92749a1c0756022f02e1c18a8
Python 3.12.6, Qt 6.7.2, Coin 4.0.3, Vtk 9.3.1, OCC 7.8.1
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/
Installed mods: 
  * OpenDark 2023.12.17
  * A2plus 0.4.68
  * fasteners 0.5.29
  * Woodworking 0.21.2.33771
  * CurvedShapes 1.0.12
  * Curves 0.6.51
```

**Comment by maxwxyz** [comment] 2024-11-04 18:47
Duplicate of https://github.com/FreeCAD/FreeCAD/issues/13313

**Closed by maxwxyz** 2024-11-04 18:47 UTC
Labels: Status: Needs triage
