### ISSUE TITLE
[Regression] Sketcher: No visual feedback when external line is selected (v1.0 RC1)

### ISSUE THREAD

**Issue by DerMouse** [FreeCAD/FreeCAD#16422] opened 2024-09-10 20:15 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

In the sketcher workbench, when using external reference lines (not only straight lines, anything), the lines are properly highlighted in the preselection mode color, but do not change color when selected. External points are properly changing color when selected.

### Full version info

```shell
OS: Gentoo Linux
Word size of FreeCAD: 64-bit
Version: 1.0.0RC1.38642 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 1.0rc1)
Hash: 60a251354e203bdb924e2190fb9f5e18b48d7362
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United Kingdom (en_GB)
Installed mods: 
  * freecad.gears 1.2.0
  * persistenttoolbars
```

### Subproject(s) affected?

Sketcher

### Anything else?

Preselecting the line (configured preselection color is light blue here)
![Selection_003](https://github.com/user-attachments/assets/d2c13f79-d4e7-434c-ad88-1cf52d28909b)

Selected a point from the external geometry
![Selection_004](https://github.com/user-attachments/assets/2854fec4-0db9-4759-a9f5-e82ed12df191)

Selected the same vertical line as in the first image (believe me : the line IS selected)
![Selection_005](https://github.com/user-attachments/assets/e1b21656-6782-4998-91d9-cd334f587e78)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Syres916** [comment] 2024-09-11 10:55
I've narrowed the regression down to 224 commits and a Git Bisect is underway, looks like sometime late July/early August time when the selection mechanism for external geometry stopped working correctly.

**Comment by kadet1090** [comment] 2024-09-11 12:26
https://github.com/FreeCAD/FreeCAD/pull/16355 this PR should fix it probably?

**Comment by Syres916** [comment] 2024-09-11 17:17
For completeness, I couldn't compile all of the commits so the best I can say is [PR15509](https://github.com/FreeCAD/FreeCAD/pull/15509) was the trigger of the regression and while https://github.com/FreeCAD/FreeCAD/pull/16355 fixes the external geometry selection, I've found that a new set of [errors](https://github.com/FreeCAD/FreeCAD/pull/16355#issuecomment-2344246162) get raised on some 'real' geometry.

**Comment by CalligaroV** [comment] 2024-09-11 22:24
Thanks @Syres916 for trying #16355 and @kadet1090 for linking it to this issue!

@Syres916, as you may have already noticed I'm participating to the discussion about the errors you found in the conversation of #16355.
Regardless for that, and considering your feedback, I'll add that PR as a fix for this issue.

Thanks again!

**Closed** 2024-09-13 02:11 UTC
Labels: Type: Bug, Status: Needs confirmation, Topic: User Interface, Mod: Sketcher, Type: Regression

**Comment by DerMouse** [comment] 2024-09-14 05:30
With latest Freecad weekly build :

OS: Gentoo Linux
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38728 (Git) AppImage
Build type: Release
Branch: main
Hash: 9de78e27f4148e8032594788a9804486e769388b
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United Kingdom (en_GB)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * freecad.gears 1.2.0
  * persistenttoolbars

this bug is solved. Thanks !
