### ISSUE TITLE
Freecad V 1.0

### ISSUE THREAD

**Issue by nkrill46** [FreeCAD/FreeCAD#17557] opened 2024-10-29 13:54 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Refresh/Redraw not working, but v1.0 is awesome software!

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 1.0.0RC2.38806 (Git)
Build type: Release
Branch: (HEAD detached at 1.0rc2)
Hash: 3d63fc6c2f665a8d5e6468845a419bcac80756c7
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/Fusion
Installed mods: 
  * Curves 0.6.45
  * fasteners 0.5.21
  * Help 1.0.3
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nkrill46** [comment] 2024-10-29 14:47
FreeCad V1.0


1) Create cube in “Part” workbench
2) Select an edge on cube
3) Tools - Measure (a ballooned measurement will  appear)
4) Edit: Refresh is inactive as is Ctrl+R
     Escape will not clear balloon, nor will anything else I’ve tried. 
  5) Selecting a different edge will create another persistent balloon and clear the first balloon,

**Comment by MiqCG** [comment] 2024-10-29 19:09
@nkrill46 , which version of FreeCAD are you using?
You can find the complete information in the Help menu > About FreeCAD > Copy to clipboard. Copy the whole clipboard here, please.

As it is reported in issue #16829 , looks like the problem of the persistent ballons was still present in RC2, but I cannot reproduce in 1.1.0dev.39057 revision.



OS: Devuan GNU/Linux 5 (daedalus) (XFCE/xfce/xcb)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.39057 (Git) AppImage
Build type: Release
Branch: main
Hash: 3be681ef62bf82d32eb1f1935d99e83c48e48da3
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: Catalan/Spain (ca_ES)
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/Fusion
Installed mods: 
  * fasteners 0.5.29

**Comment by hyarion** [comment] 2024-10-29 21:48
@luzpaz sounds like we can close this as a duplicate

**Closed** 2024-10-30 11:11 UTC
Labels: Status: Needs feedback, Status: Needs steps to reproduce
