### ISSUE TITLE
Spreadsheet not modofy Change when you have opened another workbench

### ISSUE THREAD

**Issue by Vincenzoferrara** [FreeCAD/FreeCAD#14653] opened 2024-06-13 04:06 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Generally when I use spreadsheet I do it by saying I'm using sketch, if I just want to change the cell formatting or color, I have to exit sketch to edit, and then go back in.
This takes a lot of time, and if one forgets to log out it can cause bugs.

My request is seosrsrecuqesto module (or at least its functions) to be used together with any other workbench in use.

I use my spreadsheet on a second monitor via macro which detaches my tab.

### Full version info

```shell
I'm currently starting this request from my phone, I don't have Freecad at hand.

la mia versione e l'ultima versione beta di freecad, usata sotto manjaro Linux.
```

### Subproject(s) affected?

Spreadsheet

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment] 2024-06-15 11:39
Duplicate of https://github.com/FreeCAD/FreeCAD/issues/11914

**Closed by maxwxyz** 2024-06-15 11:39 UTC
