### ISSUE TITLE
[Problem] Sketcher: circle and arc OVPs should be able to switch to diameter

### ISSUE THREAD

**Issue by pierreporte** [FreeCAD/FreeCAD#12681] opened 2024-03-01 10:53 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The OVPs for circles and arcs are currently the radius. It should be possible to easily switch to diameter, and back.

For the circle, the diameter should be the default parameter.

### Full version info

```shell
0.22
```

### Subproject(s) affected?

Sketcher

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment] 2024-03-01 11:26
Is this different to: https://github.com/FreeCAD/FreeCAD/issues/12384 ?

**Comment by maxwxyz** [comment] 2024-03-01 11:28
Duplicate of https://github.com/FreeCAD/FreeCAD/issues/12384

**Closed by maxwxyz** 2024-03-01 11:27 UTC

**Comment by pierreporte** [comment] 2024-03-01 11:40
I made sure too search for existing issues. The default part is duplicate but the switching is not. I will edit to keep only this.Le 1 mars 2024 à 12:28, Max Wilfinger ***@***.***> a écrit :﻿
Duplicate of #12384
