### ISSUE TITLE
[Problem] Display arc center marks

### ISSUE THREAD

**Issue by vladtcvs** [FreeCAD/FreeCAD#9956] opened 2023-07-18 22:15 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.21 (Development)

### Full version info

```shell
[code]
OS: Debian GNU/Linux trixie/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33593 (Git) AppImage
Build type: Release
Branch: master
Hash: 15371a04f38bbeb5a04edc5a91020ada1e30ef88
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: English/United States (en_US)
[/code]
```

### Subproject(s) affected?

None

### Problem description

Steps to reproduce:
1. Arc center marks are disabled in TechDraw preferences
2. Create section with arc or circle
3. Enable arc center marks in preferences
4. No center marks appear

But if you create section after enabling marks, they will be displayed

In the example the left section is created before enabling marks and right one was created after
![image](https://github.com/FreeCAD/FreeCAD/assets/3390973/cd88195f-b0de-4090-941d-e401ebf95a89)

Expected behaviour:

After enabling center marks, center marks appear for all circles and arcs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment] 2023-07-19 07:29
To change the display of center marks for existing views you have to change their Arc Center Marks property on the View tab in the Property editor. The preference sets the default for new views. This is intended behavior.

Closing this as resolved.

**Closed by Roy-043** 2023-07-19 07:29 UTC
Labels: WB Sketcher
