### ISSUE TITLE
PartDesign: Sketches shown in "As is" Viewmode are not visible in Wireframe View

### ISSUE THREAD

**Issue by ElPatoNoEsTu** [FreeCAD/FreeCAD#17535] opened 2024-10-28 10:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Sketches shown in "As is" Viewmode are not visible in Wireframe View:

<img width="1200" alt="2024-10-28 10_52_21-_ Allignemnt_Test - FreeCAD 1 1 0dev" src="https://github.com/user-attachments/assets/ba2d04f1-497d-49b0-95ff-04ac0745ad62">

[Alignment_Test.zip](https://github.com/user-attachments/files/17540752/Alignment_Test.zip)

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38991 (Git)
Build type: Release
Branch: main
Hash: ef2156d0f6d116b1642a5531a2d44fc6b7d17042
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Qt default
Installed mods: 
  * Curves 0.6.50
  * DynamicData 2.68.0
  * freecad.gears 1.3.0
  * LCInterlocking
  * Manipulator 1.5.7
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Syres916** [comment] 2024-10-28 12:01
This is a regression, works as expected using 0.21.x

![Screenshot from 2024-10-28 11-59-41](https://github.com/user-attachments/assets/85094afa-4f3c-49a9-8c06-3e3f11f27a20)

**Comment by Syres916** [comment] 2024-10-28 12:44
In fact it works as expected using:

```
OS: Linux Mint 22 (X-Cinnamon/cinnamon/xcb)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.39062 (Git)
Build type: Release
Branch: main
Hash: c5c64a9c70f21c4c4c2ad294645993f9a60342d8
Python 3.12.3, Qt 5.15.13, Coin 4.0.2, Vtk 9.1.0, OCC 7.6.3
Locale: English/United Kingdom (en_GB)
Stylesheet/Theme/QtStyle: Behave-dark.qss/Behave-dark/Qt default
Installed mods: 
  * FreeCAD-themes 2024.9.14
  * Silk 0.1.5
  * sheetmetal 0.4.24
  * Behave-Dark-Colors 0.1.1
  * CfdOF 1.27.5
  * 3dfindit-freecad-integration 1.2.0
  * fasteners 0.5.29
  * freecad.gears 1.3.0
  * Curves 0.6.48
  * Assembly4 0.50.15
  * A2plus 0.4.68
```

so it looks like the config files need investigating, I noticed the tree objects checkbox is enabled in the OP's screenshot so I switched that on but it still works as expected.

**Comment by maxwxyz** [comment] 2024-10-28 13:33
@ElPatoNoEsTu can you test in safe mode please (Help>Restart in safe mode)

**Comment by ElPatoNoEsTu** [comment] 2024-10-28 18:52
Hi All,  I  tried using Safe-Mode - noch change - sketches are still invisible. 

<img width="725" alt="2024-10-28 19_44_34-_ Alignment_Test - FreeCAD 1 1 0dev (Safe Mode)" src="https://github.com/user-attachments/assets/316f4f19-24dd-4a24-a892-f2b5c1ae53f6">

dont hesitate to come back onto me in case can test / try something.

Regards EpNeT

**Comment by maxwxyz** [comment] 2024-10-28 18:58
Thanks. I still cannot reproduce it.

**Comment by ElPatoNoEsTu** [comment] 2024-10-28 20:23
@maxwxyz - Hej Max - could you please post the addons you're using ?

**Comment by ElPatoNoEsTu** [comment] 2024-10-28 20:47
@Syres916  - in this simple setup you tried it works here too.

**Comment by Syres916** [comment] 2024-10-28 23:53
So this seems to be Part Design Boolean related, if I use Part>Fusion of the two Bodies then the display is as expected but when using the PartDesign>Boolean>Fusion then the issue occurs. Coin is not actually relevant to this IMHO but I compiled using Coin 4.0.3 to be show that I'm using as near as the OP's build as I can compile.

```
OS: Linux Mint 22 (X-Cinnamon/cinnamon/xcb)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.39092 (Git)
Build type: Release
Branch: main
Hash: a65d05c6e495038168eefcba6a1e43218fbb3a20
Python 3.12.3, Qt 5.15.13, Coin 4.0.3, Vtk 9.1.0, OCC 7.6.3
Locale: English/United Kingdom (en_GB)
Stylesheet/Theme/QtStyle: Behave-dark.qss/Behave-dark/Qt default
Installed mods: 
  * FreeCAD-themes 2024.9.14
  * Silk 0.1.5
  * sheetmetal 0.4.24
  * Behave-Dark-Colors 0.1.1
  * CfdOF 1.27.5
  * 3dfindit-freecad-integration 1.2.0
  * fasteners 0.5.29
  * freecad.gears 1.3.0
  * Curves 0.6.48
  * Assembly4 0.50.15
  * A2plus 0.4.68

```

**Comment by maxwxyz** [comment] 2024-10-29 04:30
@AIRCAP I've read booleans :)

**Comment by AIRCAP** [comment] 2024-10-29 10:26
@maxwxyz
This has nothing to do with the boolean fusion itself, but with the way sub shapes of Part Bodies are rendered/not rendered.

if you make a Boolean Feature in a PartDesign Body, then only the resulting shape of the boolean feature is visible, the visibility of the children (in the example Body and Body001) are not, regardless of their visibility setting in the tree. as such also their children (like sketches) are not being drawn. There is no way to have any child of this boolean feature displayed in 3d view, only its result shape, which is a solid.

If you use Subshapebinders to the bodies instead of putting the bodies itself as children of the boolean, the sketches are displayed normally based on their bodies visibility settings:

![image](https://github.com/user-attachments/assets/8fe0ddb6-8ac1-4816-92e2-1b082c8f05bd)

The issue is that the sketches in question are not in the same body as the Boolean, but in different bodies, but because those are children of the boolean, those bodies are always invisible -- and so are their sketches and any other sub-shapes in them

**Comment by AIRCAP** [comment] 2024-10-29 10:29
I'd say it is an issue, because there is no possibility to make these features visible. - The BooleanOperation feature in PartDesign hides its children even if they are set to be visible in the part tree.. it would be ok if it were to set its children to default to invisible, but it should not ignore the visibility setting

**Comment by AIRCAP** [comment] 2024-10-29 10:32
![image](https://github.com/user-attachments/assets/1a460fb9-e2ba-4090-8cf6-a22ea0503310)

**Comment by AIRCAP** [comment] 2024-10-29 10:33
suggest renaming bug PartDesign BooleanFeature view provider ignores visibility setting of children

**Comment by maxwxyz** [comment] 2024-10-29 10:34
@AIRCAP could it be the same issue as https://github.com/FreeCAD/FreeCAD/issues/11209 then?

**Comment by AIRCAP** [comment] 2024-10-29 10:36
absolutely, yes

**Comment by maxwxyz** [comment] 2024-10-29 10:36
duplicate of https://github.com/FreeCAD/FreeCAD/issues/11209

**Closed by maxwxyz** 2024-10-29 10:36 UTC
Labels: Type: Bug, Mod: Core, Topic: User Interface, Status: Confirmed
