### ISSUE TITLE
Invalid reporting of multiple solids

### ISSUE THREAD

**Issue by drcowsley** [FreeCAD/FreeCAD#11743] opened 2023-12-16 19:00 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

While refining an existing design I encountered the problem that extending a pocket reported multiple solids.  Since this design feature has worked in the past I suspect something has been left behind following some ambitious uses of fillet in the earlier model.  Starting over with a design that starts by eliminating the fillets introduces this new issue.  Pocket002 is OK at 13mm but fails at 14mm.

### Full version info

```shell
[code]
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.21.1.33668 +26 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.1)
Hash: f6708547a9bb3f71a4aaade12109f511a72c207c
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: English/United Kingdom (en_GB)
[/code]
```

### Subproject(s) affected?

None

### Anything else?

[Post-PanelAdaptor.zip](https://github.com/FreeCAD/FreeCAD/files/13693618/Post-PanelAdaptor.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment] 2023-12-16 20:38
The issue is caused by the Chamfer which results in an invalid shape. You can verify this by making the Body transparent. You need to revise your modeling strategy to avoid this.

I am closing this as a user error. Again I ask you to please consult the forum first before creating a GitHub issue.

**Closed by Roy-043** 2023-12-16 20:38 UTC
