### ISSUE TITLE
Make it possible to copy items like bodys, primitives, solids, partgroups, sketches etc directly into partgroups, groups, comp.

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6134] opened 2022-02-07 20:38 UTC
Issue imported from https://tracker.freecad.org/view.php?id=4506

* **Reporter:** tectone
* **Date submitted:** 11/28/2020
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** new
* **Tags:** #lowhangingfruit, 0.19, file, tree view

# Original report text

Link of forum discussion: [https://forum.freecadweb.org/viewtopic.php?f=3&t=52573](https://forum.freecadweb.org/viewtopic.php?f=3&t=52573)

Freecad as of today, lacks the vital capability to mimic the standard file management behavior that is used by basically every computer system in use in the tree view window that is used to access various items which are used to model objects in the software. This applies for operation systems like advertised from Microsoft and Apple but also for every Linux, Unix and Debian system and normally for every type of software like files managers (Explorer, Thunar, Dolphin etc.) but also for word processing software like Microsoft word, libreoffice,  openoffice, abiword and most gui based editors. Here the behavior is, that during a copy action of files or data, first the selection is made and afterwards the data is transferd by the key combination Ctrl+C to the clipboard. Afterwards with Ctrl+V the data is transferred/copied from the clipboard to a new target location. For example one copies a sentence in word, copies the data to the clipboard and then marks another sentence. When the data is actually copied, the marked sentence gets overwritten by the content of the clipboard. Alternatively a position of the cursor can be selected and this becomes the new target of the data from the clipboard without overwriting data. The behavior of the named file managers works very similar. It is possible to copy, move or link files which is a visual representation of the bash commands cp, mv, ln (or the commands that that achieve the same result when they are named differently).

# Additional information

I do not include a project file, because this is the standard behavior for every version of freecad, independently from the actual project. My proposal for this feature request is, that the new standard behavior is, that the user gets the option to copy directly to a selected area(active body, etc). This could be achieved with the standard Ctrl+C, Ctrl+V combination. If one intends to copy directly to the root directly without using the tree view before, one could use a different combination like Ctrl+Alt+C and Ctrl+Alt+V to achieve this different result in a fast and convenient way.

# Steps to reproduce

Freecad violates this de facto standard of file handling which was described above, because it lacks the capability of making directed mv, cp and ln correspondences of those commands directly from the clipboard in the tree view. If an item is copied (a solid, a partgroup, a body etc.) with the intention to directly copy and move or copy and link it to another grouping element (partgroup, group, compound, etc.) it goes to the root directory or the project instead. Manually selecting the items and moving/linking them to the right directions/targets is time consuming, it slows down the work flow of the user and it can make the whole project very unstructured, because after a series of copy and paste operations, a large number or items accumulate in the root directory instead of their intended target location. This is a counter intuitive and time consuming lack of functionality that does not show much weight in smaller projects with just a small number of objects. In large projects the file management becomes extremely uncomfortable and confusing.

# FreeCAD Info

```
OS: Ubuntu 19.04 (XFCE/xubuntu)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.22960 (Git) AppImage
Build type: Release
Branch: master
Hash: c5a4b01d2e4218bcc0eb6650337650a6c65ef0e4
Python version: 3.8.6
Qt version: 5.12.5
Coin version: 4.0.0
OCC version: 7.4.0
Locale: German/Germany (de_DE)
```

# Other bug information

* **Priority:** normal
* **Severity:** feature
* **Category:** Feature
* **Updated:** 2/6/2021

**Comment by maxwxyz** [comment] 2024-03-09 16:48
Duplicate of #11211

**Closed by maxwxyz** 2024-03-09 16:48 UTC
Labels: Core, Feature, Missing: feedback
