### ISSUE TITLE
ISO GPS 

### ISSUE THREAD

**Issue by sebaras** [FreeCAD/FreeCAD#12020] opened 2024-01-17 13:12 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

ISO GPS is a general Problem in TechDraw
For eg.:
The Symol (E) should be after the tolerance
There are other symbols and combines symbols missing. See examples in attachements

### Full version info

```shell
[code]
OS: Windows 10 build 19042
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: releases/FreeCAD-0-21
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: German/Switzerland (de_CH)
Installed mods: 
  * A2plus 0.4.60n
  * Assembly4 0.50.2
  * CADExchanger
  * ExplodedAssembly
  * fasteners 0.4.60
  * Help 1.0.3
[/code]
```

### Subproject(s) affected?

None

### Anything else?

![ISO GPS Position](https://github.com/FreeCAD/FreeCAD/assets/143388865/a3ed24fc-1a74-4e13-aae2-9445caeba4e8)
![ISO GPS S1](https://github.com/FreeCAD/FreeCAD/assets/143388865/69501c71-c7f0-498d-a895-df402ae894f9)
![ISO GPS S2](https://github.com/FreeCAD/FreeCAD/assets/143388865/ebfe613e-2107-4e87-8c33-8e2244e194f4)
![ISO GPS S3](https://github.com/FreeCAD/FreeCAD/assets/143388865/ea1028c3-dcb5-4273-b84b-62da856b329c)
![ISO GPS S4](https://github.com/FreeCAD/FreeCAD/assets/143388865/3c96770c-923e-4fd2-bf30-4adc331f31b7)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by WandererFan** [comment] 2024-01-17 19:21
Is this a duplicate of #11112? Seems to be some overlap at least.  

There are also corresponding standards in ASME Y14.5.

**Comment by pierreporte** [comment] 2024-01-17 19:34
@WandererFan Definitely a duplicate. GPS is a synonym of GD&T.

**Comment by adrianinsaval** [comment] 2024-01-19 20:08
closing as duplicate, feel free to repon if it turns out it's not actually a duplicate

**Closed by adrianinsaval** 2024-01-19 20:08 UTC
Labels: WB TechDraw
