### ISSUE TITLE
PD Revolution - Face button and input field is shown even when not required.

### ISSUE THREAD

**Issue by leoheck** [FreeCAD/FreeCAD#15898] opened 2024-08-16 01:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The face field is shown even when it is not required.
This behaves differently than the same operation on `Part Design > Pad` which hides the widgets that are not required by the Type of the operation.
![image](https://github.com/user-attachments/assets/796d21b0-de3a-45ac-9ccc-68cc3b403e40)

### Full version info

```shell
OS: Ubuntu 24.04 LTS (ubuntu:GNOME/ubuntu-xorg)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36438 (Git) AppImage
Build type: Release
Branch: main
Hash: 0def330a9e2119a14bb349cc406c2aa365421ab4
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * Assembly4 0.50.16-dev
  * sheetmetal 0.4.24
  * InventorLoader 1.4.0
  * ose-piping
  * OpenTheme 2024.8.15
  * fasteners 0.5.26
  * asm4_disable_version_check_popup
  * OpticsWorkbench 1.0.20
  * lattice2 1.0.0
  * kicadStepUpMod
  * OpticsWorkbench.backup1722883583.3368473 1.0.18 (Disabled)
```

### Subproject(s) affected?

PartDesign

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment] 2024-08-16 09:47
Duplicate of #13298.

**Closed by Roy-043** 2024-08-16 09:47 UTC
Labels: Mod: Part Design, Topic: User Interface, Type: Feature
