### ISSUE TITLE
Allow editing of multiple sketches at the same time

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5580] opened 2022-02-07 15:51 UTC
Issue imported from https://tracker.freecad.org/view.php?id=1391

* **Reporter:** normandc
* **Date submitted:** 2/7/2014
* **FreeCAD version:** 0.14
* **Category:** Feature
* **Status:** new
* **Tags:** 

# Original report text

Currently, it is not possible to edit two sketches at the same time. To edit a second sketch, the user has to close the first sketch.

It would be very useful to allow editing of more than one sketch at the same time.

# Other bug information

* **Priority:** normal
* **Severity:** feature
* **Category:** Feature
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by mrlukeparry 2014-02-08 00:34
I am just wondering if this is just to do with sketcer or might be related in general to ViewProvider::setEdit()?

If I remember there is specific dialogue warning if you try to open another sketch editor.

**Comment by luzpaz** [comment] 2022-02-23 20:31
Is this AKA Multiple viewports open simultaneously? Sort of how @microelly2 used to do it..
![image](https://user-images.githubusercontent.com/4140247/155403187-7613d8c8-58a7-4225-a6a9-ac45f9bfda87.png)

**Comment by maxwxyz** [comment] 2024-02-21 13:18
Duplicate of https://github.com/FreeCAD/FreeCAD/issues/11879

**Closed by maxwxyz** 2024-02-21 13:18 UTC
Labels: Core, UI/UX, Feature
