### ISSUE TITLE
AppImage update fails with python error in report view

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6138] opened 2022-02-07 20:38 UTC
Issue imported from https://tracker.freecad.org/view.php?id=4511

* **Reporter:** Vorpal
* **Date submitted:** 12/16/2020
* **FreeCAD version:** 
* **Category:** Bug
* **Status:** new
* **Tags:** 

# Original report text

Using the built in AppImage updater has since a few weeks always failed at a late stage. The resulting new AppImage file is produced, but the update does not inform the user and offer to restart with the new version. The behaviour can be seen in the attached screenshot.

Forum thread with at least two users experiencing the issue: [https://forum.freecadweb.org/viewtopic.php?f=4&t=53022](https://forum.freecadweb.org/viewtopic.php?f=4&t=53022)

# Steps to reproduce

1. Start FreeCAD 0.19dev
2. Perform AppImage update from the settings where there is an update to download
3. Select to update.
4. Towards the end of the update the python error mentioned above is reported and the update stalls, never informing the user that it completed.

# FreeCAD Info

```
OS: Ubuntu 18.04.5 LTS (X-Cinnamon/cinnamon)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.23323 (Git) AppImage
Build type: Release
Branch: master
Hash: 512d5c6141aec52b6eecc67370336a28fde862a6
Python version: 3.8.6
Qt version: 5.12.5
Coin version: 4.0.0
OCC version: 7.4.0
Locale: English/United Kingdom (en_GB)

```

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Bug
* **OS: Ubuntu  18.04**
* **Platform:** Linux
* **Updated:** 2/6/2021

**Comment by chennes** [comment] 2022-02-11 16:48
Thanks for testing again, since you had been able to reproduce it before, I think we can close this. If it recurs of course feel free to reopen.

**Closed by chennes** 2022-02-11 16:48 UTC
Labels: 🐛 bug, core
