### ISSUE TITLE
[Problem] Sketcher: Dimensions get unreadable (small) if a 2nd sketch is visible

### ISSUE THREAD

**Issue by purehunter1** [FreeCAD/FreeCAD#7860] opened 2022-11-22 13:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=13&t=43670

### Version

0.20 (Release)

### Full version info

```shell
[code]
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.20.1.29410 (Git)
Build type: Release
Branch: releases/FreeCAD-0-20
Hash: f5d13554ecc7a456fb6e970568ae5c74ba727563
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: German/Germany (de_DE)
Installed mods: 
  * CurvedShapes
  * Curves
  * fasteners
  * Lithophane
  * sheetmetal
[/code]
```

### Subproject(s) affected?

Sketcher

### Issue description

If you have 2 sketches in your project e.g. a profile (1st) and a path (2nd), perpendicular to the profile, the dimensions of the opened sketch (1st, profile) can get unreadable small if you zoom into your sketch.

I made 4 important observations:
1. only the dimensions are affected. Other symbols for constraints are not.
2. It is independent of the chosen font size for the sketcher.
3. The problem only occurs, if the 2nd sketch is "visible". If you toggle the visibility of the 2nd sketch in the model path while working on the 1st sketch, you can switch on and off the problem (dimensions readable or not)
4. It is obvious, that the severity of the shrinking of the dimensioning depends on the geometry of the 2nd sketch. If there is a point in the 2nd sketch which is virtually behind the viewer, the severity of the shrinking is highest. If the path is very long, e.g. 5000mm, one point of it is always behind the viewer and working on the profile with the path visible is impossible.

### Anything else?

This problem already existed in FC 0.18.1 or even earlier. May be it is related to issue #7082.

2 images: path visible or not (top left corner)
![Screenshot Sketch18px_ohneExtGeomOk](https://user-images.githubusercontent.com/69100386/203328541-a72f36fd-3952-47a0-84bf-b6a00a7b68ae.png)
![Screenshot Sketch18px_mitExtGeomNotOk](https://user-images.githubusercontent.com/69100386/203328580-abff6822-0737-4bd6-aef9-eada6b776744.png)

Image: font size 100px
![Screenshot Detail-Ansicht_100px](https://user-images.githubusercontent.com/69100386/203328624-99180074-dc16-4b35-b36d-8fd2516d1230.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment] 2022-11-23 10:02
Please add an example file

**Comment by purehunter1** [comment] 2022-11-23 10:08
[ZoomTest.zip](https://github.com/FreeCAD/FreeCAD/files/10074405/ZoomTest.zip)
I zipped it, as FC files are not accepted

**Comment by adrianinsaval** [comment] 2022-11-23 13:30
This is a duplicate of #7082 for me having the other sketch visible or not makes no difference, but changing between perspective and parallel view does. To work around the issue go to sketcher settings and enable the option to force parallel view when entering sketcher edit mode

**Closed** 2022-11-24 09:22 UTC
Labels: Bug, WB Sketcher
