### ISSUE TITLE
[Bug] DraftView - line style property not working

### ISSUE THREAD

**Issue by FEA-eng** [FreeCAD/FreeCAD#6733] opened 2022-04-11 16:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=35&t=67928

### Version

0.20 (Development)

### Full version info

```shell
[code]
OS: Windows 10 (10.0)
Word size of FreeCAD: 64-bit
Version: 0.20.28611 (Git)
Build type: Release
Python 3.8.13, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: Polish/Poland (pl_PL)
[/code]
```

### Subproject(s) affected?

Techdraw

### Issue description

DraftView objects have the Line Style property but it doesn't work - there's no drop-down list for it and typing in the style name (e.g. "Dashed") does nothing. Such property can be useful to turn draft objects to annotations.

The style of original Draft objects being turned into views is also not considered so there is no way to change the style of lines created by the DraftView tool.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by WandererFan** [comment] 2022-04-12 17:56
This has to be fixed on the Draft/Arch side, I believe.

**Comment by WandererFan** [comment] 2022-04-13 16:30
If you take the text of DraftView's Symbol property and give it to Inkscape you will get what looks like solid lines. Inkscape will tell you that in fact you have a line with a custom dash property, which is correct. 

The issue is this code "stroke-dasharray:0.09,0.05" in the style attribute.  This code creates a dashed line made up of very small dashes separated by very small gaps.  The result appears as a continuous line.

**Comment by yorikvanhavre** [comment] 2022-05-12 14:11
The LineStyle property is working. The problem is that SVG is a bit delicate with line patterns... It gets scaled if placed inside a scaled group. The Draft get_svg() function normally takes care of this, at https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/Draft/draftfunctions/svg.py#L52 but it still depends on what defaults are set under Edit->Preferences->Draft->Visual settings. So far I've been unable to find values that work for everyone. Some values work when you are working on a model of a building, but not when working on a screw model...

Not really sure how to handle this... Maybe the whole system needs to be redone with something more accurate, like "I want 3mm dashes with a 1mm spacing" and FreeCAD would do the whole calculation up to the printed sheet...

**Comment by Roy-043** [comment] 2022-07-21 06:55
SVG patterns refer to [Draft Patterns](https://wiki.freecadweb.org/Draft_Pattern). Why do you think these settings are related?

**Comment by paullee0** [comment] 2022-07-21 16:52
Just wild guess, the only two inputs with figures looks like multiplier ?

**Comment by luzpaz** [comment] 2023-04-13 01:10
@yorikvanhavre do you mind revisiting this ?

**Comment by yorikvanhavre** [comment] 2023-05-08 13:38
On it!

**Comment by yorikvanhavre** [comment] 2023-05-10 08:19
Above commit implements more sensible default values that give good results at all scales:

![Screenshot from 2023-05-10 09-56-54](https://github.com/FreeCAD/FreeCAD/assets/1136856/f441735d-b912-440b-aa89-9d753d28f381)

**Comment by paullee0** [comment] 2023-05-10 17:34
Looks good :)

**Closed** 2023-05-15 09:38 UTC
Labels: Bug, WB Draft, WB TechDraw, Format: SVG
