### ISSUE TITLE
[Problem] FreeCAD custom toolbars cant have subcategories

### ISSUE THREAD

**Issue by CharlotteBeLike** [FreeCAD/FreeCAD#11371] opened 2023-11-13 04:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Most CAD softwares like fusion360 and onshape have customizable toolbars that allow you to have dropdown menus with more tools. FreeCAD does have this, but not in custom toolbars. I think it would be nice for users to be able to have tools with other tools nested inside them using dropdown menus.
Thank you :)

### Full version info

```shell
0.21
```

### Subproject(s) affected?

None

### Anything else?

![Screenshot_20231112_222004](https://github.com/FreeCAD/FreeCAD/assets/150643227/70c2898e-dd81-4b2a-a24b-e65f58c9c787)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PaddleStroke** [comment] 2023-11-15 09:49
Yes this is has been discussed before and it is on the roadmap.

**Comment by maxwxyz** [comment] 2024-03-02 15:05
Duplicate of https://github.com/FreeCAD/FreeCAD/issues/9926

**Closed by maxwxyz** 2024-03-02 15:05 UTC
Labels: Core, UI/UX, Feature
