### ISSUE TITLE
Pocket operation failed: "Refine failed: Removing splitter failedPocket: Removing splitter failed"

### ISSUE THREAD

**Issue by xiongyw** [FreeCAD/FreeCAD#17936] opened 2024-11-18 09:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I have a simple object created using 0.21.2 without issue. When I open it in 1.0RC4 with recompute, it reports the problem (as indicated in the title), for the pocket operation.

Enclosed is the file to reproduce the issue (openning it using 1.0 RC4). I am using Windows.

[twist-drill-bit-10mm.zip](https://github.com/user-attachments/files/17797990/twist-drill-bit-10mm.zip)

### Full version info

```shell
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.0.0RC4.39104 (Git) Conda
Build type: Release
Branch: (HEAD detached at 1.0rc4)
Hash: 83646753e051eaf438c0d5e9351cb57bd27377ab
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: Chinese/China (zh_CN)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * A2plus 0.4.68
  * Assembly4 0.50.15
  * BIM021 2021.12.0
  * Curves 0.6.51
  * Dracula 0.0.5
  * DynamicData 2.68.0
  * ExplodedAssembly
  * fasteners 0.5.29
  * Freecad-Built-in-themes-beta 1.2.2
  * FreeCAD-themes 2024.7.24
  * freecad.gears 1.3.0
  * lattice2 1.0.0
  * OpenTheme 2024.9.1
  * ProDarkThemePreferencePack 1.0.0
  * Render 2024.9.25
  * symbols_library
  * TabBar
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment] 2024-11-18 10:11
Duplicate of https://github.com/FreeCAD/FreeCAD/issues/17802

**Closed by maxwxyz** 2024-11-18 10:11 UTC
Labels: Status: Needs triage
