### ISSUE TITLE
FreeCAD Weekly Build 38459 - Polar Pattern fails.

### ISSUE THREAD

**Issue by Bladevane** [FreeCAD/FreeCAD#15872] opened 2024-08-13 08:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Originally found in Weekly Build 38429, the Polar Pattern fails to work.

### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38459 (Git)
Build type: Release
Branch: main
Hash: 58729b3ab0060a1525fc45c87beabfd4b3d5e22e
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United Kingdom (en_GB)
Installed mods: 
  * Curves 0.5.15
  * DynamicData 2.46.0
  * fasteners 0.4.23
  * Help 1.0.3
  * lattice2 1.0.0
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment] 2024-08-13 08:51
Duplicate of https://github.com/FreeCAD/FreeCAD/issues/15856

**Closed by maxwxyz** 2024-08-13 08:51 UTC
Labels: Status: Needs triage
