### ISSUE TITLE
Fillets with variable radius

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5809] opened 2022-02-07 17:48 UTC
Issue imported from https://tracker.freecad.org/view.php?id=3608

* **Reporter:** chrisb
* **Date submitted:** 9/23/2018
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** assigned
* **Tags:** 

# Original report text

It would be great to have fillets with variable radius in Part and PartDesign workbenches. See [german forum entries](https://forum.freecadweb.org/viewtopic.php?f=13&t=26646&p=258035#p257860), Werner is already involved.

# Other bug information

* **Priority:** normal
* **Severity:** feature
* **Category:** Feature
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by wmayer 2020-09-13 09:45
https://forum.freecadweb.org/viewtopic.php?f=13&t=50170

**Comment by app4soft** [comment] 2023-07-05 12:53
Duplicate of https://github.com/FreeCAD/FreeCAD/issues/5723

**Comment by luzpaz** [comment] 2023-07-09 18:17
Closing in favor of #5723  
(thanks)

**Closed by luzpaz** 2023-07-09 18:17 UTC
Labels: WB PartDesign, Feature
