### ISSUE TITLE
Part Design: Subtractive helix doesn't subtract from cylinder 

### ISSUE THREAD

**Issue by petrubecheru** [FreeCAD/FreeCAD#14851] opened 2024-06-22 11:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

A padded circle, a sketch and a Subtractive helix (project attached bellow):
![image](https://github.com/FreeCAD/FreeCAD/assets/124100239/711fa1ed-e95d-44c4-9728-7022c5744b3d)

Result:
![image](https://github.com/FreeCAD/FreeCAD/assets/124100239/80dc9a97-9735-4a21-9f9c-d410e7b94716)

### Full version info

```shell
OS: Ubuntu Core 22 (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37843 (Git) Snap 1058
Build type: Release
Branch: main
Hash: 932c73f0de2d1e9ba3f60ae14d199cfe77255c3a
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Locale: English/United States (en_US)
```

### Subproject(s) affected?

PartDesign

### Anything else?

freecad project 
[project3.zip](https://github.com/user-attachments/files/15936377/project3.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment] 2024-06-23 05:15
Is this a duplicate of: https://github.com/FreeCAD/FreeCAD/issues/13931
@FlachyJoe FYI

**Comment by FlachyJoe** [comment] 2024-06-23 13:23
The Helix AddSubShape is correct but the boolean cut is broken without error reported. It needs further work.

```python
p = App.ActiveDocument.Pad.AddSubShape
h = App.ActiveDocument.SubtractiveHelix.AddSubShape
h.check(True)
cut = p.cut(h)
cut.check(True)
Part.show(cut,"Cut")
```
![image](https://github.com/FreeCAD/FreeCAD/assets/10371513/e96e0b83-18cb-445d-8eae-f51083962bc2)

**Comment by FlachyJoe** [comment] 2024-06-23 18:53
Same geometry fails with Part too.
![image](https://github.com/FreeCAD/FreeCAD/assets/10371513/f09f58b0-770a-414a-bb18-29aea08141fa)

**Comment by FlachyJoe** [comment] 2024-06-23 19:14
The problem is due to the sewing line, if your move the sketch to the YZ plane, it works.
![image](https://github.com/FreeCAD/FreeCAD/assets/10371513/ac2f3c99-6030-4efb-9c86-39a57af0722d)

The sewing lines are known to cause problem for OCC.

**Comment by FEA-eng** [comment] 2024-06-28 16:08
I encountered a similar issue here: https://forum.freecad.org/viewtopic.php?t=88726

[Helix.zip](https://github.com/user-attachments/files/16033216/Helix.zip)

There's also a bug with polar pattern on subtractive helix reported in that forum thread but I'll make a separate issue for it as may have a different cause.

**Comment by chennes** [comment] 2024-08-25 01:38
Confirming that this is fixed by #16009

**Closed** 2024-08-25 01:39 UTC
Labels: Type: Bug, Mod: Part Design, 3rd party: OCC, Type: Known issue

**Comment by Ely31** [comment] 2024-09-30 00:00
This is happening to me on a version I built like a week ago
[drillBitCase.zip](https://github.com/user-attachments/files/17182234/drillBitCase.zip)
![helixfail](https://github.com/user-attachments/assets/68e06ac9-d074-4a06-9c7c-5b21dba5d19b)

**Comment by luzpaz** [comment] 2024-09-30 00:34
@Ely31 full [about](https://wiki.freecad.org/About) info please. TIA

**Comment by Ely31** [comment] 2024-09-30 00:41
OS: KDE neon 6.1 (KDE/plasmax11)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38794 (Git)
Build type: Unknown
Branch: main
Hash: a47800d9ccd7d7a7cdb1779d56de03d3c64cd76e
Python 3.10.12, Qt 5.15.14, Coin 4.0.0, Vtk , OCC 7.8.1
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: OpenDark.qss/OpenDark/Qt default
Installed mods: 
  * IconThemes
  * fasteners 0.5.29
  * freecad.gears 1.3.0
  * OpenDark 2024.3.13
  * OpenTheme 2024.9.1
