### ISSUE TITLE
[Bug] ProDark theme leaves artifacts on screen (may only be specific to macOS)

### ISSUE THREAD

**Issue by HuibSmeets** [FreeCAD/FreeCAD#8197] opened 2023-01-15 17:03 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
OS: macOS 10.16
Word size of FreeCAD: 64-bit
Version: 0.20.2.29603 (Git)
Build type: Release
Branch: (HEAD detached at 0.20.2)
Hash: 930dd9a76203a3260b1e6256c70c1c3cad8c5cb8
Python 3.10.8, Qt 5.15.4, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: C/Default (C)
```

### Subproject(s) affected?

None

### Issue description

Hi,

When switching to the ProDark theme (and the same happens with the ExtrememProDark preference pack) it leaves blacklines in the window after resizing panels (Combo view, Report view etc). Switching back to one of the other themes fixes it. The behavior 'survives' stopping and restarting FreeCAD. As long as this theme is used, the lines showup when resizing panels. Not a big deal but maybe causing memory-leakage. 

### Anything else?

FreeCAD installed on an iMac with MacOS 12.6 (Monterey)

<img width="500" alt="Schermafbeelding 2023-01-15 om 17 47 43" src="https://user-images.githubusercontent.com/117679210/212554777-3f4df091-d167-4794-9555-b75dc6f45ebe.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment] 2023-01-15 17:11
@PLChris do you mind testing on macOS latest dev to see if you can reproduce ?

**Comment by HuibSmeets** [comment] 2023-01-15 17:33
I'm not PLChris but downloaded the latest dev build and it exhibits the same issue. Too add, this on an Intel Mac (Late 2015 model)

<img width="500" alt="Schermafbeelding 2023-01-15 om 18 28 50" src="https://user-images.githubusercontent.com/117679210/212556978-62bf042e-761d-461c-b85d-2fd028e08697.png">

**Comment by HuibSmeets** [comment] 2023-01-16 15:38
To add, same artifacts happen with the latest weekly development build for Apple/ARM silicon on MacOS 13.1 (Ventura).

**Comment by luzpaz** [comment] 2023-01-16 16:03
Why was this ticket closed ?

**Comment by HuibSmeets** [comment] 2023-01-16 16:07
mhmm, strange, I edited my last comment, most likely I did

**Comment by luzpaz** [comment] 2023-01-16 22:26
@ipatch can you recreate on macOS ?

**Comment by ipatch** [comment] 2023-01-17 18:10
i don't a ventura VM setup at the moment. kindof trying to juggle AFK things at the moment. 

 - i'm curious if this could be ventura related?
 - ventura only on intel?
 - or ventura on intel and arm?
- strictly related to conda?

if one those guys who is using ventura wants to download one of the builds i uploaded a while back that'd be the first place i check and if same results, i can try and check on a big sur vm at some point.

https://github.com/FreeCAD/homebrew-freecad/releases/tag/0.20.0.release

**Comment by ipatch** [comment] 2023-01-17 18:11
@chennes 

you getting these artifacts on that m1 box?

**Comment by chennes** [comment] 2023-01-18 04:55
@ipatch Yes, I just checked it on the latest weekly on my M1 and it is showing this behavior.

**Comment by luzpaz** [comment] 2023-01-19 16:50
So what's the issue here?  
Qt?  
Coin3d?

**Comment by chennes** [comment] 2023-01-20 19:58
Looks Qt to me, but that's just a guess, not solid information.

**Comment by JohnOCFII** [comment] 2023-08-13 02:34
Issue still occurs with release version of 0.21.  Issue happens with `ProDark`, as reported, and as a different test case, does not happen with the `Behave-Dark` style sheet.

```
OS: macOS 13.5
Word size of FreeCAD: 64-bit
Version: 0.21.0.33675 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.0)
Hash: 41b058e2087de60dc8fef3d3e68c7d0129e13abf
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: C/Default (C)
```


<img width="1593" alt="Screenshot 2023-08-12 at 9 27 10 PM" src="https://github.com/FreeCAD/FreeCAD/assets/7844212/49b86395-c760-49ad-a680-64aa9c7735bf">

**Comment by luzpaz** [comment] 2023-08-13 14:07
Can someone test if this is reproducible on a macOS build using Qt6 ?

**Comment by berniev** [comment] 2023-08-13 17:52
Is there a macOS build using Qt6 ?

**Comment by luzpaz** [comment] 2023-08-13 17:59
@ipatch do you happen to know if there is one ?

**Comment by ipatch** [comment] 2023-08-13 21:28
i have not built freecad with qt6.

**Comment by luzpaz** [comment] 2023-08-16 19:47
Anyone willing to start working on a Qt6 build for macos ?

**Comment by berniev** [comment] 2023-08-16 20:03
Some work was done [https://github.com/FreeCAD/FreeCAD/pull/7682](url) but was inconclusive

**Comment by luzpaz** [comment] 2023-10-13 11:01
@HuibSmeets, i'm going to close this as a duplicate of #9914

**Closed by luzpaz** 2023-10-13 11:01 UTC
Labels: Bug, UI/UX, OS: macOS, Stylesheets
