### ISSUE TITLE
[Bug] [TD] Temporary Template Dir locked when saving as ...

### ISSUE THREAD

**Issue by meropsa** [FreeCAD/FreeCAD#7714] opened 2022-11-05 09:58 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?style=1&f=13&t=72998

### Version

0.20 (Release)

### Full version info

```shell
[code]
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.20.1.29410 (Git)
Build type: Release
Branch: releases/FreeCAD-0-20
Hash: f5d13554ecc7a456fb6e970568ae5c74ba727563
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: German/Switzerland (de_CH)
Installed mods: 
  * A2plus 0.4.60
  * sheetmetal 0.2.58
[/code]
```

### Subproject(s) affected?

Techdraw

### Issue description

when saving an existing file using a new name, the template gets locked (cannot open file ...)
![2022-10-29_09-45-24](https://user-images.githubusercontent.com/117511787/200113981-619ab770-3887-4914-89fd-a04a50496d8e.png)
can be resolved by copying the temp path (transient dir) from the root item
![2022-10-29_19-36-48](https://user-images.githubusercontent.com/117511787/200114077-b2d800da-3f03-4e15-8df7-6271cac45b78.png)
and pasting it as template path (omit the file name)
![2022-10-29_19-38-52](https://user-images.githubusercontent.com/117511787/200114117-1239317d-022a-43f7-a4d8-8c9b7b458980.png)

### Anything else?

Thank you for the great work anyway!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by WandererFan** [comment] 2022-11-06 19:02
duplicate of #7376?

**Closed** 2022-11-12 16:35 UTC
Labels: Bug, WB TechDraw
