### ISSUE TITLE
Canvas background does not have a smooth color transition.

### ISSUE THREAD

**Issue by leoheck** [FreeCAD/FreeCAD#14791] opened 2024-06-19 13:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Hi, I am wondering if there is a way to get this background color transition improved somehow making it smoother. 
Improving this would make Freecad more professional.

![image](https://github.com/FreeCAD/FreeCAD/assets/1277920/949c0129-a0e8-411f-b83c-220f3fa3041d)

### Full version info

```shell
OS: Ubuntu 24.04 LTS (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37819 (Git) AppImage
Build type: Release
Branch: main
Hash: 2ca9b6ef8036d5fd808f01205b66eb0424059e21
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * POV-Ray-Rendering
  * Assembly4 0.50.12
  * sheetmetal 0.4.18
  * InventorLoader 1.4.0
  * ose-piping
  * fasteners 0.5.23
  * asm4_disable_version_check_popup
  * fasteners.backup1718509812.8005707 0.5.21 (Disabled)
  * OpenDark 2024.3.13
  * ProDarkThemePreferencePack 1.0.0
  * Render 2024.6.5
  * OpticsWorkbench 1.0.18
  * lattice2 1.0.0
  * kicadStepUpMod
```
```


### Subproject(s) affected?

None

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment] 2024-06-21 11:06
Duplicate of https://github.com/FreeCAD/FreeCAD/issues/10210

**Closed by maxwxyz** 2024-06-21 11:06 UTC
