### ISSUE TITLE
The menu text is obscured

### ISSUE THREAD

**Issue by HaydenHu** [FreeCAD/FreeCAD#15296] opened 2024-07-08 15:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

![image](https://github.com/FreeCAD/FreeCAD/assets/30103277/03ea824d-ed1e-451f-afc9-0b46c52cde2e)
![image](https://github.com/FreeCAD/FreeCAD/assets/30103277/3b274f1d-cbc3-45d9-a774-bc539a6ed3e3)
After setting the default English language to Chinese, the menu text is blocked, After setting back to English，and the problem is still the same

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38043 (Git)
Build type: Release
Branch: main
Hash: 561e521817034ea7660de987d8ab7183ad583595
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Chinese/China (zh_CN)
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MisterMakerNL** [comment] 2024-07-08 17:58
I have happen this too me too, but weird thing is it when away after rebooting my pc.
So I have no idea what happend.

**Comment by maxwxyz** [comment] 2024-07-08 18:33
Duplicate of https://github.com/FreeCAD/FreeCAD/issues/14920

**Closed by maxwxyz** 2024-07-08 18:33 UTC
