### ISSUE TITLE
[Bug] Missing B-Spline in STEP file after Part Offset2D

### ISSUE THREAD

**Issue by mpetrasinovic** [FreeCAD/FreeCAD#6727] opened 2022-04-09 09:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=3&t=67776

### Version

0.20 (Development)

### Full version info

```shell
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.20.27422 (Git)
Build type: Release
Branch: master
Hash: d938733eaf2c2ce7cb18d1cbb56147185c473530
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.3
Locale: English/United States (en_US)
```

### Subproject(s) affected?

Part

### Issue description

After applying Part Offset2D to a sketch (or Wire) that has B-Spline it is computed and shown like it is supposed to but when we export this geometry to STEP all B-Spline offsets are ignored.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment] 2022-04-09 22:07
CC @AjinkyaDahale do you mind weighing-in?

**Comment by AjinkyaDahale** [comment] 2022-04-10 14:11
I'll take a look when I can. @PaddleStroke you are also working on offsets for sketches right? Anything that strikes a bell?

**Comment by mpetrasinovic** [comment] 2022-04-10 14:33
I want to add that spline from the sketch is exported, but one from the offset is ignored.

The most promising workaround (that maybe can be implemented behind the scene) is to use the same underlying functions that Draft Shape2DView uses but to keep geometry at the exact placement. After this function, everything is exported as expected.

**Comment by PaddleStroke** [comment] 2022-04-10 19:09
Unfortunately I don't know how offset 2D tool works in details. I know how it gets the offset geometries from OCC but that's about it. And this part is working OK because you can see the offset bspline before exporting. 
So my guess is that the issue is at the export function. I would guess that the handling of the offset 2D object by the export has a problem with bspline (or they may not even be coded).
Because in Part, the offset2D is an object, it's not actually a bundle of the offset edges. Which enables to change the offset easily. So I guess the export has to get the offset edges from the offset2D object.
My plate is quite full at the moment so I can't have a deeper look in it.

**Comment by wwmayer** [comment] 2022-04-11 10:58
It's not only a problem with B-Spline but also ellipses, parabolas and hyperbolas are affected.

When looking at the output shape of the 2D offset then in most cases it's a wire of several edges. Depending on the geometry of the input shape the edges of the output shape can be lines, circles, B-Splines and sometimes the curve type "offset curve".

It looks like this curve type is causing problems and for me a STEP file with an exported offset curve can't even be loaded. What works fine is to export the offset curve as IGES because here the translator obviously converts the offset curve into one or multiple B-Splines.

**Comment by mpetrasinovic** [comment] 2022-04-11 11:24
I have posted on the forum model that has problems also with IGES export and import  (https://forum.freecadweb.org/download/file.php?id=185333&sid=b4b162c8dcc60fa209123547bbcbafd7). I tried several times to use IGES as a workaround but it transforms solid to faces while exporting. This makes new problems for usability.

**Comment by wwmayer** [comment] 2022-04-11 12:14
Here is a function to convert the offset curve of a wire with B-Splines: 3d249e0e67

**Comment by wwmayer** [comment] 2022-04-11 12:17
a13e251ad4 uses the newly added function to replace offset curves. Please check if it solves the issue.

**Comment by mpetrasinovic** [comment] 2022-04-11 13:46
I tried to compile FreeCAD again and this time I have got:

![img7](https://user-images.githubusercontent.com/33840625/162753310-f62821af-617c-45c0-b8d3-b3e4ccf78543.png)

**Comment by mpetrasinovic** [comment] 2022-04-11 14:22
I guess this is now the limit of the Offset function, I have changed the spline to the following one and now everything works, the model is exported to STEP and imported back without any problem.

![img8](https://user-images.githubusercontent.com/33840625/162760244-cd29e8cf-c7ab-4e9d-912f-bdcca09ae057.png)

**Comment by mpetrasinovic** [comment] 2022-04-11 14:56
I just checked, offsetting ellipse also worked as expected.

**Comment by wwmayer** [comment] 2022-04-11 18:48
> I have complied master and now if sketch or wire has BSpline I get makeOffset2D: result of offsetting is null! Input error.

I think that's an issue that must have happened before the change, too. 

> I tried to compile FreeCAD again and this time I have got:

Do you have a test file? What could possibly happen is that the edges of the wire are not in the expected order and thus if a new edge isn't adjacent to an edge of the wire it will be rejected.

> I guess this is now the limit of the Offset function

There should be no limitation compared to the old behaviour

**Comment by donovaly** [comment] 2022-04-12 00:52
I gave it a try and for me the issue is resolved.

**Comment by mpetrasinovic** [comment] 2022-04-12 07:06
> I think that's an issue that must have happened before the change, too.

Yes, I also think so.

> Do you have a test file? What could possibly happen is that the edges of the wire are not in the expected order and thus if a new edge isn't adjacent to an edge of the wire it will be rejected.

Maybe, I will try to find that file. But I will tomorrow have the same computer.

> There should be no limitation compared to the old behaviour

I do not think there is a limitation compared to the old behavior.

**Comment by wwmayer** [comment] 2022-04-12 09:22
> I do not think there is a limitation compared to the old behavior.

But in your second picture an edge of the offset wire is missing. However, it's also possible that it was already missing before doing the replacement.

I have tested the offset function a bit further by using an input wire where the edges are added in arbitrary order and the replacement still worked fine.

**Comment by mpetrasinovic** [comment] 2022-04-14 14:32
I tested some sketches and found this one that I can't offset.

(added zip extension in order to be able to upload it)

[2d-offset-sketch-bug.FCStd.zip](https://github.com/FreeCAD/FreeCAD/files/8489980/2d-offset-sketch-bug.FCStd.zip)

**Comment by mpetrasinovic** [comment] 2022-04-14 14:38
I think that there are two coincident control points, which is probably why offset is not working.

> But in your second picture an edge of the offset wire is missing.

I can't reproduce that again.

**Comment by donovaly** [comment] 2022-04-15 16:50
> I tested some sketches and found this one that I can't offset.
> [2d-offset-sketch-bug.FCStd.zip](https://github.com/FreeCAD/FreeCAD/files/8489980/2d-offset-sketch-bug.FCStd.zip)

Confirmed using recent master.

**Comment by wwmayer** [comment] 2022-04-16 10:47
I can confirm the failure, too. But fortunately, it's not a regression of my fix. The OCC algorithm already fails to create an initial wire from the sketch.

**Comment by mpetrasinovic** [comment] 2022-04-16 14:21
The reported bug is then solved. The latest reported problem is a different bug. This should be closed?

**Comment by donovaly** [comment] 2022-04-16 14:43
Closing as fixed then

**Closed by donovaly** 2022-04-16 14:43 UTC
Labels: Bug, WB Part, upstream, 3rd Party: OCC
