### ISSUE TITLE
BIM: Error with Stairs

### ISSUE THREAD

**Issue by gianlucafiore** [FreeCAD/FreeCAD#14285] opened 2024-05-26 00:35 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

![image](https://github.com/FreeCAD/FreeCAD/assets/50465150/8274af0c-72b8-47bc-857c-a73cc9e2306c)
![image](https://github.com/FreeCAD/FreeCAD/assets/50465150/450f791d-944a-4a1c-90dd-fcf074bea827)

**### Only when you click on the stairs icon does this error come up**

### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37464 (Git)
Build type: Release
Branch: main
Hash: db48a78d5a545bb21a5c80a9fa4b4c983fbbe951
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Spanish/Argentina (es_AR)
Installed mods: 
  * Dracula 0.0.5
  * OpenDark 2024.3.13
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment] 2024-05-26 06:23
Duplicate of https://github.com/FreeCAD/FreeCAD/issues/14262

**Closed by maxwxyz** 2024-05-26 06:23 UTC
