### ISSUE TITLE
Arch Wall Alignments using implict Sketcher Direction Constraints

### ISSUE THREAD

**Issue by about-code** [FreeCAD/FreeCAD#15058] opened 2024-06-30 10:18 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

There are various workflows proposed to build Arch walls. **This problem refers to a workflow where walls are constructed from a scetch in the Scetcher Workbench.**

#### Reproduction

1. Open the scetcher workbench.
2. Draw a line or polyline from point A to some point B.
3. Close the scetcher workbench, move to Arch/BIM workbench. 
5. Select the scetch and convert it to a wall.
6. Change the wall data property "Alignment" from "Center" to "Left" or "Right".
7. The Arc wall tool _implicitly_ assumes a direction A => B of the scetcher line in order to decide upon what's "Left" or "Right".

#### Problem

1. It is not obvious what the actual line direction is by just looking on a scetch. In complicated scetches you actually need to remember how you draw the scetch and each individual line segment
2. There is no obvious means _to change_ the line direction from B => A.

The latter is particularly painful when scetching, e.g. a more complicated floor plan for a building, using polylines, lines and point-on-object constraints and length constraints for inner/outer room dimensions.

#### Solution Proposal 

- **Scetcher:** introduce a "direction constraint" which makes an implicit line direction an explicit constraint that can be set and changed.
- **Arch/BIM:** derive wall alignment from a base scetch by evaluating line direction constraints

It may be applicable to lines and polylines, at least.

### Full version info

```shell
FreeCAD 0.19 on Ubuntu 22.04 LTS. Not found any solution description for FreeCAD 1.0, either.
```

### Subproject(s) affected?

Sketcher

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment] 2024-06-30 10:42
Duplicate of https://github.com/FreeCAD/FreeCAD/issues/11957

**Closed by maxwxyz** 2024-06-30 10:42 UTC
