### ISSUE TITLE
[Bug] [Sketcher] Point-on-line not correctly auto-removed when redundant

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5887] opened 2022-02-07 17:59 UTC
Issue imported from https://tracker.freecad.org/view.php?id=3863

* **Reporter:** @0penBrain 
* **Date submitted:** 2/25/2019
* **FreeCAD version:** 0.18
* **Category:** Bug
* **Status:** assigned
* **Tags:** 

# Original report text

When "Auto Remove Redundants" is enabled, a "Point-on-line" constraint isn't removed when redundant if the superseding constraint is applied in continue mode. Solver displays an error message about redundancy instead. Everything becomes OK if a sketch item is dragged.
It works well in preselect mode.
It seems that this faulty behavior is specific to this "Point-on-line" constraint.

# Additional information

Forum thread : [https://forum.freecadweb.org/viewtopic.php?f=3&t=34451](https://forum.freecadweb.org/viewtopic.php?f=3&t=34451)
---
OS: Ubuntu 18.04.2 LTS
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.15860 (Git)
Build type: Release
Branch: master
Hash: 3b708c7f84b0425076b520e1d95627b20fd75fe0
Python version: 2.7.15rc1
Qt version: 5.9.5
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: French/France (fr_FR)

# Steps to reproduce

1. Create a new sketch and check "Auto Remove Redundants" is enabled
2. Create 2 lines (let's call them A & B, and their respective endpoints x.1 & x.2)
3. Select line A and endpoint B.1, then add a Point-on-line constraint
4. (Preselect mode): Select endpoints A.1 & B.1, then add a Coincident constraint => Everything's fine, Point-on-line constraint is removed
5. Come back to the state at the end of step 3
6. (Postselect mode): Select Coincident constraint (w/o anything selected), then click on A1 & B1 => Ouch ! Sketch isn't updated and solver displays "Sketch contains redundant constraints". Now just drag any line/endpoint with the mouse => Sketch is now updated and redundant constraint is removed

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Bug
* **Updated:** 2/6/2021

**Comment by maxwxyz** [comment] 2024-03-09 12:55
I cannot reproduce in the current weekly build. There is warning that this behavior is wrong and Sketcher won't accept this wrong constraint. Please let me know if this is still an issue, otherwise I'll close this.
![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/986e4ad7-1935-4e41-a9b4-28e7f527cf43)

**Closed** 2024-03-30 19:36 UTC
Labels: Bug, WB Sketcher, Missing: feedback
