### ISSUE TITLE
Save FEM Clipping Plane as different elements in the model/tree

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6082] opened 2022-02-07 20:30 UTC
Issue imported from https://tracker.freecad.org/view.php?id=4390

* **Reporter:** HoWil
* **Date submitted:** 6/29/2020
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** confirmed
* **Tags:** clipping plane, FEM

# Original report text

In FEM-wb a Clipping Plane can be used to look into the model or the mesh. Unfortunately, this clipping-plane element can only be created and removed to the 3D-view but it is not saved with/in the model. This would be very helpful for selecting/changing interior faces after e.g. saving and reopening the model.
Especially after saving the model and exiting FC the clipping plane is gone.
More than one clipping plane-element would be also helpful for selecting different interior faces. 

# Additional information

https://forum.freecadweb.org/viewtopic.php?f=18&t=30876&p=258447&hilit=clipping#p258447
"Clipping plane on face" under "Menu: Utilities" on https://wiki.freecadweb.org/FEM_Module

# Other bug information

* **Priority:** normal
* **Severity:** feature
* **Category:** Feature
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by berndhahnebach 2020-11-30 10:12
this would be a good add for sure

**Comment by maxwxyz** [comment] 2024-09-01 10:28
Duplicate of https://github.com/FreeCAD/FreeCAD/issues/16187

**Closed by maxwxyz** 2024-09-01 10:28 UTC
Labels: Mod: FEM, Type: Feature
