### ISSUE TITLE
[Problem] Disabling Splash screen on Windows results in app not starting

### ISSUE THREAD

**Issue by fred-telemetrak** [FreeCAD/FreeCAD#9491] opened 2023-05-06 00:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
[code]
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.20.2.29603 (Git)
Build type: Release
Branch: releases/FreeCAD-0-20
Hash: 930dd9a76203a3260b1e6256c70c1c3cad8c5cb8
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: English/United States (en_US)
[/code]
```

### Subproject(s) affected?

None

### Problem description

Start FreeCAD, Edit:Preferences and uncheck "Enable splash screen at start up" then OK
Shut down FreeCAD
Try to restart it - it will not restart.

Deleting the C:\Users\YOURNAME\AppData\Roaming\FreeCAD\user.cfg file fixes this.

Windows System Info:
OS Name	Microsoft Windows 11 Home
Version	10.0.22621 Build 22621
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	TTRKINSPIRON16P
System Manufacturer	Dell Inc.
System Model	Inspiron 16 Plus 7620
System Type	x64-based PC
System SKU	0B3C
Processor	12th Gen Intel(R) Core(TM) i7-12700H, 2300 Mhz, 14 Core(s), 20 Logical Processor(s)
BIOS Version/Date	Dell Inc. 1.10.0, 2023-02-13
SMBIOS Version	3.4
Embedded Controller Version	255.255
BIOS Mode	UEFI
BaseBoard Manufacturer	Dell Inc.
BaseBoard Product	0DHTCW
BaseBoard Version	A00
Platform Role	Mobile
Secure Boot State	On
PCR7 Configuration	Elevation Required to View
Windows Directory	C:\Windows
System Directory	C:\Windows\system32
Boot Device	\Device\HarddiskVolume1
Locale	United States
Hardware Abstraction Layer	Version = "10.0.22621.1413"
User Name	TtrkInspiron16P\fszie
Time Zone	Pacific Daylight Time
Installed Physical Memory (RAM)	40.0 GB
Total Physical Memory	39.7 GB
Available Physical Memory	24.0 GB
Total Virtual Memory	45.4 GB
Available Virtual Memory	29.7 GB
Page File Space	5.75 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	On
Virtualization-based security	Running
Virtualization-based security Required Security Properties	
Virtualization-based security Available Security Properties	Base Virtualization Support, Secure Boot, DMA Protection, UEFI Code Readonly, SMM Security Mitigations 1.0, Mode Based Execution Control, APIC Virtualization
Virtualization-based security Services Configured	Hypervisor enforced Code Integrity
Virtualization-based security Services Running	Hypervisor enforced Code Integrity
Windows Defender Application Control policy	Enforced
Windows Defender Application Control user mode policy	Off
Device Encryption Support	Elevation Required to View
A hypervisor has been detected. Features required for Hyper-V will not be displayed.	

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chennes** [comment] 2023-05-06 03:22
Duplicate of #9086, fixed by #9454.

**Closed by chennes** 2023-05-06 03:22 UTC
