### ISSUE TITLE
PartDesign: Polar Pattern fails in 0.22

### ISSUE THREAD

**Issue by ShayGus** [FreeCAD/FreeCAD#15856] opened 2024-08-11 06:15 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Polar pattern fails to create in 0.22
Confirmed working as expected in 0.21.2
```
# -*- coding: utf-8 -*-

+++++++++++++++++++++++++++++++++++++++++++++++++
import FreeCAD
import PartDesign

# Gui.runCommand('Std_DlgMacroRecord',0)
# Gui.Selection.addSelection('Polar_Pattern_Issue','Body','Pocket.')
# Gui.Selection.addSelection('Polar_Pattern_Issue','Body','Pocket001.')
### Begin command PartDesign_PolarPattern
# Gui.getDocument('Polar_Pattern_Issue').ActiveView.setActiveObject('pdbody',App.getDocument('Polar_Pattern_Issue').getObject('Body'),'')
App.getDocument('Polar_Pattern_Issue').getObject('Body').newObject('PartDesign::PolarPattern','PolarPattern')
App.ActiveDocument.recompute()
App.getDocument('Polar_Pattern_Issue').getObject('PolarPattern').Originals = [App.getDocument('Polar_Pattern_Issue').getObject('Pocket'),App.getDocument('Polar_Pattern_Issue').getObject('Pocket001'),]
App.getDocument('Polar_Pattern_Issue').getObject('PolarPattern').Axis = (App.getDocument('Polar_Pattern_Issue').getObject('Sketch001'),['N_Axis'])
App.getDocument('Polar_Pattern_Issue').getObject('PolarPattern').Angle = 360
App.getDocument('Polar_Pattern_Issue').getObject('PolarPattern').Occurrences = 2
App.ActiveDocument.recompute()
# App.getDocument('Polar_Pattern_Issue').getObject('PolarPattern').ViewObject.ShapeAppearance=getattr(App.getDocument('Polar_Pattern_Issue').getObject('Pocket001').getLinkedObject(True).ViewObject,'ShapeAppearance',App.getDocument('Polar_Pattern_Issue').getObject('PolarPattern').ViewObject.ShapeAppearance)
# App.getDocument('Polar_Pattern_Issue').getObject('PolarPattern').ViewObject.LineColor=getattr(App.getDocument('Polar_Pattern_Issue').getObject('Pocket001').getLinkedObject(True).ViewObject,'LineColor',App.getDocument('Polar_Pattern_Issue').getObject('PolarPattern').ViewObject.LineColor)
# App.getDocument('Polar_Pattern_Issue').getObject('PolarPattern').ViewObject.PointColor=getattr(App.getDocument('Polar_Pattern_Issue').getObject('Pocket001').getLinkedObject(True).ViewObject,'PointColor',App.getDocument('Polar_Pattern_Issue').getObject('PolarPattern').ViewObject.PointColor)
# App.getDocument('Polar_Pattern_Issue').getObject('PolarPattern').ViewObject.Transparency=getattr(App.getDocument('Polar_Pattern_Issue').getObject('Pocket001').getLinkedObject(True).ViewObject,'Transparency',App.getDocument('Polar_Pattern_Issue').getObject('PolarPattern').ViewObject.Transparency)
# App.getDocument('Polar_Pattern_Issue').getObject('PolarPattern').ViewObject.DisplayMode=getattr(App.getDocument('Polar_Pattern_Issue').getObject('Pocket001').getLinkedObject(True).ViewObject,'DisplayMode',App.getDocument('Polar_Pattern_Issue').getObject('PolarPattern').ViewObject.DisplayMode)
# Gui.getDocument('Polar_Pattern_Issue').setEdit(App.getDocument('Polar_Pattern_Issue').getObject('Body'), 0, 'PolarPattern.')
# Gui.Selection.clearSelection()
App.getDocument('Polar_Pattern_Issue').getObject('Body').Tip = App.getDocument('Polar_Pattern_Issue').getObject('PolarPattern')
App.ActiveDocument.recompute()
### End command PartDesign_PolarPattern
# Gui.Selection.clearSelection()
App.getDocument('Polar_Pattern_Issue').getObject('PolarPattern').Visibility = True
App.getDocument('Polar_Pattern_Issue').getObject('PolarPattern').Axis = (App.getDocument('Polar_Pattern_Issue').getObject('Sketch001'), ['N_Axis'])
App.getDocument('Polar_Pattern_Issue').getObject('PolarPattern').Reversed = 0
App.getDocument('Polar_Pattern_Issue').getObject('PolarPattern').Mode = 0
App.getDocument('Polar_Pattern_Issue').getObject('PolarPattern').Angle = 360.000000
App.getDocument('Polar_Pattern_Issue').getObject('PolarPattern').Occurrences = 2
App.getDocument('Polar_Pattern_Issue').recompute()
App.getDocument('Polar_Pattern_Issue').getObject('Pocket001').Visibility = False
# Gui.getDocument('Polar_Pattern_Issue').resetEdit()
+++++++++++++++++++++++++++++++++++++++++++++++++

```
### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38429 (Git)
Build type: Release
Branch: main
Hash: 362cf1c80edb89957d81c0dbe6e50ce35daaa6db
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/Israel (en_IL)
Installed mods: 
  * Curves 0.6.42
```

### Subproject(s) affected?

PartDesign

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment] 2024-08-11 06:54
could you upload the example file as well?

**Comment by ShayGus** [comment] 2024-08-11 07:49
[Polar_Pattern_Issue.FCStd.gz](https://github.com/user-attachments/files/16572986/Polar_Pattern_Issue.FCStd.gz)

**Comment by mfraser** [comment] 2024-08-11 14:19
This might also affect the mirroring function as I had issues with mirroring a body containing a pad and a pocket earlier using the latest build from the PPA, but in the AppImage it works fine.

```
Version: 0.22.0dev.38334 (Git) AppImage
Hash: 61c964caa9a7e5bbc7a8d5f7d8914505d365113e
```

**Comment by tibfel** [comment] 2024-08-12 11:04
I have a similar issue when I try to mirror or rotate by 180° the pocket in my file. See attached.
[mirrorIssue.zip](https://github.com/user-attachments/files/16580678/mirrorIssue.zip)

**Comment by maxwxyz** [comment] 2024-08-12 18:32
Is this a duplicate of https://github.com/FreeCAD/FreeCAD/issues/15852 ?

**Closed** 2024-08-13 11:08 UTC
Labels: Mod: Part Design, Type: Regression
