### ISSUE TITLE
Taskplane is shifting

### ISSUE THREAD

**Issue by edwin1959** [FreeCAD/FreeCAD#17045] opened 2024-10-06 08:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I am working with a dual screen. On my second screen i placed the model and task-plane. Every time i create something the taskplane is shifting a little bit to the bottom of the screen. Finally i have to put it back in position to she options to work with.

### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 1.0.0RC2.38806 (Git)
Build type: Release
Branch: (HEAD detached at 1.0rc2)
Hash: 3d63fc6c2f665a8d5e6468845a419bcac80756c7
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: Dutch/Netherlands (nl_NL)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * 3D_Printing_Tools
  * A2plus 0.4.60n
  * Assembly4 0.50.4
  * btl 0.9.9
  * Curves 0.6.13
  * ExplodedAssembly
  * fasteners 0.4.66
  * freecad.gears 1.0.0
  * OpticsWorkbench 1.0.12
  * python36_x64-ocl
  * sheetmetal 0.4.6
```

### Subproject(s) affected?

None

### Anything else?

![Schermafbeelding 2024-10-06 102231](https://github.com/user-attachments/assets/87eea4ec-6d3a-4783-878b-8a8b4b02d1ad)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment] 2024-10-06 08:36
Duplicate of #14650.

**Closed by Roy-043** 2024-10-06 08:36 UTC
Labels: Status: Needs triage
