### ISSUE TITLE
Part Design Pad tool does not work (co-planar issue?)

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#7142] opened 2022-02-07 20:47 UTC
Issue imported from https://tracker.freecad.org/view.php?id=4606

* **Reporter:** jhelmine
* **Date submitted:** 3/25/2021
* **FreeCAD version:** 0.19
* **Category:** Bug
* **Status:** new
* **Tags:** #pending-forum, appimage

# Original report text

Hello,

Example were padding do not work in prebuild 24212 Linux version but works on Windows, compiled from git 24489.
Test file in http://jhelmine.kapsi.fi/3D/LedKehysVaunuun_test.FCStd (same included to report also).

# Additional information

Padding tested in:
FreeCAD_0.19-24212-Linux-Conda_glibc2.12-x86_64.AppImage
FreeCAD_0.19-23578-Linux-Conda_glibc2.12-x86_64.AppImage

# Steps to reproduce

To repeat error open file LedKehysVaunuun_test.FCStd.
First use "Part Design" then activate Body001Yläpallo.
Click Sketch006RuuvinRunko and click Pad this sketch.
Padding to normal direction do not show anything else than outlines in already made body. Reverse direction padding adds structure.

Windows version (0.20 from master) works as expected and I can continue. Before error situation parameters in spreadsheet ("data") was changed and paddings and pockets removed. Changing data.PallonD (text "Pallon halkaisija") to small value like 50 or less makes error situation, multiple bodies. This was done before error but correcting to back do not help.

# FreeCAD Info

```
OS: Ubuntu 20.10 (ubuntu:GNOME/ubuntu)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.24212 (Git) AppImage
Build type: Release
Branch: master
Hash: 3d227cf7179c00e57f2733f947b4b1b0368d219a
Python version: 3.8.6
Qt version: 5.12.5
Coin version: 4.0.0
OCC version: 7.4.0
Locale: Finnish/Finland (fi_FI)

```

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Bug
* **Updated:** 3/27/2021

# Discussion from Mantis ticket

### Comment by Kunda1 2021-03-27 10:25
Forum thread: https://forum.freecadweb.org/viewtopic.php?f=8&t=57132

---

### Comment by Kunda1 2021-03-27 11:47
Per looo this looks like a discrepancy between OCCT 7.4.0 and 7.5.0

**Comment by adrianinsaval** [comment] 2022-07-06 23:11
Also doesn't work on archlinux's 0.19.4:
```
OS: Linux 5.18.9-arch1-1 (KDE/plasma)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.24415 (Git)
Build type: Release
Branch: makepkg
Hash: 476ecf091941bead59b14e44afa6064d5a66afa3
Python version: 3.10.5
Qt version: 5.15.4
Coin version: 4.0.1
OCC version: 7.5.3
Locale: English/United Kingdom (en_GB)
```
Of all my test it only worked in the 0.19 flatpak when it used occt 7.3 so it could be a regression upstream

**Comment by grubertechnic** [comment] 2023-07-23 10:37
@adrianinsaval : can you retest it? For me it works flawless.


```
OS: Debian GNU/Linux 11 (bullseye) (X-Cinnamon/lightdm-xsession)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33631 (Git)
Build type: Release
Branch: master
Hash: 2167fb6f7ec6ac5c2f6365d4c3035d2db6879b1e
Python 3.9.2, Qt 5.15.2, Coin 4.0.0, Vtk 9.0.1, OCC 7.7.1
Locale: English/United States (en_US)
Installed mods: 
  * QuickMeasure 2022.10.28
  * CurvedShapes 1.0.4
  * Curves 0.6.8
```



I add the file direct here.

[LedKehysVaunuun_test.zip](https://github.com/FreeCAD/FreeCAD/files/12138512/LedKehysVaunuun_test.zip)

**Comment by adrianinsaval** [comment] 2023-07-23 16:47
I still experience this, might be fixed in occt 7.7.1, will try a version with 7.7.1 later today
```
OS: Windows 11 build 22621
Word size of FreeCAD: 64-bit
Version: 0.21.0.33593 (Git)
Build type: Release
Branch: master
Hash: 15371a04f38bbeb5a04edc5a91020ada1e30ef88
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: Spanish/Paraguay (es_PY)
```

**Comment by grubertechnic** [comment] 2023-07-23 17:44
Thanks. Note, that OCCT have created a 7.7.2 head, which means that in a certain time (normally some days) they release an update.

**Comment by adrianinsaval** [comment] 2023-07-23 18:06
Indeed, works without issue with occt 7.7.1:
```
OS: KDE Flatpak runtime
Word size of FreeCAD: 64-bit
Version: 0.21.0.33439 (Git)
Build type: Release
Branch: (HEAD detached at 976ecb3)
Hash: 976ecb3754700dfe6059699b77f896f9610891e3
Python 3.10.11, Qt 5.15.10, Coin 4.0.0, Vtk 8.2.0, OCC 7.7.1
Locale: English/United States (en_US)
```

**Comment by adrianinsaval** [comment] 2023-07-23 18:09
I'll close the issue since this is an upstream issue so not actionable by us, and it's fixed upstream so it will eventually make it's way to our releases once we get full 7.7.1 compatibility

**Closed by adrianinsaval** 2023-07-23 18:09 UTC
Labels: Bug, WB PartDesign, 3rd Party: OCC, Regression, Help Wanted

**Comment by luzpaz** [comment] 2023-07-23 19:01
Maybe we should add this as a 'Known Issue' that is solved upstream ? (especially for the distros that don't keep OCC as up to date as we do?)

**Comment by adrianinsaval** [comment] 2023-07-23 19:02
Where do we have such a list?

**Comment by luzpaz** [comment] 2023-07-23 19:15
https://forum.freecad.org/viewtopic.php?f=3&t=30573

**Comment by adrianinsaval** [comment] 2023-07-23 19:19
I think we use that for different general usage problems, mentioning specific opencascade coplanar-like problems seems like it will quickly fill the page with noise
