### ISSUE TITLE
[Problem] FreeCAD crashes when activating `Materials_Edit` (segfault)

### ISSUE THREAD

**Issue by pierreporte** [FreeCAD/FreeCAD#11686] opened 2023-12-08 12:06 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I wanted to try the latest changes to the Material worbench with the weekly AppImage version. Clicking on `Materials_Edits` crashes FreeCAD. The previous weekly (0.22.0dev.35249) doesn’t crash.

How to reproduce:

1. Start FreeCAD
2. Create a new file
3. Go to the Material workbench
4. Click on `Materials_Edit`

### Full version info

```shell
OS: Ubuntu 23.04 (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35315 (Git) AppImage
Build type: Release
Branch: main
Hash: 09f67f2f6bff1c57ac8019a5ba2f4a2c41025ee6
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: French/France (fr_FR)
Installed mods: 
  * Render 2023.8.18
  * OpenDark 2023.12.1
```

### Subproject(s) affected?

Other (specify in description)

### Anything else?

```
FreeCAD 0.22.0, Libs: 0.22.0devR35315 (Git)
© Juergen Riegel, Werner Mayer, Yorik van Havre and others 2001-2023
FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.
FreeCAD wouldn't be possible without FreeCAD community.
  #####                 ####  ###   ####  
  #                    #      # #   #   # 
  #     ##  #### ####  #     #   #  #   # 
  ####  # # #  # #  #  #     #####  #   # 
  #     #   #### ####  #    #     # #   # 
  #     #   #    #     #    #     # #   #  ##  ##  ##
  #     #   #### ####   ### #     # ####   ##  ##  ##

Loading Assembly workbench...
Program received signal SIGSEGV, Segmentation fault.
#0  /lib/x86_64-linux-gnu/libc.so.6(+0x3c460) [0x7f70c7a3c460]
#1  0x7f6fb89ae592 in Materials::MaterialProperty::setValue(QString const&) from /tmp/.mount_FreeCAmQVGm5/usr/lib/./Material.so+0x22
#2  /tmp/.mount_FreeCAmQVGm5/usr/lib/./Material.so(+0x7cc62) [0x7f6fb8979c62]
#3  0x7f6fb89843a6 in Materials::MaterialConfigLoader::addRenderWB(QMap<QString, QString>&, std::shared_ptr<Materials::Material> const&) from /tmp/.mount_FreeCAmQVGm5/usr/lib/./Material.so+0x156
#4  0x7f6fb89863c9 in Materials::MaterialConfigLoader::getMaterialFromPath(std::shared_ptr<Materials::MaterialLibrary> const&, QString const&) from /tmp/.mount_FreeCAmQVGm5/usr/lib/./Material.so+0x6b9
#5  0x7f6fb89a008c in Materials::MaterialLoader::getMaterialFromPath(std::shared_ptr<Materials::MaterialLibrary> const&, QString const&) const from /tmp/.mount_FreeCAmQVGm5/usr/lib/./Material.so+0x6c
#6  0x7f6fb89a0658 in Materials::MaterialLoader::loadLibrary(std::shared_ptr<Materials::MaterialLibrary> const&) from /tmp/.mount_FreeCAmQVGm5/usr/lib/./Material.so+0x158
#7  0x7f6fb89a0a8d in Materials::MaterialLoader::loadLibraries() from /tmp/.mount_FreeCAmQVGm5/usr/lib/./Material.so+0x4d
#8  0x7f6fb89a0b5d in Materials::MaterialLoader::MaterialLoader(std::shared_ptr<std::map<QString, std::shared_ptr<Materials::Material>, std::less<QString>, std::allocator<std::pair<QString const, std::shared_ptr<Materials::Material> > > > > const&, std::shared_ptr<std::__cxx11::list<std::shared_ptr<Materials::MaterialLibrary>, std::allocator<std::shared_ptr<Materials::MaterialLibrary> > > > const&) from /tmp/.mount_FreeCAmQVGm5/usr/lib/./Material.so+0x4d
#9  0x7f6fb89a1ece in Materials::MaterialManager::initLibraries() from /tmp/.mount_FreeCAmQVGm5/usr/lib/./Material.so+0x13e
#10  0x7f6fb89a2193 in Materials::MaterialManager::MaterialManager() from /tmp/.mount_FreeCAmQVGm5/usr/lib/./Material.so+0x23
#11  0x7f6fb8a6d6c9 in MatGui::MaterialsEditor::MaterialsEditor(QWidget*) from /tmp/.mount_FreeCAmQVGm5/usr/lib/MatGui.so+0x69
#12  0x7f6fb8a4dd08 in CmdMaterialsEdit::activated(int) from /tmp/.mount_FreeCAmQVGm5/usr/lib/MatGui.so+0x188
#13  0x7f70ca974d88 in Gui::Command::_invoke(int, bool) from /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/libFreeCADGui.so+0x2a8
#14  0x7f70ca975144 in Gui::Command::invoke(int, Gui::Command::TriggerSource) from /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/libFreeCADGui.so+0x134
#15  /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/libQt5Core.so.5(+0x2e9214) [0x7f70c80e9214]
#16  0x7f70c8f6a422 in QAction::triggered(bool) from /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/libQt5Widgets.so.5+0x32
#17  0x7f70c8f6cdeb in QAction::activate(QAction::ActionEvent) from /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/libQt5Widgets.so.5+0xab
#18  /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/libQt5Widgets.so.5(+0x25cb9a) [0x7f70c905cb9a]
#19  0x7f70c905ccd7 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) from /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/libQt5Widgets.so.5+0xe7
#20  0x7f70c9145a4a in QToolButton::mouseReleaseEvent(QMouseEvent*) from /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/libQt5Widgets.so.5+0xa
#21  0x7f70c8faebd8 in QWidget::event(QEvent*) from /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/libQt5Widgets.so.5+0x178
#22  0x7f70c8f7035e in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/libQt5Widgets.so.5+0x7e
#23  0x7f70c8f78222 in QApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/libQt5Widgets.so.5+0x13a2
#24  0x7f70ca926e19 in Gui::GUIApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/libFreeCADGui.so+0x99
#25  0x7f70c80b3fc8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/libQt5Core.so.5+0x108
#26  0x7f70c8f763ab in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) from /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/libQt5Widgets.so.5+0x1ab
#27  /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/libQt5Widgets.so.5(+0x1c6e39) [0x7f70c8fc6e39]
#28  /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/libQt5Widgets.so.5(+0x1c9f99) [0x7f70c8fc9f99]
#29  0x7f70c8f7035e in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/libQt5Widgets.so.5+0x7e
#30  0x7f70ca926e19 in Gui::GUIApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/libFreeCADGui.so+0x99
#31  0x7f70c80b3fc8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/libQt5Core.so.5+0x108
#32  0x7f70c8734bec in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) from /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/libQt5Gui.so.5+0x84c
#33  0x7f70c870ad7c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/libQt5Gui.so.5+0xac
#34  /tmp/.mount_FreeCAmQVGm5/usr/plugins/platforms/../../lib/libQt5XcbQpa.so.5(+0x6454a) [0x7f70c26c354a]
#35  /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/./libglib-2.0.so.0(+0x5a417) [0x7f70c6711417]
#36  /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/./libglib-2.0.so.0(+0x5d3c7) [0x7f70c67143c7]
#37  /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/./libglib-2.0.so.0(g_main_context_iteration+0x2e) [0x7f70c67149be]
#38  0x7f70c81083d6 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/libQt5Core.so.5+0x66
#39  0x7f70c80b2bbb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/libQt5Core.so.5+0x11b
#40  0x7f70c80ba6a2 in QCoreApplication::exec() from /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/libQt5Core.so.5+0x82
#41  0x7f70ca88accd in Gui::Application::runApplication() from /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/libFreeCADGui.so+0x20ad
#42  /tmp/.mount_FreeCAmQVGm5/usr/bin/freecad(+0x7620) [0x557d2e0c7620]
#43  /lib/x86_64-linux-gnu/libc.so.6(+0x23a90) [0x7f70c7a23a90]
#44  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x89) [0x7f70c7a23b49]
#45  /tmp/.mount_FreeCAmQVGm5/usr/bin/freecad(+0x7981) [0x557d2e0c7981]
QMutex: destroying locked mutex
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment] 2023-12-08 12:08
CC @davesrocketshop

**Comment by davesrocketshop** [comment] 2023-12-08 12:14
This already has a fix that hasn't been merged yet. I'll make a merge this weekend.

The problem is when a value is set for a property that doesn't exist. The last merge parsed render WB material files, but the models haven't been merged yet. The fix is two fold: include the models, and check if the property exists before setting the value.

**Comment by davesrocketshop** [comment] 2023-12-13 21:56
Not yet. I found another detail I'm fixing first

**Comment by davesrocketshop** [comment] 2023-12-22 23:50
> I don't know if the description matches the same issue but when using the `Render Workbench/Manage Materials/Create Material/<Select something from Choose preset>` FreeCAD crashes, it crashes when editing an existing material as well.

This will definitely cause that but there may be other issues as well. I'm currently working  on the  Render WB to use the new materials. It is known to be broken at the moment.

**Closed** 2024-01-07 00:11 UTC
Labels: Bug, Crash, Has workaround, Materials
