### ISSUE TITLE
PartDesign: Can't pad a sketch attached to a datum plane up to another datum plane

### ISSUE THREAD

**Issue by twowords** [FreeCAD/FreeCAD#16010] opened 2024-08-22 20:37 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

To reproduce:

* Open Part Design Workbench
* Create a body
* Create a datum plane attached to the body XY plane
* Create a sketch on this datum plane and draw a circle
* Create another datum plane attached to the XY plane and change it's attachment offset in the Z direction
* Try to pad the sketch up to the other datum plane using the "Up to face" option
* Click OK

If the datum planes are parallel I get the error: "BRep_Builder::Infinite parameter"
If the datum planes are not parallel then I get the error: "Geom_RectangularTrimmedSurface::U parameters out of range"

### Full version info

```shell
OS: Ubuntu Core 22 (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38500 (Git) Snap 1112
Build type: Release
Branch: main
Hash: a75003449050e5d5d10398a522c6a3648eb097a2
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Locale: English/United Kingdom (en_GB)
Installed mods: 
  * Curves 0.6.40
  * Help 1.0.3
  * lattice2 1.0.0
```

### Subproject(s) affected?

PartDesign

### Anything else?

https://forum.freecad.org/viewtopic.php?t=89957

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment] 2024-08-23 06:12
@FlachyJoe FYI

**Comment by twowords** [comment] 2024-08-23 08:31
This issue doesn't exist in 0.21 so it is a regression not a feature request.

**Comment by maxwxyz** [comment] 2024-08-23 08:57
@twowords it should've beed fixed by @FlachyJoe in https://github.com/FreeCAD/FreeCAD/pull/14397
@bgbsww any chance this is TNP related?
@FlachyJoe any idea why this seems to fail? I can confirm this, here is a simple demo file:
[Datum_Pad.zip](https://github.com/user-attachments/files/16726251/Datum_Pad.zip)

**Comment by FlachyJoe** [comment] 2024-08-23 15:29
It's a very specific failure:

- it works if the Sketch is attached to anything else
- it works if the Sketch is attached to a DatumPlane and you pad to a solid face
- it works if the Sketch is attached to a DatumPlane and you pad to another DatumPlane but intersecting a solid
![image](https://github.com/user-attachments/assets/878022e3-cb03-498f-8d49-1380ebdeafff)
- it only fails if you pad in an empty space between two planes.

This case is useless because you can place the sketch as easily as the plane but I'll try to find where this bug come from. @maxwxyz you can assign to me.

**Closed** 2024-08-31 18:09 UTC
Labels: Mod: Part Design, Blocker, Type: Regression
