### ISSUE TITLE
Path not following taper

### ISSUE THREAD

**Issue by KR-Huck** [FreeCAD/FreeCAD#17997] opened 2024-11-20 02:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Given a pad with a Taper Angle on the sides. Adaptive Profiling ignores the taper and insists on clearing the inside. Using Debian Linux Freecad 0.22.0dev also windows Freecad 0.21.2 Regular Profile also ignores the Taper Angle.

Also tested in latest release 1.0 with same results.

### Full version info

```shell
OS: Pop!_OS 22.04 LTS (LXDE/LXDE)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37063 (Git) AppImage
Build type: Release
Branch: main
Hash: 680792030fd664c94829e2c1b78b21788e8d9879
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
```

### Subproject(s) affected?

None

### Anything else?

![FreeShot](https://github.com/user-attachments/assets/ccfe1c93-90a4-45e7-8885-b41520cadeef)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment] 2024-11-20 10:15
Duplicate of #17977

**Closed by luzpaz** 2024-11-20 10:15 UTC
Labels: Status: Needs triage
