### ISSUE TITLE
Solver claims Sketch to be fully constrained which it isn't

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5951] opened 2022-02-07 19:21 UTC
Issue imported from https://tracker.freecad.org/view.php?id=4032

* **Reporter:** chrisb
* **Date submitted:** 6/20/2019
* **FreeCAD version:** 
* **Category:** Bug
* **Status:** assigned
* **Tags:** 

# Original report text

See [forum topic](https://forum.freecadweb.org/viewtopic.php?f=3&t=37063#p315459). The left vertical line of the sketch can be moved horizontally.

After removing the lower 0mm distance the solver even claims the sketch to be overconstraint.

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Bug
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by bejant 2019-09-11 14:40
Here is another example of the Solver mistakenly arriving at a Fully Constrained solution when in fact 1 DOF remains in that the upper endpoints of the vertical line segments, and the entire horizontal line segment, can be moved vertically.   File is attached in the first post of the forum topic.
https://forum.freecadweb.org/viewtopic.php?f=3&t=39233#p333307

**Comment by maxwxyz** [comment] 2024-05-22 18:20
Duplicate of https://github.com/FreeCAD/FreeCAD/issues/8324

**Closed by maxwxyz** 2024-05-22 18:20 UTC
Labels: Bug, GCS, WB Sketcher
