### ISSUE TITLE
PartDesign::Thickness fails on more complex solids with "unknown exception"

### ISSUE THREAD

**Issue by diggit** [FreeCAD/FreeCAD#15063] opened 2024-06-30 13:30 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When some more complex shape is created (additive loft or just pad), PartDesign::Thickness fails with "unknown exception". 
```
fc_pd_loft_thickness_issue#Thickness001 thrown
Thickness001: Unknown exception!
```
No more details.
Minimal sample is attached.

### Full version info

```shell
OS: Arch Linux
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37923 (Git)
Build type: Release
Branch: main
Hash: 3b304e5b1a62f3119d7311aeb736dcb53cb4faad
Python 3.12.4, Qt 6.7.2, Coin 4.0.2, Vtk 9.3.0, OCC 7.7.2
Locale: C/Default (C)
Installed mods: 
  * Curves 0.6.40
  * sheetmetal 0.4.20
  * SheetMetal 0.4.18
```

### Subproject(s) affected?

None

### Anything else?

[fc_pd_loft_thickness_issue.FCStd.zip](https://github.com/user-attachments/files/16044818/fc_pd_loft_thickness_issue.FCStd.zip)

### body1
It is not possible to create inner nor outer thickness. Opened faces should be those flat ones. I am completely clueless why, but I'd guess it's something about angles between faces.

### body2
Thickness is applied. Is is set to 0.2 mm and increasing to 0.3 mm is not possible. Issue seems obvious. Thicker wall would cause selected "entry" face to be covered by generated thickness due to neighbor face angle.
![proposed_behavior](https://github.com/FreeCAD/FreeCAD/assets/512025/2331bb83-91f0-4cb7-99e7-23bd25b665e1)
Solution would be to not let the any generated "shell" materiel to enter the opening (red boundary) and rather create extra edge (yellow). I can't describe is better, but image is probably clear.

Even error like "Opened face covered due to neighbor face added thickness covers it" would be better.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment] 2024-06-30 14:58
Duplicate of https://github.com/FreeCAD/FreeCAD/issues/5829

**Closed by maxwxyz** 2024-06-30 14:58 UTC
