### ISSUE TITLE
Thickness limitation on curved geometry

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6055] opened 2022-02-07 19:35 UTC
Issue imported from https://tracker.freecad.org/view.php?id=4332

* **Reporter:** AlStu
* **Date submitted:** 5/1/2020
* **FreeCAD version:** 
* **Category:** Bug
* **Status:** new
* **Tags:** 

# Original report text

On file 04-29b, ***Thickness works well***: It is a boat Body with longitudinal symmetry. On PartDesign WB, it is made by lofting through 3 sketches. The sketches are on the same XZ plane but displaced by Y and Z Attachments. Each sketch has 3 lines and an arc. Thickness is Reversed true and Intersection true.

On file 04-29c, ***Thickness fails***: The Body is identical to above except that on 1 ("Rib mid") of the 3 sketches, 2 lines have been replaced by very shallow arcs. The arcs are so shallow that they visually appear straight. In more detail, Thickness works up to 3.60mm and fails at 3.70mm and above. The Report says "<App> Document.cpp(3715): Failed to recompute Nonsuch_04_29c#Thickness: BRep_API: command not done".

I first asked on the forum [here](https://forum.freecadweb.org/viewtopic.php?f=3&t=45642&p=391223&hilit=thickness+limitation#p391223) and was told to change from v0.18 to v0.19 and that worked for the file 04-29b. I later asked on the forum [here](https://forum.freecadweb.org/viewtopic.php?f=3&t=456[url=https://forum.freecadweb.org/viewtopic.php?f=3&t=45832&p=393115#p393115) and have not had a reply. I used PartDesign WB but still fails on Part WB. I have tried many variations in the geometry and settings, none improve the 3.60mm max Thickness limitation, most cause complete failure.

# Additional information

My fallback would be to make a plug and use binary subtraction, but that is a pain and the Thickness limitation will still exist.

# Steps to reproduce

Because of the sweeping shape of the curves involved to create this issue, easiest to just test on the attached files, 04-29c is the one which fails. They have already had AdditiveLoft. Select Face 2 (the top face) and try to Make a Thick Solid tool above 3.60mm.

# FreeCAD Info

```
OS: Windows 10 (10.0)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.20655 (Git)
Build type: Release
Branch: master
Hash: e8e67e8c5ebbc9f9ed9ea67aba5b891969595ece
Python version: 3.8.2
Qt version: 5.12.5
Coin version: 4.0.0
OCC version: 7.4.0
Locale: English/Canada (en_CA)

```

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Bug
* **OS: Windows 10 Home, kept up**
* **Platform:** Acer Aspire V, 8GB/512GB SSD
* **Updated:** 2/7/2021

# Discussion from Mantis ticket

### Comment by sfornengo 2020-06-07 10:43
Thickness is becoming unusable, always saying "BRep_API: command not done" or "BRep_Tool:: TopoDS_Vertex hasn't gp_Pnt" even with very small thickness eg 0.1mm

---

### Comment by sfornengo 2020-06-07 13:18
Here is the most simple geometry demonstrating thickness fail.
Try to make a thickness, selecting the face with no fillet to get a simple cap results in "BRep_API: command not done"

---

### Comment by @chennes 2021-02-07 21:23
For the record, this is still failing for me with OCC 7.5:
OS: Windows 10 Version 2004
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.23971 (Git)
Build type: Debug
Branch: master
Hash: a3fb41502b079a86175e6a414d82956a48bab4e2
Python version: 3.8.6+
Qt version: 5.15.1
Coin version: 4.0.1
OCC version: 7.5.0
Locale: English/United States (en_US)

**Comment by maxwxyz** [comment] 2024-06-30 14:57
Duplicate of https://github.com/FreeCAD/FreeCAD/issues/5829

**Closed by maxwxyz** 2024-06-30 14:57 UTC
Labels: Bug, Core, Thickness
