### ISSUE TITLE
Path toolbox operation order fails

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6115] opened 2022-02-07 20:35 UTC
Issue imported from https://tracker.freecad.org/view.php?id=4465

* **Reporter:** anka
* **Date submitted:** 10/18/2020
* **FreeCAD version:** 
* **Category:** Bug
* **Status:** confirmed
* **Tags:** 

# Original report text

Using drag and drop feature when rearranging job-path operations, moved operation gets detached from operations group.

# Steps to reproduce

The issue can be reproduced this way

In comboview
1. double-click on operations
2. drag operation downwards and drop 
3. click OK (operation disappears from list after dropping - gets detached from operations group) 

For illustrated steps, look here
https://forum.freecadweb.org/viewtopic.php?f=3&t=50161#p440189

# FreeCAD Info

```
OS: macOS 10.15
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.22670 (Git)
Build type: Release
Branch: master
Hash: 12155f4aab09047c5697db0c1b3cf93b02edda03
Python version: 3.8.6
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.4.0
Locale: C/Default (C)

```

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Bug
* **OS: OSX 10.16.7**
* **Platform:** MacOSx
* **Updated:** 2/6/2021

**Comment by luzpaz** [comment] 2022-02-11 13:07
bumped forum thread

**Comment by luzpaz** [comment] 2022-02-11 13:11
Per the forum the issue is presents on macOS

**Comment by sliptonic** [comment] 2022-03-22 02:51
Not isolated to mac.  This happens on all platforms.  At the present time there is no way to prevent dragging of only some items in the tree. Thus no solution is possible now. Closing with wontfix label.

**Closed by sliptonic** 2022-03-22 02:51 UTC
Labels: Bug, wontfix, WB Path
