### ISSUE TITLE
[Issue] "Recent files" not working - lists just one file

### ISSUE THREAD

**Issue by NielsJac** [FreeCAD/FreeCAD#7742] opened 2022-11-08 10:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.21 (Development)

### Full version info

```shell
OS: Linux Mint 20.3 (X-Cinnamon/cinnamon)
Word size of FreeCAD: 64-bit
Version: 0.21.
Build type: Release
Branch: unknown
Hash: 1282fdb7e8a721e9b411358d68daf8921b0bf50a
Python 3.8.10, Qt 5.12.8, Coin 4.0.0, Vtk 7.1.1, OCC 7.5.2
Locale: English/United States (en_US) [ OS: English/United States (en_US) ]
Installed mods: 
  * sheetmetal 0.2.58
  * Help 1.0.3
  * Part-o-magic 1.0.0
  * MeshRemodel 1.8919.0
  * Pyramids-and-Polyhedrons
  * CurvedShapes 1.0.4
  * Curves 0.5.13
  * DynamicData 2.46.0
  * Assembly4 0.12.4
  * Manipulator 1.4.9
```

### Issue description

The recent files list shows only one file, which is not the most recent. 

Workaround:
In Parameters, Preferences, RecentFiles:
I added empty Text values MRU1, MRU2 etc.  (Btw the "New string" dialog is buggy - I had to enter the new name twice.)
This workaround solved the problem. 
I hope this observation will help you find the bug.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment] 2022-11-10 11:58
Can't reproduce on 
```
OS: Ubuntu Core 20 (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.30921 (Git) Snap 417
Build type: Release
Branch: master
Hash: 7acc67ea43797441948b405cd0e925775b62eadf
Python 3.8.10, Qt 5.15.5, Coin 4.0.0, Vtk 7.1.1, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * TabBar
  * ExtremeProDark 2.3.3
  * FreeCAD-BlenderBIM 2022.10.20
```

Can you please open a forum thread and have others try to reproduce. I'm closing this ticket in the meantime so it doesn't rot. x-post the discussion back to this ticket please. Also open discussion about the buggy issue with new string as well so we can take a look at that.

**Closed by luzpaz** 2022-11-10 11:58 UTC
