### ISSUE TITLE
Task panel instability

### ISSUE THREAD

**Issue by Padou-fr** [FreeCAD/FreeCAD#17939] opened 2024-11-18 13:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I'm using FREECAD on a windows 10 computer with two screens, the main window is attached to one screen, the model, tasks and report panels on the second screen.
With each command where the parameters present in the task panel change, this panel goes down about ten pixels on the screen. 
It is therefore necessary to regularly move the panel up to the top of the screen in order to read all the informations contained therein.
This phenomenon appears on all 1.x versions I tried...

### Full version info

```shell
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.1.0dev.39100 (Git)
Build type: Release
Branch: main
Hash: 8865450a3e14220925e0e449c0f1f79056b4fb89
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: French/France (fr_FR)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * A2plus 0.4.60h
  * Assembly3 0.11.4
  * Assembly4 0.12.6
  * BIM021 2021.12.0
  * DynamicData 2.57.0
  * fasteners 0.5.21
  * Help 1.0.3
  * Manipulator 1.5.0
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment] 2024-11-18 13:47
Duplicate of https://github.com/FreeCAD/FreeCAD/issues/14650

**Closed by maxwxyz** 2024-11-18 13:47 UTC
Labels: Status: Needs triage
