### ISSUE TITLE
Std_Measure ambigious

### ISSUE THREAD

**Issue by berberic2** [FreeCAD/FreeCAD#14048] opened 2024-05-16 06:59 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The Std_Measure command always measures radius even if it is a full circle. In this case it looks like the diameter is measured, but in fact the radius is given.

![Screenshot_20240516_085349](https://github.com/FreeCAD/FreeCAD/assets/13178920/6a9d27a9-6b28-4293-8c5b-7216e2e01f09)

The label should be clear about this by stating `R 3,05 mm`.
There should also be an option in the tool to select diameter and display this as `⌀ 6,1 mm`

### Full version info

```shell
OS: Debian GNU/Linux 12 (bookworm) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37308 +3 (Git)
Build type: Release
Branch: Meins
Hash: 07abef38f457a54620b84a1709b15984f0eac6e2
Python 3.11.2, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: German/Germany (de_DE)
Installed mods: 
  * Assembly4 0.50.12
  * Pyramids-and-Polyhedrons
  * sheetmetal 0.4.11
  * Silk 0.1.5
  * CurvedShapes 1.0.9
  * DynamicData 2.62.0
  * FreeCAD_assembly3 0.11.3
  * fcgear 1.0.0
  * fasteners 0.5.21
  * Render 2024.1.23
  * A2plus
  * QuickMeasure 2022.10.28
  * ExplodedAssembly
  * Curves.backup1712652295.888766 0.6.29 (Disabled)
  * Curves 0.6.34
```

### Subproject(s) affected?

None

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment] 2024-05-16 07:42
This issue is a duplicate of https://github.com/FreeCAD/FreeCAD/issues/13710 and https://github.com/FreeCAD/FreeCAD/issues/13724

**Closed by maxwxyz** 2024-05-16 07:42 UTC
