### ISSUE TITLE
Sketch constraint flips direction

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5763] opened 2022-02-07 17:42 UTC
Issue imported from https://tracker.freecad.org/view.php?id=3348

* **Reporter:** Matael
* **Date submitted:** 2/13/2018
* **FreeCAD version:** 0.17
* **Category:** General
* **Status:** new
* **Tags:** 

# Original report text

see:
https://forum.freecadweb.org/viewtopic.php?p=214793#p214793
and
https://forum.freecadweb.org/viewtopic.php?f=22&t=24807&p=194839#p194816

In a nutshell:
-To avoid constraints to flip, you have to use Levenberg Marquardt solver
-Levenberg Marquardt solver don't care about expressions and Dogleg solver is used instead

# Other bug information

* **Priority:** low
* **Severity:** minor
* **Category:** General
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by Kunda1 2018-02-13 16:11
Should I move this to GCS category ?

**Comment by maxwxyz** [comment] 2024-02-26 15:47
Duplicate of https://github.com/FreeCAD/FreeCAD/issues/5555

**Closed by maxwxyz** 2024-02-26 15:47 UTC
Labels: GCS, WB Sketcher
