### ISSUE TITLE
Full round fillet

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5569] opened 2022-02-07 15:50 UTC
Issue imported from https://tracker.freecad.org/view.php?id=1192

* **Reporter:** din743
* **Date submitted:** 7/31/2013
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** acknowledged
* **Tags:** 

# Original report text

Option to create a fillet that is tangent to three adjacent faces.

# Additional information

Example from another CAD package: http://help.solidworks.com/2013/English/SolidWorks/sldworks/r_Full_Round_Fillets.htm

# Other bug information

* **Priority:** normal
* **Severity:** feature
* **Category:** Feature
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by normandc 2013-08-02 19:13
This might require to fix #5561 first.

**Comment by adrianinsaval** [comment] 2023-03-22 17:38
this is basically not doable unless occt implements it and has been inactive since 2013, I suggest closing

**Comment by grubertechnic** [comment] 2023-07-08 14:11
@adrianinsaval : at least it is a duplicate of #5561. Not 100%, but same origin, no full fillet possibilities in OCCT. So i also suggest closing.

**Comment by adrianinsaval** [comment] 2023-08-07 06:05
Is not really the same as that one, but since it's out of scope and not a useful ticket I'm closing anyways.

**Closed by adrianinsaval** 2023-08-07 06:05 UTC
Labels: WB PartDesign, Feature
