### ISSUE TITLE
[Problem] FreeCAD crashes while exporting to 3mf

### ISSUE THREAD

**Issue by volker-raschek** [FreeCAD/FreeCAD#12151] opened 2024-01-27 13:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I have designed a simple wrench. I would like to export it as a .3mf file. During the export FreeCAD crashes. 

FreeCAD was then started via terminal to be able to extract a StackTrace. Here are the logs: 

```bash
$ FreeCAD
FreeCAD 0.21.2, Libs: 0.21.2R33771 (Git)
© Juergen Riegel, Werner Mayer, Yorik van Havre and others 2001-2023
FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.
FreeCAD wouldn't be possible without FreeCAD community.
  #####                 ####  ###   ####  
  #                    #      # #   #   # 
  #     ##  #### ####  #     #   #  #   # 
  ####  # # #  # #  #  #     #####  #   # 
  #     #   #### ####  #    #     # #   # 
  #     #   #    #     #    #     # #   #  ##  ##  ##
  #     #   #### ####   ### #     # ####   ##  ##  ##

Sheet Metal workbench loaded
Program received signal SIGSEGV, Segmentation fault.
#0  /usr/lib/libc.so.6(+0x3e710) [0x717fc745c710]
#1  0x717fca6f1464 in Gui::SoQtOffscreenRenderer::writeToImage(QImage&) const from /usr/lib/freecad/lib/libFreeCADGui.so+0xd4
#2  0x717f89512726 in MeshGui::ThumbnailExtension3MF::addMesh(Mesh::MeshObject const&) from /usr/lib/freecad/lib/MeshGui.so+0x226
#3  0x717f89a5bb90 in Mesh::Exporter3MF::addMesh(char const*, Mesh::MeshObject const&) from /usr/lib/freecad/lib/Mesh.so+0xe0
#4  0x717f89a5260a in Mesh::Exporter::addObject(App::DocumentObject*, float) from /usr/lib/freecad/lib/Mesh.so+0x3fa
#5  0x717f89a5339d in Mesh::Module::exporter(Py::Tuple const&, Py::Dict const&) from /usr/lib/freecad/lib/Mesh.so+0x51d
#6  /usr/lib/freecad/lib/Mesh.so(+0x24c161) [0x717f89a4c161]
#7  /usr/lib/freecad/lib/libFreeCADBase.so(method_keyword_call_handler+0x3e1) [0x717fc96c66a1]
#8  /usr/lib/libpython3.11.so.1.0(+0x1fb2e1) [0x717fc91fb2e1]
#9  /usr/lib/libpython3.11.so.1.0(_PyObject_MakeTpCall+0x2bc) [0x717fc91da8ec]
#10  /usr/lib/libpython3.11.so.1.0(_PyEval_EvalFrameDefault+0x6d3) [0x717fc91e4c23]
#11  /usr/lib/libpython3.11.so.1.0(+0x29c484) [0x717fc929c484]
#12  /usr/lib/libpython3.11.so.1.0(PyEval_EvalCode+0xac) [0x717fc929be6c]
#13  /usr/lib/libpython3.11.so.1.0(+0x2b9fc3) [0x717fc92b9fc3]
#14  /usr/lib/libpython3.11.so.1.0(+0x2b63ea) [0x717fc92b63ea]
#15  /usr/lib/libpython3.11.so.1.0(PyRun_StringFlags+0x6d) [0x717fc92aaa3d]
#16  0x717fc9703d20 in Base::InterpreterSingleton::runString[abi:cxx11](char const*) from /usr/lib/freecad/lib/libFreeCADBase.so+0x70
#17  0x717fca4eac99 in Gui::Command::_runCommand(char const*, int, Gui::Command::DoCmd_Type, char const*) from /usr/lib/freecad/lib/libFreeCADGui.so+0x99
#18  0x717fca41ea77 in Gui::Application::exportTo(char const*, char const*, char const*) from /usr/lib/freecad/lib/libFreeCADGui.so+0x597
#19  0x717fca4ffe8c in StdCmdExport::activated(int) from /usr/lib/freecad/lib/libFreeCADGui.so+0x4ec
#20  0x717fca4eb13f in Gui::Command::_invoke(int, bool) from /usr/lib/freecad/lib/libFreeCADGui.so+0x1ef
#21  0x717fca4eb4f7 in Gui::Command::invoke(int, Gui::Command::TriggerSource) from /usr/lib/freecad/lib/libFreeCADGui.so+0x137
#22  /usr/lib/libQt5Core.so.5(+0x2d0e27) [0x717fc7cd0e27]
#23  0x717fc896bbb7 in QAction::triggered(bool) from /usr/lib/libQt5Widgets.so.5+0x47
#24  0x717fc897160b in QAction::activate(QAction::ActionEvent) from /usr/lib/libQt5Widgets.so.5+0xbb
#25  /usr/lib/libQt5Widgets.so.5(+0x2f437b) [0x717fc8af437b]
#26  /usr/lib/libQt5Widgets.so.5(+0x2f449d) [0x717fc8af449d]
#27  0x717fc89af1a1 in QWidget::event(QEvent*) from /usr/lib/libQt5Widgets.so.5+0x8d1
#28  0x717fc89788ff in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /usr/lib/libQt5Widgets.so.5+0x8f
#29  0x717fc897ddaf in QApplication::notify(QObject*, QEvent*) from /usr/lib/libQt5Widgets.so.5+0x10ff
#30  0x717fca4b6419 in Gui::GUIApplication::notify(QObject*, QEvent*) from /usr/lib/freecad/lib/libFreeCADGui.so+0x99
#31  0x717fc7c9bef8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /usr/lib/libQt5Core.so.5+0x128
#32  0x717fc897c0ea in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) from /usr/lib/libQt5Widgets.so.5+0x1ca
#33  /usr/lib/libQt5Widgets.so.5(+0x1cd9c4) [0x717fc89cd9c4]
#34  /usr/lib/libQt5Widgets.so.5(+0x1cec17) [0x717fc89cec17]
#35  0x717fc89788ff in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /usr/lib/libQt5Widgets.so.5+0x8f
#36  0x717fca4b6419 in Gui::GUIApplication::notify(QObject*, QEvent*) from /usr/lib/freecad/lib/libFreeCADGui.so+0x99
#37  0x717fc7c9bef8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /usr/lib/libQt5Core.so.5+0x128
#38  0x717fc814196c in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) from /usr/lib/libQt5Gui.so.5+0x6ec
#39  0x717fc812a6f5 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /usr/lib/libQt5Gui.so.5+0xb5
#40  /usr/lib/libQt5XcbQpa.so.5(+0x65560) [0x717fc1f40560]
#41  /usr/lib/libglib-2.0.so.0(+0x59f69) [0x717fc5f0df69]
#42  /usr/lib/libglib-2.0.so.0(+0xb83a7) [0x717fc5f6c3a7]
#43  /usr/lib/libglib-2.0.so.0(g_main_context_iteration+0x32) [0x717fc5f0c162]
#44  0x717fc7cead0c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /usr/lib/libQt5Core.so.5+0x6c
#45  0x717fc7c9ac04 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /usr/lib/libQt5Core.so.5+0x134
#46  0x717fc7c9c0a3 in QCoreApplication::exec() from /usr/lib/libQt5Core.so.5+0x93
#47  0x717fca4271cb in Gui::Application::runApplication() from /usr/lib/freecad/lib/libFreeCADGui.so+0x1c5b
#48  FreeCAD(+0x4e13) [0x60d9f1f57e13]
#49  /usr/lib/libc.so.6(+0x27cd0) [0x717fc7445cd0]
#50  /usr/lib/libc.so.6(__libc_start_main+0x8a) [0x717fc7445d8a]
#51  FreeCAD(+0x5fd5) [0x60d9f1f58fd5]
```

### Full version info

```shell
[code]
OS: Arch Linux (X-Cinnamon/cinnamon)
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: makepkg
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.11.6, Qt 5.15.11, Coin 4.0.1, Vtk 9.3.0, OCC 7.7.2
Locale: German/Germany (de_DE)
Installed mods: 
  * sheetmetal 0.4.0
  * A2plus 0.4.62
[/code]
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Syres916** [comment] 2024-01-27 13:19
This is a duplicate of https://github.com/FreeCAD/FreeCAD/issues/12091 which is under investigation, please close as such.

**Closed** 2024-01-27 13:19 UTC
