### ISSUE TITLE
Failed to parse expression

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5786] opened 2022-02-07 17:45 UTC
Issue imported from https://tracker.freecad.org/view.php?id=3448

* **Reporter:** JCR84J
* **Date submitted:** 4/29/2018
* **FreeCAD version:** 0.17
* **Category:** Bug
* **Status:** assigned
* **Tags:** 

# Original report text

refer to Forum post with subject:
"Failed to parse expression on opening a file"
https://forum.freecadweb.org/viewtopic.php?f=3&t=28431

Bug referred on demand of :

In my opinion this is a bug, so please register it in the tracker and reference this thread.

Eivind

# Steps to reproduce

Full Description, details and file are in Forum post with subject:

"Failed to parse expression on opening a file"
https://forum.freecadweb.org/viewtopic.php?f=3&t=28431

Don't hesitate to ask to forum member JCR84J if any difficulty.

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Bug
* **OS: Windows 10 1709**
* **Platform:** Microsoft
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by ezzieyguywuf 2019-12-03 01:30
This is a duplicate of [3272](https://freecadweb.org/tracker/view.php?id=3272). Please see my discussion [on this post](https://forum.freecadweb.org/viewtopic.php?f=8&t=40777&p=350774#p351035) in the forum.

Specifically, (and quoting from that thread):
> the issue, therefore, is not specific to the Spreadsheet module, but rather in one of:
> 
>     1. The Sketcher Module (perhaps it should not allow spaces in the names of constraints)
> 2. The ExpressionParser itself (should a valid Path be allowed to have a space in it?)
> 3. (maybe) App::ObjectIdentifier - should not allow spaces in path

**Comment by luzpaz** [comment] 2022-03-15 16:07
Dupe of #5750  
Closing

**Closed by luzpaz** 2022-03-15 16:07 UTC
Labels: Bug, duplicate, Expressions
