### ISSUE TITLE
Sketcher: Polyline generates error and breaks geometry if undoing when drawing

### ISSUE THREAD

**Issue by 0penBrain** [FreeCAD/FreeCAD#14127] opened 2024-05-18 13:16 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Steps to reproduce:
 * Empty sketch
 * Polyline tool, draw 2 subsequent segments (default mode)
 * Click "Undo" (or hit Ctrl+Z) => :confused: Last segment is removed but the start point of the preview line stays where it was
 * Click on the 1st endpoint (as to "close the shape") => :warning: A full bunch of errors appears in the Report View

### Full version info

```shell
OS: Ubuntu 22.04.4 LTS (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37361 +1 (Git)
Build type: Debug
Branch: myBranch
Hash: 761d8fc69d0d9a67d0a6cd4da8fdb35401c0a7e6
Python 3.10.12, Qt 5.15.3, Coin 4.0.0, Vtk 7.1.1, OCC 7.6.3
Locale: English/United States (en_US)
```

### Subproject(s) affected?

Sketcher

### Anything else?

Easier way to trigger the errors but less visual:
 * Empty sketch
 * Polyline tool, draw a first segment
 * Hit Ctrl+Z, then click to create a new segment

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment] 2024-05-18 14:14
Duplicate of https://github.com/FreeCAD/FreeCAD/issues/9789

**Closed by maxwxyz** 2024-05-18 14:14 UTC
