### ISSUE TITLE
automatic dogumentation is not generated

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6262] opened 2022-02-07 21:53 UTC
Issue imported from https://tracker.freecad.org/view.php?id=4749

* **Reporter:** GoodFeat
* **Date submitted:** 9/23/2021
* **FreeCAD version:** 0.19
* **Category:** Bug
* **Status:** feedback
* **Tags:** #tobeclosed

# Original report text

Hello, I am trying to go to python auto-generated documentation, but the documentation does not appear.
Instead of documentation, the error "connection interrupted" occurs

ERR_CONNECTION_RESET 

# Additional information

if you write any characters after the address, then the documentation gives an error, for example "http://localhost:7465/ab" 

# Steps to reproduce

1) run the fricad program
2) go to the help section
3) load the automatic documentation python module
4) there is a transition to the address http://localhost: 7465/

# FreeCAD Info

```
OS: Windows 10 Version 2009
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.24291 (Git)
Build type: Release
Branch: releases/FreeCAD-0-19
Hash: 7b5e18a0759de778b74d3a5c17eba9cb815035ac
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.0
Locale: Russian/Russia (ru_RU)

```

# Other bug information

* **Priority:** high
* **Severity:** minor
* **Category:** Bug
* **OS: Windows  10**
* **Platform:** PC
* **Updated:** 1/24/2022

# Discussion from Mantis ticket

### Comment by Kunda1 2022-01-24 19:20
GoodFeat I can't reproduce on
OS: Ubuntu Core 20 (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.27191 (Git)
Build type: Release
Branch: master
Hash: c4c81e6e697ec69adefccd44b9645d622ce61426
Python version: 3.8.10
Qt version: 5.15.3
Coin version: 4.0.0
OCC version: 7.5.2
Locale: English/United States (en_US)

Can you try reproducing on v0.20dev https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds

**Comment by yorikvanhavre** [comment] 2022-02-11 14:16
This works for me on 0.20/master on linux...
Closing this now because we cannot reproduce, please reopen if needed!

**Closed by yorikvanhavre** 2022-02-11 14:16 UTC
Labels: 🐛 bug, core
