### ISSUE TITLE
Disappearance of thumbnails on start page

### ISSUE THREAD

**Issue by Jorge-Ks** [FreeCAD/FreeCAD#18229] opened 2024-12-01 12:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

After updating the AppImage to version 39380, after rebooting, the thumbnails of the files on the home page were no longer visible, both recent and example files.

### Full version info

```shell
OS: Linux Mint 22 (X-Cinnamon/cinnamon/xcb)
Architecture: x86_64
Version: 1.1.0dev.39380 (Git) Conda AppImage
Build type: Release
Branch: main
Hash: 797c1180b012a8aee1d67de62880df0f835a731e
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: Spanish/Argentina (es_AR)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Fusion
Installed mods: 
  * fasteners 0.5.30
```

### Subproject(s) affected?

None

### Anything else?

![Captura de pantalla de 2024-12-01 09-35-35](https://github.com/user-attachments/assets/4e672930-8ebb-4a7f-91ce-a8d04d8b7241)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment] 2024-12-01 14:02
Duplicate of https://github.com/FreeCAD/FreeCAD/issues/13676

**Closed by maxwxyz** 2024-12-01 14:02 UTC
Labels: Status: Needs confirmation, Status: Needs triage

**Comment by hasecilu** [comment] 2024-12-01 16:29
@maxwxyz Could it be that is provoked by the Thumbnail Managing Standard commit just merged few days ago and not related with that old issue? My compilations have always shown the thumbnail until just last compilation in which that commit was added.

**Comment by MiqCG** [comment] 2024-12-03 08:30
@maxwxyz , it happens too with the most recent appimage (rev 39416) but not with revision 39315 (the previous to 39380), nor with 1.0.0. 

I also think that this could be related with the recent merge of wwmayer work, implementing support for Freedesktop’s Thumbnail Management Standard v0.8.0 in the Start page. The timing is very suspicious. 


```
OS: Devuan GNU/Linux 5 (daedalus) (XFCE/xfce/xcb)
Architecture: x86_64
Version: 1.1.0dev.39416 (Git) Conda AppImage
Build type: Release
Branch: main
Hash: f6268ffd2877dadb4440ade541e12c388a517d6e
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: Catalan/Spain (ca_ES)
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/Fusion
```

**Comment by MiqCG** [comment] 2024-12-03 18:37
Just for reference, this is the forum post about the same issue, where wwmayer has pointed out the origin of the problem:
https://forum.freecad.org/viewtopic.php?p=795185#p795185
