### ISSUE TITLE
FEM: Displacement mesh isn't generated after invoking FEM_FemMesh2Mesh

### ISSUE THREAD

**Issue by ss4workonly** [FreeCAD/FreeCAD#16011] opened 2024-08-22 20:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

1. Open FEMExample
2. Click CCX_Results_Mesh in a tree view
3. Click a FEM_FemMesh2Mesh button
4. See Mesh created

The issue is that a normal mesh is created instead of displacement one as described [here](https://wiki.freecad.org/FEM_FemMesh2Mesh).

 It looks like the root cause of the issue is in this [line](https://github.com/FreeCAD/FreeCAD/blob/40d23c26390ddb50b03fa597242135ce9de6edab/src/Mod/Fem/femmesh/femmesh2mesh.py#L171) as there is no `Name` property in myResults.

`        FreeCAD.Console.PrintMessage(f"{myResults.Name}\n")
`

### Full version info

```shell
OS: Ubuntu 24.04 LTS (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38495 (Git) AppImage
Build type: Release
Branch: main
Hash: 131956e201dc5033de69ed09c28db332feb081c1
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Russian/Russia (ru_RU)
```

### Subproject(s) affected?

FEM

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment] 2024-08-22 21:33
CC @FEA-eng

**Comment by FEA-eng** [comment] 2024-08-22 21:48
Deformed mesh can be saved only using Python (example script is included on the wiki).

**Comment by ss4workonly** [comment] 2024-08-23 17:13
If this is by design than the issue can be closed. Thank you.

**Comment by FEA-eng** [comment] 2024-08-23 17:41
Yes, but there is a PR that will change it: #15858. Hopefully soon.

**Comment by FEA-eng** [comment] 2024-08-26 07:20
@maxwxyz Can you change it to feature request or just close as a duplicate of #11301?

**Comment by maxwxyz** [comment] 2024-08-26 08:56
Duplicate of #11301

**Closed by maxwxyz** 2024-08-26 08:56 UTC
Labels: Type: Bug, Mod: FEM
