### ISSUE TITLE
Transparent Overlays: Panel names are always visible. Displayed twice when hovering

### ISSUE THREAD

**Issue by maxwxyz** [FreeCAD/FreeCAD#13349] opened 2024-04-07 06:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The title names of the panels / docked windows are always visible when using the transparent overlay mode:
![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/0bcdfdb5-d1df-4908-9c57-ed8b1277bec6)

When hovering the panels, they are even displayed twice. I'm not sure when this was added or why but a few weeks ago there were no default titles displayed as seen in a screenshot from https://github.com/FreeCAD/FreeCAD/issues/11794
![292187312-8a13965e-b6d1-4340-8571-09284c732721](https://github.com/FreeCAD/FreeCAD/assets/6246609/0dad4ff9-7c6c-4f7e-9602-09254f62e432)

### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36784 (Git)
Build type: Release
Branch: main
Hash: d1930fc7e6fc35c413f9f39d22f2ea28fca827c7
Python 3.11.8, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Installed mods: 
  * 3DfindIT 1.2.0
  * BIM 2021.12.0
  * CfdOF 1.25.10
  * CurvedShapes 1.0.8
  * Curves 0.6.29
  * Defeaturing 1.2.2
  * fasteners 0.5.16
  * FEMbyGEN 2.1.0
  * freecad.gears 1.2.0
  * freecad_metal_workbench 0.0.1
  * kicadStepUpMod 11.1.0
  * lattice2 1.0.0
  * OpenDark 2023.12.17
  * Rocket 3.3.0
  * sheetmetal 0.4.10
  * Silk 0.1.5
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jag45** [comment] 2024-04-07 09:37
This coincided with the following change:
![WIP Wednesday](https://github.com/FreeCAD/FreeCAD/assets/123576926/bd9f13f2-ce8f-489c-8d39-f8f420a5a3fa)

**Comment by maxwxyz** [comment] 2024-04-07 11:02
@LemonBoy can you confirm?

**Comment by PaddleStroke** [comment] 2024-04-08 07:46
+1 I can reproduce.
- Now we have 2 bars. 
- I agree the situation was better before. I do not see value of having the title bars displayed all the time. It was better when it shows only on hover.
- The new bar looks better imo. But it lacks the settings button. It also lacks the resize handle.

![image](https://github.com/FreeCAD/FreeCAD/assets/19984177/10049c4d-3499-462e-b4a9-926fa033f2f1)
Btw it would be better to remove the eye icon and the overlay icon and put these options in the 'settings' button.

**Comment by jag45** [comment] 2024-04-08 20:32
Tried with weekly 36228, only the one bar when you hover.
Tried with weekly 36277 (released 6th March), we have the situation above, ie. 2 bars.

As an aside , I cannot find lemonboy in the member list. However there is a lemonbug, (pretty close on the keyboard) so maybe the WIP Wednesday screenshot above has a typo on the user name.

**Comment by maxwxyz** [comment] 2024-04-19 19:32
@ayushgupta9906 any news on this?
@LemonBoy could you weigh in, was it introduced with your commit?

**Comment by MisterMakerNL** [comment] 2024-04-20 19:57
I just build the latest had similar issue added a gif where is visible here:
https://github.com/FreeCAD/FreeCAD/pull/12573 (which is probably related since it is also overlay UI stuff.)

**Comment by maxwxyz** [comment] 2024-04-20 19:58
@kadet1090 could you support here?

**Comment by maxwxyz** [comment] 2024-04-20 20:01
is https://github.com/FreeCAD/FreeCAD/pull/12530 to blame?

**Comment by MisterMakerNL** [comment] 2024-04-20 20:12
Double title seems to go away when you undock the widget, so maybe it has to do with:
`OverlayManager::onDockVisibleChange`
Or maybe it can be fixed with that function?

**Comment by kadet1090** [comment] 2024-04-21 20:47
> @kadet1090 could you support here?

I'll look into that this week hopefully

**Comment by maxwxyz** [comment] 2024-04-29 15:49
@kadet1090 do you need help with testing or anything else I could support?

**Comment by kadet1090** [comment] 2024-05-05 18:29
I fixed it in #13838, but only the issue with double header. Any remodeling of the header will need to be done in https://github.com/FreeCAD/FreeCAD/pull/11998 as current implementation is tape over tape...

**Comment by maxwxyz** [comment] 2024-05-05 18:32
nice, thanks!

**Comment by MisterMakerNL** [comment] 2024-05-05 22:28
Finally the double header it's gone! Tnxs!!!

**Closed** 2024-05-06 16:26 UTC
Labels: Core, UI/UX, Regression, Status: confirmed

**Comment by MisterMakerNL** [comment] 2024-05-06 19:15
Well it is fixed a bit sometimes :)
Needs some work!
