### ISSUE TITLE
Body placement not respected when exporting to STL

### ISSUE THREAD

**Issue by Seahorde** [FreeCAD/FreeCAD#12278] opened 2024-02-07 06:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I have a model with parts, bodies and features. Some parts and bodies have placement set: axis, angle and position. The model displays perfect when in freecad application. Once I export it to STL, I see that the body placements aren't respected and bodies that have position set are rendered in wrong places.

When I set the body placement to zeroes and transfer offsets to the sketch placements inside the body, everything looks OK in the exported STL.

### Full version info

```shell
0.21.2 rev 33771
```

### Subproject(s) affected?

File formats

### Anything else?

Here's an example. The "Connector" body is affected:
[Oil Funnel.FCStd.zip](https://github.com/FreeCAD/FreeCAD/files/14190018/Oil.Funnel.FCStd.zip)

Looks OK in FreeCAD app:
![Freecad-issue-FC-app](https://github.com/FreeCAD/FreeCAD/assets/132248189/011eb068-20f8-4f78-a787-4cbbeec25491)

STL is broken:
![Freecad-issue-STL](https://github.com/FreeCAD/FreeCAD/assets/132248189/357995df-7518-4cf4-b67c-2a82df420afb)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Seahorde** [comment] 2024-02-07 08:13
In the example above the placement angle of the bodies isn't respected as well.

**Comment by Syres916** [comment] 2024-02-08 12:45
@Seahorde while I agree this appears to be a legitimate bug and should be investigated as such, you have modeled a single contiguous solid (judging by the FreeCAD screenshot) and yet you have used more than one Body and even used Part containers, all of which is unnecessary IMHO.

Part containers are where two or more non-contiguous solids are being 'assembled' so for example a plate with four tapped holes and the four fasteners that must be aligned with the plate at all times would be a perfectly acceptable use.

If you are struggling to understand how to model this as one contiguous solid then perhaps the [forum ](https://forum.freecad.org/viewforum.php?f=3) might be a good place to ask, there's plenty of PartDesign power users who will be able to advise if it's possible.

**Comment by MisterMakerNL** [comment] 2024-02-09 21:01
Works fine in 0.22 when you move the parts out of the part:
![image](https://github.com/FreeCAD/FreeCAD/assets/29804962/d04f8045-abf6-4ffa-b2cd-50a0a7fbd83a)
Please don't put parts in your parts so you can do parts in your parts.
Freecad is confusing enough without this :)

**Comment by Seahorde** [comment] 2024-02-10 09:13
I put different components into separate Bodies because:
a) Having a complex body with 10x features isn't practical as the tip easily rips apart when I'm modifying some internal features. Not to mention filets and chamfers - they are almost 100% times ruined if the source sketch and features get changed.
b) I want to shift/rotate a group of features and paint them different color. Putting them into an extra Body works the best.

BTW, I needed to re-export a model I've worked on a year ago and exported into 3mf. Now I need to export it to STL. I opened it with the recent FreeCAD, exported and immediately saw that the bug I'm talking about here is a regression. It wasn't there a year ago.

FreeCAD 0.21.2:
![image](https://github.com/FreeCAD/FreeCAD/assets/132248189/d1506cfc-b443-44fc-87ec-77fa24611333)

STL:
![image](https://github.com/FreeCAD/FreeCAD/assets/132248189/711d4958-12a9-4bde-9540-d5bb63e6f321)

**Comment by Seahorde** [comment] 2024-02-10 09:19
A workaround: Create a Part wrapper around all bodies and transfer the body positioning to the wrapper part. It's ugly, but it at least works.

![image](https://github.com/FreeCAD/FreeCAD/assets/132248189/9a4c3161-25dc-4950-a617-d4e4a47a8a6c)

**Comment by maxwxyz** [comment] 2024-02-11 15:29
@Seahorde is it working in the current dev versions for you?

**Comment by Syres916** [comment] 2024-02-11 19:18
@maxwxyz the whole issue of implications of Part containers has been going on for a number of years and as MisterMakerNL comment https://github.com/FreeCAD/FreeCAD/issues/12278#issuecomment-1936596523 using 0.22 is still not fixed. I'd love to go back and from version 0.16 see when the misbehaviour started but that's quite a bit of work in it's own right testing all the different scenarios, not just this one. Someone reported that 11 tree depth is OK but as soon as they went to 12 deep really weird things start to play out but again I cannot prove that yet and when it started.

Even importing a known good Step assembly which has all the part containers pre-populated results in odd components looking like they've tried to escape, 99% are properly assembled!! I just never use Part containers as I cannot trust what behaviour they are going to create.

**Comment by boucaron** [comment] 2024-03-16 21:54
In my case, I used the following workaround : export as OBJ, reimport the OBJ and finally export as STL. 

I had the issue on Extruded sketches. On those sketches I performed a transformation : in one case on the position, and the other case it was both the position and the rotation.

**Comment by SergiiChernov** [comment] 2024-03-24 12:09
> In my case, I used the following workaround : export as OBJ, reimport the OBJ and finally export as STL.
> 
> I had the issue on Extruded sketches. On those sketches I performed a transformation : in one case on the position, and the other case it was both the position and the rotation.

In my case *(0.21.2) obj fails as miserably as stl but step seems to work... so far.
Absolutely awful and unacceptable bug that stays unfixed for years.

**Comment by sylvainbarriere** [comment] 2024-05-23 17:35
Same issue really annoying , seems not present in version 0.21.1 so I open 0.21.1 instance to export my part

**Comment by languagelawyer** [comment] 2024-06-01 11:45
Happens to me in 0.21.2 (b9bfa5c5507506e4515816414cd27f4851d00489), doesn't in a ±fresh daily build (0.22.0dev 7d6e9b19fb6a5a5d4f29ef8c95ff43848648d9dd)

**Comment by maxwxyz** [comment] 2024-06-01 11:52
@Seahorde could you confirm that this is working in the latest weekly from: https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds

**Comment by Seahorde** [comment] 2024-06-02 21:50
@maxwxyz I tried a simple test with two displaced bodies and indeed, the STL export looks correct now! Wow!
I will do some more modeling soon and let you know if I find any issues.

**Comment by CamNorm** [comment] 2024-06-08 16:22
Same trouble with 3d objects create with the partdesign tool:
Exported with the 0.19 Freecad version works perfect, but the same Fcad file export from 0.21.2 bugs

My model in FreeCAD
![image](https://github.com/FreeCAD/FreeCAD/assets/172133707/f0679d61-6532-4958-8892-4063efb4d11a)
The exported STL with 0.19
![image](https://github.com/FreeCAD/FreeCAD/assets/172133707/128d0ea4-806f-4fe7-a618-846af0092aea)
The exported STL with 0.21.2
![image](https://github.com/FreeCAD/FreeCAD/assets/172133707/ef97ef01-d5e8-4c05-90d3-eed32a401b82)

**Comment by luzpaz** [comment] 2024-07-31 21:27
Per the discussion, this issue is fixed in the latest development 0.22.x version. A fix won't be backported to 0.21.x

**Comment by winstonford** [comment] 2024-11-15 01:55
Having a similar issue in 1.0rc4 when exporting to DXF.  Body placement not respected when exporting to DXF.  However, there is no issue when exporting same file in latest stable 0.21.2

I create a new file in 1.0rc4 and in sketcher create a sketch with a centered fully constrained square.  I create another sketch with a centered fully constrained circle inside the square and concentric with it.

With the circle sketch selected, In the data pane under Position, I set X to move circle outside square.

I select both sketches and export to dxf.  I open the dxf in librecad, Inkscape, and sharecad.  The circle is back inside the square.  It should be outside the square, but the position is not respected.

I open the file in 0.21.2 and repeat export and open steps.  There is no issue, the circle is outside the box.

The file and the 2 exported dxf files are attached.

[outside-the-box.zip](https://github.com/user-attachments/files/17760371/outside-the-box.zip)

**Comment by luzpaz** [comment] 2024-11-15 10:50
@winstonford full [About](https://wiki.freecad.org/About) info please

**Comment by maxwxyz** [comment] 2024-11-16 06:30
I cannot reproduce the original issue in the latest weekly
```
OS: Windows 11 build 26100
Architecture: x86_64
Version: 1.1.0dev.39176 (Git) Conda
Build type: Release
Branch: main
Hash: 45d3864942c6928cec7dc18f95b1f222485756e5
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: German/Germany (de_DE)
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/Fusion
Installed mods: 
  * CfdOF 1.27.14
  * Curves 0.6.51
  * dodo 1.0.1
  * fasteners 0.5.29
  * freecad.gears 1.3.0
  * Manipulator 1.5.7
  * OpenTheme 2024.9.1
  * OpticsWorkbench 1.0.26
  * Rocket 4.0.1
  * sheetmetal 0.5.3
  * Silk 0.1.5

```

The new comment is about DXF export, not STL - not sure if reopening this STL issue is the best idea. @winstonford could you please open a new issue for this? Maybe there is a similar already reported: https://github.com/FreeCAD/FreeCAD/issues?q=is%3Aissue+is%3Aopen+dxf+export+label%3A%22File+format%3A+DXF%22

**Closed by maxwxyz** 2024-11-16 06:30 UTC
Labels: Type: Bug, Mod: Core, Mod: Part, Topic: User Interface, File format: STL
