### ISSUE TITLE
[Problem] Strange diaphragm artifact.

### ISSUE THREAD

**Issue by vovodroid** [FreeCAD/FreeCAD#12570] opened 2024-02-23 19:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Strange artifact (like a diaphragm) appears

![image](https://github.com/FreeCAD/FreeCAD/assets/8691781/a65558b0-4dcc-4343-b5d5-ba34aa549809)

Just open the attached project.

Also exported STEP can't be open in PrusaSlicer (Error is "zero object size").

### Full version info

```
OS: Windows 10 build 19044
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36082 (Git)
Build type: Release
Branch: main
Hash: 7a025e4e60a607bdbdd1599627ce13bb8eeda071
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: English/Israel (en_IL)
Installed mods: 
  * Curves 0.6.13
  * ThreadProfile 1.87.0
```

### Subproject(s) affected?

None

### Anything else?

[mount.zip](https://github.com/FreeCAD/FreeCAD/files/14389581/mount.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment] 2024-02-23 19:44
@vovodroid please refine your issue as it is not clear what the problem is or how to reproduce it. You can also try to reproduce this in the current weekly builds: https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds

**Comment by vovodroid** [comment] 2024-02-23 19:48
Ok, I updated the picture. Just open the project and you will see it.

**Comment by vovodroid** [comment] 2024-02-23 19:59
The same in latest (0.22.0dev.36082) dev version.

**Comment by maxwxyz** [comment] 2024-02-24 07:03
@vovodroid it seems like your Pad004 feature is already broken which may lead to this error. If you recompute, this is the result:
![image](https://github.com/FreeCAD/FreeCAD/assets/6246609/32e4b0f4-69b4-4350-b46e-95653680edfb)
So it seems your Sketch007 is corrupted, try again and delete the Pad and the sketch and redraw this.
Your fillets had also some issues.

I've redone it here: 
[mount_corrected.zip](https://github.com/FreeCAD/FreeCAD/files/14392026/mount_corrected.zip)


I'll close this issue now as there is no bug identified.

**Closed by maxwxyz** 2024-02-24 07:03 UTC
Labels: Missing: tested on dev version, Missing: clear title
