### ISSUE TITLE
[Problem] When I resize the Combo View, it leaves behind a vertical line

### ISSUE THREAD

**Issue by K4LCIFER** [FreeCAD/FreeCAD#9914] opened 2023-07-13 01:30 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
[code]
OS: KDE Flatpak runtime (KDE/plasmawayland)
Word size of FreeCAD: 64-bit
Version: 0.20.2.29603 (Git)
Build type: Release
Branch: (HEAD detached at 0.20.2)
Hash: 930dd9a76203a3260b1e6256c70c1c3cad8c5cb8
Python 3.10.6, Qt 5.15.9, Coin 4.0.0, Vtk 8.2.0, OCC 7.6.3
Locale: English/Canada (en_CA)
[/code]
```

### Subproject(s) affected?

None

### Problem description

When I drag the combo view to resize it, it leaves behind a vertical line as shown below:
![image](https://github.com/FreeCAD/FreeCAD/assets/7829231/beff7bd5-82eb-4e22-afb8-70d7041de881)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by K4LCIFER** [comment] 2023-07-13 02:11
This appears to be an issue with the "ProDark" theme. When I switch away from this theme to, for example, "Darker-Orange", the problem goes away.

**Comment by Jamtek** [comment] 2023-07-24 11:22
I am seeing this on recent conda build in 0.21 on my M2 MacBook. I also see a horizontal line after resizing report view and or python console.

https://forum.freecad.org/viewtopic.php?t=79877

```
[code]
OS: macOS 13.4.1
Word size of FreeCAD: 64-bit
Version: 0.21.0.33631 (Git)
Build type: Release
Branch: master
Hash: 2167fb6f7ec6ac5c2f6365d4c3035d2db6879b1e
Python 3.11.0, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * A2plus 0.4.60n
  * fasteners 0.4.58
  * Curves 0.6.12
[/code]
```

**Comment by luzpaz** [comment] 2023-07-25 10:44
@MisterMakerNL is this a phenomena you've encountered too ?

**Comment by MisterMakerNL** [comment] 2023-07-25 18:53
@K4LCIFER Could you test it with this stylesheet:
https://github.com/MisterMakerNL/Freecad-Built-in-themes-beta/blob/main/Dark%20theme%20beta/Test_stylesheet.qss
You can also install beta stylesheets true the addon explorer.

**Comment by mfro0** [comment] 2023-07-26 11:47
Tested with the provided stylesheet - problem still exists (contrary to @K4LCIFER 's statement above, for me the graphics glitch also appears for me with other stylesheets as well),

As soon as you move the vertical divider between the combo view and the view right to it (it doesnt't seem to matter if that is a graphics view or anything else), a line appears that seems to be a leftover of the divider.

Note the vertical line in attached screenshot. It stays at the exact place it appeared at the first combo view resize and doesn't go away even if you move the window border later.

![image](https://github.com/FreeCAD/FreeCAD/assets/18102882/628a9d47-a131-40b1-95b2-6c9d9c75f756)

[edit: I just realised this also happens when resizing any other (also horizontal) divider.

![image](https://github.com/FreeCAD/FreeCAD/assets/18102882/a892fe0d-b478-482a-85a5-5b0a3698ed52)

Might be pure coincidence, but note that I recently ditched Gnome in favour of KDE and I'm unable to tell if I have seen this glitches with the former (might just as well be related to a recent FreeCAD change)

```
OS: Ubuntu 22.04.2 LTS (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33639 (Git)
Build type: Release
Branch: master
Hash: 1580fe7c9696654803a93da8cf372f75e75149fa
Python 3.10.6, Qt 5.15.3, Coin 4.0.0, Vtk 7.1.1, OCC 7.8.0.dev
Locale: C/Default (C)
Installed mods: 
  * lattice2 1.0.0
  * Assembly4 0.50.2
  * CurvedShapes 1.0.4
  * Curves 0.6.8
  * Silk 0.1.3
  * Behave-Dark-Colors 0.1.1
```

**Comment by yorikvanhavre** [comment] 2023-07-26 12:19
I had this problem before too, but with @MisterMakerNL's new versions the problem has disappeared (Debian+Gnome)

**Comment by mfro0** [comment] 2023-07-26 14:02
For me, the problem goes away with "no style sheet" selected from the preferences. So it's probably not related to code.

**Comment by adrianinsaval** [comment] 2023-07-26 14:23
maybe you have leftover settings from gnome that are messing up your system, what qt theme do you have configured in KDE? what is the result of running `echo $QT_QPA_PLATFORMTHEME` in your terminal? Try setting it to "kde" if it isn't already

**Comment by MisterMakerNL** [comment] 2023-07-26 14:48
If you zoom in on the line it shows as a gradient, so I added a color to all gradients to check what gradient is causing it.

There are no borders in the theme with that color so it's a background. But I have some borders thay are set to 0 or transparent I think that maybe is the issue. I'll clean up the test stylesheet from any borders that are not vissible.

**Comment by MisterMakerNL** [comment] 2023-07-26 19:24
I think I found the line in my view, it is replaced in your screenshot by a colored line.
Which is weird.
But the line I see looks to be the line you see floating.
![afbeelding](https://github.com/FreeCAD/FreeCAD/assets/29804962/4c82ee30-2990-4c26-b1e9-35a863bceb98)

**Comment by MisterMakerNL** [comment] 2023-07-26 19:49
Could you test the addon, even if it didn't fixed it, it looks a lot cleaner now. I updated all stylesheets.
https://github.com/MisterMakerNL/Freecad-Built-in-themes-beta/commit/ff84c20f3174829b760697717f49136ca762b8a0

**Comment by mfro0** [comment] 2023-07-26 20:46
did you change Test_stylesheet.qss as well? That doesn't seem to change anything. Artifact is still there.

**Comment by MisterMakerNL** [comment] 2023-07-30 18:13
Could you test it again with the addon, and delete the addon or uninstall it instead of updating it. 
Mine also didn't update although it said it did.
It should look like this:
![afbeelding](https://github.com/FreeCAD/FreeCAD/assets/29804962/d84a5169-bb3d-447e-a33a-42f5900e1999)

**Comment by Jamtek** [comment] 2023-08-01 01:03
On my Macbook ARM, I noticed that the lines are not visable if I select 'No Display sheet' or 'Behave-dark' with Classic theme or Light Theme.

I would also note that the Combo view area with no sytlesheet still appears as a dark theme.
![Screenshot 2023-07-31 at 8 59 12 PM](https://github.com/FreeCAD/FreeCAD/assets/35613772/fba07220-3548-44ec-ba3d-371f67f51019)

The Task view under the Combo view has a white background and a mixture of white and gray text.
![Screenshot 2023-07-31 at 9 01 25 PM](https://github.com/FreeCAD/FreeCAD/assets/35613772/ffd23327-16c1-4f53-bec5-ce058d9eef44)

**Comment by MisterMakerNL** [comment] 2023-08-01 16:49
@Jamtek I don't think those issues are related to this issue. I also have no idea what is going on, so far as I understand Freecad on Linux and Mac follows the system style. That is probably why it is dark.
I think you might need too restart after changing to no-stylesheet.

**Comment by MisterMakerNL** [comment] 2023-08-03 19:11
Bumb can someone test if this issue is still present in the addon version:
https://github.com/MisterMakerNL/Freecad-Built-in-themes-beta

**Comment by Jamtek** [comment] 2023-08-04 18:10
Thanks @MisterMakerNL - Still seeing lines [Freecad-Built-in-themes-beta] M2 Mac, when using 'Dark theme beta, Light theme beta with the assigned stylesheets. If I change to No stylesheet the lines no longer appear.

```
OS: macOS 13.4.1
Word size of FreeCAD: 64-bit
Version: 0.21.0.33675 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.0)
Hash: 41b058e2087de60dc8fef3d3e68c7d0129e13abf
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: C/Default (C)
Installed mods: 
  * Freecad-Built-in-themes-beta 1.2.0
```
![Screenshot 2023-08-04 at 1 57 00 PM](https://github.com/FreeCAD/FreeCAD/assets/35613772/680bbb6f-1094-4a33-9b7b-9e1d82dc0b8a)

![Screenshot 2023-08-04 at 2 03 15 PM](https://github.com/FreeCAD/FreeCAD/assets/35613772/4fb2f457-7a67-4eaa-9781-77288eb3a177)

**Comment by luzpaz** [comment] 2023-10-11 20:10
@Jamtek can you test in dev version to see if issue is still reproducible (but using MisterMakerNL's workabour stylesheets ?

**Comment by MisterMakerNL** [comment] 2023-10-11 20:30
I have not been able too reproduce thi, which makes it very annoying and hard too fix.
But yesterday a new overlay system was pushed, hopefully tackeling this bug in the process.

**Comment by Jamtek** [comment] 2023-10-13 01:47
@luzpaz ,
I am happy to report I am no longer seeing the vertical or horizontal lines when resizing the frames on my M2 Macbook air. Tested the ExtremeProDark, ExtremeProLight and the new OpenDark preference packs. 

```
OS: macOS 14.0
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.34651 (Git)
Build type: Release
Branch: main
Hash: aa5bea4e2e8089bf00f61075a0860dacda42dc8b
Python 3.11.0, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * OpenDark 2023.10.2
  * A2plus 0.4.60n
  * BIM 2021.12.0
  * fasteners 0.4.66
  * ExtremeProDark 2.9.0
  * ExtremeProLight 1.6.0
  * Curves 0.6.13
```
Thanks @MisterMakerNL!

**Comment by luzpaz** [comment] 2023-10-13 01:51
@K4LCIFER @mfro0 can y'all reproduce on latest dev version ?

**Comment by luzpaz** [comment] 2023-10-13 12:56
Closed #8197 as a dupe of this more active ticket.

**Comment by luzpaz** [comment] 2023-10-13 13:16
Closing this ticket as well unless any one else can reproduce. If so, please re-open ticket.

**Closed by luzpaz** 2023-10-13 13:16 UTC
Labels: UI/UX, Missing: feedback, Stylesheets, Missing: diagnosis

**Comment by X-Ryl669** [comment] 2023-10-19 13:40
Probably also linked, right button menu background is transparent and this is really disturbing.
![image](https://github.com/FreeCAD/FreeCAD/assets/3277165/742338c3-12cf-49c6-a5ee-9b256d2a8789)

**Comment by MisterMakerNL** [comment] 2023-10-19 14:41
Extreme pro is outdated and I am going to remove it. It's replaced by modern style in freecad.
Latetst version has a complete new interface with the ovetlay, changes this still in are very small. Although if someone her is able to test the latest dev version to test this bug that would be nice!

**Comment by X-Ryl669** [comment] 2023-10-19 14:48
I am able to test it, if only I knew what and how to test it. 

I've used the addon manager in Freecad to update the theme then cycled through all dark version of them and none worked (see above for the list of themes I've tried). What should I change to test the last version so it's useful for you to debug?

**Comment by MisterMakerNL** [comment] 2023-10-19 15:54
@X-Ryl669 I think the weekly build has the overlay:
https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds
Not sure if it got my latest PR for the theme's.

**Comment by obelisk79** [comment] 2023-10-20 18:39
@X-Ryl669 is the behavior also present with OpenDark (available in addon manager)?

**Comment by X-Ryl669** [comment] 2023-10-20 19:39
The weekly build doesn't have any issue (0.22dev), so I guess it's not worth fixing it for 0.21 if it's already going away in next release.

I haven't tried OpenDark.

**Comment by morphlaugh** [comment] 2024-02-02 04:20
@obelisk79 I am seeing the same issues he reported on 0.21.2 for Mac Intel.  The problem goes away with OpenDark.

**Comment by obelisk79** [comment] 2024-02-02 04:31
> @obelisk79 I am seeing the same issues he reported... I am on 0.21.2 for Mac Intel. The problem goes away with OpenDark.

Thanks for the update. I think we are only a couple of months out from the next release where this is supposedly already fixed. I'm glad to hear that OpenDark addresses the issue though. I'm quite close to an initial release of OpenLight, so if dark themes aren't your preferred style there should be another option.
