### ISSUE TITLE
BIM: Warning when switching to strict IFC mode (Feature Request)

### ISSUE THREAD

**Issue by kaiwas** [FreeCAD/FreeCAD#17441] opened 2024-10-24 05:50 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When we switch to the strict IFC mode, the entire document is converted to a completely different format. All the developments inherent to the freecad approach are lost irretrievably (sketches disappear, properties inherent to freecad components disappear, etc.) - only the IFC structure remains.

But at the moment of switching, no one is warned about this.

I suggest implementing a pop-up message with a warning. Something like what is shown in the picture.

![switch IFC](https://github.com/user-attachments/assets/7f5d06fd-eea2-41e3-834c-f3a6885a0fcd)

And at the moment there is no 100% way to go back if a switch has occurred. Undoing an action often causes errors.

https://github.com/user-attachments/assets/34feb48a-fd43-42da-ab9e-5206014caf3e

This is probably a separate issue, but that is why a warning is needed.

### Full version info

```shell
OS: Manjaro Linux (KDE/plasma/xcb)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.39024 (Git) AppImage
Build type: Release
Branch: main
Hash: cf8ad6637351819dfa07d49cfd65d511fe14a084
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: Russian/Russia (ru_RU)
Stylesheet/Theme/QtStyle: OpenLight.qss/OpenLight/Fusion
Installed mods: 
  * lattice2 1.0.0
  * PitchedRoof
  * addFC 0.7.4
  * OpenTheme 2024.9.1
```

### Subproject(s) affected?

BIM

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment] 2024-10-24 07:37
Duplicate of https://github.com/FreeCAD/FreeCAD/issues/17147

**Closed by maxwxyz** 2024-10-24 07:37 UTC
Labels: Status: Needs triage
