### ISSUE TITLE
Regression: Attachment mode FlatFace not working on DatumPlanes

### ISSUE THREAD

**Issue by chrisb-github** [FreeCAD/FreeCAD#12942] opened 2024-03-13 23:44 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Sketches attached with mode FlatFace to a DatumPlane show an error in the version indicated below.
- it worked in 0.21
- it is the natural way of attaching a sketch: select the DatumPlane and create a sketch.

To reproduce:
- switch to PartDesign
- create a body
- create a DatumPlane
- select the DatumPlane
- create a sketch
- add some geometry, perhaps it isn't even necessary to do this
- close Sketcher

-> error "Sketch: Null face in AttachEngine3D::calculateAttachedPlacement()!"

### Full version info

```shell
OS: macOS 13.0
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36391 (Git)
Build type: Release
Branch: main
Hash: 52fffaf50ef8facea2ecfde23d6f1a7d3ad3d80c
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: C/Default (C)
Installed mods: 
  * FC_SU
  * freecad.gears 1.2.0
  * FeedsAndSpeeds 0.5.0
  * dxf-library
  * fasteners 0.5.13
  * sheetmetal 0.4.2 (Disabled)
  * ExplodedAssembly
  * Curves 0.6.24
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment] 2024-03-14 18:13
Duplicate of https://github.com/FreeCAD/FreeCAD/issues/12880

**Closed by maxwxyz** 2024-03-14 18:13 UTC
Labels: needs triage
