### ISSUE TITLE
[Problem] Crash when filleting edge in PartDesign

### ISSUE THREAD

**Issue by ozzyman** [FreeCAD/FreeCAD#10472] opened 2023-09-01 01:34 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Full version info

```shell
OS: Ubuntu Core 20 (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.21.1.33668 +26 (Git) Snap 759
Build type: Release
Branch: tag: 0.21.1
Hash: f6708547a9bb3f71a4aaade12109f511a72c207c
Python 3.8.10, Qt 5.15.7, Coin 4.0.0, Vtk 7.1.1, OCC 7.6.3
Locale: English/Australia (en_AU)
Installed mods: 
  * kicadStepUpMod 10.19.4
  * CfdOF 1.21.7
  * OpticsWorkbench 1.0.9
  * CfdOF.backup1691301479.913904 1.21.7 (Disabled)
  * OSE3dPrinter
  * freecad.gears 1.0.0
  * sheetmetal 0.2.63
  * fasteners 0.4.59
  * 3D_Printing_Tools
  * POV-Ray-Rendering
  * Lithophane
```

### Subproject(s) affected?

PartDesign

### Problem description

Similar to issue #09000. I'm not using any external workbench however.

Filleting the indicated edge causes a hard crash. Just selecting the edge in the fillet dialog also causes an instant crash.

Steps to reproduce:

1. Open the attached part in FreeCAD
2. Select Part Design workbench
3. Select the edge (or any edge on the rear face of either slot)
4. Click the fillet tool
5. Crash

Selecting the fillet tool and then the edge also results in a crash. 

### Anything else?

![image](https://github.com/FreeCAD/FreeCAD/assets/4989367/a0ef68d7-bd13-4e13-b6b5-b37bc3f5c633)

[part.zip](https://github.com/FreeCAD/FreeCAD/files/12492023/part.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment] 2023-09-01 01:42
> Similar to issue https://github.com/FreeCAD/FreeCAD/pull/900. I'm not using any external workbench however.  

How is 900 related ?

**Comment by ozzyman** [comment] 2023-09-01 02:18
#9000

**Comment by luzpaz** [comment] 2023-09-01 02:29
9000 is a dupe of #8179

**Comment by grubertechnic** [comment] 2023-09-01 08:36
#9000 and #8179 the stacktrace looks pretty different.

in that case, it is more duplicate from #8179, the stacktrace is the same.

```
Err: Program received signal SIGSEGV, Segmentation fault.
Err: #0  /lib/x86_64-linux-gnu/libc.so.6(+0x3bfd0) [0x7ff48c25afd0]
Err: #1  0x7ff4340d2b64 in BRep_Tool::CurveOnSurface(TopoDS_Edge const&, opencascade::handle<Geom_Surface> const&, TopLoc_Location const&, double&, double&, bool*) from /lib/x86_64-linux-gnu/libTKBRep.so.7+0x164
Err: #2  0x7ff4340d2c3a in BRep_Tool::CurveOnSurface(TopoDS_Edge const&, TopoDS_Face const&, double&, double&, bool*) from /lib/x86_64-linux-gnu/libTKBRep.so.7+0xaa
Err: #3  0x7ff4340df8a5 in BRepAdaptor_Curve2d::Initialize(TopoDS_Edge const&, TopoDS_Face const&) from /lib/x86_64-linux-gnu/libTKBRep.so.7+0xd5
Err: #4  0x7ff3a833ea70 in ChFi3d_Builder::StartSol(opencascade::handle<ChFiDS_Spine> const&, opencascade::handle<BRepAdaptor_Surface>&, gp_Pnt2d&, opencascade::handle<BRepAdaptor_Curve2d>&, double&, opencascade::handle<ChFiDS_SurfData> const&, bool, int, opencascade::handle<BRepAdaptor_Surface>&, opencascade::handle<BRepAdaptor_Curve2d>&, bool&, bool&, bool&, bool&, opencascade::handle<BRepAdaptor_Surface>&, gp_Pnt2d&, bool, TopoDS_Vertex const&) const from /lib/x86_64-linux-gnu/libTKFillet.so.7+0xc40
Err: #5  0x7ff3a8343e64 in ChFi3d_Builder::PerformSetOfSurfOnElSpine(opencascade::handle<ChFiDS_ElSpine> const&, opencascade::handle<ChFiDS_Stripe>&, opencascade::handle<BRepTopAdaptor_TopolTool>&, opencascade::handle<BRepTopAdaptor_TopolTool>&, bool) from /lib/x86_64-linux-gnu/libTKFillet.so.7+0x674
Err: #6  0x7ff3a8346728 in ChFi3d_Builder::PerformSetOfKGen(opencascade::handle<ChFiDS_Stripe>&, bool) from /lib/x86_64-linux-gnu/libTKFillet.so.7+0xf8
Err: #7  0x7ff3a834b785 in ChFi3d_Builder::PerformSetOfSurf(opencascade::handle<ChFiDS_Stripe>&, bool) from /lib/x86_64-linux-gnu/libTKFillet.so.7+0x65
Err: #8  0x7ff3a8313395 in ChFi3d_Builder::Compute() from /lib/x86_64-linux-gnu/libTKFillet.so.7+0x415
Err: #9  0x7ff3a8491b7d in BRepFilletAPI_MakeFillet::Build(Message_ProgressRange const&) from /lib/x86_64-linux-gnu/libTKFillet.so.7+0x2d
Err: #10  0x7ff3a579c67d in PartDesign::Fillet::execute() from /home/user/Programs/FreeCADmaster/build/Mod/PartDesign/_PartDesign.so+0x71d
Err: #11  0x7ff48e8b27c2 in App::DocumentObject::recompute() from /home/user/Programs/FreeCADmaster/build/lib/libFreeCADApp.so+0x92
Err: #12  0x7ff3a929326b in Part::Feature::recompute() from /home/user/Programs/FreeCADmaster/build/Mod/Part/Part.so+0xb
Err: #13  0x7ff48e85a09c in App::Document::_recomputeFeature(App::DocumentObject*) from /home/user/Programs/FreeCADmaster/build/lib/libFreeCADApp.so+0x28c
Err: #14  0x7ff48e861711 in App::Document::recompute(std::vector<App::DocumentObject*, std::allocator<App::DocumentObject*> > const&, bool, bool*, int) from /home/user/Programs/FreeCADmaster/build/lib/libFreeCADApp.so+0x571
Err: #15  0x7ff48e916164 in App::DocumentPy::recompute(_object*) from /home/user/Programs/FreeCADmaster/build/lib/libFreeCADApp.so+0x2c4
Err: #16  0x7ff48e916273 in App::DocumentPy::staticCallback_recompute(_object*, _object*) from /home/user/Programs/FreeCADmaster/build/lib/libFreeCADApp.so+0x23
Err: #17  /lib/x86_64-linux-gnu/libpython3.11.so.1.0(+0x1c9ba1) [0x7ff48dbc9ba1]
Err: #18  /lib/x86_64-linux-gnu/libpython3.11.so.1.0(_PyObject_MakeTpCall+0x7d) [0x7ff48db7be8d]
Err: #19  /lib/x86_64-linux-gnu/libpython3.11.so.1.0(_PyEval_EvalFrameDefault+0x4a63) [0x7ff48db09c63]
Err: #20  /lib/x86_64-linux-gnu/libpython3.11.so.1.0(+0x3ccd3c) [0x7ff48ddccd3c]
Err: #21  /lib/x86_64-linux-gnu/libpython3.11.so.1.0(PyEval_EvalCode+0xc1) [0x7ff48dc68891]
Err: #22  /lib/x86_64-linux-gnu/libpython3.11.so.1.0(+0x2b7359) [0x7ff48dcb7359]
Err: #23  /lib/x86_64-linux-gnu/libpython3.11.so.1.0(PyRun_StringFlags+0x6b) [0x7ff48dcb850b]
Err: #24  0x7ff48e32db78 in Base::InterpreterSingleton::runString[abi:cxx11](char const*) from /home/user/Programs/FreeCADmaster/build/lib/libFreeCADBase.so+0x58
Err: #25  0x7ff48f412e90 in Gui::Command::_runCommand(char const*, int, Gui::Command::DoCmd_Type, char const*) from /home/user/Programs/FreeCADmaster/build/lib/libFreeCADGui.so+0x80
Err: #26  0x7ff48f412fec in Gui::Command::_doCommand(char const*, int, Gui::Command::DoCmd_Type, char const*, ...) from /home/user/Programs/FreeCADmaster/build/lib/libFreeCADGui.so+0xcc
Err: #27  0x7ff48f4130f2 in Gui::Command::updateActive() from /home/user/Programs/FreeCADmaster/build/lib/libFreeCADGui.so+0x32
Err: #28  0x7ff3a4f14c85 in finishFeature(Gui::Command const*, App::DocumentObject*, App::DocumentObject*, bool, bool) from /home/user/Programs/FreeCADmaster/build/Mod/PartDesign/PartDesignGui.so+0x235
Err: #29  0x7ff3a4f19212 in finishDressupFeature(Gui::Command const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Part::Feature*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) from /home/user/Programs/FreeCADmaster/build/Mod/PartDesign/PartDesignGui.so+0x652
Err: #30  0x7ff3a4f22ba8 in makeChamferOrFillet(Gui::Command*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) from /home/user/Programs/FreeCADmaster/build/Mod/PartDesign/PartDesignGui.so+0xb8
Err: #31  0x7ff3a4f22d95 in CmdPartDesignFillet::activated(int) from /home/user/Programs/FreeCADmaster/build/Mod/PartDesign/PartDesignGui.so+0x35
Err: #32  0x7ff48f41b0a4 in Gui::Command::_invoke(int, bool) from /home/user/Programs/FreeCADmaster/build/lib/libFreeCADGui.so+0x264
Err: #33  0x7ff48f41b503 in Gui::Command::invoke(int, Gui::Command::TriggerSource) from /home/user/Programs/FreeCADmaster/build/lib/libFreeCADGui.so+0x133
Err: #34  /lib/x86_64-linux-gnu/libQt5Core.so.5(+0x2e8f4f) [0x7ff48c6e8f4f]
Err: #35  0x7ff48d35c782 in QAction::triggered(bool) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x42
Err: #36  0x7ff48d35f3ab in QAction::activate(QAction::ActionEvent) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0xab
Err: #37  /lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x256e8a) [0x7ff48d456e8a]
Err: #38  0x7ff48d456fd7 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0xf7
Err: #39  0x7ff48d54faaa in QToolButton::mouseReleaseEvent(QMouseEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0xa
Err: #40  0x7ff48d3a4db8 in QWidget::event(QEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x1a8
Err: #41  0x7ff48d362fae in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x7e
Err: #42  0x7ff48d36b552 in QApplication::notify(QObject*, QEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x13c2
Err: #43  0x7ff48f3d1b48 in Gui::GUIApplication::notify(QObject*, QEvent*) from /home/user/Programs/FreeCADmaster/build/lib/libFreeCADGui.so+0x68
Err: #44  0x7ff48c6b16f8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x118
Err: #45  0x7ff48d36965e in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x1be
Err: #46  /lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x1bdbd8) [0x7ff48d3bdbd8]
Err: #47  /lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x1c0f60) [0x7ff48d3c0f60]
Err: #48  0x7ff48d362fae in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x7e
Err: #49  0x7ff48f3d1b48 in Gui::GUIApplication::notify(QObject*, QEvent*) from /home/user/Programs/FreeCADmaster/build/lib/libFreeCADGui.so+0x68
Err: #50  0x7ff48c6b16f8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x118
Err: #51  0x7ff48cb3d3ed in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) from /lib/x86_64-linux-gnu/libQt5Gui.so.5+0x80d
Err: #52  0x7ff48cb11cac in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /lib/x86_64-linux-gnu/libQt5Gui.so.5+0xac
Err: #53  /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5(+0x6deca) [0x7ff4869beeca]
Err: #54  /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x299) [0x7ff48a91e7a9]
Err: #55  /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x54a38) [0x7ff48a91ea38]
Err: #56  /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x2c) [0x7ff48a91eacc]
Err: #57  0x7ff48c709836 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x66
Err: #58  0x7ff48c6b017b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x12b
Err: #59  0x7ff48c6b82d6 in QCoreApplication::exec() from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x96
Err: #60  0x7ff48f32446f in Gui::Application::runApplication() from /home/user/Programs/FreeCADmaster/build/lib/libFreeCADGui.so+0x22ff
Err: #61  /home/user/Programs/FreeCADmaster/build/bin/FreeCAD(+0x9a7f) [0x55ee524baa7f]
Err: #62  /lib/x86_64-linux-gnu/libc.so.6(+0x271ca) [0x7ff48c2461ca]
Err: #63  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x85) [0x7ff48c246285]
Err: #64  /home/user/Programs/FreeCADmaster/build/bin/FreeCAD(+0x9d11) [0x55ee524bad11]
```


```
OS: Debian GNU/Linux 12 (bookworm) (X-Cinnamon/lightdm-xsession)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.34104 (Git)
Build type: Release
Branch: master
Hash: db4a4fabc2144ac44575685fbf83531a68477e3e
Python 3.11.2, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * QuickMeasure 2022.10.28
```

**Comment by grubertechnic** [comment] 2023-09-02 14:54
Should not that e closed as duplicate?

**Closed** 2023-09-02 14:56 UTC
Labels: WB PartDesign, 3rd party: OCC, Crash
