### ISSUE TITLE
Pad "Up to Face" not working

### ISSUE THREAD

**Issue by borish43b** [FreeCAD/FreeCAD#16524] opened 2024-09-13 21:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I tried to replicate an exercise from the solid works model mania and struggled when padding a certain sketch "Up to Face" (see screenshots):
Sketch:
![grafik](https://github.com/user-attachments/assets/957ac639-795d-476d-8c5a-448a9f0beedc)
Padded "Up to Face":
![grafik](https://github.com/user-attachments/assets/255bd30f-e77f-41c0-bdf3-f1b913cb6cf5)
The pad extends basically to infinity and starts from the wrong position.
I tried to position the circle sketch either by setting an offset and by using a datum plane, both resulting in the same issue.

The previous steps consists of:
1.  Create a quarter of the sketch
2. Pad the sketch
3. Apply fillet
4. Apply thickness
5. Multi-Transform mirrored (2x)

Model attached:
[up_to_face_issue.zip](https://github.com/user-attachments/files/16999497/up_to_face_issue.zip)

I had other tries with combinations of transforms and fillets and thickness where the "Up to Face" operation worked as expected.

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 1.0.0RC1.38643 (Git)
Build type: Release
Branch: main
Hash: fe40748c10503eed367840239db3e0f81873e359
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US) [ OS: German/Germany (de_DE) ]
Installed mods: 
  * Curves 0.6.47
  * fasteners 0.5.28
  * freecad.gears 1.2.0
  * PieMenu 1.8.0
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Syres916** [comment] 2024-09-13 21:31
Duplicate of #14663 , [PR](https://github.com/FreeCAD/FreeCAD/pull/16030) is WIP

**Closed** 2024-09-14 06:21 UTC
Labels: Status: Needs triage
