### ISSUE TITLE
[Issue] v0.20.0 crashes on MacOS when constraining a circle

### ISSUE THREAD

**Issue by titanic-jb** [FreeCAD/FreeCAD#9238] opened 2023-04-12 13:11 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
[code]
OS: macOS 10.16
Word size of FreeCAD: 64-bit
Version: 0.20.2.29603 (Git)
Build type: Release
Branch: (HEAD detached at 0.20.2)
Hash: 930dd9a76203a3260b1e6256c70c1c3cad8c5cb8
Python 3.10.8, Qt 5.15.4, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: C/Default (C)
Installed mods: 
  * fasteners 0.4.56
  * Assembly4 0.12.7
[/code]
```

### Subproject(s) affected?

None

### Issue description

I was playing with the taper function, when creating a pad.  I therefore sketched a cylinder and extruded it.

Afterwards I placed another sketch on top of the cylinder.  I catched the circumference of the cylinder outline as external geometry (Sketcher_External).  

Then I saved the file, which I can upload, if interested.

Next, I choose the diameter constraint tool (Sketcher_CompConstrainRadDia) and placed the cursor over the outline circle.  When I clicked the mouse button, FreeCAD crashed.

I saved the MacOS crash report and can upload it to you also, if interested.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by titanic-jb** [comment] 2023-04-12 13:12
Actual version of the File
[flanschdeckel.FCStd.zip](https://github.com/FreeCAD/FreeCAD/files/11211771/flanschdeckel.FCStd.zip)

**Comment by titanic-jb** [comment] 2023-04-12 13:13
MacOS crash report:
[crash.txt.zip](https://github.com/FreeCAD/FreeCAD/files/11211774/crash.txt.zip)

**Comment by Eqyizo** [comment] 2023-04-14 06:18
I'm following the tutorial linked below, and I'm also crashing when constraining multiple circles. I'm on Windows, just downloaded the stable version of FreeCAD 0.20.2 yesterday. I've linked the video to the timestamp of the exact actions I'm taking. Obviously I've just started to learn the program, so probably won't be much more help than telling you it's happening.

https://youtu.be/DFTGt_-jeos?t=553

**Comment by xtemp09** [comment] 2023-12-13 12:56
I cannot reproduce on:


```ruby
OS: Ubuntu 22.04.3 LTS (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35335 (Git)
Build type: Debug
Branch: main
Hash: 0e5d2c46f0d2661d9f8b6692ae0bfad6c5504762
Python 3.10.12, Qt 5.15.3, Coin 4.0.0, Vtk 9.1.0, OCC 7.5.1
Locale: English/United States (en_US)
```


and


```ruby
OS: Windows 10 build 19044
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35370 (Git)
Build type: Release
Branch: main
Hash: 1066bb54ceec8f4f8376b5149253acda5677651d
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: Russian/Russia (ru_RU)
```

**Comment by luzpaz** [comment] 2023-12-24 13:49
@JohnOCFII can you reproduce on macOS ?

**Comment by JohnOCFII** [comment] 2023-12-24 17:54
> @JohnOCFII can you reproduce on macOS ?

No, I cannot reproduce this crash on macOS Sonoma using:

```
OS: macOS 14.2.1
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35414 (Git)
Build type: Release
Branch: main
Hash: 759930e3aab711355d2f0895f641a8657897af48
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: C/Default (C)
```

**Comment by JohnOCFII** [comment] 2024-01-12 19:57
Seems this could be closed as well.

**Comment by luzpaz** [comment] 2024-07-26 13:40
Closing

**Closed by luzpaz** 2024-07-26 13:40 UTC
Labels: OS: macOS, Crash
