### ISSUE TITLE
[PartDesign] New sketch on face : tool -> selection not working

### ISSUE THREAD

**Issue by PaddleStroke** [FreeCAD/FreeCAD#12919] opened 2024-03-13 08:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

![image](https://github.com/FreeCAD/FreeCAD/assets/19984177/2b71b8bd-28de-46ef-81cf-45381b26172d)

If you select a face, then click new sketch, it works.
If you select new sketch, then select a face, you cannot validate.

### Full version info

```shell
0.22
```

### Subproject(s) affected?

PartDesign

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment] 2024-03-13 08:23
Duplicate of https://github.com/FreeCAD/FreeCAD/issues/11604

I thinks that's currently not supported so no bug but rather a feature request?
It would be possible with this FR: https://github.com/FreeCAD/FreeCAD/issues/11133 as it is implemented in RT Link branch.

**Closed by maxwxyz** 2024-03-13 08:23 UTC
Labels: needs triage
