### ISSUE TITLE
Bug in Techdraw of Freecad

### ISSUE THREAD

**Issue by ricou1** [FreeCAD/FreeCAD#12244] opened 2024-02-03 09:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The dimensions by Techdraw are not the same as in partdesignn. it is partdersign which is true

### Full version info

```shell
The dimensions by Techdraw are not the same as in partdesignn. it is partdersign which is true
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment] 2024-02-03 11:44
Please re-edit report. Add your full [About](https://wiki.freecad.org/About) info in the **Full version info**  portion. Add screenshots of what the problem is, zip up an example file and drag-drop into github here as an attachment. TIA

**Comment by ricou1** [comment] 2024-02-03 12:34
Sorry i was not squcessfull to paste an picture, in a html page; so i send
you an email.
There is  a problem in the dimensions given par tyechdraw. See the two
picture of the same3 object. After verification <with a caliper techdraw as
wrong, partdde3s36ign3 is good.
si30n3ce3re3ly 3yours.

**Comment by luzpaz** [comment] 2024-02-03 12:47
Emails don't work with attachments. 
Go back to github, zip the freecad file (in to a .zip) and then drag and drop into github text box (the area where you can type replies intoi. 

For attaching images: right click on a picture and copy then ctrl+v or drag-drop into github text box.

**Comment by Roy-043** [comment] 2024-02-04 09:45
@ricou1 You have now created a 3rd issue for the same problem! That is not the right way to do things. Please do not do this again.

Closing this as a duplicate.

**Closed by Roy-043** 2024-02-04 09:45 UTC
Labels: Missing: 'About' info, Missing: example file, Missing: steps to reproduce, Missing: clear title

**Comment by WandererFan** [comment] 2024-02-10 14:26
If you select geometry on the TechDraw page, you will get the dimension of the projected geometry and the "Measure Type" will be "Projected".  This will only be accurate if the projection direction is orthogonal to the dimension line.  If you are dimensioning an axonometric view, your dimension value will be incorrect.

If you want to use the actual dimension from the 3d model, then you should select the geometry in the 3d window.   This will create a "True" dimension.

You can use "repair references" to change from projected geometry to actual geometry.

**Comment by bernerus** [comment] 2024-02-11 15:47
Maybe this is another issue, but at least related. 
When I try setting "Measure Type" to true, on an axonometric view, the value 0 (zero) is shown. Repairing references does not help.

**Comment by ricou1** [comment] 2024-02-11 15:49
Yes that is that I have seen

**Comment by WandererFan** [comment] 2024-02-11 20:46
You can only have a true measurement if you have 3d references.  

If you are using 2d references and set the Measure Type to true, there should be an error message generated.

**Comment by bernerus** [comment] 2024-02-12 19:21
Agree, setting the value to 0 is just confusing and leaves no hint on what's wrong.

-- Chris
