### ISSUE TITLE
Sketch: defining a symmetry line / rotational axis for dimensioning diameters is not possible (profiles of rotational parts)

### ISSUE THREAD

**Issue by imaluschi** [FreeCAD/FreeCAD#16833] opened 2024-09-25 22:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Dimensioning a sketch for the profile / cross section of a rotational part: it is not possible to dimension diameters because it is not possible to define a symmetry line / rotational axis.

![Screenshot_20240925_225519](https://github.com/user-attachments/assets/cd4cb0ba-ef07-4470-a800-d2e64bf18592)

After years of working with professional CAD-Software (Autodesk Mechanical and Inventor, Unigraphics NX and Siemens PLM NX, CATIA V5) in different companies: nobody, really nobody dimensions such sketches with radii.

Doing such a sketch in CATIA V5:
After drawing a line you can define it as a symmetry line
(The german text in the screenshot: axis generation "The selected line will be converted into an axis. Should the line be converted?")
![Screenshot 2024-09-26 011548](https://github.com/user-attachments/assets/647dc234-20c0-414e-94f1-8b4ac897d685)

When dimensioning you can choose if you want to define the diameter instead of the radius.
![Screenshot 2024-09-26 011614](https://github.com/user-attachments/assets/c30b366f-704c-421c-9e38-6420e078849a)

The fully defined sketch.
![Screenshot 2024-09-26 011910](https://github.com/user-attachments/assets/d03cf619-6552-4a58-81d0-163389d556e7)

When creating the rotation the rotational axis is recognised automatically - because it was already defined in the sketch. Of course you can choose another rotational axis (no matter whether it makes sense).
![Screenshot 2024-09-26 011950](https://github.com/user-attachments/assets/ef7086fc-6eb5-4b3d-81d1-f32b01c4e9d8)

And no, defining the diameters as parameters and dimension with parameter/2 is no alternative.
For a part like this would that be impossible - at least without a table of all diameters. And if there are changes (in the part) it is unmanageable.
![Screenshot_20240926_000436](https://github.com/user-attachments/assets/d06b5fcc-20dd-47f5-8607-c7bff469c6e0)

Of course FreeCAD is not CATIA or any other professional CAD-software - and should not be! But at least the working method should be possible.
The attempt to switch to FreeCAD failed for the moment. Maybe one attemp more if the described working method will be possible. I don't feel like spending more than twice the time is a way to go.

### Full version info

```shell
OS: Fedora Linux 40 (KDE Plasma) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38842 (Git)
Build type: Release
Branch: main
Hash: 69676a0f9d2d5b288bda3d1c6dbad5a6ec26bfaa
Python 3.12.6, Qt 6.7.2, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: German/Austria (de_AT)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/breeze
Installed mods: 
  * sheetmetal 0.4.26
  * Defeaturing 1.2.2
  * InventorLoader 1.4.0
```

### Subproject(s) affected?

Sketcher

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FEA-eng** [comment] 2024-09-26 07:46
Duplicate of #7334

**Comment by Roy-043** [comment] 2024-09-26 08:50
Closing this as a duplicate.

**Closed by Roy-043** 2024-09-26 08:50 UTC
Labels: Status: Duplicate, Mod: Sketcher
