### ISSUE TITLE
PNG: importing file shows garbage (memory contents?)

### ISSUE THREAD

**Issue by speters** [FreeCAD/FreeCAD#18154] opened 2024-11-27 11:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Importing a PNG (as exported by Inkcape) file shows garbage which looks like memory contents.
![Screenshot_20241127-114800](https://github.com/user-attachments/assets/d4998539-553c-41f5-bd36-adf1978e90c3)
Should have displayed this:
![bitmap](https://github.com/user-attachments/assets/942c447d-6d12-4067-8640-e05d679f78ea)

Tested with PNG made by Gimp, it displays at least something recognizable, but it looks overlayed, cut:
![Screenshot_20241127-115658](https://github.com/user-attachments/assets/e4302aec-9461-46a1-9a27-d36b45f43b9f)
Not sure if this is again some memory parts displayed.
(result is the same with 16/8bit RGB/RGBA PNG, as well as indexed PNG)

### Full version info

```shell
OS: Arch Linux (KDE/plasmax11/xcb)
Architecture: x86_64
Version: 1.1.0dev.39315 (Git) Conda AppImage
Build type: Release
Branch: main
Hash: 710542d121c2cabce05561591cfb00ef3b6e745c
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C) [ OS: German/Germany (de_DE) ]
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * lattice2 1.0.0
  * fasteners.backup1710268663.2371168 0.4.66 (Disabled)
  * fasteners 0.5.14
  * A2plus 0.4.64
  * Curves 0.6.24
  * kicadStepUpMod 10.19.5
  * CurvedShapes 1.0.5
  * sheetmetal 0.3.0
  * Manipulator 1.5.0
```

### Subproject(s) affected?

File formats

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tarman3** [comment] 2024-11-27 11:35
Can not reproduce.
Please attach PNG file.

**Comment by tarman3** [comment] 2024-11-27 12:26
Looks like any process by imagemagick resolve the issue.
E.g. convert PNG to PNG also resolve the issue.

**Comment by luzpaz** [comment] 2024-11-27 13:12
@tarman3 cool. that's a work-around though. Can you pinpoint the PNG issue ? Is it a bug in GIMP ?

**Comment by tarman3** [comment] 2024-11-27 13:41
I tried to create images in InkScape and Gimp, but can not reproduce this situation.
I do not know how to create image with this issue.

**Comment by tarman3** [comment] 2024-11-27 14:55
Confirm

**Comment by wwmayer** [comment] 2024-11-28 14:18
Fixed with https://github.com/FreeCAD/FreeCAD/pull/18166

**Closed** 2024-11-28 18:41 UTC
Labels: Type: Bug, Mod: Core, Status: Confirmed
