### ISSUE TITLE
Levenberg-Marquardt: Solver reports Sketch to be fully constrained which it isn't

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5861] opened 2022-02-07 17:56 UTC
Issue imported from https://tracker.freecad.org/view.php?id=3773

* **Reporter:** chrisb
* **Date submitted:** 1/15/2019
* **FreeCAD version:** 0.18
* **Category:** General
* **Status:** assigned
* **Tags:** 

# Original report text

Using arcs and symmetry Levenberg-Marquardt solver claims sketch to be fully constrained, see [forum discussion](https://forum.freecadweb.org/viewtopic.php?f=3&t=33438#p279976). 
In a similar case a redundancy is not recognized, description in same forum post.

DogLeg solver is ok.

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** General
* **Updated:** 2/6/2021

**Comment by maxwxyz** [comment] 2024-05-22 18:34
Duplicate of https://github.com/FreeCAD/FreeCAD/issues/8324

**Closed by maxwxyz** 2024-05-22 18:34 UTC
Labels: GCS, WB Sketcher
