### ISSUE TITLE
Hard crash on simple chamfer

### ISSUE THREAD

**Issue by carstenorthbandt** [FreeCAD/FreeCAD#14622] opened 2024-06-11 21:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I have a relatively simple part that makes FreeCAD crash hard when trying to set a chamfer on a specific set of edges.

### Full version info

```shell
[code]
OS: Arch Linux (GNOME/gnome)
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: makepkg
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.12.3, Qt 6.7.0, Coin 4.0.2, Vtk 9.3.0, OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * Curves 0.6.37
  * A2plus 0.4.63
[/code]
```

### Subproject(s) affected?

PartDesign

### Anything else?

[fw13magfanbar.zip](https://github.com/user-attachments/files/15794715/fw13magfanbar.zip)
![crash_edge](https://github.com/FreeCAD/FreeCAD/assets/17904346/3b65fec5-863b-4bbb-acc4-da75c0a0247a)

Apparently, any of the edges in the three identical pockets cause a crash. One of the edges is selected in the attached screenshot.

Both attached files are hereby public domain.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment] 2024-06-13 06:53
I'll close this then as duplicate of #14370

**Closed by maxwxyz** 2024-06-13 06:53 UTC
