### ISSUE TITLE
DIN 6784 or DIN ISO 13715 Edge symbols

### ISSUE THREAD

**Issue by sebaras** [FreeCAD/FreeCAD#14360] opened 2024-05-29 08:12 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Edge symbols are missing in Techdraw

### Full version info

```shell
[code]
OS: Windows 10 build 19042
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: releases/FreeCAD-0-21
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: German/Switzerland (de_CH)
Installed mods: 
  * A2plus 0.4.60n
  * Assembly4 0.50.2
  * CADExchanger
  * ExplodedAssembly
  * fasteners 0.4.60
  * Help 1.0.3
[/code]
```

### Subproject(s) affected?

Techdraw

### Anything else?

Editable edge symbols, like writen on this webpage, are missing in Techdraw.
https://blog.nupis.de/kantensymbole-im-inventor/
![kantenbruch-symbole](https://github.com/FreeCAD/FreeCAD/assets/143388865/01e51540-9efd-4e5f-a076-cfa4a1ebd06a)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sebaras** [comment] 2024-05-29 09:03
![Kantenbruch](https://github.com/FreeCAD/FreeCAD/assets/143388865/7aaa6e1c-4e34-425d-a55d-74e13ffe16d5)

**Comment by maxwxyz** [comment] 2024-05-29 11:15
Duplicate of https://github.com/FreeCAD/FreeCAD/issues/13572

**Closed by maxwxyz** 2024-05-29 11:15 UTC
