### ISSUE TITLE
Crash upon solving expression referencing named Constraint

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5950] opened 2022-02-07 19:21 UTC
Issue imported from https://tracker.freecad.org/view.php?id=4031

* **Reporter:** dhka2
* **Date submitted:** 6/20/2019
* **FreeCAD version:** 
* **Category:** Bug
* **Status:** confirmed
* **Tags:** 

# Original report text

Freecad git build as of 18.06.2019 sometimes crashes with signal 11 upon referencing a named constraint in an expression. This is width python 3 and qt5.

stdout output:

```Program received signal SIGSEGV, Segmentation fault.
#0  /lib/libc.so.6(+0x378b0) [0x7f160e65a8b0]
#1  0x7f160fe90f76 in App::ObjectIdentifier::Component::get(Py::Object const&) const from /usr/lib/freecad/lib/libFreeCADApp.so+0x1c6
#2  0x7f160fe96638 in App::ObjectIdentifier::access(App::ObjectIdentifier::ResolveResults const&, Py::Object*) const from /usr/lib/freecad/lib/libFreeCADApp.so+0x1b8
#3  0x7f160fe9ae14 in App::ObjectIdentifier::getPyValue(bool, bool*) const from /usr/lib/freecad/lib/libFreeCADApp.so+0x84
#4  0x7f160fe04ca2 in App::VariableExpression::_getPyValue(int*) const from /usr/lib/freecad/lib/libFreeCADApp.so+0x62
#5  0x7f160fdf3e2c in App::Expression::getPyValue(int, int*) const from /usr/lib/freecad/lib/libFreeCADApp.so+0x4c
#6  0x7f160fdf4f62 in App::Expression::eval(int) const from /usr/lib/freecad/lib/libFreeCADApp.so+0x42
#7  0x7f16105e2cfc in Gui::Dialog::DlgExpressionInput::textChanged(QString const&) from /usr/lib/freecad/lib/libFreeCADGui.so+0x1fc
#8  0x7f160ec388e7 in QMetaObject::activate(QObject*, int, int, void**) from /lib/libQt5Core.so.5+0x777
#9  0x7f160f15c963 in QLineEdit::textChanged(QString const&) from /lib/libQt5Widgets.so.5+0x33
#10  /lib/libQt5Widgets.so.5(+0x29c662) [0x7f160f163662]
#11  0x7f160ec388e7 in QMetaObject::activate(QObject*, int, int, void**) from /lib/libQt5Core.so.5+0x777
#12  0x7f160f164276 in QWidgetLineControl::textChanged(QString const&) from /lib/libQt5Widgets.so.5+0x36
#13  0x7f160f167710 in QWidgetLineControl::finishChange(int, bool, bool) from /lib/libQt5Widgets.so.5+0x2a0
#14  0x7f160f16abaf in QWidgetLineControl::processKeyEvent(QKeyEvent*) from /lib/libQt5Widgets.so.5+0xebf
#15  0x7f160f15caeb in QLineEdit::keyPressEvent(QKeyEvent*) from /lib/libQt5Widgets.so.5+0x1b
#16  0x7f161053668f in Gui::ExpressionLineEdit::keyPressEvent(QKeyEvent*) from /usr/lib/freecad/lib/libFreeCADGui.so+0x1f
#17  0x7f160f060b88 in QWidget::event(QEvent*) from /lib/libQt5Widgets.so.5+0x258
#18  0x7f160f162ebb in QLineEdit::event(QEvent*) from /lib/libQt5Widgets.so.5+0xab
#19  0x7f160f01fda4 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /lib/libQt5Widgets.so.5+0x84
#20  0x7f160f02833c in QApplication::notify(QObject*, QEvent*) from /lib/libQt5Widgets.so.5+0x118c
#21  0x7f1610539019 in Gui::GUIApplication::notify(QObject*, QEvent*) from /usr/lib/freecad/lib/libFreeCADGui.so+0x89
#22  0x7f160ec0def9 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /lib/libQt5Core.so.5+0x179
#23  /lib/libQt5Widgets.so.5(+0x1b7b42) [0x7f160f07eb42]
#24  0x7f160f01fda4 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /lib/libQt5Widgets.so.5+0x84
#25  0x7f160f0273c1 in QApplication::notify(QObject*, QEvent*) from /lib/libQt5Widgets.so.5+0x211
#26  0x7f1610539019 in Gui::GUIApplication::notify(QObject*, QEvent*) from /usr/lib/freecad/lib/libFreeCADGui.so+0x89
#27  0x7f160ec0def9 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /lib/libQt5Core.so.5+0x179
#28  0x7f160ce9a50d in QGuiApplicationPrivate::processKeyEvent(QWindowSystemInterfacePrivate::KeyEvent*) from /lib/libQt5Gui.so.5+0x16d
#29  0x7f160ce9f526 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) from /lib/libQt5Gui.so.5+0x116
#30  0x7f160ce7a55c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /lib/libQt5Gui.so.5+0xbc
#31  /lib/libQt5XcbQpa.so.5(+0x6db7c) [0x7f16088f2b7c]
#32  /lib/libglib-2.0.so.0(g_main_context_dispatch+0x2bf) [0x7f160c2ca90f]
#33  /lib/libglib-2.0.so.0(+0x6d869) [0x7f160c2cc869]
#34  /lib/libglib-2.0.so.0(g_main_context_iteration+0x2e) [0x7f160c2cc8ae]
#35  0x7f160ec63079 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /lib/libQt5Core.so.5+0x69
#36  0x7f160ec0cabc in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /lib/libQt5Core.so.5+0x13c
#37  0x7f160f21864e in QDialog::exec() from /lib/libQt5Widgets.so.5+0x1de
#38  0x7f153a96cc92 in openEditDatumDialog(Sketcher::SketchObject*, int) from /usr/lib/freecad/lib/SketcherGui.so+0x422
#39  0x7f153a96d77f in finishDistanceConstraint(Gui::Command*, Sketcher::SketchObject*, bool) from /usr/lib/freecad/lib/SketcherGui.so+0x19f
#40  0x7f153a970f66 in CmdSketcherConstrainDistanceY::activated(int) from /usr/lib/freecad/lib/SketcherGui.so+0xb86
#41  0x7f161056a30c in Gui::Command::invoke(int, Gui::Command::TriggerSource) from /usr/lib/freecad/lib/libFreeCADGui.so+0x36c
#42  0x7f160ec388e7 in QMetaObject::activate(QObject*, int, int, void**) from /lib/libQt5Core.so.5+0x777
#43  0x7f160f0195e3 in QAction::triggered(bool) from /lib/libQt5Widgets.so.5+0x43
#44  0x7f160f01bcca in QAction::activate(QAction::ActionEvent) from /lib/libQt5Widgets.so.5+0xfa
#45  0x7f160f01c5d5 in QAction::event(QEvent*) from /lib/libQt5Widgets.so.5+0x55
#46  0x7f160f01fda4 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /lib/libQt5Widgets.so.5+0x84
#47  0x7f160f0273c1 in QApplication::notify(QObject*, QEvent*) from /lib/libQt5Widgets.so.5+0x211
#48  0x7f1610539019 in Gui::GUIApplication::notify(QObject*, QEvent*) from /usr/lib/freecad/lib/libFreeCADGui.so+0x89
#49  0x7f160ec0def9 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /lib/libQt5Core.so.5+0x179
#50  0x7f160cec8890 in QShortcutMap::dispatchEvent(QKeyEvent*) from /lib/libQt5Gui.so.5+0x110
#51  0x7f160cec8973 in QShortcutMap::tryShortcut(QKeyEvent*) from /lib/libQt5Gui.so.5+0x63
#52  0x7f160ce7dedc in QWindowSystemInterface::handleShortcutEvent(QWindow*, unsigned long, int, QFlags<Qt::KeyboardModifier>, unsigned int, unsigned int, unsigned int, QString const&m /lib/libQt5Gui.so.5+0x18c
#53  0x7f160ce9a42e in QGuiApplicationPrivate::processKeyEvent(QWindowSystemInterfacePrivate::KeyEvent*) from /lib/libQt5Gui.so.5+0x8e
#54  0x7f160ce9f526 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) from /lib/libQt5Gui.so.5+0x116
#55  0x7f160ce7a55c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /lib/libQt5Gui.so.5+0xbc
#56  /lib/libQt5XcbQpa.so.5(+0x6db7c) [0x7f16088f2b7c]
#57  /lib/libglib-2.0.so.0(g_main_context_dispatch+0x2bf) [0x7f160c2ca90f]
#58  /lib/libglib-2.0.so.0(+0x6d869) [0x7f160c2cc869]
#59  /lib/libglib-2.0.so.0(g_main_context_iteration+0x2e) [0x7f160c2cc8ae]
#60  0x7f160ec63079 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /lib/libQt5Core.so.5+0x69
#61  0x7f160ec0cabc in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /lib/libQt5Core.so.5+0x13c
#62  0x7f160ec14c46 in QCoreApplication::exec() from /lib/libQt5Core.so.5+0x96
#63  0x7f16104ba880 in Gui::Application::runApplication() from /usr/lib/freecad/lib/libFreeCADGui.so+0x1570
#64  freecad(main+0x6ef) [0x55727def245f]
#65  /lib/libc.so.6(__libc_start_main+0xf3) [0x7f160e646ce3]
#66  freecad(_start+0x2e) [0x55727def277e]
```

# Additional information

OS: Arch Linux
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.18336 (Git)
Build type: Release
Branch: makepkg
Hash: 52d0f1db0905f11497241aa2ed35d5d990eda53f
Python version: 3.7.3
Qt version: 5.12.4
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/United States (en_US)

# Steps to reproduce

1. open TestPlate.FCStd
2. go to part design workbench
4. create sketch
5. draw circle somewhere
5. create vertical constraint between center and origin.
6. click on expression button
7. type in Sketch.Constraints.w
8. observe crash

# Other bug information

* **Priority:** normal
* **Severity:** crash
* **Category:** Bug
* **OS: Arch **
* **Platform:** Linux
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by openBrain 2019-06-20 16:34
dhka2 : thanks a lot for reporting with valuable information.
However as requested in the bug reporting policy (in the giant yellow banner on top of this page, and in the "Read this before reporting" on the left), it is advised to first open a dedicated topic on the [Help subforum](https://forum.freecadweb.org/viewforum.php?f=3). This will allow other forumers to confirm the issue and help finding the root cause. Once issue is eventually confirmed, forum thread & ticket can be crosslinked to ease bug fixing.
Thanks

---

### Comment by openBrain 2019-06-20 16:44
Looks to me as a duplicate of #4003 thus of #3379 as 'w' is unit symbol for Watt.
dhka2 : according previous tickets, it should work with "Sketch.Constraints.<<w>>". Could you please confirm ?

---

### Comment by dhka2 2019-06-20 18:06
[quote=openBrain]However as requested in the bug reporting policy (in the giant yellow banner on top of this page, and in the "Read this before reporting" on the left), it is advised to first open a dedicated topic on the Help subforum. This will allow other forumers to confirm the issue and help finding the root cause. Once issue is eventually confirmed, forum thread & ticket can be crosslinked to ease bug fixing.[/quote]

The forum sticky suggests a forum post is only necessary if it is unclear if encountered behaviour is a bug or a featureTM. "2. If you are unsure, discuss the problem on the forum first. ". As a segmentation fault is always a bug i thought it not necessary. If the intent is to always have a forum post before a bug report this is a documentation bug. 

Indeed this is related to 0004003 and 003379 however these bug reports do not state that a crash occurs. Indeed all reserved letters input into the expression window in this manner result in a crash.

---

### Comment by openBrain 2019-06-20 19:08
[quote=dhka2]The forum sticky suggests a forum post is only necessary if it is unclear if encountered behaviour is a bug or a featureTM. "2. If you are unsure, discuss the problem on the forum first. ". If the intent is to always have a forum post before a bug report this is a documentation bug.[/quote]
Indeed a forum post is always expected. The flow diagram of the [bug submission guidelines topic](https://forum.freecadweb.org/viewtopic.php?f=3&t=5236) is clear about it. And you can see in the posts following the OP that there is a discussion to clarify also that in the text. :)
[quote=dhka2]As a segmentation fault is always a bug i thought it not necessary.[/quote] The reason for which a forum thread is asked is more than a bug can have external reason or specificity (OS, libraries, hardware, ...). This is what we try to identify in the forum so the ticket is as precise as possible. ;)

Just ways to improve your next bug reporting. ;)

---

### Comment by openBrain (private) 2019-06-20 19:10
[quote=dhka2]Indeed this is related to 0004003 and 003379 however these bug reports do not state that a crash occurs[/quote]
Kunda1 what's the right way to go ? Delete the "duplicate" attribute of this ticket and replace with a "related to" ? Or increase the severity level of older ticket (#3379) to "crash) ?

---

### Comment by Kunda1 (private) 2019-06-20 21:05
What I would do:
mark this ticket as dupe, 
copy over the FreeCAD/OS/Distro version info + crash backtrace; 
CC the OP for this ticket to participate in the other ticket, 
close this ticket.

---

### Comment by Kunda1 2019-06-28 10:47
eivindkvedalen care to take a look at this ?

---

### Comment by ezzieyguywuf 2019-12-01 04:52
I'm struggling to reproduce this: what is the "expression button" referenced in step 6?

---

### Comment by Kunda1 2019-12-01 05:44
ezzieyguywuf 
I believe it's this: https://www.freecadweb.org/wiki/File:Sketcher_Expressions.png

---

### Comment by mikeprice99 2020-07-02 11:54
Just a few observations:
1/ A vertical constraint does not take a parameter, so no expression button is available. Did you mean vertical distance constraint?
2/ 'Sketch' in your sample file does not include a constraint called 'w' (Did you mean Spreadsheet.w )?
3/ If I use a vertical distance constraint and enter the value Sketch002.Constraints.Nw (which does exist!) it works.

So I guess either 
a) the bug does not affect Windows 
b) it has been fixed since revision 18336
c) it is particular to branch makepkg

My test environment: 
OS: Windows 10 (10.0)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.21769 (Git)
Build type: Release
Branch: master
Hash: 801bfe4ba5f0910e9b2885917c521ab7fd8e9020
Python version: 3.6.8
Qt version: 5.12.1
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/United Kingdom (en_GB)

**Comment by adrianinsaval** [comment] 2022-02-10 22:31
while this comes from the same issue as #5770 the crash should be adressed separately IMO, will test later in arch to see if it's still crashing

**Comment by adrianinsaval** [comment] 2022-02-11 02:53
No crash

OS: Linux 5.16.7-arch1-1 (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.27465 (Git)
Build type: Release
Branch: master
Hash: 092afacfcb5127eb67c385a43cbe34a4cd15bef4
Python version: 3.10.2
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.3
Locale: English/United Kingdom (en_GB)

but there was no named constrains in Sketch so I'm not fully grasping what was OP doing to begin with, naming a constrain w and then using it worked without issues so it might not have been a duplicate of the other issues to begin with.

There was a w cell in the spreadsheet though, but similarly it didn't give me any issues

**Comment by adrianinsaval** [comment] 2023-04-14 22:22
I'm closing this one due to not being reproducible and inactivity, if there ever was an actual problem it's likely been solved.

**Closed by adrianinsaval** 2023-04-14 22:22 UTC
Labels: Bug, Expressions
