### ISSUE TITLE
Always loses response when editing sketches with arcs

### ISSUE THREAD

**Issue by ChenKe404** [FreeCAD/FreeCAD#9966] opened 2023-07-21 15:36 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
Version: 0.20.2
OS: win10 x64
```

### Subproject(s) affected?

Sketcher

### Problem description

When I open a sketch with arcs(one ocr more), the program always loses its response when I drag the view, and I have to forced close the program.

### Anything else?

like this one 
![image](https://github.com/FreeCAD/FreeCAD/assets/75658944/759ca0fe-da43-4f49-a8cd-e7773b616a2c)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by grubertechnic** [comment] 2023-07-22 13:02
At minimum we need
 - a file with the issue
 - precise steps to reproduce
 
Also please test it with 0.21 builds, the chance is high, that it is already solved and it will be nothing more backported.

**Comment by Roy-043** [comment] 2023-07-29 10:30
Too much information is missing.

Closing this as "can't reproduce".

**Closed by Roy-043** 2023-07-29 10:30 UTC
Labels: WB Sketcher, missing: 'About' info, missing: example file, missing: tested on dev version, missing: steps to reproduce

**Comment by grubertechnic** [comment] 2023-07-29 12:10
> Closing this as "can't reproduce".

Thanks, that makes the tracker more clean, else it will dumping here maybe years and and consumes very (re)view unnecessary lifetime. I really appreciate this.
