### ISSUE TITLE
New Sketch on face only works with preselected faces. 

### ISSUE THREAD

**Issue by P-C-R** [FreeCAD/FreeCAD#14267] opened 2024-05-24 23:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

See video.

i would expect that

Create Sketch -->Click Face --> Jump into Sketch works

https://github.com/FreeCAD/FreeCAD/assets/47773180/2cd366c0-bcbe-45aa-90d4-0553ee06db20

### Full version info

```shell
OS: Fedora Linux 40 (Workstation Edition) (GNOME/gnome)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37436 (Git) AppImage
Build type: Release
Branch: main
Hash: 040502280fc9637fb3aada037523283168b81a02
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * Dracula 0.0.5
  * Behave-Dark-Colors 0.1.1
  * OpenTheme 2024.5.3
  * OpenDark 2024.3.13
  * ProDarkThemePreferencePack 1.0.0
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment] 2024-05-25 06:21
Duplicate of https://github.com/FreeCAD/FreeCAD/issues/11133

**Closed by maxwxyz** 2024-05-25 06:21 UTC
