### ISSUE TITLE
Crashes when clicking close button to close sketch in task when spreadsheet is in foreground 

### ISSUE THREAD

**Issue by dptsolutions** [FreeCAD/FreeCAD#16597] opened 2024-09-17 04:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Reproduction steps:
1. Add a spreadsheet to the project
2. In Part Design workbench, add a body and a sketch to the project
3. Open sketch
4. Open spreadsheet, so it is the active tab in the main pane
5. Select the task tab in the left pane (should be the task pane for the sketch that is open)
6. Click the close button in the task pane

Expected Behavior:
App does not crash, sketch is closed

Actual Behavior:
App Crashes with segfault (stacktrace)

```
Program received signal SIGSEGV, Segmentation fault.
#0  /lib/x86_64-linux-gnu/libc.so.6(+0x45320) [0x720e40445320]
#1  0x720e3ffccb41 in SoRenderManager::setRenderMode(SoRenderManager::RenderMode) from /tmp/.mount_FreeCAMPD7Vq/usr/bin/../lib/./libCoin.so.80+0x1
#2  0x720db8559c05 in SketcherGui::ViewProviderSketch::unsetEdit(int) from /tmp/.mount_FreeCAMPD7Vq/usr/lib/SketcherGui.so+0x155
#3  0x720e43b69b73 in Gui::ViewProvider::finishEditing() from /tmp/.mount_FreeCAMPD7Vq/usr/bin/../lib/libFreeCADGui.so+0x13
#4  0x720e437017dd in Gui::Document::_resetEdit() from /tmp/.mount_FreeCAMPD7Vq/usr/bin/../lib/libFreeCADGui.so+0x9d
#5  0x720e436802ca in Gui::Application::setEditDocument(Gui::Document*) from /tmp/.mount_FreeCAMPD7Vq/usr/bin/../lib/libFreeCADGui.so+0x3a
#6  0x720e437162b0 in Gui::DocumentPy::resetEdit(_object*) from /tmp/.mount_FreeCAMPD7Vq/usr/bin/../lib/libFreeCADGui.so+0x30
#7  0x720e437162e4 in Gui::DocumentPy::staticCallback_resetEdit(_object*, _object*) from /tmp/.mount_FreeCAMPD7Vq/usr/bin/../lib/libFreeCADGui.so+0x24
#8  /tmp/.mount_FreeCAMPD7Vq/usr/bin/../lib/libpython3.11.so.1.0(+0x206068) [0x720e42e06068]
#9  /tmp/.mount_FreeCAMPD7Vq/usr/bin/../lib/libpython3.11.so.1.0(_PyObject_MakeTpCall+0x26c) [0x720e42de5b5c]
#10  /tmp/.mount_FreeCAMPD7Vq/usr/bin/../lib/libpython3.11.so.1.0(_PyEval_EvalFrameDefault+0x6f2) [0x720e42df1532]
#11  /tmp/.mount_FreeCAMPD7Vq/usr/bin/../lib/libpython3.11.so.1.0(+0x2abd1d) [0x720e42eabd1d]
#12  /tmp/.mount_FreeCAMPD7Vq/usr/bin/../lib/libpython3.11.so.1.0(PyEval_EvalCode+0xa4) [0x720e42eab794]
#13  /tmp/.mount_FreeCAMPD7Vq/usr/bin/../lib/libpython3.11.so.1.0(+0x2cabf3) [0x720e42ecabf3]
#14  /tmp/.mount_FreeCAMPD7Vq/usr/bin/../lib/libpython3.11.so.1.0(+0x2c669a) [0x720e42ec669a]
#15  /tmp/.mount_FreeCAMPD7Vq/usr/bin/../lib/libpython3.11.so.1.0(PyRun_StringFlags+0x69) [0x720e42eba9c9]
#16  0x720e4213db0c in Base::InterpreterSingleton::runString[abi:cxx11](char const*) from /tmp/.mount_FreeCAMPD7Vq/usr/bin/../lib/libFreeCADBase.so+0x6c
#17  0x720e4378dbd4 in Gui::Command::_runCommand(char const*, int, Gui::Command::DoCmd_Type, char const*) from /tmp/.mount_FreeCAMPD7Vq/usr/bin/../lib/libFreeCADGui.so+0x94
#18  0x720e4378dd63 in Gui::Command::_doCommand(char const*, int, Gui::Command::DoCmd_Type, char const*, ...) from /tmp/.mount_FreeCAMPD7Vq/usr/bin/../lib/libFreeCADGui.so+0xe3
#19  0x720db8595b25 in SketcherGui::TaskDlgEditSketch::reject() from /tmp/.mount_FreeCAMPD7Vq/usr/lib/SketcherGui.so+0x145
#20  0x720e43ad4a77 in Gui::TaskView::TaskView::reject() from /tmp/.mount_FreeCAMPD7Vq/usr/bin/../lib/libFreeCADGui.so+0x67
#21  /tmp/.mount_FreeCAMPD7Vq/usr/bin/../lib/libQt5Core.so.5(+0x2eb6f2) [0x720e40aeb6f2]
#22  /tmp/.mount_FreeCAMPD7Vq/usr/bin/../lib/libQt5Widgets.so.5(+0x2fab70) [0x720e41afab70]
#23  /tmp/.mount_FreeCAMPD7Vq/usr/bin/../lib/libQt5Core.so.5(+0x2eb964) [0x720e40aeb964]
#24  0x720e41a5b522 in QAbstractButton::clicked(bool) from /tmp/.mount_FreeCAMPD7Vq/usr/bin/../lib/libQt5Widgets.so.5+0x32
#25  /tmp/.mount_FreeCAMPD7Vq/usr/bin/../lib/libQt5Widgets.so.5(+0x25b73a) [0x720e41a5b73a]
#26  /tmp/.mount_FreeCAMPD7Vq/usr/bin/../lib/libQt5Widgets.so.5(+0x25d1c8) [0x720e41a5d1c8]
#27  0x720e41a5d3d7 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) from /tmp/.mount_FreeCAMPD7Vq/usr/bin/../lib/libQt5Widgets.so.5+0xe7
#28  0x720e419aec08 in QWidget::event(QEvent*) from /tmp/.mount_FreeCAMPD7Vq/usr/bin/../lib/libQt5Widgets.so.5+0x178
#29  0x720e419703ae in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /tmp/.mount_FreeCAMPD7Vq/usr/bin/../lib/libQt5Widgets.so.5+0x7e
#30  0x720e41978262 in QApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAMPD7Vq/usr/bin/../lib/libQt5Widgets.so.5+0x13a2
#31  0x720e43742519 in Gui::GUIApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAMPD7Vq/usr/bin/../lib/libFreeCADGui.so+0x99
#32  0x720e40ab6b28 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /tmp/.mount_FreeCAMPD7Vq/usr/bin/../lib/libQt5Core.so.5+0x108
#33  0x720e419763eb in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) from /tmp/.mount_FreeCAMPD7Vq/usr/bin/../lib/libQt5Widgets.so.5+0x1ab
#34  /tmp/.mount_FreeCAMPD7Vq/usr/bin/../lib/libQt5Widgets.so.5(+0x1c6e6f) [0x720e419c6e6f]
#35  /tmp/.mount_FreeCAMPD7Vq/usr/bin/../lib/libQt5Widgets.so.5(+0x1ca0c9) [0x720e419ca0c9]
#36  0x720e419703ae in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /tmp/.mount_FreeCAMPD7Vq/usr/bin/../lib/libQt5Widgets.so.5+0x7e
#37  0x720e43742519 in Gui::GUIApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAMPD7Vq/usr/bin/../lib/libFreeCADGui.so+0x99
#38  0x720e40ab6b28 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /tmp/.mount_FreeCAMPD7Vq/usr/bin/../lib/libQt5Core.so.5+0x108
#39  0x720e411353ec in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) from /tmp/.mount_FreeCAMPD7Vq/usr/bin/../lib/libQt5Gui.so.5+0x84c
#40  0x720e4110b0bc in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCAMPD7Vq/usr/bin/../lib/libQt5Gui.so.5+0xac
#41  /tmp/.mount_FreeCAMPD7Vq/usr/plugins/platforms/../../lib/libQt5XcbQpa.so.5(+0x64bea) [0x720e3b456bea]
#42  /tmp/.mount_FreeCAMPD7Vq/usr/bin/../lib/./libglib-2.0.so.0(+0x5bad7) [0x720e3f110ad7]
#43  /tmp/.mount_FreeCAMPD7Vq/usr/bin/../lib/./libglib-2.0.so.0(+0x5eac7) [0x720e3f113ac7]
#44  /tmp/.mount_FreeCAMPD7Vq/usr/bin/../lib/./libglib-2.0.so.0(g_main_context_iteration+0x2e) [0x720e3f1140ce]
#45  0x720e40b0aa36 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCAMPD7Vq/usr/bin/../lib/libQt5Core.so.5+0x66
#46  0x720e40ab570b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCAMPD7Vq/usr/bin/../lib/libQt5Core.so.5+0x11b
#47  0x720e40abd212 in QCoreApplication::exec() from /tmp/.mount_FreeCAMPD7Vq/usr/bin/../lib/libQt5Core.so.5+0x82
#48  0x720e436a3a23 in Gui::Application::runApplication() from /tmp/.mount_FreeCAMPD7Vq/usr/bin/../lib/libFreeCADGui.so+0x983
#49  /tmp/.mount_FreeCAMPD7Vq/usr/bin/freecad(+0x7640) [0x606fabcf0640]
#50  /lib/x86_64-linux-gnu/libc.so.6(+0x2a1ca) [0x720e4042a1ca]
#51  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x8b) [0x720e4042a28b]
#52  /tmp/.mount_FreeCAMPD7Vq/usr/bin/freecad(+0x79a9) [0x606fabcf09a9]
```

### Full version info

```shell
OS: Ubuntu 24.04.1 LTS (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38768 (Git) AppImage
Build type: Release
Branch: main
Hash: 758674d40be45e365f4148fb2a5ea6bd6f93bc74
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
```

### Subproject(s) affected?

PartDesign

### Anything else?

Depending on the order of how you set up the scenario I think I got a couple of different stack traces, but it always ends in a crash if the sketcher task pane is visible, the spreadsheet is in the foreground, and you click the close button in the task pane.

Attached is a sample project in a zip file that can demonstrate the repro steps.
[Close Button Crash.zip](https://github.com/user-attachments/files/17022896/Close.Button.Crash.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xtemp09** [comment] 2024-09-17 07:18
This is a duplicate of #15918. The PR #16378 fixes this issue. I hope, it will be merged soon.

**Closed** 2024-09-17 07:48 UTC
Labels: Status: Needs triage
