### ISSUE TITLE
Std_Measure: Center Of Mass do not update correctly

### ISSUE THREAD

**Issue by 0penBrain** [FreeCAD/FreeCAD#14120] opened 2024-05-18 10:15 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Steps to reproduce:
 * New document
 * Add a Part::Box
 * Add a Center of Mass measure to the box
 * Change Length of the box => :warning: While 'Result' and 'Placement' (Property Pane) of measure are updated, nothing is on the screen (neither Label, nor value display, nor position of the measure line)

### Full version info

```shell
OS: Ubuntu 22.04.4 LTS (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37361 +1 (Git)
Build type: Debug
Branch: myBranch
Hash: 761d8fc69d0d9a67d0a6cd4da8fdb35401c0a7e6
Python 3.10.12, Qt 5.15.3, Coin 4.0.0, Vtk 7.1.1, OCC 7.6.3
Locale: English/United States (en_US)
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment] 2024-05-18 11:06
Duplicate of #13730

**Closed by maxwxyz** 2024-05-18 11:06 UTC
