### ISSUE TITLE
[Bug] [WB Draft] Undo doesn't work after using Move function on lines created in Draft WB

### ISSUE THREAD

**Issue by acp693** [FreeCAD/FreeCAD#8044] opened 2022-12-14 08:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=3&t=74424

### Version

0.21 (Development)

### Full version info

```shell
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.21.31109 (Git)
Build type: Release
Branch: master
Hash: c23ee7ad88433a0f00e84afae0a62fe738be0c09
Python 3.10.8, Qt 5.15.4, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: German/Germany (de_DE)
Installed mods: 
  * CurvedShapes 1.0.4
  * Curves 0.5.3
  * FeedsAndSpeeds 0.5.0
  * Marz 0.0.26-alpha
  * Silk 1.0.0
```

### Subproject(s) affected?

Draft

### Issue description

Create a line in Draft WB. Use the Move function in Draft WB to move the line and then press undo (ctrl Z), the line doesn't move back to it's original position. However, other objects not created in Draft WB do move back to their original positions such as primitives created in Part WB when the undo function is used. It seems to be lines, splines etc. created in Draft WB that aren't working properly.

This seems to be potentially just a windows problem. Another user, DrMarco, reported correct behaviour from a Linux installation of Freecad.

The problem occurs on the latest development version of Freecad 0.21.31109 and the stable version(0.20.1)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment] 2022-12-29 18:00
@Roy-043 can you test when you get a chance? (Also there is a [rotate bug](https://forum.freecadweb.org/viewtopic.php?p=647336#p647336) not sure it's DraftWB related). This may be just a Windows issues, btw

**Comment by Roy-043** [comment] 2022-12-30 10:42
First of all, I can only confirm this.

The issue seems related to the code used in the `execute` function of the Wire object class. This function is triggered by a recompute inside the move transaction. This somehow 'breaks' undo-redo. There are two potential solutions:
1. Remove/fix the problem code in the `execute` function.
2. Do not recompute inside the transaction, but do so after the transaction has been committed.

See test codes below. The only difference between the two is the position of `doc.recompute()`.

Test code "undo_problem":
```
import FreeCAD as App
import Draft

doc = App.ActiveDocument

p1 = App.Vector(0, 0, 0)
p2 = App.Vector(10, 10, 0)
line = Draft.make_line(p1, p2)
doc.recompute()

delta = App.Vector(20, 0, 0)

doc.openTransaction("undo_problem")
Draft.move(line, delta, copy=False)
doc.recompute()
doc.commitTransaction()
```

Test code "undo_ok":
```
import FreeCAD as App
import Draft

doc = App.ActiveDocument

p1 = App.Vector(0, 0, 0)
p2 = App.Vector(10, 10, 0)
line = Draft.make_line(p1, p2)
doc.recompute()

delta = App.Vector(20, 0, 0)

doc.openTransaction("undo_ok")
Draft.move(line, delta, copy=False)
doc.commitTransaction()
doc.recompute()
```

**Comment by Roy-043** [comment] 2022-12-30 13:31
This is a regression introduced in V0.19.

**Comment by Roy-043** [comment] 2022-12-31 14:57
A 3rd potential solution:
Move the call to `recompute` to the `Draft.move` function. During the V0.19 development cycle this call was deliberately removed.

But since the issue also occurs if you change the Placement of a Draft_Line in the Property editor, the solution probably must be found in the `execute` function. What is strange is that this function has not been changed since V0.18, and in V0.18 the issue does not occur even when directly changing the Placement of the object. This suggests that the cause may involve more than just the code from the Draft Workbench.

**Comment by wwmayer** [comment] 2023-01-01 16:10
Second thread: https://forum.freecadweb.org/viewtopic.php?f=10&t=74920

**Comment by Roy-043** [comment] 2023-01-07 09:46
Here are files that implement the workaround mentioned in the second forum thread: avoid the creation of a new Shape if only the Placement is changed.
https://forum.freecadweb.org/viewtopic.php?f=10&t=74920

Instructions:
1. Make backups of `../Mod/Draft/draftfunctions/` and `../Mod/Draft/draftobjects/`.
2. Unpack [draftfunctions.zip](https://github.com/FreeCAD/FreeCAD/files/10365916/draftfunctions.zip) and [draftobjects.zip](https://github.com/FreeCAD/FreeCAD/files/10365922/draftobjects.zip) in the correct folder.
3. Restarts FreeCAD.

**Closed** 2023-01-31 20:38 UTC
Labels: Bug, WB Draft, UI/UX, Undo / Redo, OS: Windows, Regression
