### ISSUE TITLE
Save "Skip recompute" in Document

### ISSUE THREAD

**Issue by Trallala-Hobsassa** [FreeCAD/FreeCAD#16911] opened 2024-09-29 17:15 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Hi!

You can't save the "Skip recomputes" and the follow-up function "Allow partial recomputes". In large projects with many calculations, this function is particularly missing. 

For me, the project crashes frequently (for reasons still unknown), and then of course you forget to set these settings, which leads to long waiting times...

I've been missing this feature since Version 0.19... It would be great if you could add that! 

Thank you and best regards
Trallala-Hobsassa!

### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 1.0.0RC2.38806 (Git)
Build type: Release
Branch: (HEAD detached at 1.0rc2)
Hash: 3d63fc6c2f665a8d5e6468845a419bcac80756c7
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * 3D_Printing_Tools
  * fasteners 0.5.29
  * freecad.gears 1.3.0

```

### Subproject(s) affected?

None

### Anything else?

![image](https://github.com/user-attachments/assets/d14f8fc0-f500-4a90-a012-6c6a2f2e0656)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment] 2024-10-03 06:53
Duplicate of https://github.com/FreeCAD/FreeCAD/issues/12700

**Closed by maxwxyz** 2024-10-03 06:53 UTC
Labels: Status: Needs triage
