### ISSUE TITLE
Undetected redundant constraint

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6224] opened 2022-02-07 21:48 UTC
Issue imported from https://tracker.freecad.org/view.php?id=4673

* **Reporter:** chrisb
* **Date submitted:** 6/1/2021
* **FreeCAD version:** 0.2
* **Category:** Bug
* **Status:** assigned
* **Tags:** 

# Original report text

Description and file ar in this [forum post](https://forum.freecadweb.org/viewtopic.php?f=3&t=59000).

# FreeCAD Info

```
OS: macOS 10.16
Word size of FreeCAD: 64-bit
Version: 0.20.24825 (Git)
Build type: Release
Branch: master
Hash: ccc4151b3020969450325466e385850783795325
Python version: 3.9.2
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.1
Locale: C/Default (C)

```

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Bug
* **Updated:** 6/1/2021

**Comment by katepavlu** [comment] 2024-05-28 17:47
@maxwxyz 
cannot reproduce in 0.22
no activity in the last 3 years
I think this can be closed

**Comment by maxwxyz** [comment] 2024-05-28 17:52
This is related to https://github.com/FreeCAD/FreeCAD/issues/6201 and maybe also to https://github.com/FreeCAD/FreeCAD/issues/13551
I'll close this one then

**Closed as not planned by maxwxyz** 2024-05-28 17:52 UTC
Labels: Type: Bug, Mod: Sketcher
