### ISSUE TITLE
[Problem] Qt flickering black under Wayland

### ISSUE THREAD

**Issue by willrabbermann** [FreeCAD/FreeCAD#12622] opened 2024-02-26 13:58 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I installed FreeCAD from flatpak. If I open FreeCAD under Wayland the Qt GUI flickers black and back to normal so much its unusable.
![Screenshot from 2024-02-26 07-33-09](https://github.com/FreeCAD/FreeCAD/assets/105755092/db2860c0-3fec-4a5c-bc41-01c05884d2a2)
I hate to switch off of Wayland every-time I want to use FreeCAD.

### Full version info
```
OS: KDE Flatpak runtime (GNOME/gnome)
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: (HEAD detached at b9bfa5c)
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.11.7, Qt 5.15.10, Coin 4.0.0, Vtk 8.2.0, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * A2plus 0.4.63
  * Assembly4 0.50.7
  * fasteners 0.5.12
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jtang613** [comment] 2024-02-29 16:14
Also experiencing this issue. I've tried various Display settings combinations like Software OpenGL, OpenGL, Render Cache, MSAA, but the problem is persistent. This makes the program virtually unusable.

**Comment by Rexbas** [comment] 2024-02-29 17:03
Related: https://forum.freecad.org/viewtopic.php?t=83187

I have the same problem both using Flatpak and self compiled. It is probably a NVIDIA related issue.
```
OS: KDE neon 6.0 (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36120 +1 (Git)
Build type: Release
Branch: fix-navigation-style
Hash: 98f92a1bc36c3564b1abd5050a7b9be2b2619be5
Python 3.11.6, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
```
```
Operating System: KDE neon 6.0
KDE Plasma Version: 6.0.0
KDE Frameworks Version: 6.0.0
Qt Version: 6.6.2
Kernel Version: 6.5.0-21-generic (64-bit)
Graphics Platform: Wayland
Processors: 16 × 12th Gen Intel® Core™ i5-12600K
Memory: 31,1 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2
Manufacturer: Gigabyte Technology Co., Ltd.
Product Name: Z690 UD DDR4
```

**Comment by jtang613** [comment] 2024-02-29 17:22
[code]
OS: Fedora Linux 39 (Workstation Edition) (GNOME/gnome)
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0.21.2)
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.6.3
Locale: English/Canada (en_CA)
Installed mods: 
  * 3DfindIT 1.2.0
  * A2plus 0.4.61
  * freecad.gears 1.0.0
  * kicadStepUpMod 10.21.1
[/code]

**Comment by willrabbermann** [comment] 2024-03-05 15:40
> We need full [About](https://wiki.freecad.org/About) info please to see what dependencies are causing this and saves triage and testing time. TIA

[code]
OS: KDE Flatpak runtime (GNOME/gnome)
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: (HEAD detached at b9bfa5c)
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.11.7, Qt 5.15.10, Coin 4.0.0, Vtk 8.2.0, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * A2plus 0.4.63
  * Assembly4 0.50.7
  * fasteners 0.5.12
[/code]

**Comment by sam9032** [comment] 2024-04-07 13:25
Hi there,
same problem here:

[code]
OS: Arch Linux (GNOME/gnome)
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: makepkg
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.11.8, Qt 6.6.3, Coin 4.0.2, Vtk 9.3.0, OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * Behave-Dark-Colors 0.1.1
  * ArchTextures
  * toSketch 1.0.1
  * 3DfindIT 1.2.0
[/code]

- Wayland Session
- NVIDIA GTX 1070

The problem doesn`t appear in a X11 Session.

**Comment by Rexbas** [comment] 2024-05-31 15:37
I am currently running with NVIDIA driver 555 and the flickering seems to be resolved.

**Comment by HorstBaerbel** [comment] 2024-06-28 14:52
This is also an issue with the weekly AppImage version, not only the FlatPak and it makes FreeCAD basically unusable for me. I run Fedora 40 with Nvidia driver 550.90.07.

**Comment by Rexbas** [comment] 2024-07-07 11:22
@HorstBaerbel, I believe NVIDIA driver 555 is now available on Fedora 40, If you decide to update to this new driver version, can you let us know if this resolved the flickering? For me driver 555 resolved the flickering on KDE Neon but I would like to know if it also resolves the problem for other people and other distros.

**Comment by HorstBaerbel** [comment] 2024-07-07 19:16
> @HorstBaerbel, I believe NVIDIA driver 555 is now available on Fedora 40, If you decide to update to this new driver version, can you let us know if this resolved the flickering? For me driver 555 resolved the flickering on KDE Neon but I would like to know if it also resolves the problem for other people and other distros.

Seems to be fixed with Nvidia driver 555.58.02

**Comment by sam9032** [comment] 2024-07-07 21:36
Same here!

Nvidia 555.58.02 on Arch Linux, with Gnome and Wayland. It works without flickering :rocket:

**Comment by Rexbas** [comment] 2024-07-08 15:49
Nice, then I think this issue can be closed, @maxwxyz.

**Closed** 2024-07-08 15:58 UTC
Labels: Bug, Core, UI/UX, 3rd party component, Status: confirmed
