### ISSUE TITLE
Not able to add object in simulation [Problem] 

### ISSUE THREAD

**Issue by joshdm16** [FreeCAD/FreeCAD#9732] opened 2023-06-06 10:34 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
there is no button under the dpsh window to add object in simulation. Please help me :(
```

### Subproject(s) affected?

None

### Problem description

there is no button under the dpsh window to add object in simulation. Please help me :(

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adrianinsaval** [comment] 2023-06-06 17:21
The issue is too vague and was not submitted properly so I will close this (besides I suspect it's related to an addon), for general help request to understand usage of something please head to the help forum instead: https://forum.freecad.org/viewforum.php?f=3
make sure to read the guidelines before posting.

**Closed by adrianinsaval** 2023-06-06 17:21 UTC
