### ISSUE TITLE
Windows arm64 MSVC - FreeCAD failed to build with "fatal error C1189: #error:  "Byte order of target CPU unknown.""

### ISSUE THREAD

**Issue by YangYang129** [FreeCAD/FreeCAD#6990] opened 2022-06-08 09:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=10&t=68974&p=598112&hilit=msvc#p598112

### Version

0.20 (Development)

### Full version info

```shell
https://github.com/FreeCAD/FreeCAD/commit/5792c502bfaf955e6a7b20f23c64ace1e8b4f218
```

### Issue description

FreeCAD failed to build with "fatal error C1189: #error:  "Byte order of target CPU unknown."" with MSVC on windows arm64. It can reproduce on latest version https://github.com/FreeCAD/FreeCAD/commit/5792c502bfaf955e6a7b20f23c64ace1e8b4f218 on master branch. Could you please help look at this issue?
**Repro steps:**
1. open VS2019 x64 tools command
2. set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=arm64
3. git clone https://github.com/FreeCAD/FreeCAD F:\FreeCAD
4. cd F:\FreeCAD
5. Add "set(Boost_ARCHITECTURE "-x64")" in cmakelists.txt file
6. mkdir build_arm64 & cd build_arm64 
7. cmake -G "Visual Studio 16 2019" -A arm64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0  -DFREECAD_LIBPACK_DIR=F:\gitP\FreeCAD\tools\FreeCADLibs_12.5.2_x64_VC17 -DBUILD_FEM_NETGEN=OFF -DFREECAD_RELEASE_PDB=OFF -DFREECAD_RELEASE_SEH=OFF -DFREECAD_LIBPACK_USE=ON -DCMAKE_BUILD_TYPE=Release ..
8. msbuild /m /p:Platform=arm64 /p:Configuration=Release FreeCAD.sln /t:Rebuild

**Error log:**
[FreeCAD_msbuild_arm64.log](https://github.com/FreeCAD/FreeCAD/files/8860132/FreeCAD_msbuild_arm64.log)

**Error info:**
```
169>F:\gitP\FreeCAD\tools\FreeCADLibs_12.5.2_x64_VC17\include\vtk-8.2\vtkkwiml/abi.h(476,1): fatal error C1189: #error:  "Byte order of target CPU unknown." (compiling source file F:\FreeCAD\src\3rdParty\salomesmesh\src\SMDS\SMDS_Mesh0DElement.cpp) [F:\FreeCAD\build_arm64\src\3rdParty\salomesmesh\SMDS.vcxproj]
   169>F:\gitP\FreeCAD\tools\FreeCADLibs_12.5.2_x64_VC17\include\vtk-8.2\vtkkwiml/abi.h(476,1): fatal error C1189: #error:  "Byte order of target CPU unknown." (compiling source file F:\FreeCAD\src\3rdParty\salomesmesh\src\SMDS\SMDS_BallElement.cpp) [F:\FreeCAD\build_arm64\src\3rdParty\salomesmesh\SMDS.vcxproj]
   169>F:\gitP\FreeCAD\tools\FreeCADLibs_12.5.2_x64_VC17\include\vtk-8.2\vtkkwiml/abi.h(476,1): fatal error C1189: #error:  "Byte order of target CPU unknown." (compiling source file F:\FreeCAD\src\3rdParty\salomesmesh\src\SMDS\SMDS_MeshElement.cpp) [F:\FreeCAD\build_arm64\src\3rdParty\salomesmesh\SMDS.vcxproj]
   169>F:\gitP\FreeCAD\tools\FreeCADLibs_12.5.2_x64_VC17\include\vtk-8.2\vtkkwiml/abi.h(476,1): fatal error C1189: #error:  "Byte order of target CPU unknown." (compiling source file F:\FreeCAD\src\3rdParty\salomesmesh\src\SMDS\SMDS_MeshElementIDFactory.cpp) [F:\FreeCAD\build_arm64\src\3rdParty\salomesmesh\SMDS.vcxproj]
   169>F:\gitP\FreeCAD\tools\FreeCADLibs_12.5.2_x64_VC17\include\vtk-8.2\vtkkwiml/abi.h(476,1): fatal error C1189: #error:  "Byte order of target CPU unknown." (compiling source file F:\FreeCAD\src\3rdParty\salomesmesh\src\SMDS\SMDS_MeshGroup.cpp) [F:\FreeCAD\build_arm64\src\3rdParty\salomesmesh\SMDS.vcxproj]
   169>F:\gitP\FreeCAD\tools\FreeCADLibs_12.5.2_x64_VC17\include\vtk-8.2\vtkkwiml/abi.h(476,1): fatal error C1189: #error:  "Byte order of target CPU unknown." (compiling source file F:\FreeCAD\src\3rdParty\salomesmesh\src\SMDS\SMDS_MeshEdge.cpp) [F:\FreeCAD\build_arm64\src\3rdParty\salomesmesh\SMDS.vcxproj]
   169>F:\gitP\FreeCAD\tools\FreeCADLibs_12.5.2_x64_VC17\include\vtk-8.2\vtkkwiml/abi.h(476,1): fatal error C1189: #error:  "Byte order of target CPU unknown." (compiling source file F:\FreeCAD\src\3rdParty\salomesmesh\src\SMDS\SMDS_Downward.cpp) [F:\FreeCAD\build_arm64\src\3rdParty\salomesmesh\SMDS.vcxproj]

```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by donovaly** [comment] 2022-06-08 13:16
I don't understand the bug report. The linked forum thread is not about compiling for the ARM platform.
Also the given version info is invalid. However this is understandable because we don't provide that FreeCAD is built on the ARM platform.

Closing the issue to get this fixed:
- please open a new forum thread to describe briefly what you want, what you did to achieve this (e.g. from where did you get the different libraries for the ARM platform?)
- when people in the discussion there agrees the issue is real and fixable, then update the forum link in your initial post in this issue
- reopen the issue ;-)

Don't wonder about this, it is just that we get too many issues reported and we therefore require a forum discussion first to assure the issue is valid.

**Closed by donovaly** 2022-06-08 13:16 UTC
Labels: packaging/building, OS: Windows
