### ISSUE TITLE
FEM, GUI, constraint force, scale factor

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5768] opened 2022-02-07 17:43 UTC
Issue imported from https://tracker.freecad.org/view.php?id=3375

* **Reporter:** HarryvL
* **Date submitted:** 3/14/2018
* **FreeCAD version:** 0.17
* **Category:** Feature
* **Status:** confirmed
* **Tags:** 

# Original report text

Object FemConstraintForce. See post:https://forum.freecadweb.org/viewtopic.php?f=18&t=27401

Forces of equal size are displayed differently. Changing the Scale parameter in the FemConstraintForce object Data Panel has no effect.

Displacement boundary conditions cannot be scaled at all and are sometimes so small that they are invisible for a model that fits the display window

# Additional information

Version:

OS: Ubuntu 16.04.4 LTS
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.17.13346 (Git)
Build type: None
Branch: master
Hash: 22ee06de8441bfcc9fded2c6de4232d763fb11bc
Python version: 2.7.12
Qt version: 4.8.7
Coin version: 4.0.0a
OCC version: 7.1.0
Locale: English/UnitedStates (en_US)

# Steps to reproduce

Always

# Other bug information

* **Priority:** normal
* **Severity:** feature
* **Category:** Feature
* **OS: Ubuntu 16.04**
* **Platform:** PC
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by berndhahnebach 2018-09-18 06:02
Mhh, since this was never really implemented it is more a feature request, IMHO.

**Comment by maxwxyz** [comment] 2024-04-06 15:19
Duplicate of https://github.com/FreeCAD/FreeCAD/issues/11306

**Closed by maxwxyz** 2024-04-06 15:19 UTC
Labels: Duplicate, WB FEM, Feature
