### ISSUE TITLE
preferences settings in the Mac 

### ISSUE THREAD

**Issue by riccardodoria** [FreeCAD/FreeCAD#10370] opened 2023-08-26 08:50 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Full version info

```shell
[code]
OS: macOS 13.4.1
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.33848 (Git)
Build type: Release
Branch: master
Hash: 312975edba4e5af0ca1348bfdcf3a71567c52c1b
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: C/Default (C)
Installed mods: 
  * ExtremeProLight 1.6.0
[/code]
```

### Subproject(s) affected?

Other (specify in description)

### Problem description

Today is the first time I installed Freecad Mac version on my macmini M1 with OSX Ventura 13.4.1 operating system. when setting the preferences, the settings window does not come out but only 4 menus: default, transform, cut, color while the instruction manual shows a complete screen that allows you to set the program. out of curiosity, having Parallers and windows installed, I tried the 0.21 version of windows and saw that the screen appears in the preferences. Among other things, I tried to install the beta version of 0.22 on amc but I see that it has the same problem. I am attaching the two screenshots (mac and windows) to be clearer. Thank you

### Anything else?

<img width="1920" alt="version MAC" src="https://github.com/FreeCAD/FreeCAD/assets/2914361/d9526caa-4a81-4dfb-8042-48a0715ed535">
<img width="2032" alt="Version WINDOWS" src="https://github.com/FreeCAD/FreeCAD/assets/2914361/bae9ebae-35f4-4b43-bc1c-1139cb0ad249">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment] 2023-08-26 11:05
Duplicate of #10183

**Closed by luzpaz** 2023-08-26 11:05 UTC
