### ISSUE TITLE
[Bug] Hang on start up when using dual monitors

### ISSUE THREAD

**Issue by e12voltsdac** [FreeCAD/FreeCAD#7070] opened 2022-06-22 05:04 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?style=3&f=4&t=64973

### Version

0.20 (Release)

### Full version info

```shell
[code]
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.20.29177 (Git)
Build type: Release
Branch: releases/FreeCAD-0-20
Hash: 68e337670e227889217652ddac593c93b5e8dc94
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.2
Locale: English/United States (en_US)
Installed mods: 
  * A2plus
  * Assembly4
[/code]
```

### Issue description

FreeCAD will hang on start up when I have last used the program on my second monitor. It seems to be related to the last window position and trying to start from there. Opening FreeCAD results in a frozen blank window, need to kill from Task Manager.

If I modify the registry key for window position to 'reset' it, then I can successfully start FreeCAD. Another work around is disabling the second monitor to force FreeCAD to open on my native monitor.

On Windows 10, monitor resolutions are both 2560 x 1440. Windows scale for viewing set to 100% (no scale).

I can reproduce the issue each time I start FreeCAD by closing it from my second monitor.

Registry key: 
[HKEY_CURRENT_USER\SOFTWARE\FreeCAD\FreeCAD\Qt5.15]
"Position"="@Point(-1 -8)"

### Anything else?

Issue is mentioned in the following forums:

https://forum.freecadweb.org/viewtopic.php?style=3&f=4&t=64973

https://forum.freecadweb.org/viewtopic.php?style=4&p=599231

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment] 2022-06-24 11:21
Sounds like a Qt related multimonitor issue. Any upstream tickets open regarding this?

**Comment by adrianinsaval** [comment] 2022-06-25 00:19
https://forum.freecadweb.org/viewtopic.php?f=3&t=69071
https://forum.freecadweb.org/viewtopic.php?f=4&t=69664
other people also had this problem

**Comment by adrianinsaval** [comment] 2022-06-25 00:20
@wwmayer does freecad do anything to restore the window position of previous session or is this all auto managed by qt?

**Comment by wwmayer** [comment] 2022-06-26 13:57
Yes, it saves current window size, position and the layout of the toolbars or dock windows. Depending on the OS the information is saved in different locations. E.g. on Windows it's saved to the registry or under Linux to the file FreeCAD.conf.

**Comment by chennes** [comment] 2022-06-26 15:13
For the record this is working fine for me under Windows 11, except that FreeCAD always launches on my primary display, regardless of where I had it last.

**Comment by e12voltsdac** [comment] 2023-02-11 21:12
Just wanted to follow up on this issue. I downloaded 20.2 and the issue still exists. Looks like the Qt version is still the same. 
Qt 5.15.2

Does this need to be escalated up to a Qt ticket? 
Thanks!

**Comment by chennes** [comment] 2023-02-11 22:37
No point - they don't support 5.15 anymore, so I certainly wouldn't expect any action on it. I wonder if we can detect an invalid window position and reset it ourselves -- @wwmayer do you know if it's possible to "intercept" or otherwise detect Qt's window reloading code?

**Comment by wwmayer** [comment] 2023-02-15 12:05
The restoring of the main window is done here: https://github.com/FreeCAD/FreeCAD/blob/master/src/Gui/MainWindow.cpp#L1463

**Comment by luzpaz** [comment] 2023-03-15 11:48
bumping for visibility

**Comment by luzpaz** [comment] 2023-09-04 14:29
Anyone want to pick up the mantle on this issue?

**Comment by adrianinsaval** [comment] 2023-09-19 21:06
I can't reproduce this on windows 11
```yml
OS: Windows 11 build 22621
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.34089 +13 (Git)
Build type: Release
Branch: pr/Pesc0/9663
Hash: ed74312cd933b0f80ca4010460f53598872cd641
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: C/Default (C) [ OS: Spanish/Paraguay (es_PY) ]
Installed mods: 

```

**Comment by luzpaz** [comment] 2023-09-23 23:18
@e12voltsdac can you reproduce on development build ? (https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds)

**Comment by luzpaz** [comment] 2023-11-01 14:46
Another dual monitor issue: #11102

**Comment by luzpaz** [comment] 2023-11-17 15:14
@macdroid53 @maxwxyz can you reproduce ?

**Comment by macdroid53** [comment] 2023-11-17 15:59
I have started today's code on Debian/XFCE and Manjaro/Plasma, with dual and triple monitors, no issue.

**Comment by luzpaz** [comment] 2023-11-17 16:25
Can anyone test on windows ?

**Comment by adrianinsaval** [comment] 2023-11-17 16:53
No issue on windows 11

**Comment by luzpaz** [comment] 2023-11-17 18:38
@e12voltsdac we're going to close this ticket. If you can reproduce on latest stable 0.21.2 or latest development 0.22.x please re-open.

**Closed by luzpaz** 2023-11-17 18:38 UTC
Labels: Bug, Core, UI/UX, Missing: feedback, Help wanted, 3rd party: Qt
