### ISSUE TITLE
Export to step fails.

### ISSUE THREAD

**Issue by Panda631** [FreeCAD/FreeCAD#11789] opened 2023-12-21 08:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I designed a part for a old radio model.

![grafik](https://github.com/FreeCAD/FreeCAD/assets/138193590/ee068838-4fdf-4848-9aa2-baec961f2538)

After finishing, I exported to step for 3D printing. No additional options clicked at the dialog box just OK. Than imported the step file back to FreeCAD (took a long time) and finaly looks like that:

![grafik](https://github.com/FreeCAD/FreeCAD/assets/138193590/5be84506-b8e7-4ac7-8a1e-5f080e8eab3a)

The same step file imported to the slicer reported an error "non-manifold edges" and looks like that:

![grafik](https://github.com/FreeCAD/FreeCAD/assets/138193590/a153e910-9167-4782-a64c-503a75fdb68f)

Can anyone comfirm that behavior? Maybe I did something wrong with the model. An export to stl works perfect!

Here the model.

[Step_problem.zip](https://github.com/FreeCAD/FreeCAD/files/13737845/Step_problem.zip)

### Full version info

```shell
[code]
OS: Windows 11 build 22621
Word size of FreeCAD: 64-bit
Version: 0.21.1.33668 +26 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.1)
Hash: f6708547a9bb3f71a4aaade12109f511a72c207c
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: German/Germany (de_DE)
Installed mods: 
  * Assembly3 0.12.0
  * Assembly4 0.50.4
  * EM
  * fasteners 0.4.70
  * Help 1.0.3
  * kicadStepUpMod 10.17.1
  * Manipulator 1.5.0
  * Render 2023.8.18
  * sheetmetal 0.2.61
[/code]
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment] 2023-12-22 17:19
The cause of the problem was already found in the related forum topic:
https://forum.freecad.org/viewtopic.php?t=83681&start=10#p727218

Closing this as a user error.

**Closed** 2023-12-22 17:19 UTC
Labels: WB PartDesign, WB Sketcher

**Comment by Panda631** [comment] 2023-12-22 17:24
The descriped change does not solve the problem.!
The failure appears anyway.

**Comment by luzpaz** [comment] 2023-12-22 19:22
Please elaborate @Panda631

**Comment by Panda631** [comment] 2023-12-22 19:31
I can follow now Domad's solution.
Sorry for my fault and thanks for the investigation.
