### ISSUE TITLE
Illegal storage access! in Part.makeRuledSurface

### ISSUE THREAD

**Issue by more10** [FreeCAD/FreeCAD#8116] opened 2023-01-01 14:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.20.2.29177 +426 (Git)
Build type: Release
Branch: (HEAD detached from 0.20.2)
Hash: 930dd9a76203a3260b1e6256c70c1c3cad8c5cb8
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: Swedish/Sweden (sv_SE)
```

### Subproject(s) affected?

None

### Issue description

```
    surface = Part.makeRuledSurface(wire.Shape, wire_1.Shape)
<class 'RuntimeError'>: FreeCAD exception thrown (Illegal storage access! Please save your work under a new file name and restart the application!)
```

I am making a ruled surface between two b-splines (Draft.makeBSpline). 

It works in 0.18, but not in 0.19 (and not in 0.20).

I have tried to output a log file, using the --write-log switch, but I was unsuccessful. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment] 2023-01-01 21:27
Can you attach an example file please

**Comment by more10** [comment] 2023-01-02 23:57
I will make a simple one. In a few days.

**Comment by more10** [comment] 2023-01-03 21:58
![FreeCAD 0 18](https://user-images.githubusercontent.com/2485088/210448076-5bfd4c24-cf6d-4d4e-8e81-525b4d7f3557.png)
![FreeCAD 0 20 2](https://user-images.githubusercontent.com/2485088/210448091-a86a4aab-6953-4cfc-8fad-ee310abdbc71.png)
[bug.zip](https://github.com/FreeCAD/FreeCAD/files/10340063/bug.zip)

**Comment by Roy-043** [comment] 2023-08-14 21:28
The problem is caused by the Draft code. During the V0.19 dev cycle it was decided to remove calls to `recompute` from the Draft `make` functions. As a programmer you now have to explicitly call `recompute` yourself.

See for example:
https://wiki.freecad.org/Draft_BSpline#Scripting

Closing this.

**Closed by Roy-043** 2023-08-14 21:28 UTC
