### ISSUE TITLE
[Bug] FreeCAD crashes immediately on clicking Import

### ISSUE THREAD

**Issue by DR2D** [FreeCAD/FreeCAD#6447] opened 2022-02-24 17:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=3&t=66618

### Version

0.19 (Release)

### Full version info

```shell
OS: Windows 7 Version 6.1 (Build 7601: SP 1)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.24267 +99 (Git)
Build type: Release
Branch: Branch_0.19.3
Hash: 6530e364184ce05ccff39501e175cf2237e6ee4b
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.3
Locale: English/United States (en_US)
```

### Issue description

The FreeCAD crash immediately on clicking the import button was due to two factors.  FreeCAD remembers the last import file path to "HELP" you.  AND, if you have the "default" list of file extensions/types set (the one at the top of the list) and there's a file in the directory FreeCAD doesn't like "Good-BYE - Right NOW - No Warning - Just Good-bye".  

Now you're stuck in a loop.  Restarting FreeCAD and clicking "Import" Repeats the Crash.

To get out of the loop you have to go in and delete the .cfg files and then reset the import file extension/type selection to anything other than the top default selection.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chennes** [comment] 2022-02-24 17:58
Thanks for the report -- we triage these in the FreeCAD Forums, so I've started a topic here:
https://forum.freecadweb.org/viewtopic.php?f=3&t=66618

**Comment by DR2D** [comment] 2022-02-24 18:20
Chris,

 

After a bit more experimentation it may be the characters in the file name or some other crazy combination.  I created a dummy directory and this “Ver-8” file crashes.  It’s not .STL files because those file types in other directories import OK.  Attached is another .STL file that works.

 

Dave

**Comment by DR2D** [comment] 2022-02-24 18:50
After a bit more experimentation it may be the characters in the file name or some other crazy combination.  I created a dummy directory and this “Ver-8” file crashes.  It’s not .STL files because those file types in other directories import OK.  Attached is another .STL file that works.
[source_cup(1).zip](https://github.com/FreeCAD/FreeCAD/files/8135023/source_cup.1.zip)
[Probe_Tray_6x2_Ver-8.zip](https://github.com/FreeCAD/FreeCAD/files/8135028/Probe_Tray_6x2_Ver-8.zip)

**Comment by chennes** [comment] 2022-02-25 02:47
I wasn't able to reproduce the error in the latest 0.20_dev, so let me explain my steps and we can discuss where they differ from yours:
1) I downloaded both of your zip files from above
2) I extracted the Probe tray first, into a folder named Probe Tray
3) I extracted the cup and put it in that same folder
4) I loaded FreeCAD 0.20 dev
5) I created a new FreeCAD file
6) I chose File->Import
7) I navigated into the folder with the two files in it
8) I imported the cup
9) I clicked File->Import again
10) FreeCAD opened in the same folder (as expected).
11) I was able to select the Probe tray and import it

**Comment by DR2D** [comment] 2022-02-25 14:50
Chris,

 

Try it again with version 0.19

 

Dave

**Comment by luzpaz** [comment] 2022-02-26 22:49
@DR2D 
1. can you reproduce the bug the way chennes wrote it out meticulously step-by-step?
2. If we can't reproduce on v0.20dev then usually there is little need to test on v0.19.x (reason: with very high probability it's been fixed)

**Comment by DR2D** [comment] 2022-02-27 00:20
I think the program crash has something to do with the file name.  Maybe the (-) instead of (_) in the file name.  In 0.19 I can set the file type to .STL and it crashes immediately upon clicking the Import key when the default directory is set to point toward the one containing the “bad” file.  I also have some .CSG files in that same directory, And, setting the file type to .CSG the directory will open with the “Import” key click.  Then before selecting a file, if I reset the file type to .STL FreeCAD immediately crashes.

 

I haven’t loaded version 0.2 yet.  That’s a ½ gig download that takes some time with my internet connection.

 

Dave

**Comment by luzpaz** [comment] 2022-03-19 15:35
@donovaly can you reproduce on windows with v0.19.4?  

@DR2D can you please test on v0.20dev ?

**Comment by donovaly** [comment] 2022-03-19 17:03
I imported the [Probe_Tray_6x2_Ver-8.zip](https://github.com/FreeCAD/FreeCAD/files/8135028/Probe_Tray_6x2_Ver-8.zip) using FreeCAD 0.19.4 and don't get a crash. Also with latest 0.20dev there is no crash.

**Comment by donovaly** [comment] 2022-03-19 17:05
Closing this issue because our rule is that only issues will be considered that have been reported in the forum and that can be reproduced by at least another user.

In case this issue can be reproduced, please reopen.

**Comment by gsaury** [comment] 2023-04-23 20:05
Hello Guys, i encountered the same issue today with import of STL file . I soon as i click on STL file freeCAD crashes without any message. I use the last version just installed a the moment. Strangely dragging & dropping the  STL file works fine. 
(I m on Win 10). What i noticed when i try to import the file is that the preview can't be displayed. On one STL file it works, i don't know why this one (more simple?) but the display has worked. 
Below is my FreeCAD configuration:
[code]
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.20.2.29603 (Git)
Build type: Release
Branch: releases/FreeCAD-0-20
Hash: 930dd9a76203a3260b1e6256c70c1c3cad8c5cb8
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: French/France (fr_FR)
Installed mods: 
  * 3DfindIT 1.2.0
  * 3D_Printing_Tools
  * A2plus 0.4.60k
  * CADExchanger
  * Curves 0.6.8
  * fasteners 0.4.56
  * freecad.gears 1.0.0
  * Help 1.0.3
  * sheetmetal 0.2.63
  * Silk 0.1.0
[/code]

An idea about this issue? 
Thanks

**Comment by xtemp09** [comment] 2023-04-24 07:16
@gsaury, I think it would be better to provide the file.

**Comment by gsaury** [comment] 2023-04-24 08:55
Hello, it is not on one file but all stl files. Some time the software crashes just with a double click on the folder where are stored the stl files.

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by gsaury** [comment] 2023-04-25 18:13
The crash appears even no stl file selected, just opening a folder. I think that is not an issue with stl file finally.
 So i've tried to make a video to show you the problem and .., has usually with computer science it has disappeared!  FreeCAD works fine now aarrgh!  Hoping it will continue for a long time , sorry for the distraction.

**Comment by adrianinsaval** [comment] 2023-05-04 05:45
might have been related to the problems we had with special characters on paths, since we don't have reproduction instructions, OP has not responded anymore and even the second reporter themselves can't reproduce anymore I'll close this issue, feel free to reopen if you are able to reproduce on latest 0.21 dev version.

**Closed by adrianinsaval** 2023-05-04 05:45 UTC
Labels: Bug
