### ISSUE TITLE
Reliable crash in Data::ElementMap::addName exiting sketcher after adding constraint

### ISSUE THREAD

**Issue by johnsonm** [FreeCAD/FreeCAD#15305] opened 2024-07-09 02:17 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Rename [Frame.zip](https://github.com/user-attachments/files/16136170/Frame.zip) to Frame.FCStd and open it.

Open Sketch014 in SpindleFrame body:

![image](https://github.com/FreeCAD/FreeCAD/assets/79751/bb2476ba-6b07-4bd1-90ca-c1baa721a682)

Add a single point. It doesn't seem to matter where, but here I have added it to the left shorter line, accepting an automatic symmetric constraint:

![image](https://github.com/FreeCAD/FreeCAD/assets/79751/f4436fe8-9a06-450d-9646-4d6565e5ba4e)

Close the sketch, crash:

```
Program received signal SIGSEGV, Segmentation fault.
#0  /lib/x86_64-linux-gnu/libc.so.6(+0x3c050) [0x7f80367d4050]
#1  0x7f8039afbaf6 in std::_Rb_tree<Data::MappedName, std::pair<Data::MappedName const, Data::IndexedName>, std::_Select1st<std::pair<Data::MappedName const, Data::IndexedName> >, std::less<void>, std::allocator<std::pair<Data::MappedName const, Data::IndexedName> > >::_M_mbegin() const from /var/home/johnsonm/d/FreeCAD/build/lib/libFreeCADApp.so+0xc
#2  0x7f8039afb9d8 in std::_Rb_tree<Data::MappedName, std::pair<Data::MappedName const, Data::IndexedName>, std::_Select1st<std::pair<Data::MappedName const, Data::IndexedName> >, std::less<void>, std::allocator<std::pair<Data::MappedName const, Data::IndexedName> > >::_M_begin() from /var/home/johnsonm/d/FreeCAD/build/lib/libFreeCADApp.so+0x18
#3  0x7f8039b211a2 in std::_Rb_tree<Data::MappedName, std::pair<Data::MappedName const, Data::IndexedName>, std::_Select1st<std::pair<Data::MappedName const, Data::IndexedName> >, std::less<void>, std::allocator<std::pair<Data::MappedName const, Data::IndexedName> > >::lower_bound(Data::MappedName const&) from /var/home/johnsonm/d/FreeCAD/build/lib/libFreeCADApp.so+0x2c
#4  0x7f8039b1c5af in std::map<Data::MappedName, Data::IndexedName, std::less<void>, std::allocator<std::pair<Data::MappedName const, Data::IndexedName> > >::lower_bound(Data::MappedName const&) from /var/home/johnsonm/d/FreeCAD/build/lib/libFreeCADApp.so+0x23
#5  0x7f8039b18650 in std::enable_if<std::is_constructible<std::pair<Data::MappedName const, Data::IndexedName>, std::pair<Data::MappedName, Data::IndexedName> >::value, std::pair<std::_Rb_tree_iterator<std::pair<Data::MappedName const, Data::IndexedName> >, bool> >::type std::map<Data::MappedName, Data::IndexedName, std::less<void>, std::allocator<std::pair<Data::MappedName const, Data::IndexedName> > >::insert<std::pair<Data::MappedName, Data::IndexedName> >(std::pair<Data::MappedName, Data::IndexedName>&&) from /var/home/johnsonm/d/FreeCAD/build/lib/libFreeCADApp.so+0x2c
#6  0x7f8039b0bb92 in Data::ElementMap::addName(Data::MappedName&, Data::IndexedName const&, QVector<App::StringIDRef> const&, bool, Data::IndexedName*) from /var/home/johnsonm/d/FreeCAD/build/lib/libFreeCADApp.so+0x262
#7  0x7f8039b0c6de in Data::ElementMap::setElementName(Data::IndexedName const&, Data::MappedName const&, long, QVector<App::StringIDRef> const*, bool) from /var/home/johnsonm/d/FreeCAD/build/lib/libFreeCADApp.so+0x53e
#8  0x7f7ffb4ab6b7 in Data::ComplexGeoData::setElementName(Data::IndexedName const&, Data::MappedName const&, long, QVector<App::StringIDRef> const*, bool) from /var/home/johnsonm/d/FreeCAD/build/Mod/Sketcher/Sketcher.so+0x61
#9  0x7f7ffb46f1a1 in Sketcher::SketchObject::buildShape() from /var/home/johnsonm/d/FreeCAD/build/Mod/Sketcher/Sketcher.so+0x221
#10  0x7f7ffb46ecd7 in Sketcher::SketchObject::execute() from /var/home/johnsonm/d/FreeCAD/build/Mod/Sketcher/Sketcher.so+0x393
#11  0x7f8039829d3f in App::DocumentObject::recompute() from /var/home/johnsonm/d/FreeCAD/build/lib/libFreeCADApp.so+0x75
#12  0x7f800a490059 in Part::Feature::recompute() from /var/home/johnsonm/d/FreeCAD/build/Mod/Part/Part.so+0x1d
#13  0x7f80397501ff in App::Document::_recomputeFeature(App::DocumentObject*) from /var/home/johnsonm/d/FreeCAD/build/lib/libFreeCADApp.so+0x1eb
#14  0x7f803974db2e in App::Document::recompute(std::vector<App::DocumentObject*, std::allocator<App::DocumentObject*> > const&, bool, bool*, int) from /var/home/johnsonm/d/FreeCAD/build/lib/libFreeCADApp.so+0x986
#15  0x7f80398e3c43 in App::DocumentPy::recompute(_object*) from /var/home/johnsonm/d/FreeCAD/build/lib/libFreeCADApp.so+0x2c7
#16  0x7f80398db649 in App::DocumentPy::staticCallback_recompute(_object*, _object*) from /var/home/johnsonm/d/FreeCAD/build/lib/libFreeCADApp.so+0xf3
#17  /lib/x86_64-linux-gnu/libpython3.11.so.1.0(+0x1c9ba1) [0x7f8038024ba1]
#18  /lib/x86_64-linux-gnu/libpython3.11.so.1.0(_PyObject_MakeTpCall+0x7d) [0x7f8037fd6e8d]
#19  /lib/x86_64-linux-gnu/libpython3.11.so.1.0(_PyEval_EvalFrameDefault+0x4a63) [0x7f8037f64c63]
#20  /lib/x86_64-linux-gnu/libpython3.11.so.1.0(+0x3ccd3c) [0x7f8038227d3c]
#21  /lib/x86_64-linux-gnu/libpython3.11.so.1.0(PyEval_EvalCode+0xc1) [0x7f80380c3891]
#22  /lib/x86_64-linux-gnu/libpython3.11.so.1.0(+0x2b7359) [0x7f8038112359]
#23  /lib/x86_64-linux-gnu/libpython3.11.so.1.0(PyRun_StringFlags+0x6b) [0x7f803811350b]
#24  0x7f803890bad1 in Base::InterpreterSingleton::runString[abi:cxx11](char const*) from /var/home/johnsonm/d/FreeCAD/build/lib/libFreeCADBase.so+0xed
#25  0x7f803b4192d4 in Gui::Command::_runCommand(char const*, int, Gui::Command::DoCmd_Type, char const*) from /var/home/johnsonm/d/FreeCAD/build/lib/libFreeCADGui.so+0xc6
#26  0x7f803b418f8d in Gui::Command::_doCommand(char const*, int, Gui::Command::DoCmd_Type, char const*, ...) from /var/home/johnsonm/d/FreeCAD/build/lib/libFreeCADGui.so+0xfd
#27  0x7f803b41a11b in Gui::Command::updateActive() from /var/home/johnsonm/d/FreeCAD/build/lib/libFreeCADGui.so+0x3d
#28  0x7f7ff9238d74 in SketcherGui::ViewProviderSketch::unsetEdit(int) from /var/home/johnsonm/d/FreeCAD/build/Mod/Sketcher/SketcherGui.so+0x2e8
#29  0x7f803b9438af in Gui::ViewProvider::finishEditing() from /var/home/johnsonm/d/FreeCAD/build/lib/libFreeCADGui.so+0x31
#30  0x7f803b30b182 in Gui::Document::_resetEdit() from /var/home/johnsonm/d/FreeCAD/build/lib/libFreeCADGui.so+0x100
#31  0x7f803b253624 in Gui::Application::setEditDocument(Gui::Document*) from /var/home/johnsonm/d/FreeCAD/build/lib/libFreeCADGui.so+0x94
#32  0x7f803b30b07f in Gui::Document::resetEdit() from /var/home/johnsonm/d/FreeCAD/build/lib/libFreeCADGui.so+0x23
#33  0x7f803b381183 in Gui::DocumentPy::resetEdit(_object*) from /var/home/johnsonm/d/FreeCAD/build/lib/libFreeCADGui.so+0x4f
#34  0x7f803b37caad in Gui::DocumentPy::staticCallback_resetEdit(_object*, _object*) from /var/home/johnsonm/d/FreeCAD/build/lib/libFreeCADGui.so+0xf3
#35  /lib/x86_64-linux-gnu/libpython3.11.so.1.0(+0x1c9ba1) [0x7f8038024ba1]
#36  /lib/x86_64-linux-gnu/libpython3.11.so.1.0(_PyObject_MakeTpCall+0x7d) [0x7f8037fd6e8d]
#37  /lib/x86_64-linux-gnu/libpython3.11.so.1.0(_PyEval_EvalFrameDefault+0x4a63) [0x7f8037f64c63]
#38  /lib/x86_64-linux-gnu/libpython3.11.so.1.0(+0x3ccd3c) [0x7f8038227d3c]
#39  /lib/x86_64-linux-gnu/libpython3.11.so.1.0(PyEval_EvalCode+0xc1) [0x7f80380c3891]
#40  /lib/x86_64-linux-gnu/libpython3.11.so.1.0(+0x2b7359) [0x7f8038112359]
#41  /lib/x86_64-linux-gnu/libpython3.11.so.1.0(PyRun_StringFlags+0x6b) [0x7f803811350b]
#42  0x7f803890bad1 in Base::InterpreterSingleton::runString[abi:cxx11](char const*) from /var/home/johnsonm/d/FreeCAD/build/lib/libFreeCADBase.so+0xed
#43  0x7f803b4192d4 in Gui::Command::_runCommand(char const*, int, Gui::Command::DoCmd_Type, char const*) from /var/home/johnsonm/d/FreeCAD/build/lib/libFreeCADGui.so+0xc6
#44  0x7f803b418f8d in Gui::Command::_doCommand(char const*, int, Gui::Command::DoCmd_Type, char const*, ...) from /var/home/johnsonm/d/FreeCAD/build/lib/libFreeCADGui.so+0xfd
#45  0x7f7ff92a1453 in SketcherGui::TaskDlgEditSketch::reject() from /var/home/johnsonm/d/FreeCAD/build/Mod/Sketcher/SketcherGui.so+0x19f
#46  0x7f803b8659c3 in Gui::TaskView::TaskView::reject() from /var/home/johnsonm/d/FreeCAD/build/lib/libFreeCADGui.so+0x9d
#47  0x7f803b8692fb in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (Gui::TaskView::TaskView::*)()>::call(void (Gui::TaskView::TaskView::*)(), Gui::TaskView::TaskView*, void**) from /var/home/johnsonm/d/FreeCAD/build/lib/libFreeCADGui.so+0x6b
#48  0x7f803b868dc5 in void QtPrivate::FunctionPointer<void (Gui::TaskView::TaskView::*)()>::call<QtPrivate::List<>, void>(void (Gui::TaskView::TaskView::*)(), Gui::TaskView::TaskView*, void**) from /var/home/johnsonm/d/FreeCAD/build/lib/libFreeCADGui.so+0x42
#49  0x7f803b8685c5 in QtPrivate::QSlotObject<void (Gui::TaskView::TaskView::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) from /var/home/johnsonm/d/FreeCAD/build/lib/libFreeCADGui.so+0x80
#50  /lib/x86_64-linux-gnu/libQt5Core.so.5(+0x2e8f4f) [0x7f8036e7bf4f]
#51  /lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x2fe860) [0x7f8037ab2860]
#52  /lib/x86_64-linux-gnu/libQt5Core.so.5(+0x2e8f7c) [0x7f8036e7bf7c]
#53  0x7f8037a08fc2 in QAbstractButton::clicked(bool) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x42
#54  /lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x25522a) [0x7f8037a0922a]
#55  /lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x256db8) [0x7f8037a0adb8]
#56  0x7f8037a0afd7 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0xf7
#57  0x7f8037958db8 in QWidget::event(QEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x1a8
#58  0x7f8037916fae in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x7e
#59  0x7f803791f552 in QApplication::notify(QObject*, QEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x13c2
#60  0x7f803b3ba247 in Gui::GUIApplication::notify(QObject*, QEvent*) from /var/home/johnsonm/d/FreeCAD/build/lib/libFreeCADGui.so+0xff
#61  0x7f8036e446f8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x118
#62  0x7f803791d65e in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x1be
#63  /lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x1bdbd8) [0x7f8037971bd8]
#64  /lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x1c0f60) [0x7f8037974f60]
#65  0x7f8037916fae in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x7e
#66  0x7f803b3ba247 in Gui::GUIApplication::notify(QObject*, QEvent*) from /var/home/johnsonm/d/FreeCAD/build/lib/libFreeCADGui.so+0xff
#67  0x7f8036e446f8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x118
#68  0x7f80372233ed in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) from /lib/x86_64-linux-gnu/libQt5Gui.so.5+0x80d
#69  0x7f80371f7cac in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /lib/x86_64-linux-gnu/libQt5Gui.so.5+0xac
#70  /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5(+0x6deca) [0x7f8030c76eca]
#71  /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x299) [0x7f8034e587a9]
#72  /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x54a38) [0x7f8034e58a38]
#73  /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x2c) [0x7f8034e58acc]
#74  0x7f8036e9c836 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x66
#75  0x7f8036e4317b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x12b
#76  0x7f8036e4b2d6 in QCoreApplication::exec() from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x96
#77  /var/home/johnsonm/d/FreeCAD/build/lib/libFreeCADGui.so(+0x1258942) [0x7f803b258942]
#78  /var/home/johnsonm/d/FreeCAD/build/lib/libFreeCADGui.so(+0x1258bf7) [0x7f803b258bf7]
#79  0x7f803b258ed4 in Gui::Application::runApplication() from /var/home/johnsonm/d/FreeCAD/build/lib/libFreeCADGui.so+0x1e2
#80  /var/home/johnsonm/d/FreeCAD/build/bin/FreeCAD(+0x2d5f3) [0x55c98fc035f3]
#81  /lib/x86_64-linux-gnu/libc.so.6(+0x2724a) [0x7f80367bf24a]
#82  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x85) [0x7f80367bf305]
#83  /var/home/johnsonm/d/FreeCAD/build/bin/FreeCAD(+0x2c801) [0x55c98fc02801]
```

### Full version info

```shell
OS: Debian GNU/Linux 12 (bookworm) (GNOME/gnome)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38088 (Git)
Build type: Unknown
Branch: main
Hash: 5568b40a07fac70e70df7f7fe5d60a650418c00c
Python 3.11.2, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * Assembly4 0.50.4
  * Curves 0.6.13
  * sheetmetal 0.3.0
  * ExplodedAssembly
  * fasteners 0.5.24
  * MeshRemodel 1.8919.0
  * freecad.gears 1.0.0
  * Pyramids-and-Polyhedrons
  * dxf_library
  * lattice2 1.0.0
  * boltsfc 2022.11.5
  * in3dca-freegrid 2.0.0
  * parts_library
  * Defeaturing 1.2.0
  * A2plus 0.4.60n
  * CurvedShapes 1.0.4
  * Manipulator 1.5.0
  * Pyramids-and-Polyhedrons.backup1696298372.5270553 (Disabled)
  * Assembly3 0.12.2
  * DynamicData 2.62.0
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xtemp09** [comment] 2024-07-09 06:55
Looks like another duplicate of #15102.

**Comment by maxwxyz** [comment] 2024-07-10 06:30
duplicate of #15102

**Closed by maxwxyz** 2024-07-10 06:30 UTC
