### ISSUE TITLE
improvement of the "hide" function

### ISSUE THREAD

**Issue by 4a3** [FreeCAD/FreeCAD#13956] opened 2024-05-11 15:35 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

it is inconvenient to work with objects when there are many of them. it is better to be able to hide unnecessary things with a "short cut"

### Full version info

```shell
please supplement the "hide selected object" function ("space" button) with the "hide everything except the selected one" function ("ctrl + space" button) and the "show all" function ("alt + space" button)..
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pierreporte** [comment] 2024-05-11 15:53
Do you mean something similar to what is presented in #12142?

**Comment by maxwxyz** [comment] 2024-05-11 16:38
duplicate of https://github.com/FreeCAD/FreeCAD/issues/12142

**Closed by maxwxyz** 2024-05-11 16:38 UTC
