### ISSUE TITLE
When joining a polygon to the end of an arc a tangent is implied

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6144] opened 2022-02-07 20:39 UTC
Issue imported from https://tracker.freecad.org/view.php?id=4521

* **Reporter:** DrC
* **Date submitted:** 12/24/2020
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** new
* **Tags:** #post-to-forum, 0.19, Poly-line, UI

# Original report text

This feature seems to activate at imperceptible movement of the mouse or stylus.  It results in an arbitrary tangent side added at whatever length fits the algorithm arbitrating between the gratuitous tangent and the new side.

A more user friendly approach might be to require a mouse click to define the tangent length.

# Additional information

See my previous report - number to follow.

# Steps to reproduce

See my previous report - number to follow.

# FreeCAD Info

```
OS: Windows 10 (10.0)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.23141 (Git)
Build type: Release
Branch: master
Hash: 0eba78d40096720f7a637a9a73c382a08b820bca
Python version: 3.8.6
Qt version: 5.12.5
Coin version: 4.0.0
OCC version: 7.4.0
Locale: English/United Kingdom (en_GB)

```

# Other bug information

* **Priority:** normal
* **Severity:** major
* **Category:** Feature
* **OS: Windows 10 **
* **Platform:** HP laptop
* **Updated:** 2/7/2021

# Discussion from Mantis ticket

### Comment by DrC 2020-12-24 14:18
Previous report was

0004520: Doubleclick when drawing a polygon seems to results in an unresolvable double point.

---

### Comment by Kunda1 2021-01-31 12:09
Forum thread please

---

### Comment by DrC 2021-02-05 05:38
Sorry - there was no thread to attach this to.  I had a bug mid-job and needed to get it down while I could still remember how it happened.

I probably shouldn't even be here because I'm not a developer and not a professional bug fixer (any more) but merely trying to use FreeCad.  Trouble is I feel an obligation to tell you about as bug when I see it even when (as it always will be) it's mid job and I'm doing something new.

A section headed 'report all bugs here' in the forum might help me - but would it help you?

I really need it to be a one step process unless you can't replicate it.

---

### Comment by DrC 2021-02-05 06:28
https://forum.freecadweb.org/viewtopic.php?f=3&t=5236&p=474546#p474546

---

### Comment by chennes 2021-02-07 03:39
I believe the OP means "polyLINE" rather than "polyGON" -- the effect is that there is an extra segment to your polyline if your cursor is positioned too close to the arc. The logic behind this construction eludes me. IMO, the OP is right, I don't think it should behave like this: I suspect it is an actual bug rather than a feature misbehaving, but this is probably something for abdullah to look into.

---

### Comment by DrC 2021-02-07 11:18
Confirm - polyLINE

Apologies.

Software I grew up with drew 'polygons' this way.

**Comment by grubertechnic** [comment] 2023-07-25 17:45
There was/is an issue, that when you have a simply arc and then you use the polyline tool and want just constrain on it coincident on an endpoint on it, it automatic makes it tangential, which was really annoying. Now it tested it and can not reproduce it anymore, but did not test it very well. When i have time i test it more intensive.

**Comment by grubertechnic** [comment] 2023-07-25 23:18
@adrianinsaval : the issue is gone. I think (means i do not definitely know), that commit 8d33584eeed94884192613e95b457fd7898ba956 seems to fix that. At least that is what i find in the commit history, that fits a little bit, even it is more b-spline related. But at least it was _around_ a half year ago still here and not anymore.

It seems to be save to close it.

**Comment by adrianinsaval** [comment] 2023-07-25 23:21
thanks for testing, I'm closing then

**Closed by adrianinsaval** 2023-07-25 23:21 UTC
Labels: Feature, WB Sketcher
