### ISSUE TITLE
TechDraw: Insert Horizontal/Vertical Extent Dimension Location Problem

### ISSUE THREAD

**Issue by Pendelf** [FreeCAD/FreeCAD#18577] opened 2024-12-17 15:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When Insert Horizontal/Vertical Extent Dimension is used, the dimensions appear centered on the object. Perhaps they should appear outside the object boundary

How it works now

![Снимок экрана 2024-12-17 223214](https://github.com/user-attachments/assets/7f6e8ec5-8783-4497-855c-3a6a19546ad1)

How it's probably supposed to work

![Снимок экрана 2024-12-17 223228](https://github.com/user-attachments/assets/5d92d974-32b7-4e96-a0bc-94667bcb4d06)

https://github.com/user-attachments/assets/b5c0f9b6-dbf9-4d09-9aaf-a482ee102c4e

### Full version info

```shell
OS: Windows 11 build 26100
Architecture: x86_64
Version: 1.1.0dev.39646 (Git) Conda
Build type: Release
Branch: main
Hash: b25b83c1a58bf0ae95cbd502d0ccae27e8127cad
Python 3.11.11, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: Russian/Russia (ru_RU)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Fusion
Installed mods: 
  * Curves 0.6.52
  * fasteners 0.5.33
  * PieMenu 1.10.2
  * sheetmetal 0.6.2
```

### Subproject(s) affected?

TechDraw

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment] 2024-12-17 18:43
Duplicate of https://github.com/FreeCAD/FreeCAD/issues/13832

**Closed by maxwxyz** 2024-12-17 18:43 UTC
Labels: Status: Needs confirmation, Status: Needs triage
