### ISSUE TITLE
Sketcher: Can't delete elements created with "create external geometry" tool

### ISSUE THREAD

**Issue by drew585** [FreeCAD/FreeCAD#15743] opened 2024-08-04 01:11 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Problem in 22.0.38385
Pink line created with "make external geometry" tool. Now I can't delete it.
Highlighting in "elements" window and hitting delete key does nothing.
Right clicking in "elements" window and selecting delete with mouse does nothing.
Tried to select and delete in view space. When hovering mouse over pink external line, it changes colors for pre-selection, but when clicked does not select, reverting to pink when mouse is moved away.
![image](https://github.com/user-attachments/assets/978d16c3-8d58-4440-a7ea-a81ec6bccec4)

Opened same file in 21.2 (flatpack) and it works as expected in stable. Can delete via all three methods described above.

### Full version info

```shell
OS: Linux Mint 22 (X-Cinnamon/cinnamon)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38385 (Git) AppImage
Build type: Release
Branch: main
Hash: 58241e027e7187a1ecaeeb75668ef9a497437c68
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * fasteners 0.5.25
```

### Subproject(s) affected?

Sketcher

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nazar-pc** [comment] 2024-08-04 01:27
Possibly duplicate of https://github.com/FreeCAD/FreeCAD/issues/15738 where external geometry wasn't fully deleted either. The build you're using should have resolved deletion with https://github.com/FreeCAD/FreeCAD/pull/15712, but apparently it didn't, at least not fully.

**Closed** 2024-08-04 04:27 UTC
