### ISSUE TITLE
0.22DEV  Access Violation

### ISSUE THREAD

**Issue by RREE** [FreeCAD/FreeCAD#15542] opened 2024-07-20 17:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The model is a case for the RPi 3A+. Creating sketches for the various holes (SD card, USB-C, USB-A, HDMI, jack) I realized a red exclamation mark in dem model and an "access violation" in the console window. The attached file is a zip of the FCStd file. ([Gehäuse.zip](https://github.com/user-attachments/files/16321831/Gehause.zip))

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38231 (Git)
Build type: Release
Branch: main
Hash: 29889bfd9a7ba0f0496f2e2699d454ea5fb5a05a
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Installed mods: 
  * Gridfinity 0.5.0
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xtemp09** [comment] 2024-07-21 07:40
Here is the backtrace, indicating that this is a duplicate of #15102. bgbsww [claims that]( https://github.com/FreeCAD/FreeCAD/issues/15102#issuecomment-2241162161) the bug has been fixed in the latest dev build.




@RREE, have you tried to reproduce the bug in the latest weekly bundle?





<details>


```cpp
Process 1750 stopped
* thread #1, name = 'FreeCAD', stop reason = signal SIGSEGV: address not mapped to object (fault address: 0x50)
    frame #0: 0x00007ffff6404e77 libFreeCADApp.so`std::map<Data::MappedName, Data::IndexedName, std::less<void>, std::allocator<std::pair<Data::MappedName const, Data::IndexedName>>>::lower_bound(Data::MappedName const&) [inlined] std::_Rb_tree<Data::MappedName, std::pair<Data::MappedName const, Data::IndexedName>, std::_Select1st<std::pair<Data::MappedName const, Data::IndexedName>>, std::less<void>, std::allocator<std::pair<Data::MappedName const, Data::IndexedName>>>::_M_mbegin(this=0x0000000000000040) const at stl_tree.h:737:73
   734 
   735        _Link_type
   736        _M_mbegin() const _GLIBCXX_NOEXCEPT
-> 737        { return static_cast<_Link_type>(this->_M_impl._M_header._M_parent); }
   738 
   739        _Link_type
   740        _M_begin() _GLIBCXX_NOEXCEPT
(lldb) bt
* thread #1, name = 'FreeCAD', stop reason = signal SIGSEGV: address not mapped to object (fault address: 0x50)
  * frame #0: 0x00007ffff6404e77 libFreeCADApp.so`std::map<Data::MappedName, Data::IndexedName, std::less<void>, std::allocator<std::pair<Data::MappedName const, Data::IndexedName>>>::lower_bound(Data::MappedName const&) [inlined] std::_Rb_tree<Data::MappedName, std::pair<Data::MappedName const, Data::IndexedName>, std::_Select1st<std::pair<Data::MappedName const, Data::IndexedName>>, std::less<void>, std::allocator<std::pair<Data::MappedName const, Data::IndexedName>>>::_M_mbegin(this=0x0000000000000040) const at stl_tree.h:737:73
    frame #1: 0x00007ffff6404e77 libFreeCADApp.so`std::map<Data::MappedName, Data::IndexedName, std::less<void>, std::allocator<std::pair<Data::MappedName const, Data::IndexedName>>>::lower_bound(Data::MappedName const&) [inlined] std::_Rb_tree<Data::MappedName, std::pair<Data::MappedName const, Data::IndexedName>, std::_Select1st<std::pair<Data::MappedName const, Data::IndexedName>>, std::less<void>, std::allocator<std::pair<Data::MappedName const, Data::IndexedName>>>::_M_begin(this=0x0000000000000040) at stl_tree.h:741:25
    frame #2: 0x00007ffff6404e77 libFreeCADApp.so`std::map<Data::MappedName, Data::IndexedName, std::less<void>, std::allocator<std::pair<Data::MappedName const, Data::IndexedName>>>::lower_bound(Data::MappedName const&) [inlined] std::_Rb_tree<Data::MappedName, std::pair<Data::MappedName const, Data::IndexedName>, std::_Select1st<std::pair<Data::MappedName const, Data::IndexedName>>, std::less<void>, std::allocator<std::pair<Data::MappedName const, Data::IndexedName>>>::lower_bound(__k=0x00007fffffffa010, this=0x0000000000000040) at stl_tree.h:1271:30
    frame #3: 0x00007ffff6404e73 libFreeCADApp.so`std::map<Data::MappedName, Data::IndexedName, std::less<void>, std::allocator<std::pair<Data::MappedName const, Data::IndexedName>>>::lower_bound(this=size=0, __x=0x00007fffffffa010) at stl_map.h:1309:32
    frame #4: 0x00007ffff6409df2 libFreeCADApp.so`_ZNSt3mapIN4Data10MappedNameENS0_11IndexedNameESt4lessIvESaISt4pairIKS1_S2_EEE6insertIS5_IS1_S2_EEENSt9enable_ifIXsrSt16is_constructibleIS7_JT_EE5valueES5_ISt17_Rb_tree_iteratorIS7_EbEE4typeEOSE_(this=size=0, __x=0x00007fffffffa010) at stl_map.h:857:31
    frame #5: 0x00007ffff63fb0dc libFreeCADApp.so`Data::ElementMap::addName(this=0x0000000000000000, name=0x00007fffffffa2b0, idx=0x00007fffffffa6c0, sids=0x00007fffffffa298, overwrite=false, existing=0x00007fffffffa2a0) at ElementMap.cpp:507:38
    frame #6: 0x00007ffff63fc8c0 libFreeCADApp.so`Data::ElementMap::setElementName(this=0x0000000000000000, element=0x00007fffffffa6c0, name=0x00007fffffffa710, masterTag=0, sid=0x00007fffffffa298, overwrite=false) at ElementMap.cpp:583:87
    frame #7: 0x00007fffb7e8f810 Sketcher.so`Sketcher::SketchObject::buildShape() [inlined] Data::ComplexGeoData::setElementName(overwrite=false, sid=0x0000000000000000, masterTag=0, name=0x00007fffffffa710, element=0x00007fffffffa6c0, this=0x00007fffffffa8b0) at ComplexGeoData.h:262:86
    frame #8: 0x00007fffb7e8f7dd Sketcher.so`Sketcher::SketchObject::buildShape(this=0x0000555557214200) at SketchObject.cpp:273:34
    frame #9: 0x00007fffb7e901e5 Sketcher.so`Sketcher::SketchObject::execute(this=0x0000555557214200) at SketchObject.cpp:250:15
    frame #10: 0x00007ffff623ee4b libFreeCADApp.so`App::DocumentObject::recompute(this=0x0000555557214200) at DocumentObject.cpp:162:29
    frame #11: 0x00007fffc3470576 Part.so`Part::Feature::recompute(this=<unavailable>) at PartFeature.cpp:105:42
    frame #12: 0x00007ffff61cedcc libFreeCADApp.so`App::Document::_recomputeFeature(this=0x0000555559b4e6c0, Feat=0x0000555557214200) at Document.cpp:3129:41
    frame #13: 0x00007ffff61d7008 libFreeCADApp.so`App::Document::recompute(this=0x0000555559b4e6c0, objs=<unavailable>, force=<unavailable>, hasError=0x0000000000000000, options=<unavailable>) at Document.cpp:2856:48
    frame #14: 0x00007ffff62a4f49 libFreeCADApp.so`App::DocumentPy::recompute(this=0x00005555589a58a0, args=<unavailable>) at DocumentPyImp.cpp:578:54
    frame #15: 0x00007ffff62a51eb libFreeCADApp.so`App::DocumentPy::staticCallback_recompute(self=0x00005555589a58a8, args=<unavailable>) at DocumentPy.cpp:1958:66
    frame #16: 0x00007ffff5328008 libpython3.10.so.1.0`___lldb_unnamed_symbol3713 + 72
    frame #17: 0x00007ffff52dfadc libpython3.10.so.1.0`_PyObject_MakeTpCall + 140
    frame #18: 0x00007ffff527ba1c libpython3.10.so.1.0`_PyEval_EvalFrameDefault + 40380
    frame #19: 0x00007ffff53c23af libpython3.10.so.1.0`___lldb_unnamed_symbol4418 + 1647
    frame #20: 0x00007ffff53bd3de libpython3.10.so.1.0`PyEval_EvalCode + 190
    frame #21: 0x00007ffff540c4cd libpython3.10.so.1.0`___lldb_unnamed_symbol4668 + 157
    frame #22: 0x00007ffff540d4f9 libpython3.10.so.1.0`PyRun_StringFlags + 121
    frame #23: 0x00007ffff59fc371 libFreeCADBase.so`Base::InterpreterSingleton::runString[abi:cxx11](this=<unavailable>, sCmd="App.ActiveDocument.recompute()") at Interpreter.cpp:249:15
    frame #24: 0x00007ffff7a1816a libFreeCADGui.so`Gui::Command::_runCommand(file="/home/xtemp09/Downloads/FreeCAD/freecad-source/src/Gui/Command.cpp", line=851, eType=App, sCmd="App.ActiveDocument.recompute()") at Command.cpp:725:38
    frame #25: 0x00007ffff7a18328 libFreeCADGui.so`Gui::Command::_doCommand(file="/home/xtemp09/Downloads/FreeCAD/freecad-source/src/Gui/Command.cpp", line=851, eType=App, sCmd="") at Command.cpp:677:16
    frame #26: 0x00007ffff7a18415 libFreeCADGui.so`Gui::Command::updateActive() at Command.cpp:851:5
    frame #27: 0x00007fffb6edf354 SketcherGui.so`SketcherGui::ViewProviderSketch::unsetEdit(this=0x0000555557220df0, ModNum=<unavailable>) at ViewProviderSketch.cpp:3346:39
    frame #28: 0x00007ffff7d58847 libFreeCADGui.so`Gui::ViewProvider::finishEditing(this=0x0000555557220df0) at ViewProvider.cpp:153:14
    frame #29: 0x00007ffff79894f2 libFreeCADGui.so`Gui::Document::_resetEdit(this=0x0000555559b0c860) at Document.cpp:480:44
    frame #30: 0x00007ffff792de42 libFreeCADGui.so`Gui::Application::setEditDocument(this=0x00007fffffffd7f0, doc=0x0000000000000000) at Application.cpp:1153:29
    frame #31: 0x00007ffff798471a libFreeCADGui.so`Gui::Document::resetEdit(this=<unavailable>) at Document.cpp:467:43
    frame #32: 0x00007ffff79ba420 libFreeCADGui.so`Gui::DocumentPy::resetEdit(this=0x0000555559b1c140, args=<unavailable>) at DocumentPyImp.cpp:169:32
    frame #33: 0x00007ffff79ba469 libFreeCADGui.so`Gui::DocumentPy::staticCallback_resetEdit(self=0x0000555559b1c148, args=<unavailable>) at DocumentPy.cpp:643:66
    frame #34: 0x00007ffff5328008 libpython3.10.so.1.0`___lldb_unnamed_symbol3713 + 72
    frame #35: 0x00007ffff52dfadc libpython3.10.so.1.0`_PyObject_MakeTpCall + 140
    frame #36: 0x00007ffff527ba1c libpython3.10.so.1.0`_PyEval_EvalFrameDefault + 40380
    frame #37: 0x00007ffff53c23af libpython3.10.so.1.0`___lldb_unnamed_symbol4418 + 1647
    frame #38: 0x00007ffff53bd3de libpython3.10.so.1.0`PyEval_EvalCode + 190
    frame #39: 0x00007ffff540c4cd libpython3.10.so.1.0`___lldb_unnamed_symbol4668 + 157
    frame #40: 0x00007ffff540d4f9 libpython3.10.so.1.0`PyRun_StringFlags + 121
    frame #41: 0x00007ffff59fc371 libFreeCADBase.so`Base::InterpreterSingleton::runString[abi:cxx11](this=<unavailable>, sCmd="Gui.getDocument('Geh__use').resetEdit()") at Interpreter.cpp:249:15
    frame #42: 0x00007ffff7a1816a libFreeCADGui.so`Gui::Command::_runCommand(file="/home/xtemp09/Downloads/FreeCAD/freecad-source/src/Mod/Sketcher/Gui/TaskDlgEditSketch.cpp", line=137, eType=Gui, sCmd="Gui.getDocument('Geh__use').resetEdit()") at Command.cpp:725:38
    frame #43: 0x00007ffff7a18328 libFreeCADGui.so`Gui::Command::_doCommand(file="/home/xtemp09/Downloads/FreeCAD/freecad-source/src/Mod/Sketcher/Gui/TaskDlgEditSketch.cpp", line=137, eType=Gui, sCmd="") at Command.cpp:677:16
    frame #44: 0x00007fffb6f1ff05 SketcherGui.so`SketcherGui::TaskDlgEditSketch::reject(this=0x0000555558f5d4f0) at TaskDlgEditSketch.cpp:137:19
    frame #45: 0x00007ffff7ccacf2 libFreeCADGui.so`Gui::TaskView::TaskView::reject(this=0x0000555555c685e0) at TaskView.cpp:830:40
    frame #46: 0x00007ffff7ccc092 libFreeCADGui.so`QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (Gui::TaskView::TaskView::*)()>::call(f=<unavailable>, o=<unavailable>, arg=<unavailable>) at qobjectdefs_impl.h:152:20
    frame #47: 0x00007ffff7ccc0d0 libFreeCADGui.so`QtPrivate::QSlotObject<void (Gui::TaskView::TaskView::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) [inlined] void QtPrivate::FunctionPointer<void (Gui::TaskView::TaskView::*)()>::call<QtPrivate::List<>, void>(arg=<unavailable>, o=<unavailable>, f=<unavailable>) at qobjectdefs_impl.h:185:95
    frame #48: 0x00007ffff7ccc0c8 libFreeCADGui.so`QtPrivate::QSlotObject<void (Gui::TaskView::TaskView::*)(), QtPrivate::List<>, void>::impl(which=<unavailable>, this_=<unavailable>, r=<unavailable>, a=<unavailable>, ret=<unavailable>) at qobjectdefs_impl.h:418:49
    frame #49: 0x00007ffff3ef819f libQt5Core.so.5`void doActivate<false>(QObject*, int, void**) [inlined] QtPrivate::QSlotObjectBase::call(a=0x00007fffffffbe90, r=0x0000555555c685e0, this=0x00005555578f6260) at qobjectdefs_impl.h:398:57
    frame #50: 0x00007ffff3ef8183 libQt5Core.so.5`void doActivate<false>(sender=0x0000555558d13d70, signal_index=10, argv=0x00007fffffffbe90) at qobject.cpp:3925:30
    frame #51: 0x00007ffff3eef16f libQt5Core.so.5`QMetaObject::activate(sender=<unavailable>, m=0x0000000000737280, local_signal_index=3, argv=0x0000000000000000) at qobject.cpp:3985:26
    frame #52: 0x00007ffff4d48984 libQt5Widgets.so.5`QDialogButtonBox::rejected(this=<unavailable>) at moc_qdialogbuttonbox.cpp:299:26
    frame #53: 0x00007ffff4d48ff6 libQt5Widgets.so.5`QDialogButtonBoxPrivate::_q_handleButtonClicked(this=<unavailable>) at qdialogbuttonbox.cpp:882:29
    frame #54: 0x00007ffff4d4a4e7 libQt5Widgets.so.5`QDialogButtonBox::qt_static_metacall(_o=<unavailable>, _c=<unavailable>, _id=<unavailable>, _a=<unavailable>) at moc_qdialogbuttonbox.cpp:159:53
    frame #55: 0x00007ffff3ef8340 libQt5Core.so.5`void doActivate<false>(sender=0x0000555558df11f0, signal_index=9, argv=0x00007fffffffc040) at qobject.cpp:3937:33
    frame #56: 0x00007ffff3eef16f libQt5Core.so.5`QMetaObject::activate(sender=0x0000555558df11f0, m=0x000000000072e060, local_signal_index=2, argv=0x00007fffffffc040) at qobject.cpp:3985:26
    frame #57: 0x00007ffff4c886a4 libQt5Widgets.so.5`QAbstractButton::clicked(this=0x0000555558df11f0, _t1=<unavailable>) at moc_qabstractbutton.cpp:308:26
    frame #58: 0x00007ffff4c889b4 libQt5Widgets.so.5`QAbstractButtonPrivate::emitClicked(this=0x0000555558df0eb0) at qabstractbutton.cpp:415:20
    frame #59: 0x00007ffff4c8a33d libQt5Widgets.so.5`QAbstractButtonPrivate::click(this=0x0000555558df0eb0) at qabstractbutton.cpp:408:20
    frame #60: 0x00007ffff4c8a588 libQt5Widgets.so.5`QAbstractButton::mouseReleaseEvent(this=0x0000555558df11f0, e=0x00007fffffffc820) at qabstractbutton.cpp:1044:17
    frame #61: 0x00007ffff4bbafe9 libQt5Widgets.so.5`QWidget::event(this=0x0000555558df11f0, event=0x00007fffffffc820) at qwidget.cpp:8671:26
    frame #62: 0x00007ffff4c8b99e libQt5Widgets.so.5`QAbstractButton::event(this=0x0000555558df11f0, e=0x00007fffffffc820) at qabstractbutton.cpp:1001:26
    frame #63: 0x00007ffff4d45b5d libQt5Widgets.so.5`QPushButton::event(this=0x0000555558df11f0, e=0x00007fffffffc820) at qpushbutton.cpp:718:34
    frame #64: 0x00007ffff4b6eee3 libQt5Widgets.so.5`QApplicationPrivate::notify_helper(this=<unavailable>, receiver=0x0000555558df11f0, e=0x00007fffffffc820) at qapplication.cpp:3640:31
    frame #65: 0x00007ffff4b77cda libQt5Widgets.so.5`QApplication::notify(this=<unavailable>, receiver=0x0000555558df11f0, e=0x00007fffffffc820) at qapplication.cpp:3084:43
    frame #66: 0x00007ffff79e0cf2 libFreeCADGui.so`Gui::GUIApplication::notify(this=0x00007fffffffd770, receiver=0x0000555558df11f0, event=0x00007fffffffc820) at GuiApplication.cpp:83:40
    frame #67: 0x00007ffff3eb3cdd libQt5Core.so.5`QCoreApplication::notifyInternal2(receiver=0x0000555558df11f0, event=0x00007fffffffc820) at qcoreapplication.cpp:1064:24
    frame #68: 0x00007ffff3eb3f78 libQt5Core.so.5`QCoreApplication::sendSpontaneousEvent(receiver=0x0000555558df11f0, event=0x00007fffffffc820) at qcoreapplication.cpp:1474:27
    frame #69: 0x00007ffff4b76a4b libQt5Widgets.so.5`QApplicationPrivate::sendMouseEvent(receiver=0x0000555558df11f0, event=0x00007fffffffc820, alienWidget=0x0000555558df11f0, nativeWidget=0x00007fffffffd7b0, buttonDown=0x00007ffff5157a30, lastMouseReceiver=0x00007ffff5157a10, spontaneous=true, onlyDispatchEnterLeave=false) at qapplication.cpp:2622:56
    frame #70: 0x00007ffff4bd84eb libQt5Widgets.so.5`QWidgetWindow::handleMouseEvent(this=0x000055555adb9620, event=0x00007fffffffce80) at qwidgetwindow.cpp:684:44
    frame #71: 0x00007ffff4bdbf0a libQt5Widgets.so.5`QWidgetWindow::event(this=0x000055555adb9620, event=0x00007fffffffce80) at qwidgetwindow.cpp:300:25
    frame #72: 0x00007ffff4b6eee3 libQt5Widgets.so.5`QApplicationPrivate::notify_helper(this=0x0000555555730a70, receiver=0x000055555adb9620, e=0x00007fffffffce80) at qapplication.cpp:3640:31
    frame #73: 0x00007ffff4b7788e libQt5Widgets.so.5`QApplication::notify(this=0x00007fffffffd770, receiver=0x000055555adb9620, e=0x00007fffffffce80) at qapplication.cpp:2980:31
    frame #74: 0x00007ffff79e0cf2 libFreeCADGui.so`Gui::GUIApplication::notify(this=0x00007fffffffd770, receiver=0x000055555adb9620, event=0x00007fffffffce80) at GuiApplication.cpp:83:40
    frame #75: 0x00007ffff3eb3cdd libQt5Core.so.5`QCoreApplication::notifyInternal2(receiver=0x000055555adb9620, event=0x00007fffffffce80) at qcoreapplication.cpp:1064:24
    frame #76: 0x00007ffff3eb3f78 libQt5Core.so.5`QCoreApplication::sendSpontaneousEvent(receiver=<unavailable>, event=<unavailable>) at qcoreapplication.cpp:1474:27
    frame #77: 0x00007ffff432abf3 libQt5Gui.so.5`QGuiApplicationPrivate::processMouseEvent(e=0x0000555555c4db40) at qguiapplication.cpp:2285:42
    frame #78: 0x00007ffff432c5e8 libQt5Gui.so.5`QGuiApplicationPrivate::processWindowSystemEvent(e=0x0000555555c4db40) at qguiapplication.cpp:2005:50
    frame #79: 0x00007ffff4306188 libQt5Gui.so.5`QWindowSystemInterface::sendWindowSystemEvents(flags=(i = 36)) at qwindowsysteminterface.cpp:1169:61
    frame #80: 0x00007fffee204104 libQt5XcbQpa.so.5`xcbSourceDispatch(source=<unavailable>, (null)=<unavailable>, (null)=<unavailable>) at qxcbeventdispatcher.cpp:105:51
    frame #81: 0x00007ffff331bd3b libglib-2.0.so.0`g_main_context_dispatch + 619
    frame #82: 0x00007ffff33712b8 libglib-2.0.so.0`___lldb_unnamed_symbol2709 + 488
    frame #83: 0x00007ffff33193e3 libglib-2.0.so.0`g_main_context_iteration + 51
    frame #84: 0x00007ffff3f20d83 libQt5Core.so.5`QEventDispatcherGlib::processEvents(this=0x0000555555870a40, flags=(i = 36)) at qeventdispatcher_glib.cpp:423:43
    frame #85: 0x00007fffee2044c4 libQt5XcbQpa.so.5`QXcbGlibEventDispatcher::processEvents(this=<unavailable>, flags=<unavailable>) at qxcbeventdispatcher.cpp:143:47
    frame #86: 0x00007ffff3eb165f libQt5Core.so.5`QEventLoop::processEvents(this=0x00007fffffffd270, flags=<unavailable>) at qeventloop.cpp:142:68
    frame #87: 0x00007ffff3eb1d00 libQt5Core.so.5`QEventLoop::exec(this=0x00007fffffffd270, flags=(i = 0)) at qeventloop.cpp:235:22
    frame #88: 0x00007ffff3ebc6a3 libQt5Core.so.5`QCoreApplication::exec() at qcoreapplication.cpp:1375:36
    frame #89: 0x00007ffff431dca6 libQt5Gui.so.5`QGuiApplication::exec() at qguiapplication.cpp:1870:34
    frame #90: 0x00007ffff4b6ee4d libQt5Widgets.so.5`QApplication::exec() at qapplication.cpp:2832:33
    frame #91: 0x00007ffff79349db libFreeCADGui.so`(anonymous namespace)::tryRunEventLoop(mainApp=0x00007fffffffd770) at Application.cpp:2063:23
    frame #92: 0x00007ffff7934ca4 libFreeCADGui.so`(anonymous namespace)::runEventLoop(mainApp=0x00007fffffffd770) at Application.cpp:2083:24
    frame #93: 0x00007ffff7938b1e libFreeCADGui.so`Gui::Application::runApplication() at Application.cpp:2160:17
    frame #94: 0x0000555555570a15 FreeCAD`main(argc=<unavailable>, argv=<unavailable>) at MainGui.cpp:300:45
    frame #95: 0x00007ffff3429d90 libc.so.6`__libc_start_call_main(main=(FreeCAD`main at MainGui.cpp:107:1), argc=1, argv=0x00007fffffffdd48) at libc_start_call_main.h:58:16
    frame #96: 0x00007ffff3429e40 libc.so.6`__libc_start_main_impl(main=(FreeCAD`main at MainGui.cpp:107:1), argc=1, argv=0x00007fffffffdd48, init=<unavailable>, fini=<unavailable>, rtld_fini=<unavailable>, stack_end=0x00007fffffffdd38) at libc-start.c:392:3
    frame #97: 0x0000555555570275 FreeCAD`_start + 37
(lldb)
```


```ruby
OS: Ubuntu 22.04.4 LTS (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38239 (Git)
Build type: Debug
Branch: main
Hash: 0278bd8f27df454d34920e0f9a4243783b3e9ebf
Python 3.10.12, Qt 5.15.14, Coin 4.0.0, Vtk , OCC 7.5.1
Locale: English/United States (en_US)
```



</details>

**Comment by maxwxyz** [comment] 2024-07-21 09:18
Duplicate of #15102

**Closed by maxwxyz** 2024-07-21 09:18 UTC

**Comment by xtemp09** [comment] 2024-07-21 13:06
In the latest dev build there is neither "Access violation" nor crash. _FreeCAD_ reports:


> Aussparungen vorne: Shape must be a wire, edge or compound. Something else was supplied.



```ruby
OS: Ubuntu 22.04.4 LTS (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38275 (Git)
Build type: Debug
Branch: main
Hash: 41d67f8e108a77ec0b98a9ca47d85575eb43476c
Python 3.10.12, Qt 5.15.14, Coin 4.0.0, Vtk , OCC 7.5.1
Locale: English/United States (en_US)
```
