### ISSUE TITLE
Latest nighly is reported to be damaged by MacOS 14.6.1

### ISSUE THREAD

**Issue by pboe** [FreeCAD/FreeCAD#16067] opened 2024-08-26 10:28 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The latest 
FreeCAD_weekly-builds-38506-conda-macOS-arm64-py311.dmg 
could not be started on a Macbook Pro M3 with MacOS 14.6.1.
MacOS reports the file to be damaged and recommends to remove it.
sha256 is correct and an old weekly build 38127 still works fine.

### Full version info

```shell
Latest Weekly Build 38506
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment] 2024-08-26 10:48
Duplicate of https://github.com/FreeCAD/FreeCAD-Bundle/issues/291

**Closed by maxwxyz** 2024-08-26 10:48 UTC
Labels: Status: Needs triage
