### ISSUE TITLE
Floor/Building container don't keep objects hidden

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5923] opened 2022-02-07 19:18 UTC
Issue imported from https://tracker.freecad.org/view.php?id=3951

* **Reporter:** Geoplace
* **Date submitted:** 4/30/2019
* **FreeCAD version:** 0.18
* **Category:** Bug
* **Status:** assigned
* **Tags:** 

# Original report text

Floor Container has an impact of not maintaining the desired object visibility (hide) when you edit other objects inside it, the hided ones are shown again.

Also when you save the file with the rectangle hidden and when re-open it again it will show everything. (Don’t save the hide status of the children objects)

[Link to the forum discussion ](https://forum.freecadweb.org/viewtopic.php?p=304822#p304822)

# Additional information

When all the elements are outside the Floor Container you can modify the line elements and the visibility of the rectangle stays as needed (hide)

This a very annoying bug when you are editing the elements inside a Floor or building object. You have to be hiding and hiding over and over every edition made in order to could work.

There's is no work around beside avoid using the floor container and lacking the levels functionality of it.

***Here is a sample file where you just need to do step 5 and 6 to view the bug.***

Tested with:
OS: Windows 8.1
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.16110 (Git)
Build type: Release
Branch: (HEAD detached at upstream/releases/FreeCAD-0-18)
Hash: f7dccfaa909e5b9da26bf50c4a22ccca9bb10c40
Python version: 3.6.6
Qt version: 5.6.2
Coin version: 4.0.0a
OCC version: 7.3.0

OS: Windows 8.1
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.16502 (Git)
Build type: Release
Branch: master
Hash: 06962535fa9ff348acca1b893cc4239908fb8bae
Python version: 3.6.6
Qt version: 5.6.2
Coin version: 4.0.0a
OCC version: 7.3.0

# Steps to reproduce

1.-Choose the Arch workbench.
2.-Draw a line (one or more) and a rectangle (its face property is true)
3.-Create a floor object.
4.-Drag and Drop the line and rectangle inside the floor object.
5.-Select the Rectangle object and hit spacebar key (to toggle visibility) hide it.

6.-Draw a new line or trim extend one existent. Or change its length and clic recompute button (F5).
7.-The rectangle show again without request. (If it is the base of a slab, the slab will show)

# Other bug information

* **Priority:** normal
* **Severity:** major
* **Category:** Bug
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by @yorikvanhavre 2019-05-02 17:04
Assigning this to me for now, but I thnk the problem lies somewhere in the group extension...

---

### Comment by Geoplace 2019-05-03 21:04
[Related to Bug 3664](3664) 

That is a more general test case compared to the bug in this report.

---

### Comment by @Roy-043 2019-09-13 09:30
This V0.19 issue seems related:
https://forum.freecadweb.org/viewtopic.php?f=3&t=39255

**Comment by Roy-043** [comment] 2023-01-01 20:21
I cannot reproduce the issue in v0.20.2 and v0.21.0. Therefore closing this.
```
OS: Windows 8.1 Version 6.3 (Build 9600)
Word size of FreeCAD: 64-bit
Version: 0.21.0.31432 (Git)
Build type: Release
Branch: master
Hash: 63a2855751d638bf27ed969dc60654bda2b54baf
Python 3.10.8, Qt 5.15.4, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: Dutch/Netherlands (nl_NL)
Installed mods:
```

**Closed by Roy-043** 2023-01-01 20:21 UTC
Labels: Bug, WB Arch
