### ISSUE TITLE
Different preferences window on different languages

### ISSUE THREAD

**Issue by pOmelchenko** [FreeCAD/FreeCAD#16668] opened 2024-09-19 21:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

i use macos and I installed 1.0rc version and it's fine. I open preferences window
<img width="1007" alt="Screen Shot 2024-09-20 at 00 26 58" src="https://github.com/user-attachments/assets/df522098-e761-485b-b228-d0e421a418f7">
but than I change language to russian and saw this
<img width="1043" alt="Screen Shot 2024-09-20 at 00 26 39" src="https://github.com/user-attachments/assets/658ac7eb-fc66-4f9d-bc02-4913ee5bb1cd">

all tries I open thees windows with menu 

en
<img width="298" alt="Screen Shot 2024-09-20 at 00 35 46" src="https://github.com/user-attachments/assets/37de6f16-db49-4c6e-aad6-0d9e722f4d3d">

ru
<img width="342" alt="Screen Shot 2024-09-20 at 00 36 07" src="https://github.com/user-attachments/assets/75b7fb2b-d1c8-4827-b862-90650b4cfe40">

ua
<img width="339" alt="Screen Shot 2024-09-20 at 00 38 15" src="https://github.com/user-attachments/assets/159984c4-f124-416b-b749-2c383bf4eaef">

### Full version info

```shell
OS: macOS 12.7.6
Word size of FreeCAD: 64-bit
Version: 1.0.0RC1.38642 (Git)
Build type: Release
Branch: (HEAD detached at 1.0rc1)
Hash: 60a251354e203bdb924e2190fb9f5e18b48d7362
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C)
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment] 2024-09-20 21:30
Sometimes restarting freecad between language changes fixes weird behavior. Can you test that ?

**Comment by pOmelchenko** [comment] 2024-09-21 09:29
> Can you test that ?
It doesn't help. Restart freecad a few times and restart OS, but problem wasn't go

**Comment by pOmelchenko** [comment] 2024-09-21 22:25
I'll check this bug with weekly-build version

**Comment by pOmelchenko** [comment] 2024-09-22 01:04
```
OS: macOS 12.7.6
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38794 (Git)
Build type: Release
Branch: main
Hash: a47800d9ccd7d7a7cdb1779d56de03d3c64cd76e
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Qt default
```

The problem remains

**Comment by luzpaz** [comment] 2024-09-22 02:04
@johnocfii sorry for the odd request but could you reproduce this on macOS ? TIA!

**Comment by luzpaz** [comment] 2024-09-22 12:31
@kaktusus do you see this ?

**Comment by kaktusus** [comment] 2024-09-22 13:26
Now the situation looks correct. It must be mistakes from the past.
https://crowdin.com/editor/freecad/27908/en-ru?view=comfortable#6622867

In the Polish translation we had an analogous problem that surfaced out of nowhere ...
![obraz](https://github.com/user-attachments/assets/d4effce1-b294-4104-b96a-dd1801cdc8ac)


The next translation export from Crowdin should fix this.
It's worth watching. :stuck_out_tongue_winking_eye:

**Comment by JohnOCFII** [comment] 2024-09-22 15:04
> @JohnOCFII sorry for the odd request but could you reproduce this on macOS ? TIA!

I'd agree that something isn't working correctly. (Now to figure out how to get back to English!)

<img width="1495" alt="Screenshot 2024-09-22 at 10 00 18 AM" src="https://github.com/user-attachments/assets/857cf3b6-e3e9-4dc2-9a49-6ecff0581e05">

```
OS: macOS 15.0
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38794 (Git)
Build type: Release
Branch: main
Hash: a47800d9ccd7d7a7cdb1779d56de03d3c64cd76e
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C)
Stylesheet/Theme/QtStyle: OpenDark.qss/OpenDark/Fusion
Installed mods: 
  * FeedsAndSpeeds 0.5.0
  * OpenTheme 2024.9.1
  * fasteners 0.5.29
  * Curves 0.6.47
```

**Comment by JohnOCFII** [comment] 2024-09-22 15:12
> I'd agree that something isn't working correctly. (Now to figure out how to get back to English!)

Found it: `          <FCText Name="Language">English</FCText>`

**Comment by maxwxyz** [comment] 2024-11-10 11:07
Duplicate of https://github.com/FreeCAD/FreeCAD/issues/12006

**Closed by maxwxyz** 2024-11-10 11:07 UTC
Labels: Translation, Status: Needs confirmation, Topic: User Interface, Status: Needs feedback, Topic: Preferences
