### ISSUE TITLE
Suggestion for improvement of the new Materials thing.

### ISSUE THREAD

**Issue by leoheck** [FreeCAD/FreeCAD#15197] opened 2024-07-04 18:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

This is an example of what the Material properties should be.
You can find this on the new Assembly > Insert Component.
It has an input field where you can type a string to find anything.

![image](https://github.com/FreeCAD/FreeCAD/assets/1277920/cde93673-e70c-498a-a3ad-9aaaa0edb11e)

This is how it is now. It is a huge list in a small space which is hard to understand/locate/use.

![image](https://github.com/FreeCAD/FreeCAD/assets/1277920/bc0cbf0d-dd2a-479d-9823-3330f9583c2c)

Also, how do we use this Material thing? Is there a wiki page?
Why I cannot add a color to my part? The buttons are grayed out.

### Full version info

```shell
OS: Ubuntu 24.04 LTS (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38001 (Git) AppImage
Build type: Release
Branch: main
Hash: 1fc6da959b936a2999774a4fe5b4c4b12bf6ac8d
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * POV-Ray-Rendering
  * Assembly4 0.50.12
  * InventorLoader 1.4.0
  * ose-piping
  * OpenTheme 2024.7.3
  * SheetMetal 0.4.20
  * fasteners 0.5.24
  * asm4_disable_version_check_popup
  * Render 2024.6.5
  * OpticsWorkbench 1.0.18
  * lattice2 1.0.0
  * kicadStepUpMod
```
```


### Subproject(s) affected?

None

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment] 2024-07-04 18:17
This seems to be a duplicate of https://github.com/FreeCAD/FreeCAD/issues/14686 and https://github.com/FreeCAD/FreeCAD/issues/14940

**Closed by maxwxyz** 2024-07-04 18:17 UTC
