### ISSUE TITLE
[Feature Request] UI/UX Fix distance tool's readability (white-on-light)

### ISSUE THREAD

**Issue by ita1024** [FreeCAD/FreeCAD#6860] opened 2022-05-10 16:06 UTC
### Is there an existing request for this?

- [X] I have searched the existing requests

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=34&t=68576

### Subproject(s) affected?

Part

### Idea description

In Freecad 0.2 (28793 Git), the labels from the measurement tool appear as white on light green when the part or a face is selected. This gets even worse with the pre-selection highlighting (white on yellow), and with the distance tool's size (tiny white cross).

![yes](https://user-images.githubusercontent.com/508304/167672206-f8eeac36-cbc0-40e9-8e8d-cd972b1e0713.png)

Early video players had a similar problem, which was is usually solved by adding a dark outline. The colors could also be inverted, or a background could be added behind the text to increase the contrast. Though I changed the default colors (the pre-highlighting is way too light), the faces sometimes take light colors again due to the illumination so this does not fix the problem.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment] 2023-03-15 15:01
@MisterMakerNL can you reproduce on ExtremeProDark ?

**Comment by MisterMakerNL** [comment] 2023-03-15 18:44
@luzpaz Yes, and I also looked into if this is themable, but without any luck.
The measure distance future is also 1 pix width which is not ideal.
@realthunder Already has an improved measure tool in Linkstage, might want to add the color when he has time to implement the new tool?

**Comment by maxwxyz** [comment] 2024-02-21 13:34
Duplicate of https://github.com/FreeCAD/FreeCAD/issues/8561
Will be fixed with the unified measurement tool.

**Closed by maxwxyz** 2024-02-21 13:34 UTC
Labels: UI/UX, Feature
