### ISSUE TITLE
Thicken sketch

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6057] opened 2022-02-07 19:35 UTC
Issue imported from https://tracker.freecad.org/view.php?id=4334

* **Reporter:** wmayer
* **Date submitted:** 5/3/2020
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** new
* **Tags:** 

# Original report text

https://forum.freecadweb.org/viewtopic.php?f=8&t=31624

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Feature
* **Updated:** 2/6/2021

**Comment by maxwxyz** [comment] 2024-08-28 06:44
Duplicate of https://github.com/FreeCAD/FreeCAD/issues/10538

**Closed by maxwxyz** 2024-08-28 06:44 UTC
Labels: Mod: Part Design, Type: Feature, Topic: Thickness
