### ISSUE TITLE
Colour reverts after any edit

### ISSUE THREAD

**Issue by bluewave-aqua** [FreeCAD/FreeCAD#15818] opened 2024-08-08 02:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I have coloured a part yellow by setting its 'shape colour'. After any edit (or even opening and closing an underlying sketch with no changes) the part reverts to default grey in 3D view, despite the 'shape colour' remaining set to yellow. Only fix is to open the 'shape colour' dialog, set to another colour, close dialog, then reopen and apply yellow again.

Work around might be to change colours of underlying parts, but is still wrong for a part with 'shape colour' set yellow to be displayed gray.

### Full version info

```shell
[code]
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.21.1.33668 +26 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.1)
Hash: f6708547a9bb3f71a4aaade12109f511a72c207c
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: English/New Zealand (en_NZ)
Installed mods: 
  * BIM 2021.12.0
  * dxf-library
  * kicadStepUpMod
  * sheetmetal 0.4.23
[/code]
```

### Subproject(s) affected?

None

### Anything else?

Discussed here, with example freecad file:

https://forum.freecad.org/viewtopic.php?p=775299

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment] 2024-08-08 07:18
Duplicate of https://github.com/FreeCAD/FreeCAD/issues/15503

**Closed by maxwxyz** 2024-08-08 07:18 UTC
Labels: Status: Needs triage
