### ISSUE TITLE
Part vs Part Design 

### ISSUE THREAD

**Issue by leoheck** [FreeCAD/FreeCAD#16085] opened 2024-08-27 03:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

This is a special issue for the new 1.0 specially when considering new users.
Is it possible to improve this `Part` vs `Part Design` naming? Both workbenches have quite the same name. Maybe the `Part Workbench ` could be changed to something else.

### Full version info

```shell
0.22-dev.
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment] 2024-08-27 05:38
Duplicate of https://github.com/FreeCAD/FreeCAD/issues/12637

**Closed by maxwxyz** 2024-08-27 05:38 UTC
Labels: Status: Needs triage
