### ISSUE TITLE
[Problem] Representing threading on arbors or shafts

### ISSUE THREAD

**Issue by didieryvron** [FreeCAD/FreeCAD#12051] opened 2024-01-20 11:48 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

This is concern **Part Design** workshop, in my opinion, it will be interesting to have a function which permit to define **partial lenght thread on the extremity of arbors or shafts**. It may be symbolic to limit the weight of the file or represented if necessary.
It will be a good thing to link this function with TechDraw. Please excuse me for my poor english. Regards - Didier

### Full version info

```shell
[code]
OS: KDE Flatpak runtime (X-Cinnamon/cinnamon)
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: (HEAD detached at b9bfa5c)
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.11.7, Qt 5.15.10, Coin 4.0.0, Vtk 8.2.0, OCC 7.6.3
Locale: French/France (fr_FR)
Installed mods: 
  * Curves 0.6.22
  * freecad.gears 1.0.0
  * boltsfc 2022.11.5
  * A2plus 0.4.62
  * fasteners 0.5.0
  * sheetmetal 0.3.16
  * Help 1.0.3
[/code]
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pierreporte** [comment] 2024-01-20 11:49
Duplicate of #5567.

**Closed** 2024-01-23 09:37 UTC
