### ISSUE TITLE
Assembly: define suffix to name multiple but equal parts

### ISSUE THREAD

**Issue by BernhardSchiffner** [FreeCAD/FreeCAD#14425] opened 2024-06-01 12:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

If  multiple parts of the same type are added to an assembly, their reference is an automagic combination of  their name with some number.
If  a bearing of type "302002"  is used multiple times, then it is first referenced as "302002"  then "302003" and so on.
But "302003" decribes a bearing with different geometry which can led to confusion

I'd like to have an option how the reference (link) in the assembly is named.
Let it be (as example) some suffix with an increasing number: 302002_01 , 302002_02 and so on.
This can be described "as %n_%d%d" in a config option. (%n for part / body name, _ for some free text, %d for count in digits.)

### Full version info

```shell
OS: Ubuntu 22.04.4 LTS (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37573 (Git)
Build type: Unknown
Branch: main
Hash: 91aac05021023c946dc1545f2b13512ccf326550
Python 3.10.12, Qt 5.15.3, Coin 4.0.0, Vtk 9.1.0, OCC 7.5.2
Locale: German/Germany (de_DE)
Installed mods: 
  * Curves 0.6.37
  * kicadStepUpMod 11.1.6
  * sheetmetal 0.4.16
  * fasteners 0.5.21
  * Assembly3 0.12.2 (Disabled)
```

### Subproject(s) affected?

None

### Anything else?

![Bildschirmfoto vom 2024-06-01 14-07-36](https://github.com/FreeCAD/FreeCAD/assets/152042368/fbbc4662-cfc4-4664-98d0-36f0b3590877)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pierreporte** [comment] 2024-06-01 14:43
Duplicate of #12139.

**Closed** 2024-06-03 11:21 UTC
Labels: Feature, Preferences, WB Assembly
