### ISSUE TITLE
Recompute does not create a solid containing a complex shaped hole (upstream OCC bug)

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5787] opened 2022-02-07 17:45 UTC
Issue imported from https://tracker.freecad.org/view.php?id=3458

* **Reporter:** chrisb
* **Date submitted:** 5/4/2018
* **FreeCAD version:** 0.18
* **Category:** Bug
* **Status:** confirmed
* **Tags:** #ready-for-migration, OCC 7.3, OCC Bug, upstream

# Original report text

When a solid contains a very complex hole it is not displayed correctly.
See [forum discussion](https://forum.freecadweb.org/viewtopic.php?f=3&t=28487)

UR_ has found a fix: https://forum.freecadweb.org/viewtopic.php?f=3&t=28487&start=10#p231534

and some code:

```
obj = App.getDocument("kuggkuggkugg_ur").getObject("Offset")
obj.ViewObject.update()
```

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Bug
* **Updated:** 1/24/2022

# Discussion from Mantis ticket

### Comment by @wwmayer 2018-05-27 16:39
It's a 100% OCCT bug. With v7.2 it at least can create the missing face but must perform the meshing twice.

---

### Comment by @luzpaz 2018-05-30 23:39
wmayer should a bug be submitted upstream ?

---

### Comment by @luzpaz 2022-01-15 13:25
user1234 writes in https://forum.freecadweb.org/viewtopic.php?p=534396#p534396 
> Pads without issues, well, it the padding works a few seconds since the insane amount of segments, but the geometry check takes a few minutes. But it works out of the box and the shape is valid. The padded file is too big to attach.

OS: Debian GNU/Linux 11 (bullseye) (X-Cinnamon/lightdm-xsession)
Word size of FreeCAD: 64-bit
Version: 0.20.25751 (Git)
Build type: Release
Branch: master
Hash: ef0e303235c03811eb29bc17e71f22ebdce95356
Python version: 3.9.2
Qt version: 5.15.2
Coin version: 4.0.0
OCC version: 7.5.3
Locale: English/United States (en_US)

**Comment by adrianinsaval** [comment] 2023-04-21 21:53
Looks like this has been long solved in occt, I can't reproduce with our current release and we don't ship any version with old enough occt versions to be worried about this issue IMO, since someone else has also reported not being able to reproduce already with occt 7.5.3 I'll close this issue.

**Closed by adrianinsaval** 2023-04-21 21:53 UTC
Labels: Bug, Duplicate, WB Part, Upstream, 3rd Party: OCC
