### ISSUE TITLE
Strange Symbol in report view, task view and property view

### ISSUE THREAD

**Issue by evansdaniel79** [FreeCAD/FreeCAD#18582] opened 2024-12-17 17:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I have noticed that in Freecad 1.0 and 1.1 there seems to be a bug where there is the & symbol in the report view and other tabs. I haven't noticed any functional impart but it looks very strange. I am using open theme in the about section but it does it on the original theme too.
![Screenshot_20241217_093148](https://github.com/user-attachments/assets/0fc76909-6566-49bf-93c9-fff3b9354d82)

### Full version info

```shell
OS: KDE Flatpak runtime (KDE/plasma/wayland)
Architecture: x86_64
Version: 1.1.0dev.39241 (Git) Flatpak
Build type: Release
Branch: (HEAD detached at cdb9276)
Hash: cdb92768fe4f33d900664415c613f9eced5b8927
Python 3.11.10, Qt 6.7.3, Coin 4.0.3, Vtk 9.2.6, OCC 7.8.1
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: OpenDark.qss/OpenDark/
Installed mods: 
  * OpenTheme 2024.9.1
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment] 2024-12-17 18:40
@snow-faerie could it be because or https://github.com/FreeCAD/FreeCAD/pull/15532 ?

**Comment by Syres916** [comment] 2024-12-21 15:34
This is a duplicate of https://github.com/FreeCAD/FreeCAD/issues/16640

**Closed** 2024-12-21 15:36 UTC
Labels: Mod: Core, Status: Needs confirmation, Topic: User Interface, Topic: Wayland
