### ISSUE TITLE
[Problem] Shortcut for Sketcher CompConstrainRadDia not working

### ISSUE THREAD

**Issue by PLChris** [FreeCAD/FreeCAD#11230] opened 2023-10-30 00:37 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Since the introduction of the smart dimensioning tool the shortcut R for CompConstrainRadDia doesn't work.
When Preferences->Dimensioning is set to both, and the CompConstrainRadDia tool is selected, then the Shortcut should be R as indicated in the help text. However, R always invokes the radius.

### Full version info

```shell
[code]
OS: macOS 13.0
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.34789 (Git)
Build type: Release
Branch: main
Hash: 41503d63ebc3de96d156e6eb0cdb889ebb150bd4
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: C/Default (C)
Installed mods: 
  * FC_SU
  * freecad.gears 1.0.0
  * FeedsAndSpeeds 0.5.0
  * dxf-library
  * fcgear 1.0.0
  * fasteners 0.4.59
  * sheetmetal 0.2.62
  * ExplodedAssembly
  * Curves 0.6.8
[/code]
```

### Subproject(s) affected?

Sketcher

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment] 2023-10-30 11:49
@PaddleStroke do you know who worked on smart/auto dimensioning in Sketcher ?

**Comment by wwmayer** [comment] 2023-10-31 07:01
I cannot reproduce this problem either.

**Comment by luzpaz** [comment] 2023-11-15 13:30
@PLChris can you please respond?

**Comment by Roy-043** [comment] 2024-01-14 18:53
I can't reproduce either. Closing this.

**Closed by Roy-043** 2024-01-14 18:53 UTC
Labels: Bug, WB Sketcher, Regression, Missing: feedback, Shortcut
