### ISSUE TITLE
UI consistency of Tasks breaks with the Appearance & Measurement tool's task UI

### ISSUE THREAD

**Issue by rahmanshaber** [FreeCAD/FreeCAD#7516] opened 2022-09-22 17:12 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?p=623293#p623293

### Version

0.20 (Release)

### Full version info

```shell
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.20.1.29410 (Git)
Build type: Release
Branch: releases/FreeCAD-0-20
Hash: f5d13554ecc7a456fb6e970568ae5c74ba727563
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * Assembly4 0.12.0
  * kicadStepUpMod 10.14.0
```

### Issue description

All the tool's task UI's "Cancel" and "OK" button in top except the measurement tool's. Same is true for appearance tool's task.
We also need cancel button for "appearance" to remove the changes that is done. Currently if you change something there and no way to go back
![image](https://user-images.githubusercontent.com/30831735/191809788-f6534270-b665-499d-991a-b6967d0b2856.png)
![image](https://user-images.githubusercontent.com/30831735/191809814-6fa06821-d01e-4665-be33-2e1966802386.png)

These tool's task page have the buttons in top
![image](https://user-images.githubusercontent.com/30831735/191809882-5be94de8-dd88-4b70-b93b-ac56420c5514.png)
![image](https://user-images.githubusercontent.com/30831735/191809908-1b188c65-c45a-441f-a6bb-c2a130b6fcd0.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Zolko-123** [comment] 2022-10-28 12:54
This is not a [Bug] and the title should be renamed.

**Comment by luzpaz** [comment] 2022-10-28 14:19
How to characterize it then, suggestions?

**Comment by luzpaz** [comment] 2022-10-29 15:19
It is discussed on the forum. It is being tracked here so we don't forget. It's also labeled UI/UX

**Comment by adrianinsaval** [comment] 2022-11-04 01:48
Buttons are now on top so that part of the issue is tackled, should this be kept open for the cancel buttons? IMO a cancel button doesn't make sense for the measurements tool
the appearance dialog would need some refactoring to get a cancel button I think

**Comment by chennes** [comment] 2022-11-04 02:39
I think that adding Cancel to appearance is a significant enough amount of work to warrant it's own issue -- my preference is to close this one and create a new, focused issue, and cross-link them.

**Comment by luzpaz** [comment] 2022-11-04 14:49
@adrianinsaval thank you!

@chennes I agree. Lets close and open an issue for 'Cancel' button.

**Comment by rahmanshaber** [comment] 2022-11-04 16:50
@adrianinsaval that cancel button in the measurement tool won't put the measured value after you close that dialog. But if user clicks okay then the measurements will be there with the part

**Comment by adrianinsaval** [comment] 2024-07-21 19:08
this measurement tool has been removed so this is no longer relevant

**Closed by adrianinsaval** 2024-07-21 19:08 UTC
Labels: UI/UX
