### ISSUE TITLE
[Problem] Draft: Shapestring error

### ISSUE THREAD

**Issue by dross012** [FreeCAD/FreeCAD#11069] opened 2023-10-17 04:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I'm using the latest stable version, no custom preferences except grid size.
When I try to create a shapestring I get the following error.
Thank you!

>  Traceback (most recent call last):
  File "C:\Program Files\FreeCAD 0.21\Mod\Draft\drafttaskpanels\task_shapestring.py", line 148, in accept
    self.createObject()
  File "C:\Program Files\FreeCAD 0.21\Mod\Draft\drafttaskpanels\task_shapestring.py", line 169, in createObject
    x = App.Units.Quantity(self.form.sbX.text()).Value
<class 'ValueError'>: syntax error

### Full version info

```shell
[code]
OS: Windows 11 build 22621
Word size of FreeCAD: 64-bit
Version: 0.21.1.33668 +26 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.1)
Hash: f6708547a9bb3f71a4aaade12109f511a72c207c
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: English/United States (en_US)
[/code]
```

### Subproject(s) affected?

Draft

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment] 2023-10-17 08:11
You need to provide a step-by-step scenario. Including which coordinate values you have entered. With the current information I can't reproduce.
```
OS: Windows 8 build 9600
Word size of FreeCAD: 64-bit
Version: 0.21.1.33668 +26 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.1)
Hash: f6708547a9bb3f71a4aaade12109f511a72c207c
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: Dutch/Netherlands (nl_NL)
Installed mods:
```

**Comment by dross012** [comment] 2023-10-18 01:55
I redesigned the project and no longer need Shapestring. Thank you for your reply.

**Comment by luzpaz** [comment] 2023-10-18 02:15
@dross012 if you found a bug..help us reproduce it

**Comment by dross012** [comment] 2023-10-18 23:41
Attached is the things I did to get the error message. I also attached the project I'm working on. I hope this helps you. If there is anything else you need, please let me know. Thank you for your help!!!

**Comment by luzpaz** [comment] 2023-10-19 03:08
@dross012 nothing attached. You need to drag drop the file in zipped format in to github text box for it to upload.

**Comment by dross012** [comment] 2023-10-19 03:42
[Shop.zip](https://github.com/FreeCAD/FreeCAD/files/13037403/Shop.zip)

**Comment by yorikvanhavre** [comment] 2023-10-19 08:27
It's strange... You are working in imperial units, right?
I can reproduce the problem once, then switching to centimeters works, then switching back to imperial works too

**Comment by dross012** [comment] 2023-10-19 11:48
Yes, I'm using feet and inches.

**Comment by dross012** [comment] 2023-10-20 12:08
Update: I was using Build US not Imperial

**Comment by luzpaz** [comment] 2023-11-18 14:16
@Roy-043 can you take a stab at reproducing ?

**Comment by Roy-043** [comment] 2023-11-20 17:20
There is an issue with the Building US unit system. This may be related.
See #11345.

**Comment by Roy-043** [comment] 2023-11-21 18:07
This is indeed related to the Building US unit system.

**Comment by Roy-043** [comment] 2023-11-22 10:28
Closing this as Duplicate.

**Closed by Roy-043** 2023-11-22 10:28 UTC
Labels: Duplicate, Core, WB Draft, Units
