### ISSUE TITLE
[Problem] Erroneously switching file when confirming/pressing tab/double clicking/pressing space on macOS

### ISSUE THREAD

**Issue by EMPRSR** [FreeCAD/FreeCAD#10589] opened 2023-09-07 13:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

This problem only occurs when multiple files (including the 'Start Page') are in the 'Combo View' ('Tree View') and happens often when a value in the 'Property Editor' is changed and confirmed by pressing Enter or Tab. It automatically switches to the first opened document unrelated to the arrangement in the tab row in the 'Main View Area'.

The issue also happens every time when for example a sketch or 'Part Design' operation in the 'Combo View' is double clicked for editing. Same problem when toggling the visibility of objects pressing space.

A full reinstall of FreeCAD did not help despite using the brew uninstaller and manually hunting any remaining files.
Furthermore, deactivating the Treeview Actions (such as Sync View) has no effect.

Using FreeCAD Version 0.21.0 (33675) on macOS 13.

### Full version info

```shell
[code]
OS: macOS 13.0
Word size of FreeCAD: 64-bit
Version: 0.21.0.33675 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.0)
Hash: 41b058e2087de60dc8fef3d3e68c7d0129e13abf
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: English/United States (en_US) [ OS: C/Default (C) ]
Installed mods: 
  * Behave-Dark-Colors 0.1.1
  * freecad.gears 1.0.0
  * FeedsAndSpeeds 0.5.0
  * Dracula 0.0.5
  * Manipulator 1.5.0
  * fasteners 0.4.63
  * CurvedShapes 1.0.4
  * Help 1.0.3
  * Curves 0.6.13
  * Assembly3 0.12.0
[/code]
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by henrebotha** [comment] 2024-01-19 16:09
I am on macOS 12.7.2 and FreeCAD 0.21.1, and I'm getting the same behaviour. It happens in FreeCAD Link too ([this version](https://github.com/realthunder/FreeCAD/commit/096210d21183e9dfdc3b25777760bfb6c00a210b)).

**Comment by henrebotha** [comment] 2024-01-31 12:12
FWIW this is a massive UX problem and almost makes the software unusable.

**Comment by 3rduino** [comment] 2024-02-10 09:42
Same for me on MacOS 14.3 (Sonoma) and FreeCAD 21.2

**Comment by Achu69** [comment] 2024-03-10 20:06
Same issue, using. The only possible work around is not to use enter/tab when editing data parameters and just click out of the box instead or only have one model open i.e. close all other tabs, including Start Page.

OS: macOS 14.4
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36331 (Git)
Build type: Release
Branch: main
Hash: eb5a1b333946ce4ac8a4ead835cba8bdcf602a87
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: C/Default (C)

**Comment by luzpaz** [comment] 2024-08-22 12:59
@JohnOCFII do you mind trying to reproduce ?

**Comment by Achu69** [comment] 2024-08-22 14:05
Hi, sure.

My current system:
OS: macOS 14.6.1
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38459 (Git)
Build type: Release
Branch: main
Hash: 58729b3ab0060a1525fc45c87beabfd4b3d5e22e
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C)
Installed mods:
  * Gridfinity 0.5.0
  * A2plus 0.4.65
  * fasteners 0.5.26
  * LCInterlocking
  * Curves 0.6.42

The issue:

Open two files:

***@***.***

Select the one on the right for working

***@***.***

Create some geometry and pad it. In this case a circle with 10mm pad and click ok. Select the pad operation in the tree

***@***.***


Try to change the pad thickness via data tab • Length to say 15mm and press <Enter>

***@***.***

***@***.***

The working model gets switched to the one on left

***@***.***

This also happen if instead of pressing <Enter> you press <Tab>. The working file changes only from right to left until it gets to the first tab on the left.

Hope this helps and please let me if I can help further.

Regards
Ed.


From: luzpaz ***@***.***>
Date: Thursday, 22 August 2024 at 13:59
To: FreeCAD/FreeCAD ***@***.***>
Cc: Achu69 ***@***.***>, Comment ***@***.***>
Subject: Re: [FreeCAD/FreeCAD] [Problem] Erroneously switching file when confirming/pressing tab/double clicking/pressing space on macOS (Issue #10589)

@JohnOCFII<https://github.com/JohnOCFII> do you mind trying to reproduce ?

**Comment by luzpaz** [comment] 2024-08-22 14:09
@Achu69 unfortunately responding via email b0rks the formatting and excludes attachments. It's better to respond directly on github

**Comment by Achu69** [comment] 2024-08-22 14:42
Sorry, here it is again, and thank you for your dedication to this great tool!
 
My current system:
OS: macOS 14.6.1
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38459 (Git)
Build type: Release
Branch: main
Hash: 58729b3ab0060a1525fc45c87beabfd4b3d5e22e
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C)
Installed mods:
  * Gridfinity 0.5.0
  * A2plus 0.4.65
  * fasteners 0.5.26
  * LCInterlocking
  * Curves 0.6.42
 
The issue:
 
Open two files:

![Unknown](https://github.com/user-attachments/assets/849dca8f-f2ef-4762-8408-1b3af911c3c7)

Select the one on the right for working

![Unknown](https://github.com/user-attachments/assets/fd495a7d-ee30-4350-a318-d6bc7e2d1862)

Create some geometry and pad it. In this case, draw a circle with 10mm pad and click ok. Select the pad operation in the tree

![Unknown](https://github.com/user-attachments/assets/ec50ce6f-fcfb-449a-b36e-9fbcb624c035)

Try to change the pad thickness via data tab --> Length to say 15mm and press Enter

![Unknown](https://github.com/user-attachments/assets/d73baf89-b6de-408d-9ddc-8f7d823115c4)
![Unknown](https://github.com/user-attachments/assets/a5bdf1a2-9f8b-4921-a974-3f7f59bcd791)

The working model gets switched to the one on left

![Unknown](https://github.com/user-attachments/assets/d2b3d630-2e78-4477-8854-5f4925258bce)

This will also happen if, instead of pressing Enter, you press Tab. The working file changes only from right to left until it gets to the first tab on the left.

**Comment by JohnOCFII** [comment] 2024-08-22 15:16
> @JohnOCFII do you mind trying to reproduce ?

I can reproduce this problem with the most recent functioning weekly build (38459), but the problem is resolved with the change added in PR# 15944.

**Closed** 2024-08-25 01:40 UTC
Labels: Type: Bug, Mod: Core, Topic: User Interface, OS: macOS
