### ISSUE TITLE
[Issue] Notification box is not a subwindow of FreeCAD

### ISSUE THREAD

**Issue by donovaly** [FreeCAD/FreeCAD#8971] opened 2023-03-20 14:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.21 (Development)

### Full version info

```shell
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.21.0.32394 (Git)
Build type: Release
Branch: master
Hash: 431fafc5337976c43bf50aae7bc75b46ee8037c7
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: English/United States (en_US) [ OS: German/Germany (de_DE) ]
```

### Subproject(s) affected?

Core

### Issue description

from @donovaly:
The notification stay on top over all windows. So when I get a notification, then switch to another program, I still see the notification. This is confusing. The notification should be a subwindow of FC's main window not a windows of the OS.

from @PaddleStroke:
I have the messages still showing even when I go to another app, it's very intrusive

from @Syres916:
If I'm 'sending' meshes from FreeCAD to Cura using a macro and I need to change one of the numerous settings then the Profile window in Cura becomes a right pain to keep getting access to it as FC appears to be pushing it to the bottom.

### Anything else?

@abdullahtahiriyo 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by donovaly** [comment] 2023-03-20 14:41
@abdullahtahiriyo

**Comment by abdullahtahiriyo** [comment] 2023-03-20 15:09
@Syres916 

I am specially interested in your case, because of the notifications sending cura to the background.

**Comment by abdullahtahiriyo** [comment] 2023-03-20 19:28
@donovaly 

I am having the problem opposite to yours. I am not having annoying notifications when I am not using FreeCAD and this makes it difficult for me to test improvements.

I have tried to reproduce with a Python script:
```
import time

for i in range(1,100):
    time.sleep(5)
    Err("My Error")
```
However, this does not work, as notifications are only shown when the script is finished. I am not good at Python.

Can you recommend me a way to generate annoying warnings while I read a PDF?

I

**Comment by chennes** [comment] 2023-03-20 20:07
You need to send the errors from a non-GUI thread, or cycle a private event loop. The "cleanest" way to do this is probably to use a QTimer, something like (untested):
```
myTimer = QtCore.QTimer()
myTimer.setInterval(5000)
myTimer.timeout.connect(lambda: Err("My Error"))
myTimer.start()
```

**Comment by abdullahtahiriyo** [comment] 2023-03-21 09:26
@chennes 

Thank you very much. I tend to forget that everything I can do with QT in c++ I can do in Python.

**Comment by 0penBrain** [comment] 2023-03-26 19:17
> The "cleanest" way to do this is probably to use a QTimer, something like (untested):
> 
> ```
> myTimer = QtCore.QTimer()
> myTimer.setInterval(5000)
> myTimer.timeout.connect(lambda: Err("My Error"))
> myTimer.start()
> ```

When doing such things in a macro (that happens if you have to run it often), I'd advise to attach the test object (timer here) to a steady object with something like `setattr(Gui.getMainWindow(), 'testTimer', myTimer)`
First it prevents unwanted deletion from garbage collector, but it is then practical to continue interacting with it, for example `Gui.getMainWindow().testTimer.stop()`

**Comment by luzpaz** [comment] 2023-06-10 22:05
Target for v0.21.x or out of scope ?

**Comment by 0penBrain** [comment] 2023-06-11 09:39
Is it still current ? I tested and notification box is hidden (and kept hidden) as soon as I make another app to be the active one.

**Comment by abdullahtahiriyo** [comment] 2023-06-11 13:04
I think the wanted effect was achieved using a different solution.

**Comment by 0penBrain** [comment] 2023-06-13 11:13
Can one using Windows confirm it's fixed now? Thx

**Comment by 0penBrain** [comment] 2023-06-20 06:53
@donovaly @PaddleStroke @Syres916 may you please feedback?

**Comment by PaddleStroke** [comment] 2023-06-20 07:30
For me it is solved. When the main program change the notification is dismissed.

Something else that is perhaps not ideal though, is that 'show report view on error' is True by default. So on error by default you still have the report view that opens + the notification message. For me the point of notification message is to replace the report view poping up (+ intrusive messages that existed to avoid poping on report view) I'll perhaps open a new issue about it.

**Comment by 0penBrain** [comment] 2023-06-20 09:47
@PaddleStroke thx for feedback. Closing.

**Closed by 0penBrain** 2023-06-20 09:47 UTC
Labels: Core, UI/UX, Help Wanted
