### ISSUE TITLE
Changing of the transparency parameter on Radeon GPU

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5845] opened 2022-02-07 17:53 UTC
Issue imported from https://tracker.freecad.org/view.php?id=3725

* **Reporter:** mnv
* **Date submitted:** 12/12/2018
* **FreeCAD version:** 0.18
* **Category:** Bug
* **Status:** feedback
* **Tags:** #pending-forum, display

# Original report text

I got problem with changing transparency parameter with FreeCAD based on Qt5.
You can see result of the applying transparency value for model on the attachment screenshot.
This problem was reproduced on AMD Radeon HD7700, AMD Radeon HD6670 and AMD Radeon R9 380.
Graphic drivers were updated on the last available version. 

![image](https://user-images.githubusercontent.com/4140247/164440453-5ccb6f90-7916-4fb1-8c95-0a340b5630c4.png)

# Additional information

FreeCAD About Info:
OS: Windows 10
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.15299 (Git)
Build type: Release
Branch: master
Hash: 5217b245b4f98cf1e3f63ecfe20e379fe4923d80
Python version: 3.6.6
Qt version: 5.6.2
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/UnitedStates (en_US)

# Steps to reproduce

1. Run FreeCAD
2. Open any model
3. Select part of model or full model
4. Change Transparency value

# Other bug information

* **Priority:** normal
* **Severity:** major
* **Category:** Bug
* **Updated:** 3/13/2021

# Discussion from Mantis ticket

### Comment by Kunda1 2018-12-12 23:48
Please post a link to this ticket on the forum to discuss with the community 

---

### Comment by mnv 2018-12-14 09:21
https://forum.freecadweb.org/viewtopic.php?f=3&t=32787

---

### Comment by Kunda1 2021-03-13 21:36
mnv is this solved in a higher version of Qt5 ?

**Comment by luzpaz** [comment] 2022-04-21 10:41
@kisolre on the [forum](https://forum.freecadweb.org/viewtopic.php?p=565307#p565307) couldn't reproduce.  

@mwganson wrote
> I think this was determined ultimately to be an issue with COIN 4.0.0a

Closing this ticket for now. Please re-open if necessary

**Closed by luzpaz** 2022-04-21 10:41 UTC
Labels: Bug, core
