### ISSUE TITLE
Always orient dimensions upside up while sketch is rotating

### ISSUE THREAD

**Issue by vovodroid** [FreeCAD/FreeCAD#16756] opened 2024-09-23 17:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When you rotate the sketch dimensions also rotates and could be shown upside down

![image](https://github.com/user-attachments/assets/15a07244-f451-4580-a693-498a708cb303)

It would be nice to have them always oriented in correct way (like Realthunder Link Branch does)

### Full version info

```shell
OS: Windows 10 build 19044
Word size of FreeCAD: 64-bit
Version: 1.0.0RC1.38642 (Git)
Build type: Release
Branch: (HEAD detached at 1.0rc1)
Hash: 60a251354e203bdb924e2190fb9f5e18b48d7362
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English
Installed mods: 
  * Curves 0.6.13
  * ThreadProfile 1.87.0
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FEA-eng** [comment] 2024-09-23 17:48
Duplicate of #13315

**Closed** 2024-09-23 17:50 UTC
Labels: Status: Needs triage
