### ISSUE TITLE
[Problem] Tracing external geometry arc results in over constrained sketch.

### ISSUE THREAD

**Issue by ksdsksd** [FreeCAD/FreeCAD#12156] opened 2024-01-27 17:24 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I cannot find this exact issue.

Attempting draw the same arc(center and endpoints),  as the external geometry results in an over constrained sketch.
![Screenshot_20240127_121644](https://github.com/FreeCAD/FreeCAD/assets/17296616/3c71a946-e72c-47e6-bbf9-193ba7795ab8)
![Screenshot_20240127_121654](https://github.com/FreeCAD/FreeCAD/assets/17296616/5f383e38-65f3-48fa-91e2-ace0c6afca0b)
![Screenshot_20240127_121658](https://github.com/FreeCAD/FreeCAD/assets/17296616/8dec8792-e49e-42a1-87a3-b4df64c4ca7a)

### Full version info

```shell
[code]
OS: Ubuntu 23.10 (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0.21.2)
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * A2plus 0.4.60g
  * fcgear 1.0.0
  * Assembly4 0.12.5
  * Curves 0.5.4
[/code]
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roy-043** [comment] 2024-01-29 10:48
The 2nd coincident constraint fixes the radius a 2nd time. Try replacing it with a horizontal or vertical constraint.

**Comment by ksdsksd** [comment] 2024-01-30 21:40
The same steps in version 0.20, it becomes partially redundant and shows in green.
![Screenshot_20240130_160934](https://github.com/FreeCAD/FreeCAD/assets/17296616/a127ed8e-f39c-45de-82ea-7e4569deee38)

**Comment by Roy-043** [comment] 2024-02-10 14:28
Duplicate of #11852.

**Closed by Roy-043** 2024-02-10 14:28 UTC
