### ISSUE TITLE
Sketcher solver problem constraints

### ISSUE THREAD

**Issue by berberic2** [FreeCAD/FreeCAD#14214] opened 2024-05-22 17:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

It is possible to constrain a sketch in a way, so the sketcher solver thinks the sketch is fully constraint even he ist not.

For an example please see: https://forum.freecad.org/viewtopic.php?t=87565 [german] 
There is a freecad-file ([full-constraint.FCStd](https://forum.freecad.org/download/file.php?id=263485&sid=812ef6af0fad18cbde35d0b12ff8d807)) attached.

### Full version info

```shell
OS: Debian GNU/Linux 12 (bookworm) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37361 +3 (Git)
Build type: Release
Branch: Meins
Hash: 25834835f6264c58a8448fb92f6ce2b0564e8c88
Python 3.11.2, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: German/Germany (de_DE)
Installed mods: 
  * Assembly4 0.50.12
  * Pyramids-and-Polyhedrons
  * sheetmetal 0.4.11
  * Silk 0.1.5
  * CurvedShapes 1.0.9
  * DynamicData 2.62.0
  * FreeCAD_assembly3 0.11.3
  * fcgear 1.0.0
  * fasteners 0.5.21
  * Render 2024.1.23
  * A2plus
  * QuickMeasure 2022.10.28
  * ExplodedAssembly
  * Curves.backup1712652295.888766 0.6.29 (Disabled)
  * Curves 0.6.34
```

### Subproject(s) affected?

Sketcher

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment] 2024-05-22 18:20
Duplicate of https://github.com/FreeCAD/FreeCAD/issues/8324

**Closed by maxwxyz** 2024-05-22 18:20 UTC
