### ISSUE TITLE
Thumbnail not showing on weekly 39315

### ISSUE THREAD

**Issue by Shkolik** [FreeCAD/FreeCAD#18153] opened 2024-11-27 06:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

No thumbnails on a start page. Looks like they are saving - can see in previous weekly build.

39315:

![image](https://github.com/user-attachments/assets/a7abf3e3-5fa1-4038-96e0-78a385ac7db4)

Older 39240:
![image](https://github.com/user-attachments/assets/7c08b438-a961-4175-aa53-cc581a33c133)

### Full version info

```shell
OS: Windows 11 build 26100
Architecture: x86_64
Version: 1.1.0dev.39315 (Git) Conda
Build type: Release
Branch: main
Hash: 710542d121c2cabce05561591cfb00ef3b6e745c
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/Fusion
Installed mods: 
  * CurvedShapes 1.0.8
  * Curves 0.6.28
  * fasteners 0.5.21
  * Foamcut 0.1.5
  * Marz 0.1.5
  * OpenTheme 2024.9.1
  * PieMenu 1.8.1
  * SmartReportFields1.xlsx
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment] 2024-11-27 06:47
Duplicate of https://github.com/FreeCAD/FreeCAD/issues/13676
Can you add your findings there?

**Closed by maxwxyz** 2024-11-27 06:47 UTC
Labels: Status: Needs confirmation, Status: Needs triage
