### ISSUE TITLE
[Problem] FreeCAD 0.21 does not open in macOS 10.15.7 (Catalina)

### ISSUE THREAD

**Issue by rainell** [FreeCAD/FreeCAD#10252] opened 2023-08-16 14:37 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Full version info

```shell
Unable to provide the requested info as the software does not open, but is the last version FreeCAD, 0.21.
```

### Subproject(s) affected?

None

### Problem description

The software just does not open, apparently nothing happens, not even the app or related processes are displayed in the macOS Activity Monitor.
I tried to install both the FreeCAD-0.21.0-WIN-x64-installer-1.exe file and the FreeCAD-0.21.0-coin_patch-mac-intel_x86.dmg file and the same problem occurs.

### Anything else?

**Hardware description**
iMac 27, late 2012
Processor: 2.9 GHz Intel Core i5 quad-core 
Memory: 16GB 1600 MHz DDR3
Graphics Card: NVIDIA GeForce GTX 660M 512MB 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chennes** [comment] 2023-08-16 19:00
Duplicate of https://github.com/FreeCAD/FreeCAD/issues/10090

**Closed** 2023-08-16 19:00 UTC
Labels: Bug, OS: macOS
