### ISSUE TITLE
Warning: "No hasherRef" when loading a file

### ISSUE THREAD

**Issue by furgo16** [FreeCAD/FreeCAD#15468] opened 2024-07-16 16:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Whenever I open [this file](https://github.com/user-attachments/files/16254607/F04.zip), I get these warnings on the report window:

```
Reading failed from embedded file: StringHasher.Table.txt (8834 bytes, 922 bytes compressed)
<ElementMap> <string>(1): No hasherRef
<ElementMap> <string>(1): No hasherRef
<ElementMap> <string>(1): No hasherRef
<ElementMap> <string>(1): No hasherRef
<ElementMap> <string>(1): No hasherRef
<ElementMap> <string>(1): No hasherRef
<ElementMap> <string>(1): No hasherRef
<ElementMap> <string>(1): No hasherRef
<ElementMap> <string>(1): No hasherRef
<ElementMap> <string>(1): No hasherRef
<ElementMap> <string>(1): No hasherRef
```

I would generally not worry too much about them, but they tend at some point to derive into a ["Solve failed" error](https://github.com/FreeCAD/FreeCAD/issues/15385) when attempting to put together the assembly.
 

I'm not sure if it's a general TNP issue (the warning comes from the file below) or it's related to Assembly. In any case, it started manifesting itself when I first built the assembly.

```
git grep -n "No hasherRef"
src/App/ElementMap.cpp:447:                        hasherWarn = "No hasherRef";
```

### Full version info

```shell
OS: Ubuntu Core 22 (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38232 (Git) Snap 1078
Build type: Release
Branch: main
Hash: 3a32ae9985475416324551f44a92f3e578964cf2
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Installed mods: 
  * OpenTheme 2024.7.3
  * Curves 0.6.40
  * ezydxf
  * Ondsel-Lens 2024.7.5.02
  * Assembly4 0.50.15
```

### Subproject(s) affected?

Assembly

### Anything else?

- The attached file was created with a TNP-enabled build (from a recent daily build). The original model had been created with a pre-TNP-enabled version, and I recreated it from scratch when I started getting the warnings. However, the warnings seem to exist in the new file too.
- The assembly is not finished, I'm just adding the state that started outputting the warnings.
- The warnings go away if the assembly is deleted.
- The parts contain many features that could be conflated into less sketches and features. This is intended for educational and manual processing purposes.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by depthoffocus** [comment] 2024-07-16 16:55
> I'm not sure if it's a general TNP issue (the warning comes from the file below) or it's related to Assembly. In any case, it started manifesting itself when I first built the assembly.

I don't think it's to do with assemblies because I don't use Assembly and I've seen it.

I have a feeling I've seen this in 0.21.2 as well.

**Comment by furgo16** [comment] 2024-07-16 20:25
> I don't think it's to do with assemblies because I don't use Assembly and I've seen it.

I cannot tell. The warnings go away if the assembly is deleted, but I'm not sure it's the actual cause.

**Comment by spkane** [comment] 2024-07-19 00:04
I also see something similar with a file I am working on in one of the 0.22 dev releases. To help with debugging, it would be nice to get some better output on what object is triggering this.

```
16:58:22  <ElementMap> <string>(1): No hasherRef
16:58:22  <ElementMap> <string>(1): No hasherRef
```


```
OS: macOS 14.5
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38231 (Git)
Build type: Release
Branch: main
Hash: 29889bfd9a7ba0f0496f2e2699d454ea5fb5a05a
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C)
Installed mods: 
  * Freecad-Built-in-themes-beta 1.2.2
  * SearchBar 1.0.2
  * slic3r-tools
  * DynamicData 2.62.0
  * 3DfindIT 1.2.0
  * ProDarkThemePreferencePack 1.0.0
  * Defeaturing 1.2.2
  * QuickMeasure 2022.10.28
  * Manipulator 1.5.7
  * fasteners 0.5.24
  * CubeMenu
  * 3D_Printing_Tools
  * ToolbarStyle
  * Help 1.0.3
  * Curves 0.6.41
```

**Comment by nazar-pc** [comment] 2024-07-28 00:14
Here is a file that triggers this on loading:
```
03:09:56  Reading failed from embedded file: StringHasher.Table.txt (1733 bytes, 296 bytes compressed)
03:09:56  <ElementMap> <string>(2): No hasherRef
03:09:56  <ElementMap> <string>(2): No hasherRef
03:09:56  <ElementMap> <string>(2): No hasherRef
```

[NPW-2.0.zip](https://github.com/user-attachments/files/16401799/NPW-2.0.zip)

I believe I saw zero sizes with earlier builds of FreeCAD, but not this time.

```
OS: Ubuntu 24.04 LTS (Custom/custom)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38334 (Git) AppImage
Build type: Release
Branch: main
Hash: 61c964caa9a7e5bbc7a8d5f7d8914505d365113e
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Ukrainian/Ukraine (uk_UA)
Installed mods: 
  * OpenTheme 2024.7.3
  * fasteners 0.5.24
  * parts_library
  * Curves 0.6.40
```

**Comment by maxwxyz** [comment] 2024-07-28 04:58
I get this almost all times when trying files from submitted issues.
@bgbsww is this TNP related?

**Comment by bgbsww** [comment] 2024-07-29 14:47
This appears to be another variant of the save/restore problems fixed in the series that ends at #15575.  If you resave the Core file in the example and reload it, the problem is gone.  Are all the files that exhibit this saved from the recent 0.22 releases?

**Comment by nazar-pc** [comment] 2024-07-29 14:50
I can confirm, if save and reopen, those are no longer present in logs :+1:

**Comment by maxwxyz** [comment] 2024-07-29 16:05
This should be fixed with #15575 
Please test again with the latest weekly tomorrow: https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds

**Comment by furgo16** [comment] 2024-07-29 20:37
@bgbsww thank you. Given https://github.com/FreeCAD/FreeCAD/pull/15575#issuecomment-2256014265, does that mean that files that exhibited this warning cannot be fully fixed? Do they need to be recreated from scratch to be error-free?

**Comment by bgbsww** [comment] 2024-07-29 20:51
That's a tricky question; there's a lot of evidence that files that are opened, recomputed, saved, and then reloaded are fine - and if you aren't seeing any continued messages after that, it is fairly likely that all is fine.

Unfortunately, the fix in question here involved fixing the save and restores of many elements, and so I cannot be positive that any given file restores correctly.  However, there haven't been any cases of subtle failures - they tend to be obvious.

**Comment by maxwxyz** [comment] 2024-07-31 10:21
Can this issue be closed then?

**Comment by furgo16** [comment] 2024-07-31 19:43
Unless someone beats me to it, I'd like to validate the fix with the original report's file before closing it. I should be able to some time tomorrow.

**Comment by nazar-pc** [comment] 2024-07-31 19:45
I tested with my files as described earlier and it works fine after re-saving previously problematic documents. I believe this is safe to close as resolved.

**Comment by furgo16** [comment] 2024-08-01 06:58
@bgbsww here's the result of testing the fix with the original file from the report. it appears either the issue is not fixed, or the file is unrecoverable. 

1. Open the [file](https://github.com/user-attachments/files/16254607/F04.zip).
2. The following warnings are shown. Notice the original `Reading failed from embedded file` message is not shown this time around.
   ```
   08:47:53  <ElementMap> ElementMap.cpp(476): No hasherRef
   08:47:53  <ElementMap> ElementMap.cpp(476): No hasherRef
   08:47:53  <ElementMap> ElementMap.cpp(476): No hasherRef
   08:47:53  <ElementMap> ElementMap.cpp(476): No hasherRef
   08:47:53  <ElementMap> ElementMap.cpp(476): No hasherRef
   08:47:53  <ElementMap> ElementMap.cpp(476): No hasherRef
   08:47:53  <ElementMap> ElementMap.cpp(476): No hasherRef
   08:47:53  <ElementMap> ElementMap.cpp(476): No hasherRef
   08:47:53  <ElementMap> ElementMap.cpp(476): No hasherRef
   08:47:53  <ElementMap> ElementMap.cpp(476): No hasherRef
   08:47:53  <ElementMap> ElementMap.cpp(476): No hasherRef
   08:47:53  <ElementMap> ElementMap.cpp(476): No hasherRef
   08:47:53  <ElementMap> ElementMap.cpp(476): No hasherRef
   08:47:53  <ElementMap> ElementMap.cpp(476): No hasherRef
   08:47:53  <ElementMap> ElementMap.cpp(476): No hasherRef
   08:47:53  <ElementMap> ElementMap.cpp(476): No hasherRef
   08:47:53  <ElementMap> ElementMap.cpp(476): No hasherRef
   08:47:53  <ElementMap> ElementMap.cpp(476): No hasherRef
   08:47:53  <ElementMap> ElementMap.cpp(476): No hasherRef
   08:47:53  <ElementMap> ElementMap.cpp(476): No hasherRef
   08:47:53  <ElementMap> ElementMap.cpp(476): No hasherRef
   08:47:53  <ElementMap> ElementMap.cpp(476): No hasherRef
   ```
3. Mark the file to recompute
4. Recompute with <kbd>Ctrl</kbd>+<kbd>R</kbd>
5. See this new warning in the report view:
   ```
   08:51:29  <PropertyLinks> PropertyLinks.cpp(441): F04#Sketch065.AttachmentSupport auto change element reference F04#Pad006 ;g22233;SKT;:H365,E;FAC;:H365:4,F;:G0;XTR;:H365:8,F.Face10 -> ;g381;SKT;:H365,E;FAC;:H365:4,F;:G0;XTR;:H365:8,F.Face10
   ```
6. Save file
7. Close file
8. Open file. Even more warnings appear on the report window now. Truncating the report, but there are now 76 of them (about 3 times more than in the original file):
   ```
   08:52:50  <ElementMap> ElementMap.cpp(476): No hasherRef
   ```

Tested with the latest daily image
```
OS: Ubuntu Core 22 (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38383 (Git) Snap 1095
Build type: Release
Branch: main
Hash: c5408de52591f4a1dfebe14a2a3b589af58d1f3d
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Installed mods: 
  * OpenTheme 2024.7.3
```

**Comment by bgbsww** [comment] 2024-08-01 21:29
Interesting.  So those error messages are because we're reading back element maps without having a hasher defined.  I have been meaning to add that hasher definition ( which obscures the names in the elementMap ), so this probably pushes that over the edge.

**Comment by bgbsww** [comment] 2024-08-03 18:50
So I fixed the hasher issue, and this is still there.  Something else to find ...

**Comment by furgo16** [comment] 2024-08-03 19:46
Thank you. Is there anything I can do to help with testing?

**Comment by bgbsww** [comment] 2024-08-03 19:53
So, instrumenting up StringHasher::restoreStreamNew reveals that the last line of the StringHasher.Table.txt file in that model is read on loop 5581, but the table header says there are 5583 and it fails resulting in the other warnings.

Resaving results in yet another file with the same problem, so it points at a problem in StringHasher::saveStream triggered somehow.

**Comment by bgbsww** [comment] 2024-08-03 20:52
There is a last line missing that is -1.0 0:Shape cache  on ls3, and isn't written by main.

**Comment by bgbsww** [comment] 2024-08-03 22:04
I'm increasingly suspicious that this specific file suffers from something that went wrong with the cache when the assembly was created; I'm having trouble duplicated this anywhere else and creating a tests, but 5000+ entries is too much of a haystack to find 1 or two needles in.

Any chance the assembly can be recreated using code that includes the #15734 fix?

**Comment by furgo16** [comment] 2024-08-04 05:37
> Any chance the assembly can be recreated using code that includes the https://github.com/FreeCAD/FreeCAD/pull/15734 fix?

I can give it a go in the next few days. I've had to recreate both the parts and the assembly multiple times in this development cycle. So essentially the steps would be:

1. Open original file as in the original report
2. Delete assembly
3. Recompute file
4. Save file
5. Recreate assembly from scratch
6. Save and report back

Are these correct?

**Comment by bgbsww** [comment] 2024-08-04 11:59
Yes; I would do multiple recomputes if necessary to eliminate all messages.

**Comment by FeedTheChunk** [comment] 2024-08-09 18:32
This is happening in 38419

OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38419 (Git)
Build type: Release
Branch: main
Hash: 270bb0122ea15bbc562942b9d0756fabb89362c0
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * A2plus 0.4.65
  * Behave-Dark-Colors 0.1.1
  * Dracula 0.0.5
  * ExplodedAssembly
  * fasteners 0.5.24
  * FreeCAD-themes 2024.7.24
  * Ondsel-Lens 2024.7.5.02
  * OpenTheme 2024.7.30
  * ProDarkThemePreferencePack 1.0.0

13:49:10  Reading failed from embedded file: StringHasher.Table.txt (8978 bytes, 1845 bytes compressed)
13:49:10  <ElementMap> <string>(1): No hasherRef
13:49:10  <ElementMap> <string>(1): No hasherRef
13:49:10  <ElementMap> <string>(1): No hasherRef

**Comment by bgbsww** [comment] 2024-08-09 19:22
Correct, and already found.   The code in StringHasher.cpp that writes the
element map takes different paths in main vs LS3 due to writing to a
subfile, and only the code in LS3 had the correct changes to write the
stringhasher count correctly.  Fix coming shortly.  Earlier fixes addressed
the types of entries in the StringHasher table, and so could sidestep the
issue.  Anything with a dressup in a transformation should trigger it
though.

**Closed** 2024-08-12 12:48 UTC
Labels: Type: Bug, Mod: Core, Blocker, Help wanted, Topic: Toponaming

**Comment by maxwxyz** [comment] 2024-08-16 07:28
@bgbsww is this already in the latest weekly from Monday (38459)?
As I've now got the same error when opening the demo file from https://github.com/FreeCAD/FreeCAD/issues/15879 which I have created in the same FreeCAD version.

**Comment by bgbsww** [comment] 2024-08-16 12:04
If I go to the commits list, and then browse the repo at this commit:  https://github.com/FreeCAD/FreeCAD/tree/6f849e1ce2dca58d6ecd4b773e63a6ac93084ab0 then it indicates 38437 commits.  38459 from Monday is bigger than that, so yes, this should be in that weekly.

The LoftV22 file from #15879 has a Documents.xml file inside it that says ProgramVersion="0.22R38314" so it was written from a version that did not have the fix in it, so the file contains a bad StringHasherTable.txt that will continue to throw warnings until it is resaved from a version without the bug.

**Comment by maxwxyz** [comment] 2024-08-17 07:27
@bgbsww ok now I've got it again.
The file was created from scratch with the weekly from this week Monday (38459).
Opening this file in today's weekly (38467) results in this warning:
![grafik](https://github.com/user-attachments/assets/279257db-8b66-49c2-9185-ec7bea2106bc)

Here is the file:
[WoMo-Schranköse.zip](https://github.com/user-attachments/files/16643968/WoMo-Schrankose.zip)

**Comment by bgbsww** [comment] 2024-08-17 11:27
I think this was fixed in
https://github.com/FreeCAD/FreeCAD/commit/a1ce9830358129cda4d3d2cf66a803aa22e13429
at 38461.  The file in question was written by 38459.

Resaving it in a version after 38461 results in no errors.

**Comment by luzpaz** [comment] 2024-08-17 13:46
I forgot how to check what revision a commit belongs to in order to make sure the current available revision includes said commit ? Anyone remember how to check this ?

**Comment by bgbsww** [comment] 2024-08-17 15:51
I browse the repository at the commit, and look at the count of commits at
the top right.  Maybe there are other ways?

**Comment by leoheck** [comment] 2025-04-01 12:50
I am still seeing this:
```
<ElementMap> ElementMap.cpp(483): No hasherRef
```

```
OS: Ubuntu 24.04.2 LTS (ubuntu:GNOME/ubuntu-xorg/xcb)
Architecture: x86_64
Version: 1.1.0dev.40971 (Git) Conda
Build date: 2025/03/24 18:02:34
Build type: Release
Branch: main
Hash: b33c2363226a5fc1e8222a02659118c95e1a5119
Python 3.11.11, Qt 6.7.3, Coin 4.0.3, Vtk 9.3.1, IfcOpenShell 0.8.1, OCC 7.8.1
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: OpenDark.qss/OpenDark/
Logical DPI/Physical DPI/Pixel Ratio: 96/145.143/1
Installed mods: 
  * Assembly4 0.50.19-dev
  * sheetmetal 0.7.22
  * DynamicData 2.73.0
  * Curves 0.6.60
  * InventorLoader 1.5.1
  * ose-piping
  * OpenTheme 2024.9.1
  * fasteners 0.5.37
  * osh-autodoc-workbench 0.2.3
  * OpticsWorkbench 1.1.2
  * lattice2 1.0.0
  * kicadStepUpMod 11.5.7

```
