### ISSUE TITLE
"New File" option buttons on Welcome Screen shrink when theme is selected

### ISSUE THREAD

**Issue by borish43b** [FreeCAD/FreeCAD#15062] opened 2024-06-30 12:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Each time when I select a theme on the welcome screen for a fresh install, the buttons in the "New File" portion of the screen shrinks.

Steps:

1. Start FreeCAD
2. Select Theme "Dark theme"
3. Select Theme "Classic"

Expected behavior:
The theme is applied 

Actual behavior:
The theme is applied and the buttons shrink (see screenshots). When the theme is applied via "Done" button, the "New File" buttons stay in that state.
![after_start](https://github.com/FreeCAD/FreeCAD/assets/61952043/3095da98-3635-40bb-806c-d4c23701d681)
![after_first_theme_selection](https://github.com/FreeCAD/FreeCAD/assets/61952043/83498dae-12a7-4c9b-a368-5281bd9f81f3)
![after_second_theme_selection](https://github.com/FreeCAD/FreeCAD/assets/61952043/5589ad0f-6364-4e86-85ce-ad4cf0f45e50)

### Full version info

```shell
OS: Debian GNU/Linux 12 (bookworm) (GNOME/gnome)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37928 (Git) AppImage
Build type: Release
Branch: main
Hash: e7699b531eba4bee262f7214699f07b96f66ba7b
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FEA-eng** [comment] 2024-06-30 12:58
Duplicate of #14347

**Closed** 2024-06-30 13:41 UTC
