### ISSUE TITLE
[Problem] sometimes can't deselect things in newly created sketches

### ISSUE THREAD

**Issue by dominikh** [FreeCAD/FreeCAD#9538] opened 2023-05-10 17:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.21 (Development)

### Full version info

```shell
[code]
OS: NixOS 23.05 (Stoat)
Word size of FreeCAD: 64-bit
Version: 0.21.0.Unknown
Build type: Release
Python 3.10.10, Qt 5.15.8, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.2
Locale: English/United States (en_US)
Installed mods: 
  * fasteners 0.4.56
  * ProDarkThemePreferencePack 1.0.0
[/code]
```

### Subproject(s) affected?

Sketcher

### Problem description

When creating a new sketch in a certain way it is not possible to deselect objects such as lines by clicking on them in the 3D view.

One exact sequence of operations to reproduce the issue:

1. Start FreeCAD. Using an almost default config this starts me off in the Start workbench
2. Ctrl+N to start a new document
3. Click the _Create Part_ button in the toolbar
4. Switch to the PartDesign workbench
5. Click the _Create sketch_ button in the toolbar
6. Click on the XY-plane in the 3D view
7. Click the _Create rectangles_ button in the toolbar and draw any rectangle
8. Press ESC to exit out of the rectangle tool
9. Click on an edge to select it
10. Click on the same edge again to deselect it. It will not work.

After exiting out of the sketch and going back in, selected edges can now be deselected by clicking on them.

Note that the sequence I described is one of multiple sequences that lead to the same issue.

### Anything else?

Rebasing points to 3e33a91aa9fc81e9d5f4c6f99181273761ee0ab1.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adrianinsaval** [comment] 2023-05-11 16:36
Rebasing points to https://github.com/FreeCAD/FreeCAD/commit/3e33a91aa9fc81e9d5f4c6f99181273761ee0ab1

do you mean that you are running the version from hat commit or what?

your version information is incomplete as it is missing the revision and commit hash information

**Comment by dominikh** [comment] 2023-05-11 17:13
Sorry, I typoed. I meant to say that *bisecting* pointed to 3e33a91aa9fc81e9d5f4c6f99181273761ee0ab1.

Sorry about the incomplete version information; it doesn't seem able to embed that information with the way I am building it (via Nix). I was running yesterday's master branch, but the commit that seemingly causes it is much older, anyway.

**Comment by adrianinsaval** [comment] 2023-05-11 18:46
@wwmayer any clues?

**Comment by wwmayer** [comment] 2023-05-12 06:27
I can confirm the issue but it's not related to the mentioned commit.

In all versions before this commit the created sketch was not added to the Part container and that's why the issue wasn't observed. But if you slightly modify the workflow the issue can also be reproduced with v0.20 or v0.19:
1. Click the Create Part button in the toolbar
2. Switch to the PartDesign workbench
3. Create a new body. It will be added to the Part container
4. Click the Create sketch button in the toolbar
5. ...

**Comment by wwmayer** [comment] 2023-05-12 13:05
The class ViewProviderSketch has the member variables `editObjName` and `editSubName`. When editing the sketch directly after creation these names are different compared to when closing and re-enter edit mode.
In the first case the names are:
`editObjName = "Body", editSubName = "Sketch."`
In the second case the names are:
`editObjName = "Part", editSubName = "Body.Sketch."`

Because of this the function `ViewProviderSketch::isSelected` always returns false when checking whether the element "Body.Sketch.Edge1" is selected because its full name is `Part.Body.Sketch.Edge1`. Thus, it re-selects a clicked edge even if it's already selected.

`ViewProviderSketch::setEditViewer` must be further analyzed why it delivers different results in the two cases.

**Comment by wwmayer** [comment] 2023-05-12 13:25
Found it!

When editing a sketch after creation the function `PartDesignGui::setEdit` with the sketch and body objects as argument is used. This will create a Python statement like this:
`Gui.ActiveDocument.setEdit(App.ActiveDocument.Body, 0, "Sketch.")`

When editing a sketch by double-clicking on the tree item the C++ function `Gui::Document::setEdit` with the sketch view provider as argument is used.

**Closed** 2023-06-01 01:25 UTC
