### ISSUE TITLE
Draft: Saving values in input fields and copy-checkbox when the "continue" checkbox is active

### ISSUE THREAD

**Issue by kaiwas** [FreeCAD/FreeCAD#13334] opened 2024-04-06 13:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

If you need to perform an action with the "continue" parameter, a value equal to zero is useful only at the very first activation of the action (because the program cannot know the required value). But after the value has been entered, it would be more correct to save this value if the “continue” checkbox is active.
The example is quite simple. If you need to arrange (or rotate) an object by a certain step, you have to constantly re-enter the data (for example, step 1000 mm). It's very tiring.
If at some stage the step is 1000 mm. you will need to change it to another, it is not difficult to do. But the value =0 is essentially completely useless. Because copying an element in place of the original object is very rarely required. If necessary, you can simply change the value to zero.

Also, the “copy” checkbox is reset if it is activated for the “move” tool and is saved only for the “copy” tool. It is not right. If the user has activated this toggle, it should remain enabled. (exactly the opposite. If the checkbox for the “copy” tool is turned off, it should not be turned on again). This will speed up the process and won't require you to exit the tool and start another one.

Short summary. For repetitive operations, you have to do too many unnecessary steps.
For comparison, similar operations in Corel Draw. (for comparison in the speed of performing identical actions).

https://github.com/FreeCAD/FreeCAD/assets/32273833/508c8e18-4f53-42be-b8d2-fdb5b507004b

One more example. At any stage, you can change the values and get a predictable result without constantly entering values. You can quickly create hundreds of copies of an object at the desired increments.

https://github.com/FreeCAD/FreeCAD/assets/32273833/d9e9cb18-5fad-42cc-9a0b-f6fcbff94b74

### Full version info

```shell
Any Versions
```

### Subproject(s) affected?

Draft

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment] 2024-04-06 14:40
So maybe there could be a checkbox in the applicable Draft tools to keep the value.

**Comment by kaiwas** [comment] 2024-04-06 15:28
> So maybe there could be a checkbox in the applicable Draft tools to keep the value.

Yes. This could be arranged as an option. It would be especially nice if this setting was the default.
To be honest, I can’t imagine in what situation the current option might be convenient. but perhaps in some special cases it is really useful.

**Comment by kaiwas** [comment] 2024-04-06 15:45
But if we think logically, the “continue” checkbox itself implies that the user expects the action to be repeated. Any zeroing or resetting of parameters is harmful. Because in this case there is not a continuation, but a new activation of an empty action.

**Comment by Roy-043** [comment] 2024-04-06 21:25
This a duplicate of #12500.

**Closed by Roy-043** 2024-04-06 21:25 UTC
Labels: WB Draft, UI/UX, Feature, Missing: 'About' info, Missing: tested on dev version

**Comment by kaiwas** [comment] 2024-04-07 06:15
> This a duplicate of #12500.

Despite the fact that there are similarities between the topics, these are TWO DIFFERENT PROBLEMS. They solve different problems (although there are overlaps).
In the case of "repeat last action CTRL+X" anything can be used (change color, delete or something). In this case, when performing repeated steps, there is no way to change those steps because the action is always the same.
In the case of working with fields (closed topic), we simply quickly perform a certain operation when working with fields and have the opportunity to change the parameters if necessary. For example, a pitch of 1000 mm. change to 2000 mm.. after the 5th copy.

If necessary, I can record an explanatory video that will demonstrate the difference between the two topics.
