### ISSUE TITLE
Preferences: Section/Group Header not padded correctly

### ISSUE THREAD

**Issue by tibfel** [FreeCAD/FreeCAD#15701] opened 2024-07-31 05:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

In the preferences, there is an incorrect padding for group/section headers. They are not legible. I am using FreeCAD Light/Dark theme. 

![image](https://github.com/user-attachments/assets/db70dc6c-c930-4d22-a7a7-0bc34230c821)

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38375 (Git)
Build type: Release
Branch: main
Hash: fe702349e848571802c01659668cc4bee519f4c6
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Slovak/Slovakia (sk_SK)
Installed mods: 
  * SelectorToolbar
  * sheetmetal 0.4.13
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment] 2024-07-31 10:14
Duplicate of https://github.com/FreeCAD/FreeCAD/issues/15591

**Closed by maxwxyz** 2024-07-31 10:14 UTC
