### ISSUE TITLE
Acess violation - Editing sketch and spreadsheet at once

### ISSUE THREAD

**Issue by lucas-bueno777** [FreeCAD/FreeCAD#16497] opened 2024-09-13 01:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

While changing variables in a spreadsheet, I accidentally didn't close the sketch I was working on. This resulted in an access violation - I can no longer edit or delete the sketch, breaking my file.

I recreated this specific condition in a minimal file. Steps to reproduce:

1. Open the attached file.
2. Double-click the spreadsheet to open it in a new window
3. Double-click the sketch to edit it
4. Without exiting the sketch, go to the spreadsheet and add any text to any cell
5. Close (stop editing) the sketch
6. The access violation takes place
7. (Bonus) If you try to close the document window, FreeCAD crashes.

I get the following error message:
`22:17:44  pyException: Traceback (most recent call last):
  File "<string>", line 1, in <module>
<class 'OSError'>: Access violation
22:17:44  Unhandled Base::Exception caught in GUIApplication::notify.
The error message is: Access violation`

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 1.0.0RC1.38643 (Git)
Build type: Release
Branch: main
Hash: fe40748c10503eed367840239db3e0f81873e359
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Portuguese/Brazil (pt_BR)
```

### Subproject(s) affected?

Sketcher

### Anything else?

File with the example of access violation:
[Acess_violation_bug.FCStd.zip](https://github.com/user-attachments/files/16987280/Acess_violation_bug.FCStd.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xtemp09** [comment] 2024-09-13 06:34
This is a duplicate of #15918. This "access violation" is fixed in PR #16378, which is to be merged later or sooner.

**Closed** 2024-09-13 10:44 UTC
Labels: Status: Needs triage
