### ISSUE TITLE
TechDraw WB Section issue

### ISSUE THREAD

**Issue by supernaturaljoe** [FreeCAD/FreeCAD#10340] opened 2023-08-24 08:00 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Full version info

```shell
[code]
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.21.0.33668 +7 (Git)
Build type: Release
Branch: (HEAD detached at 0.21)
Hash: 41b058e2087de60dc8fef3d3e68c7d0129e13abf
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: Bulgarian/Bulgaria (bg_BG)
Installed mods: 
  * A2plus 2021.12.0
  * ArchTextures
  * Assembly4 0.50.2
  * BIM 1.0.0
  * dodo 2021.12.0
  * ExplodedAssembly
  * Help 1.0.3
  * parts_library
[/code]
```

### Subproject(s) affected?

Techdraw

### Problem description

I'm making a section view on a kitchen assembly and during that I gives me different section view than the arrow section location (screenshot attached)
Zip file attached. File to open: ASSM_Kitchen_Section_Issue. Page "изглед А" with the section issue
![RFhhT2hzRn](https://github.com/FreeCAD/FreeCAD/assets/125272836/9a3b51e5-19ce-4945-8c9c-fea2f7c6c4d6)

### Anything else?

[kitchen.zip](https://github.com/FreeCAD/FreeCAD/files/12426947/kitchen.zip)
![RFhhT2hzRn](https://github.com/FreeCAD/FreeCAD/assets/125272836/747ee482-4fee-46b7-aa7a-a8c1dab3c0cb)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by WandererFan** [comment] 2023-08-24 13:49
Although this https://forum.freecad.org/viewtopic.php?t=80362 talks about ComplexSection, it also applies to simple sections. 

The result with the current v022 code: 
![ASSM_Kitchen_Section_Issue_v022](https://github.com/FreeCAD/FreeCAD/assets/3587161/9d6a3676-1d42-472f-88ca-2baa67eddc9a)

**Comment by WandererFan** [comment] 2023-08-24 14:26
Duplicate of #10212?

**Comment by supernaturaljoe** [comment] 2023-08-25 06:34
@WandererFan I installed latest v.0.21 yesterday. I have done section of another section before but never had issues till yesterday. Maybe it's a file bug or something.

**Comment by supernaturaljoe** [comment] 2023-08-25 06:39
Thanks for the response. I'll use the original view to make sections.

**Closed** 2023-08-25 06:39 UTC
Labels: WB TechDraw
