### ISSUE TITLE
[Sketcher/SectionView tool] Display plain section rather than 3D clipping plane

### ISSUE THREAD

**Issue by bebenlebricolo** [FreeCAD/FreeCAD#18448] opened 2024-12-12 15:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Hi team, 

I've been using Sketcher for a while now and it feels that whenever I'm drawing a sketch underneath some preexisting geometry, I need to use the section tool of the sketcher.

This section tool is nice, but it's only adjusting the 3D clipping plane (it seems) and doesn't not provide enough 3D information to ease the design process and spatial representation.

Here is what it looks like today (on an elastic coupler, because it shows up the feature quite nicely) : 
![SectionRaw](https://github.com/user-attachments/assets/ce0af08c-368d-4f8b-94c1-7822e8008530)
Note that we are actually loosing quite a lot of visual details as visual lines are not recomputed with the 3D clipping plane.

And what it could look like : 

![SectionLight](https://github.com/user-attachments/assets/c1c4788a-97f5-46dc-986d-1508624e0457)

Or a darker version : 

![SectionDark](https://github.com/user-attachments/assets/49cb43c4-c7a6-4362-9941-f386341f7a32)

It requires a temporary "real" section cut to be performed, but it's really helpful to visual objects and new sketches.
Furthermore, on assemblies this is paramount to achieve easy, in-situ, precision design
Those kind of views can provide the visual details needed when designing.

Regarding the UI perspective, I suggest that section view colors can be edited in Preferences (or maybe via a right click context menu action ?).

Note : I added some extracted geometry to display that this is actually a real cut and it can be used while designing.

## Side note 2 
Something that could be nice as well would be to have sketch's UI in X-Ray mode by default (even without the section view).
That would be another feature request but I think it might be easier to develop (modal UI) than the section view. But I may probably be wrong on this one.

### Full version info

```shell
OS: Windows 11 build 22631
Architecture: x86_64
Version: 1.0.0.39109 (Git) Conda
Build type: Release
Branch: (HEAD detached at 1.0.0)
Hash: 2fcc5317fe3aee96ca73475986a577719fc78e20
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: French/France (fr_FR)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Fusion
```

### Subproject(s) affected?

Sketcher

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment] 2024-12-13 11:31
Duplicate of https://github.com/FreeCAD/FreeCAD/issues/5570

**Closed by maxwxyz** 2024-12-13 11:31 UTC
Labels: Status: Needs confirmation, Status: Needs triage
