### ISSUE TITLE
[Issue] FreeCAD crashes after clicking adaptive path for 3rd time

### ISSUE THREAD

**Issue by JakeEhrlich** [FreeCAD/FreeCAD#8365] opened 2023-02-05 21:35 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
[code]
OS: Ubuntu 20.04.5 LTS (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.20.1.
Build type: Release
Branch: unknown
Hash: 1397818c9664d158281339a84be59d3e9887f6ad
Python 3.8.10, Qt 5.12.8, Coin 4.0.0, Vtk 7.1.1, OCC 7.5.2
Locale: English/United States (en_US)
[/code]
If it helps this was from an official Ubuntu package
```

### Subproject(s) affected?

Path

### Issue description

I was just using the Path workbench and while I had the last adaptive path selected under my operations folder, I clicked adaptive path on the tool bar to add another adaptive path. FreeCAD instantly crashed leaving this backtrace

```
distance = 3.800000000000001mm    unit distance = 3.80 mm
solution count: 2
   solution 1:
      point1 -79   4.6   12.8
      point2 -79   4.6   9
      DeltaX 0
      DeltaY 0
      DeltaZ 3.800000000000001
      shape type on object1 is: Vertex
      shape type on object2 is: Vertex
   solution 2:
      point1 -79   93.65000000000001   12.8
      point2 -79   93.65000000000001   9
      DeltaX 0
      DeltaY 0
      DeltaZ 3.800000000000001
      shape type on object1 is: Vertex
      shape type on object2 is: Vertex


Failed to get shape


Failed to get shape

PathGeom.INFO: Zero working area to process. Check your selection and settings.
PathAdaptive.INFO: *** Adaptive toolpath processing started...

PathAdaptive.INFO: *** Done. Elapsed time: 0.006917 sec


Program received signal SIGSEGV, Segmentation fault.
#0  /lib/x86_64-linux-gnu/libc.so.6(+0x43090) [0x7f838aedd090]
#1  0x7f8388ee1931 in QCheckBox::event(QEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x11
#2  /usr/lib/python3/dist-packages/PySide2/QtWidgets.cpython-38-x86_64-linux-gnu.so(+0x45dd2e) [0x7f8368760d2e]
#3  /lib/x86_64-linux-gnu/libpython3.8.so.1.0(+0x2a10bd) [0x7f83895ad0bd]
#4  /lib/x86_64-linux-gnu/libpython3.8.so.1.0(+0x74d6d) [0x7f8389380d6d]
#5  /lib/x86_64-linux-gnu/libpython3.8.so.1.0(_PyEval_EvalFrameDefault+0xea8) [0x7f8389382018]
#6  /lib/x86_64-linux-gnu/libpython3.8.so.1.0(+0x8006b) [0x7f838938c06b]
#7  /lib/x86_64-linux-gnu/libpython3.8.so.1.0(+0x74d6d) [0x7f8389380d6d]
#8  /lib/x86_64-linux-gnu/libpython3.8.so.1.0(_PyEval_EvalFrameDefault+0xea8) [0x7f8389382018]
#9  /lib/x86_64-linux-gnu/libpython3.8.so.1.0(+0x8006b) [0x7f838938c06b]
#10  /lib/x86_64-linux-gnu/libpython3.8.so.1.0(_PyObject_FastCallDict+0xe7) [0x7f83895b6417]
#11  /lib/x86_64-linux-gnu/libpython3.8.so.1.0(_PyObject_Call_Prepend+0xcd) [0x7f83895b652d]
#12  /lib/x86_64-linux-gnu/libpython3.8.so.1.0(+0x243d47) [0x7f838954fd47]
#13  /lib/x86_64-linux-gnu/libpython3.8.so.1.0(+0x2491b9) [0x7f83895551b9]
#14  /lib/x86_64-linux-gnu/libpython3.8.so.1.0(_PyObject_MakeTpCall+0xab) [0x7f83895b4b2b]
#15  /lib/x86_64-linux-gnu/libpython3.8.so.1.0(+0x74df3) [0x7f8389380df3]
#16  /lib/x86_64-linux-gnu/libpython3.8.so.1.0(_PyEval_EvalFrameDefault+0x12fd) [0x7f838938246d]
#17  /lib/x86_64-linux-gnu/libpython3.8.so.1.0(_PyEval_EvalCodeWithName+0x8fb) [0x7f83894d6e4b]
#18  /lib/x86_64-linux-gnu/libpython3.8.so.1.0(_PyFunction_Vectorcall+0x94) [0x7f83895b4124]
#19  /lib/x86_64-linux-gnu/libpython3.8.so.1.0(+0x2a8d37) [0x7f83895b4d37]
#20  /lib/x86_64-linux-gnu/libpython3.8.so.1.0(PyVectorcall_Call+0x60) [0x7f83895b4840]
#21  0x7f838a2dfb2e in Gui::ViewProviderPythonFeatureImp::setEdit(int) from /usr/lib/freecad-python3/lib/libFreeCADGui.so+0x21e
#22  0x7f82efce992d in Gui::ViewProviderPythonFeatureT<PathGui::ViewProviderPath>::setEdit(int) from /usr/lib/freecad-python3/lib/PathGui.so+0x1d
#23  0x7f838a2fac08 in Gui::ViewProvider::startEditing(int) from /usr/lib/freecad-python3/lib/libFreeCADGui.so+0x18
#24  0x7f838a2e8c68 in Gui::ViewProviderDragger::startEditing(int) from /usr/lib/freecad-python3/lib/libFreeCADGui.so+0x18
#25  0x7f838a204c18 in Gui::Document::setEdit(Gui::ViewProvider*, int, char const*) from /usr/lib/freecad-python3/lib/libFreeCADGui.so+0xd48
#26  0x7f838a5f3d75 in Gui::DocumentPy::setEdit(_object*) from /usr/lib/freecad-python3/lib/libFreeCADGui.so+0xd5
#27  0x7f838a5f3f0c in Gui::DocumentPy::staticCallback_setEdit(_object*, _object*) from /usr/lib/freecad-python3/lib/libFreeCADGui.so+0x2c
#28  /lib/x86_64-linux-gnu/libpython3.8.so.1.0(+0x2a8697) [0x7f83895b4697]
#29  /lib/x86_64-linux-gnu/libpython3.8.so.1.0(_PyObject_MakeTpCall+0xab) [0x7f83895b4b2b]
#30  /lib/x86_64-linux-gnu/libpython3.8.so.1.0(+0x74df3) [0x7f8389380df3]
#31  /lib/x86_64-linux-gnu/libpython3.8.so.1.0(_PyEval_EvalFrameDefault+0x7d86) [0x7f8389388ef6]
#32  /lib/x86_64-linux-gnu/libpython3.8.so.1.0(+0x8006b) [0x7f838938c06b]
#33  /lib/x86_64-linux-gnu/libpython3.8.so.1.0(+0x74d6d) [0x7f8389380d6d]
#34  /lib/x86_64-linux-gnu/libpython3.8.so.1.0(_PyEval_EvalFrameDefault+0x12fd) [0x7f838938246d]
#35  /lib/x86_64-linux-gnu/libpython3.8.so.1.0(+0x8006b) [0x7f838938c06b]
#36  /lib/x86_64-linux-gnu/libpython3.8.so.1.0(+0x2a8e3b) [0x7f83895b4e3b]
#37  /lib/x86_64-linux-gnu/libpython3.8.so.1.0(PyVectorcall_Call+0x60) [0x7f83895b4840]
#38  /usr/lib/freecad-python3/lib/libFreeCADBase.so(PP_Run_Method+0xec) [0x7f83898f521c]
#39  0x7f838996378e in Base::InterpreterSingleton::runMethodVoid(_object*, char const*) from /usr/lib/freecad-python3/lib/libFreeCADBase.so+0x2e
#40  0x7f838a5a604b in Gui::PythonCommand::activated(int) from /usr/lib/freecad-python3/lib/libFreeCADGui.so+0xbb
#41  0x7f838a5b1d22 in Gui::Command::_invoke(int, bool) from /usr/lib/freecad-python3/lib/libFreeCADGui.so+0x212
#42  0x7f838a5b209e in Gui::Command::invoke(int, Gui::Command::TriggerSource) from /usr/lib/freecad-python3/lib/libFreeCADGui.so+0xfe
#43  0x7f83883ed1d0 in QMetaObject::activate(QObject*, int, int, void**) from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x7d0
#44  0x7f8388dd53e6 in QAction::triggered(bool) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x46
#45  0x7f8388dd7aa2 in QAction::activate(QAction::ActionEvent) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0xf2
#46  /lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x260e10) [0x7f8388ed1e10]
#47  0x7f8388ed2035 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0xe5
#48  0x7f8388fc55fe in QToolButton::mouseReleaseEvent(QMouseEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0xe
#49  0x7f8388e1e2b6 in QWidget::event(QEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x286
#50  0x7f8388fc56a8 in QToolButton::event(QEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x38
#51  0x7f8388ddba66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x86
#52  0x7f8388de5343 in QApplication::notify(QObject*, QEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x583
#53  0x7f838a5e5218 in Gui::GUIApplication::notify(QObject*, QEvent*) from /usr/lib/freecad-python3/lib/libFreeCADGui.so+0x88
#54  0x7f83883c180a in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x18a
#55  0x7f8388de4457 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x1b7
#56  /lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x1c935d) [0x7f8388e3a35d]
#57  /lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x1cc1ec) [0x7f8388e3d1ec]
#58  0x7f8388ddba66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x86
#59  0x7f8388de50f0 in QApplication::notify(QObject*, QEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x330
#60  0x7f838a5e5218 in Gui::GUIApplication::notify(QObject*, QEvent*) from /usr/lib/freecad-python3/lib/libFreeCADGui.so+0x88
#61  0x7f83883c180a in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x18a
#62  0x7f83887aa7d3 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) from /lib/x86_64-linux-gnu/libQt5Gui.so.5+0x6e3
#63  0x7f83887ac10b in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) from /lib/x86_64-linux-gnu/libQt5Gui.so.5+0x25b
#64  0x7f838878635b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /lib/x86_64-linux-gnu/libQt5Gui.so.5+0xbb
#65  /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5(+0x7932e) [0x7f838226932e]
#66  /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x27d) [0x7f838622e17d]
#67  /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x52400) [0x7f838622e400]
#68  /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x33) [0x7f838622e4a3]
#69  0x7f8388419435 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x65
#70  0x7f83883c03ab in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x12b
#71  0x7f83883c8116 in QCoreApplication::exec() from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x96
#72  0x7f838a65de0c in Gui::Application::runApplication() from /usr/lib/freecad-python3/lib/libFreeCADGui.so+0x1b6c
#73  freecad(+0x52b4) [0x556822af32b4]
#74  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f838aebe083]
#75  freecad(+0x630e) [0x556822af430e]
```

I was not able to recover the CAM work that I had lost (it wasn't much luckily).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment] 2023-02-05 21:44
Official Ubuntu FreeCAD package is broken. Please try to recreate on AppImage, Flatpak, or Snap and report back.

**Comment by sliptonic** [comment] 2023-02-22 23:08
I'm unable to reproduce this.  Without a reproducible test case, I'm closing.  Will reopen if OP can reproduce it.

**Closed by sliptonic** 2023-02-22 23:08 UTC
Labels: WB Path, packaging: Ubuntu
