### ISSUE TITLE
Add the ability to clear recent documents list

### ISSUE THREAD

**Issue by furgo16** [FreeCAD/FreeCAD#13749] opened 2024-05-01 05:15 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Sometimes the list of recent files can become cluttered, particularly if the number of files shown is set to be reasonably high. This is a feature request to provide the ability to clear that list. Potential use cases:

- The user has finished working with a multiple files project, moves on to the next project and wants a clean slate.

An example implementation from a CAD package (QCAD):
![Clear recent](https://github.com/FreeCAD/FreeCAD/assets/148809153/e1aa2ab4-d191-4c7d-bb7d-ab00691b23cc)

### Full version info

```shell
OS: Ubuntu Core 22 (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36999 (Git) Snap 1002
Build type: Release
Branch: main
Hash: ed77603af999525b65dcfc4a41337f15a052c9ef
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Installed mods: 
  * OpenTheme 2024.4.20
  * BIM 2021.12.0
  * Curves 0.6.35
  * ezydxf
  * ExplodedAssembly
  * BillOfMaterials 0.0.8.2
  * Ondsel-Lens 2024.4.16.01
  * Assembly4 0.50.12
```

### Subproject(s) affected?

Core

### Anything else?

- This issue is concerned with the first task of https://github.com/FreeCAD/FreeCAD/issues/12842. To keep things simple, it advocates for removing the entire history only. Arguably, only a small minority of users would require specific file removal from the history list, and it would add more complexity and maintenance effort to the code for only a small benefit.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment] 2024-05-01 06:57
please add the comments to https://github.com/FreeCAD/FreeCAD/issues/12842 this should be fixed together.

**Comment by maxwxyz** [comment] 2024-05-01 06:57
Duplicate of https://github.com/FreeCAD/FreeCAD/issues/12842

**Closed by maxwxyz** 2024-05-01 06:57 UTC

**Comment by furgo16** [comment] 2024-05-01 07:12
Thanks, I don't mind either way. Alternatively, the two issues on #12842 could be written as a [GitHub task list](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/about-task-lists#about-issue-task-lists), with the first one pointing to this one.
