### ISSUE TITLE
PartDesign: Pad / Extrude "to First", "to Last" not working as expected

### ISSUE THREAD

**Issue by maxwxyz** [FreeCAD/FreeCAD#11111] opened 2023-10-20 06:37 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The Part Design Pad Feature Length Attributes "up to face", "to last" and "to first" are not working as expected or like in any other CAD applications.
It seems that currently the center of the profile/sketch is projected in the normal direction of the sketch and this would result in a static dimension for the extrude length.

This can lead to problems when the center of the profile is extended and does not find a face because of a hole or a curving face as Shalmeneser pointed out [here](https://forum.freecad.org/viewtopic.php?t=81740): 
![Capture d’écran 2023-10-05 190907](https://github.com/FreeCAD/FreeCAD/assets/6246609/5af1c007-073b-492d-82da-fe44c0f679f0)

Also, the profile is extended in the pad direction and ends with a parallel face to the profile/sketch plane. 
Expected would be a behavior, where the extrude of the pad feature seamlessly join with the curved face it should be padded to like in this example of other CAD programs:
![correctextrude](https://github.com/FreeCAD/FreeCAD/assets/6246609/b8d3ccad-5e59-46d5-bde7-866d63ff5721)

Currently in FreeCAD a pad "to last" produced the following wrong result, when the outer shell face is selected:
![upto](https://github.com/FreeCAD/FreeCAD/assets/6246609/2640b61c-4046-432a-bb07-9d1a3caefbf6)
A workaround of a manual length does not work with thin and curved objects as the planar extrude would protrude or stick out of the other side and must be trimmed manually (painful on casted or molded parts).
In the example above, the pad operation with length set to "to first" or "to face" does not work at all, as the distance currently determined by the pad feature is too short to join the extruded profile with the existing geometry which would result in a multibody (error: "resulting shape is empty").

### Full version info

```shell
0.21
0.22dev
```
[code]
OS: Windows 11 build 22621
Word size of FreeCAD: 64-bit
Version: 0.21.1.33668 +26 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.1)
Hash: f6708547a9bb3f71a4aaade12109f511a72c207c
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: German/Germany (de_DE)
Installed mods: 
   * CfdOF 1.24.5
  * Curves 0.6.13
   * OpenDark 2023.10.9
  * sheetmetal 0.3.1
[/code]

### Subproject(s) affected?

PartDesign

### Anything else?

https://forum.freecad.org/viewtopic.php?t=81740

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FlachyJoe** [comment] 2023-10-20 07:24
Related to #7189 and it's partial fix #9743.

**Comment by adrianinsaval** [comment] 2023-10-20 07:46
> Currently in FreeCAD a pad "to last" produced the following wrong result, when the outer shell face is selected:

can you provide an example file for this? I cannot reproduce this, and please always provide full version information
![image](https://github.com/FreeCAD/FreeCAD/assets/36372335/3093d83b-7fc8-4206-bcf8-138dcfdf2e99)

**Comment by adrianinsaval** [comment] 2023-10-20 07:52
you are right that the centroid of the profile is projected in the pad direction, but this is only used to find which face should be used as limit of the pad, then that faced is passed on to occt to use as limit, we do not pass just a length value calculated from this intersection.

**Comment by maxwxyz** [comment] 2023-10-20 09:56
Please try to edit the length dimension in the attached file to anything like to face, to last or to first. None will work in 0.22dev.
[extrude.zip](https://github.com/FreeCAD/FreeCAD/files/13052916/extrude.zip)

**Comment by FlachyJoe** [comment] 2023-10-20 11:11
@maxwxyz UpToFace is working as expected on my side. Only UpToFirst and UpToLast fail because of the looking for face along the CoG normal.
As I point before it's an OCC limitation and I can't see any workaround.

@adrianinsaval :+1: I never see the Pad stops perpendicularly at the length of the intersection.

**Comment by adrianinsaval** [comment] 2023-10-20 11:54
> Please try to edit the length dimension in the attached file to anything like to face, to last or to first. None will work in 0.22dev. [extrude.zip](https://github.com/FreeCAD/FreeCAD/files/13052916/extrude.zip)

here the problem seems to be that the profile is outside of the bounds of the limiting face, and we currently have no way of selecting more than one face as limiting surface (and I'm not sure if occt supports this)

**Comment by maxwxyz** [comment] 2023-10-20 12:25
in the attached example it is working with three faces (angled to each other and the second with a fillet to a third face) 
![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/aa546c0b-a8a6-49a6-b0c6-99de4b71a21e)
[multiplefaces.zip](https://github.com/FreeCAD/FreeCAD/files/13054172/multiplefaces.zip)

**Comment by maxwxyz** [comment] 2023-10-20 12:27
> @maxwxyz UpToFace is working as expected on my side. Only UpToFirst and UpToLast fail because of the looking for face along the CoG normal. As I point before it's an OCC limitation and I can't see any workaround.

Up to face is not working on either available faces for me in current 0.22 weekly build and stable 0.21.1: 
![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/48f6217d-b1b9-4a8c-ab38-e16ce346a690)
How and what was your result?

**Comment by luzpaz** [comment] 2023-10-20 13:13
Folks, please use full [About](https://wiki.freecad.org/About) info. It saves a lot of time and confusion.

**Comment by maxwxyz** [comment] 2023-10-20 18:19
> > @maxwxyz UpToFace is working as expected on my side. Only UpToFirst and UpToLast fail because of the looking for face along the CoG normal. As I point before it's an OCC limitation and I can't see any workaround.
> 
> Up to face is not working on either available faces for me in current 0.22 weekly build and stable 0.21.1: ![grafik](https://user-images.githubusercontent.com/6246609/276929775-48f6217d-b1b9-4a8c-ab38-e16ce346a690.png) How and what was your result?

see below, not working and also in current stable.
[code]
OS: Windows 11 build 22621
Word size of FreeCAD: 64-bit
Version: 0.21.1.33668 +26 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.1)
Hash: f6708547a9bb3f71a4aaade12109f511a72c207c
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: German/Germany (de_DE)
Installed mods: 
  * CfdOF 1.24.5
  * Curves 0.6.13
  * OpenDark 2023.10.9
  * sheetmetal 0.3.1
[/code]

**Comment by FlachyJoe** [comment] 2023-10-20 18:28
@maxwxyz please provide the failing file.

**Comment by maxwxyz** [comment] 2023-10-20 18:29
It is right there: https://github.com/FreeCAD/FreeCAD/issues/11111#issuecomment-1772432318

**Comment by adrianinsaval** [comment] 2023-10-20 18:39
> in the attached example it is working with three faces (angled to each other and the second with a fillet to a third face) 

in this case the center plane face is used as bound when doing up to first and plane faces are extended as infinite planes for the operations, by chance that gives the expected result here. If you do up to face and select the other plane face you'll see that is used as an infinite plane as the limit:
![image](https://github.com/FreeCAD/FreeCAD/assets/36372335/a2f48e95-f544-45c4-abf9-23c34418924d)
that doesn't work if you select the curved face though:
![image](https://github.com/FreeCAD/FreeCAD/assets/36372335/90febe6e-09b2-4240-af1d-6b7d4350f99d)

the problem in these cases is that round faces cannot be reliably extended to cover the full profile like we can for plane faces

**Comment by maxwxyz** [comment] 2023-10-20 18:41
Attached is another one failing in stable FC. Try changing the last Pad Feature to either "to first", "to last" or "to face". In all cases it is either an error or protruding through the object:
[example2.zip](https://github.com/FreeCAD/FreeCAD/files/13057597/example2.zip)
![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/3f8e1bb1-bdc8-4c1a-addd-4c236dac88ac)
![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/3d57c253-8bbf-485b-bf1f-7d19e10d0fcf)
![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/e9e13b70-d07c-4d89-912f-d30c0cc0e6c2)
and here I have tried all different faces:
![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/b1d8b6b8-ee4c-4210-adde-4adf972a8e9f)
![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/ee2860c0-42aa-4c85-9598-40c21b81f99c)
![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/4e1213f7-7cba-42b0-823a-a15d16b8ba23)

The right result should look in all cases like this:
![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/24b7100b-9736-4523-9ecb-ee7f18e45ea4)

In this case I have just removed the protruding material, but in complex parts (castings/molded parts) no chance to always remove all excess material for each pad operation.




[code]
OS: Windows 11 build 22621
Word size of FreeCAD: 64-bit
Version: 0.21.1.33668 +26 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.1)
Hash: f6708547a9bb3f71a4aaade12109f511a72c207c
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: German/Germany (de_DE)
Installed mods: 
  * 3DfindIT 1.2.0
  * 3D_Printing_Tools
  * BIM 2021.12.0
  * CfdOF 1.24.5
  * CurvedShapes 1.0.4
  * Curves 0.6.13
  * Defeaturing 1.2.1
  * fasteners 0.4.66
  * freecad.gears 1.0.0
  * freecad_metal_workbench
  * OpenDark 2023.10.9
  * sheetmetal 0.3.1
  * Silk 0.1.5
[/code]

**Comment by adrianinsaval** [comment] 2023-10-20 18:47
to solve this first we have to check if occt supports passing multiple surfaces as limit for prism generation. If yes, then we need to work on improving the "upToFace" selection mechanism (which seriously needs improvement anyways) to allow selecting multiple faces and lastly we need to change the up to last/first algorithms, perhaps we can project lines from each vertex in the profile instead of just from the centroid.

**Comment by maxwxyz** [comment] 2023-10-20 18:56
Attached another simple example where every operation is generating an error.

[example3.zip](https://github.com/FreeCAD/FreeCAD/files/13057737/example3.zip)

Try adjusting the distance below either to first, to last or to face.
![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/c756668d-b480-411e-aaa5-66350764a447)

**Comment by FlachyJoe** [comment] 2023-10-21 08:37
If the projection is partially out of the selected face it fails and it's a normal behavior. Where should the prism stop?

In _example3_ you can't select a face which totally constrain the prism end. At the opposite this is valid as the projection is contained by the selected face:
![image](https://github.com/FreeCAD/FreeCAD/assets/10371513/29df6115-1ab8-46c1-b5c2-99663742bb54)

@maxwxyz All the problems you reports are related to the impossibility to select multiple faces and by the GoC projection to find the limit.
The multiple faces selection need a further dig into OCC sources. I plan it.

Proposed workaround to Pad to multiple faces:

1. Split the sketch in a way each part is projected in a unique face.
2. Pad each part to the subsequent face.

**Comment by maxwxyz** [comment] 2023-10-21 08:40
If there is a solution this would not only help the Pad feature but maybe also hole, pocket, loft and especially to find the "end" for https://github.com/FreeCAD/FreeCAD/issues/10538

Is it possible to somehow project the geometry of the profile in the direction of the extrude onto the body / other remaining geometry and loft to between those two to create a workaround (or maybe as an idea for the pad feature)?

**Comment by FlachyJoe** [comment] 2023-10-21 11:23
About CoG projection the possibilities are:

- Improve OCC to use vertexes instead of CoG -> an OCC issue should be opened
- Create our own algorithm to make the prism -> low level shape manipulation is not in the FreeCAD aims and it require sufficient acknowledgment.
- Imagine a workaround to use the OCC implementation as is -> only needs time and tests.

About multiple faces as end:

- Check for OCC capabilities and implement the faces selection
- Automatize the workaround proposed above and implement the faces selection

Note: this report confuses two problems, the already known Issue with CoG projection and the Feature Request for multiple faces selection.
IMHO this should be closed in favor of #7189 reopening (only partially fixed) and a clear new FR.

**Comment by maxwxyz** [comment] 2023-10-21 12:18
I cannot reopen https://github.com/FreeCAD/FreeCAD/issues/7189, can you describe the clear new FR with the differences which should already be fixed?

**Comment by FlachyJoe** [comment] 2023-10-21 12:51
@maxwxyz FR done with #11135

@AjinkyaDahale can reopen #7189

**Comment by adrianinsaval** [comment] 2023-10-22 02:35
> Improve OCC to use vertexes instead of CoG -> an OCC issue should be opened

I could be wrong but I think this is a FreeCAD problem not an OCC problem

**Comment by adrianinsaval** [comment] 2023-10-22 02:36
> @AjinkyaDahale can reopen #7189

I think it's better to create a new issue for the cog problem, that one is really about faces that are intersected twice

**Comment by FlachyJoe** [comment] 2023-10-22 09:58
> I could be wrong but I think this is a FreeCAD problem not an OCC problem

The concerned OCC code was linked yet: https://github.com/FreeCAD/FreeCAD/pull/9743#issuecomment-1583202179

**Comment by luzpaz** [comment] 2024-12-09 12:30
@FlachyJoe do you mind checking what's left to do here?

**Comment by FlachyJoe** [comment] 2024-12-10 21:13
We still can't pad to a closed cylinder internal because the prism stops at the first frontier but I think all the other problems was solved.
![image](https://github.com/user-attachments/assets/1f079797-af18-4a1c-9844-0e436b92d2e7)

**Comment by luzpaz** [comment] 2024-12-11 08:34
> We still can't pad a hollow profile to a closed cylinder internal because the prism stops at the first frontier  

Should we close this and open a separate ticket for that ?

**Comment by FlachyJoe** [comment] 2024-12-11 18:07
Yes, a clean new issue is a good option.

**Comment by luzpaz** [comment] 2024-12-11 20:11
Closing as complete. Remaining issue has been split into a new ticket 
* #18436

**Closed by luzpaz** 2024-12-11 20:11 UTC
Labels: Type: Bug, Mod: Part Design
