### ISSUE TITLE
Added measurement mode in the measurement tool

### ISSUE THREAD

**Issue by Roberto8303** [FreeCAD/FreeCAD#16624] opened 2024-09-18 06:24 UTC
### Original PR

https://github.com/FreeCAD/FreeCAD/issues/new?assignees=&labels=needs+triage%2Cbackport&projects=&template=BACKPORT_REQUEST.yml&title=%5BBackport%5D+

### Description and Justification

Hi, I would like to propose the idea of ​​adding a measurement function on three axes between two objects such as non-aligned holes. 
With the current measuring tool it is not possible to know the minimum distance or center of the holes.
I attach some example photos.
Could we add a function called for example orthogonal measurement which takes the three axes between the two holes? both center of holes and minimum distance between holes.
![460524920_1684212755712592_8770246560181655572_n](https://github.com/user-attachments/assets/cd3000c0-6042-471d-bf96-ff951d7896f5)
![458779309_493267753601925_4495200864569861537_n](https://github.com/user-attachments/assets/b0277139-37d4-4ea1-b41f-8e8fc9656c45)
![458603124_541905265177412_8084989716840612449_n](https://github.com/user-attachments/assets/af95feef-3538-4d88-89a2-1c77dc81e09a)

**Comment by maxwxyz** [comment] 2024-09-18 07:13
Please use the issue template. This is a duplicate of https://github.com/FreeCAD/FreeCAD/issues/13708

**Closed by maxwxyz** 2024-09-18 07:13 UTC
