### ISSUE TITLE
[Problem] Language change doesn't work properly in start page

### ISSUE THREAD

**Issue by TuomasLattila** [FreeCAD/FreeCAD#9996] opened 2023-07-25 15:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
[code]
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.20.2.29603 (Git)
Build type: Release
Branch: releases/FreeCAD-0-20
Hash: 930dd9a76203a3260b1e6256c70c1c3cad8c5cb8
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: Finnish/Finland (fi_FI)
[/code]
```

### Subproject(s) affected?

None

### Problem description

Test case:

1. Open freeCAD
2. Go to Edit > Preferences ... > Change language
3. Change language to different one
4. Press OK

Now the language should be changed, but actually some of the text (Start page) are written still in the previous language. 

To get the Start page texts also in the right language you must restart freeCAD.

### Anything else?

<img width="377" alt="BugFreeCAD" src="https://github.com/FreeCAD/FreeCAD/assets/120785942/93ccfdcb-c253-4913-9337-606237a3b995">

Here is example picture where the language has been changed from Finnish to English.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by grubertechnic** [comment] 2023-07-25 17:49
IF the translation is the issue, there is an extra tracker for it, see https://github.com/FreeCAD/FreeCAD-translations/issues. Also maybe @kaktusus know more about that.

**Comment by kaktusus** [comment] 2023-07-25 18:17
I tested on new builds

```
OS: Debian GNU/Linux trixie/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33636 (Git) AppImage
Build type: Release
Branch: master
Hash: a5e350ad469f4030b46baa6fd3d1770375f1ddd1
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
Installed mods: 
...
```

After changing the language in the preferences, the start page is not refreshed and the tab labels are not reloaded.
Therefore changing the language is not 100% effective.
A restart of FreeCAD is necessary in this case.

Please move this ticket to FreeCAD    /    FreeCAD-translations.

**Comment by TuomasLattila** [comment] 2023-07-25 19:02
Yes, that is the bug that I tried to show in this ticket. It does the translation when restarted.

What is the best way to move this ticket? I have never done it before.

**Comment by kaktusus** [comment] 2023-07-25 19:12
This must be done by a person with higher authority.

I recommend you to use the developer version. There are a lot of improvements there and you have access to new features.

You can download it here:

https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds#Asets
You download, unzip, and run it
and enjoy the freshness. :grinning: 
Nothing needs to be installed.

A developer once asked me to report such cases when a reboot is required to update the GUI language. But I forget who it was. :cry:

**Comment by TuomasLattila** [comment] 2023-07-25 19:26
Ah ok, I don't have the authority. Thanks for the recommendation :+1:

**Comment by benj5378** [comment] 2023-07-26 10:37
Is this really a bug or just a technical limitation of how FreeCAD works? I believe it would take an extrodinary workload and add uneeded complexity to make sure all gui is reloaded without restarting FreeCAD... when one can just restart FreeCAD

**Comment by kaktusus** [comment] 2023-07-26 10:46
I don't consider it a bug. :wink: 
But as I mentioned earlier some developer asked me to catch such "phenomena". Apparently he thinks otherwise.
As for me, it is worth moving it to the translation corner.

**Comment by yorikvanhavre** [comment] 2023-07-26 12:43
There is a way to do this relatively simply, on [Start workbench Activated/Deactivated](https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/Start/InitGui.py#L43C37-L43C37), an observer must be added/removed to the language property, that triggers a reload. Something like this (not tested):

```python
class observer:
    def onChange(self, paramGrp, param):
        if(param == "Language"):
            mw = FreeCADGui.getMainWindow()
            if mw:
                # close all opened start page instances
                title = QtGui.QApplication.translate("Workbench","Start page")
                mdi = mw.findChild(QtGui.QMdiArea)
                if mdi:
                    for mdichild in mdi.children():
                        for subw in mdichild.findChildren(QtGui.QMdiSubWindow):
                            if subw.windowTitle() == title:
                                subw.close()
            FreeCADGui.runCommand("Start_StartPage")

p = FreeCAD.ParamGet("User parameter:BaseApp/Preferences/General")
p.Attach(observer())
```
This observer must then be removed on Start WB deactivation, so it does not weight on normal FreeCAD operation

**Comment by yorikvanhavre** [comment] 2023-07-26 12:45
It is not exactly a translation issue, though... Isn't it better to leave it here?

**Comment by kaktusus** [comment] 2023-07-26 12:49
Such topics were discussed in that corner .... well unless I misremembered.

do as you think  :wink:

**Comment by kaktusus** [comment] 2023-07-26 12:52
Yorik please add a wiki editor account for a girl from the Polish team.
Sorry to bring this up here but it's important to me.

**Comment by yorikvanhavre** [comment] 2023-07-26 13:24
which girl?

**Comment by kaktusus** [comment] 2023-07-26 13:33
Kat_ka

**Comment by yorikvanhavre** [comment] 2023-07-27 12:31
Done!

**Comment by luzpaz** [comment] 2023-07-28 00:00
#6704

**Comment by kaktusus** [comment] 2023-07-28 05:02
Thanks luzpaz for finding this topic.

**Comment by kaktusus** [comment] 2023-07-28 05:18
However, I misremembered the conversation about the necessary restart was going on in the main branch.

**Comment by yorikvanhavre** [comment] 2023-07-28 09:30
I think we can add the above change nevertheless, but it's better to do it after 0.21 as it could introduce new bugs.

**Comment by luzpaz** [comment] 2023-08-04 02:01
@yorikvanhavre should this be assigned to you ?

**Comment by yorikvanhavre** [comment] 2023-08-07 12:58
Yes!

**Comment by superbonaci** [comment] 2023-11-10 20:01
Same happens to cube that describes the views: TOP, LEFT, FRONT, etc. A restart is required to match the language of the words in the faces the language in the menu:

![FREECAD-BAD-TRANSLATION](https://github.com/FreeCAD/FreeCAD/assets/8339596/46ac24aa-299c-43d8-b90e-d29800c34b3c)

The language has been changed from English to French but some parts are not translated until restart. Maybe just adding to preferences that needs restart would be enough:
`Preferences` - `General` - `Language (needs program restart):`

Is important to mention that the restart if for the program and not for the OS.

**Comment by kaktusus** [comment] 2023-11-10 20:32
Since this topic returns like a boomerang I will remind you of the possibility of its solution:

https://github.com/FreeCAD/FreeCAD/issues/6704#issuecomment-1716986923

:wink:

**Comment by superbonaci** [comment] 2023-11-10 22:12
> Since this topic returns like a boomerang I will remind you of the possibility of its solution:
> 
> [#6704 (comment)](https://github.com/FreeCAD/FreeCAD/issues/6704#issuecomment-1716986923)
> 
> 😉

The solution is pretty simple: mention that a program restart is required inside Settings.

**Comment by superbonaci** [comment] 2023-11-16 22:34
I think this is the line that has to be changed:
https://github.com/FreeCAD/FreeCAD/blob/main/src/Gui/PreferencePages/DlgSettingsGeneral.ui#L41

Also the drop list has to be moved to give way for translations:

![Preferences_General_Tab_General](https://github.com/FreeCAD/FreeCAD/assets/8339596/72a107ab-5eb8-4774-a175-40b92512eb9d)

I could submit a pull request if somebody tells me which code to change.

**Comment by yorikvanhavre** [comment] 2023-11-20 11:18
I just had a look at this, the start page is apparently well reloaded when the language changes. The problem is that the strings in https://github.com/FreeCAD/FreeCAD/blob/main/src/Mod/Start/StartPage/TranslationTexts.py get translated once, when the module is imported, at FreeCAD startup, and not anymore after that.

The solution here is probably to:

1. Place all translated strings into some retranslate() function
2. One needs to decide how StartPage.py will access these strings. Either they are global variables and get updated by the retranslate function, or the StartPage module needs to fetch them differently
3. Run that function everytime the start page is generated

**Comment by kaktusus** [comment] 2023-11-20 11:33
I know that the developers decided to make such functionality possible. But as you can see there are more problems with it than benefits. In addition there is no one to take care of it.

Is this really necessary? Maybe the information about the need to reload the program will be enough?

**Comment by yorikvanhavre** [comment] 2023-11-20 11:54
The problem is that adding a message is just a cosmetic workaround, and it will need an extra commit to remove it afterwards. It's better to fix things correctly right from the start.

I will do this when I have a moment, but my time is limited right now

**Comment by luzpaz** [comment] 2023-11-27 12:19
Can y'all test yorik's fix ?

**Comment by superbonaci** [comment] 2023-11-27 17:00
> Allow dynamic translation of start page -
can't compile due to https://github.com/FreeCAD/FreeCAD/issues/11438

**Comment by superbonaci** [comment] 2023-11-27 17:00
> Can y'all test yorik's fix ?

Can't compile due to https://github.com/FreeCAD/FreeCAD/issues/11438

**Closed** 2023-11-27 17:06 UTC
Labels: Translation, WB Start

**Comment by kaktusus** [comment] 2023-11-28 04:27
It agrees the cube wall captions after switching the language were not refreshed correctly.

**Comment by kaktusus** [comment] 2023-11-28 04:36
https://crowdin.com/translate/freecad/549/en-pl#6613111
https://crowdin.com/translate/freecad/549/en-pl#6613109
https://crowdin.com/translate/freecad/549/en-pl#6613107
https://crowdin.com/translate/freecad/549/en-pl#6613105
https://crowdin.com/translate/freecad/549/en-pl#6613103
https://crowdin.com/translate/freecad/549/en-pl#6613101

**Comment by superbonaci** [comment] 2023-11-28 15:28
> https://crowdin.com/translate/freecad/549/en-pl#6613111 https://crowdin.com/translate/freecad/549/en-pl#6613109 https://crowdin.com/translate/freecad/549/en-pl#6613107 https://crowdin.com/translate/freecad/549/en-pl#6613105 https://crowdin.com/translate/freecad/549/en-pl#6613103 https://crowdin.com/translate/freecad/549/en-pl#6613101

It requires an account to see the content.

**Comment by superbonaci** [comment] 2023-11-28 16:08
Thanks but not needed. Is there where translations are made?

**Comment by kaktusus** [comment] 2023-11-28 16:20
Yes, we do translations on the Crowdin platform. That's where these links come from.
here's how it looks:

![obraz](https://github.com/FreeCAD/FreeCAD/assets/39754351/8cd7677f-966c-4309-94a0-a3c97693e246)
