### ISSUE TITLE
Renaming elements in the DataTab can make Expressions invalid

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5721] opened 2022-02-07 16:37 UTC
Issue imported from https://tracker.freecad.org/view.php?id=3151

* **Reporter:** chrisb
* **Date submitted:** 8/8/2017
* **FreeCAD version:** 0.17
* **Category:** Bug
* **Status:** assigned
* **Tags:** spreadsheet

# Original report text

There is a [forum topic](https://forum.freecadweb.org/viewtopic.php?p=185800#p185800) containing a model and screenshot.

In that Model I use Expressions
- I have given the name "R" to the radius of Sketch
- I use it in the second sketch, dividing it by 2 and give that small radius the name "r"
- I pad the second sketch and use an expression Sketch001.r for the length.

Next I want to rename the Sketch001 to something more sensible, let's say "SketchInner"

I go to the Data Tab and delete "001". The problem is, that on every keystroke the name is set - to be seen in the python console. So there is a point where both sketches have the same name. I add "Inner" and leave the input field. I had expected that the second pad would break, but the second sketch breaks as well, because instead of "Sketch.R" it uses now "SketchI.R". The renaming mechanism inserts the first "I" of "Inner".

# Other bug information

* **Priority:** low
* **Severity:** minor
* **Category:** Bug
* **OS: MacOS 11**
* **Platform:** Macbook
* **Updated:** 2/6/2021

**Comment by adrianinsaval** [comment] 2022-03-10 17:19
I can't reproduce this issue in master, seems to be fixed

**Comment by adrianinsaval** [comment] 2022-03-11 01:46
OP (chrisb) confirmed it's fixed in the forum. Issue can be closed

**Comment by luzpaz** [comment] 2022-03-11 02:41
Thx! Closing

**Closed by luzpaz** 2022-03-11 02:41 UTC
Labels: Bug, WB PartDesign
