### ISSUE TITLE
TechDraw: Line Width doesn't work for Views

### ISSUE THREAD

**Issue by ajohn77** [FreeCAD/FreeCAD#13471] opened 2024-04-15 09:19 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

No change visible after changing the "Line Width" of the View in TechDraw.
The dimensions "line width" work as expected on the other hand.

When exported to PDF, the line width seems very thin too, rendering it unusable for practical purposes.

Also the "Line Width Group" set in Preferences [TD->Annotation] makes no change, the new view is created with proper Line Width (according to properties->Data->LineWith), but it still displays inappropriate thin line.

### Full version info

```shell
[code]
OS: Ubuntu 22.04.4 LTS (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.2)
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.10.12, Qt 5.15.3, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: English/United States (en_US)
[/code]
```

### Subproject(s) affected?

Techdraw

### Anything else?

example project : [line_width_bug.zip](https://github.com/FreeCAD/FreeCAD/files/14976519/line_width_bug.zip)

![line_width_screenshot](https://github.com/FreeCAD/FreeCAD/assets/132054827/dcd433a4-f6e6-4921-8a18-6c01a9bdec8a)

exported PDF:  [line_width.pdf](https://github.com/FreeCAD/FreeCAD/files/14976580/line_width.pdf)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by WandererFan** [comment] 2024-04-15 17:18
Changing the Line Group in preferences only applies the default to new views.  Once the view has been created, the values in the the View tab are the ones to change. 

Changing the values works here with:

OS: Linux Mint 20.3 (X-Cinnamon/cinnamon)
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0.21.2)
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.6.3
Locale: English/Canada (en_CA)
Installed mods: 
  * BOLTSFC 2022.11.5
  * sheetmetal 0.2.63
  * fasteners 0.4.56
  * FreeCAD_Electric
  * freecad.gears 1.0.0
  * Curves 0.6.29
  * Assembly4 0.50.9
  * A2plus 0.4.64

**Comment by ajohn77** [comment] 2024-04-17 12:28
**It seems this is obviously issue of PPA version.**

I can confirm that "the same" 0.21.2 version works when downloaded as AppImage, but from PPA it doesn't:

**Not working for me:**
[code]
OS: Ubuntu 22.04.4 LTS (KDE/plasma)
Word size of FreeCAD: 64-bit
**Version: 0.21.2.33771 (Git)**
Build type: Release
Branch: (HEAD detached at 0.21.2)
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.10.12, Qt 5.15.3, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: English/United States (en_US)
[/code]

**Works normally:**
[code]
OS: Ubuntu 22.04.4 LTS (KDE/plasma)
Word size of FreeCAD: 64-bit
**Version: 0.21.2.33771 (Git) AppImage**
Build type: Release
Branch: (HEAD detached at 0.21.2)
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.6.3
Locale: English/United States (en_US)
[/code]

The behavior is still the same - no visible reaction to attribute Line Width in TechDraw.

**Comment by luzpaz** [comment] 2024-04-17 13:05
Is it just me or does the PPA not show `PPA` in the 'About' in ?

**Comment by WandererFan** [comment] 2024-05-17 19:32
Isn't this a duplicate of #6698?

**Comment by adrianinsaval** [comment] 2024-07-21 19:20
I assume this means that the issue is present only on the stable ppa, is the daily ppa affected?

**Comment by luzpaz** [comment] 2024-08-27 17:05
@ajohn77 can you test the daily PPA ?

**Comment by softlab** [comment] 2024-09-12 14:22
Freecad RC1,  Kubuntu 22.04. Daily ppa:freecad-maintainers/freecad-daily),  Viruald box VM
![1](https://github.com/user-attachments/assets/a667dc75-07b7-4f3d-9a90-98b7aceab376)
Export looks good. 

BTW, could you set the default collor of objects into added  views to white

**Comment by WandererFan** [comment] 2024-09-21 15:25
<<BTW, could you set the default collor of objects into added views to white>>

I don't know where the change to blue (turquoise?) for the default face colour came from, but you should be able to set it back to white on the Colors tab of Preferences.

![ColorsTab_FaceColor](https://github.com/user-attachments/assets/c6bc8b37-4577-4273-a39b-0702f6ba37a7)

**Comment by WandererFan** [comment] 2024-10-19 13:35
The default turquoise colour has been corrected.  

The ppa issue is covered here: https://github.com/FreeCAD/FreeCAD/issues/6698

**Closed** 2024-10-19 13:38 UTC
Labels: Mod: TechDraw, Packaging: PPA, Status: Needs test on dev version
