### ISSUE TITLE
Sketcher: Zoomed Out view measurements draw line over text

### ISSUE THREAD

**Issue by samohd** [FreeCAD/FreeCAD#16204] opened 2024-09-02 01:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

This is a minor visual issue. When the below shown measurement is zoomed in, it looks as expected (left image), zoomed out to one scroll wheel jump before it's bad (center image), zoomed further a line extends out that crosses out the measurement (right image). I don't see any intentional reason for this behavior.

![FreeCAD_ZoomSize](https://github.com/user-attachments/assets/9c3d72f7-5eba-465c-aa52-89fbc5385bab)

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38555 (Git)
Build type: Release
Branch: main
Hash: 73cb5bafe0c32c178d9b594a6ca03124483d305f
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment] 2024-09-02 05:25
Duplicate of https://github.com/FreeCAD/FreeCAD/issues/13432

**Closed by maxwxyz** 2024-09-02 05:25 UTC
Labels: Status: Needs triage
