### ISSUE TITLE
Will the Sketch section feature come?

### ISSUE THREAD

**Issue by sedatkrn** [FreeCAD/FreeCAD#16184] opened 2024-09-01 07:15 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

"A development proposal for being able to take reference lines and points from any drawing section taken from a 3D created object."
![Ekran görüntüsü 2024-09-01 101921](https://github.com/user-attachments/assets/f9c9c032-4f49-4e71-958b-b1f75ebeaed7)

### Full version info

```shell
After creating an object, we take sketch planes from different regions to perform certain operations and add new shapes. However, we are unable to add the reference geometries of some intersection regions to our sketches on these planes. On this topic, 'Zheng Lei (realthunder)' has developed very useful features in his own FreeCAD branch, and adding these features to the main FreeCAD would be very beneficial.

For more details, please check the forum.
https://forum.freecad.org/viewtopic.php?p=776096#p776096
```

### Subproject(s) affected?

PartDesign

### Anything else?

https://forum.freecad.org/download/file.php?id=272607
https://forum.freecad.org/download/file.php?id=272606

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment] 2024-09-01 07:22
@sedatkrn PLease use a concise title and description, the problem is not clear

**Comment by maxwxyz** [comment] 2024-09-01 07:24
Duplicate of https://github.com/FreeCAD/FreeCAD/issues/12670

**Closed by maxwxyz** 2024-09-01 07:24 UTC
Labels: Status: Needs feedback
