### ISSUE TITLE
[Problem] Cloning a rounded rectangle does not preserve constraints

### ISSUE THREAD

**Issue by cnc50** [FreeCAD/FreeCAD#7997] opened 2022-12-09 09:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```
version 20.1 - 29410
```

### Subproject(s) affected?

None

### Issue description

Tried to clone a rectangle with rounded edges from the menu in scetcher workbench. Doesn`t work, if I change the width or height from the original rectangle. Only changes in radius work.

[clone rounded rectangle.zip](https://github.com/FreeCAD/FreeCAD/files/10193291/clone.rounded.rectangle.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adiazubierna** [comment] 2022-12-11 19:40
I could reproduce your issue with the version 0.20.1.29410

First I tried with your file and then I create a new one from scratch. According to the documentation, all the constrains in the clone should change when the constrains of the original rectangle are changed.

**Comment by chennes** [comment] 2022-12-18 00:01
I cannot reproduce in 0.21_dev: when I clone I get perfectly matching constraints. Can you retest with the latest development version?
```
[code]
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.21.0.31337 +1 (Git)
Build type: Release
Branch: addonManagerExtractInstaller
Hash: 430d8600603c764e44b7a33ff19a15dd8507cd35
Python 3.8.6+, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.5.3
Locale: English/United States (en_US)
```

**Comment by cnc50** [comment] 2022-12-18 10:33
I found out  to be very careful of selecting the item ( including all
necessary constraints)  which should be cloned.
Must take a closer look.
Thanks a lot.


Am So., 18. Dez. 2022 um 01:01 Uhr schrieb Chris Hennes <
***@***.***>:

**Comment by luzpaz** [comment] 2022-12-29 18:05
@cnc50 ping

**Comment by luzpaz** [comment] 2023-01-08 14:14
@cnc50 please follow-up testing on the development build https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds

**Comment by cnc50** [comment] 2023-01-08 14:21
Thanks a lot.
What is the difference between py38 and py310 7z-file?

Am So., 8. Jan. 2023 um 15:14 Uhr schrieb luzpaz ***@***.***>:

**Comment by luzpaz** [comment] 2023-01-08 14:23
@cnc50 one is built against python v3.8 and the other python v3.10

**Comment by cnc50** [comment] 2023-01-08 14:27
Thanks

Am So., 8. Jan. 2023 um 15:23 Uhr schrieb luzpaz ***@***.***>:

**Comment by luzpaz** [comment] 2023-01-19 16:51
@cnc50 ping

**Comment by luzpaz** [comment] 2023-11-26 16:38
@cnc50 ping

**Comment by maxwxyz** [comment] 2024-03-24 11:35
I'll close this as the new tool was merged and there was no further feedback.

**Closed by maxwxyz** 2024-03-24 11:35 UTC
Labels: WB Sketcher, Missing: feedback
