### ISSUE TITLE
Trim of ellipse creates invalid constraints

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6100] opened 2022-02-07 20:33 UTC
Issue imported from https://tracker.freecad.org/view.php?id=4419

* **Reporter:** chrisb
* **Date submitted:** 8/18/2020
* **FreeCAD version:** 
* **Category:** Bug
* **Status:** assigned
* **Tags:** 

# Original report text

As the title says, trim of ellipse creates invalid constraints, sometimes sort of unattended by the solver.
See [german forum post](https://forum.freecadweb.org/viewtopic.php?f=3&t=49517) and
[forum post](https://forum.freecadweb.org/viewtopic.php?f=3&t=49517).

# FreeCAD Info

```
OS: macOS High Sierra (10.13)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.22246 (Git)
Build type: Release
Branch: master
Hash: abd18ff88f7682e9b1160c36bb785b14a33473ef
Python version: 3.8.5
Qt version: 5.12.5
Coin version: 4.0.0
OCC version: 7.4.0
Locale: C/Default (C)

```

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Bug
* **Updated:** 2/6/2021

**Comment by maxwxyz** [comment] 2024-05-28 19:33
Cannot reproduce either, the blog post is also 4 years old. Closing this.

**Closed by maxwxyz** 2024-05-28 19:33 UTC
Labels: Bug, WB Sketcher
