### ISSUE TITLE
[Feature] Clipping plane to show the cut parts as a solid object, not just the surfaces

### ISSUE THREAD

**Issue by czinehuba** [FreeCAD/FreeCAD#11044] opened 2023-10-14 21:06 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

It is difficult to see the cross-section with the clipping plane tool. 
As per the forum discussion https://forum.freecad.org/viewtopic.php?t=81772, I'm opening this feature request. It would be a nice addition to add this from RT's branch or an alternative solution.

It is a lot clearer to see the parts in an assembly, thus makes the design process less error prone. Please see the comparison.

Assembly in FreeCAD 
![Screenshot from 2023-10-14 22-04-56](https://github.com/FreeCAD/FreeCAD/assets/48809015/58e723e6-7f11-441e-92c0-ba3bf65b4578)

Assembly in Link branch
![Screenshot from 2023-10-14 21-45-42](https://github.com/FreeCAD/FreeCAD/assets/48809015/ca73cfe6-6680-495d-88d5-259c06eabdbd)

Thank you.

### Full version info

```shell
[code]
OS: Ubuntu Core 20 (GNOME/gnome)
Word size of FreeCAD: 64-bit
Version: 0.21.1.33668 +26 (Git) Snap 759
Build type: Release
Branch: tag: 0.21.1
Hash: f6708547a9bb3f71a4aaade12109f511a72c207c
Python 3.8.10, Qt 5.15.7, Coin 4.0.0, Vtk 7.1.1, OCC 7.6.3
Locale: English/United Kingdom (en_GB)
Installed mods: 
  * 3DfindIT 1.2.0
  * fasteners 0.4.66
  * lattice2 1.0.0
  * sheetmetal 0.3.1
  * QuickMeasure 2022.10.28
  * freecad.gears 1.0.0
[/code]
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adrianinsaval** [comment] 2023-10-14 22:06
duplicate of #5570

**Closed by adrianinsaval** 2023-10-14 22:06 UTC
