### ISSUE TITLE
[GUI] Request: add python accessible progress display mechanism

### ISSUE THREAD

**Issue by FlachyJoe** [FreeCAD/FreeCAD#18243] opened 2024-12-02 11:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

We could improve user experience by showing the progress of algorithms. OCC can report such information and it's commonly easy to compute it in time consuming macros.

Thus a unique place is required to show these progresses.

@FreeCAD/design-working-group will decide the gui but IMHO QtCreator is a good example to follow.
![image](https://github.com/user-attachments/assets/d80031d4-b540-48b4-b97c-d6cbadc83a1a)

### Full version info

```shell
1.1.0devR39393
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment] 2024-12-02 12:06
Duplicate of https://github.com/FreeCAD/FreeCAD/issues/5566 ?

**Closed** 2024-12-02 12:21 UTC
Labels: Status: Needs confirmation, Status: Needs triage
