### ISSUE TITLE
Spreadsheet and TD views cannot be undocked

### ISSUE THREAD

**Issue by prokoudine** [FreeCAD/FreeCAD#14856] opened 2024-06-22 17:18 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

This request is coming from a user, confirmed on any recent version of FreeCAD.

Currently it is impossible to undock a spreadsheet or a techdraw page to place them on a different physical monitor in a dual-screen setup. It would be great to be able to do that though.

### Full version info

```shell
OS: Ubuntu 24.04 LTS (ubuntu:GNOME/ubuntu-xorg)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37709 (Git) AppImage
Build type: Release
Branch: main
Hash: dd816a635ccacc39f29b1761c6ccfed21a90b646
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * ExtremeProDark 2.9.0
  * DynamicData 2.60.0
  * Assembly4 0.50.6
  * cura_engine
  * ExplodedAssembly
  * fasteners 0.5.21
  * sheetmetal 0.4.11
  * A2plus 0.4.61
  * BIM021 2021.12.0
  * OpenTheme 2024.4.20
  * Render 2023.12.28
  * Rocket 3.2.4
  * Curves 0.6.21
  * freecad.gears 1.2.0
  * Assembly3 0.12.0
  * boltsfc 2022.11.5
  * OpenDark 2023.12.17
  * dodo 1.0.0
  * Ondsel-Lens 2024.4.16.01
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Syres916** [comment] 2024-06-22 18:43
This looks very much like a duplicate of https://github.com/FreeCAD/FreeCAD/issues/14545

**Closed** 2024-06-22 18:51 UTC
