### ISSUE TITLE
Origin planes appear solid with anti-aliasing: Line smoothing

### ISSUE THREAD

**Issue by EmEiBee** [FreeCAD/FreeCAD#15114] opened 2024-07-02 12:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Task window on the right (picture 1):
New -> Part -> Sketch -> Massive, unreadable axis areas (middle), also no selection options for the drawing area (right).

Task window on the left (picture 2):
New -> Part -> Sketch -> Massive, unreadable axis areas (middle), but selection options for the drawing area are there (left).

Fun fact: In the morning all was ok and I haven't changed anything meanwhile (except catching one bug after an other...). I just was with the dogs for an hour...

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37928 (Git)
Build type: Release
Branch: main
Hash: e7699b531eba4bee262f7214699f07b96f66ba7b
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
```

### Subproject(s) affected?

None

### Anything else?

![img-2024-07-02-13-59-22](https://github.com/FreeCAD/FreeCAD/assets/30090331/1f335e20-0ab1-40b0-8b73-0a5914c0a664)

![img-2024-07-02-14-04-39](https://github.com/FreeCAD/FreeCAD/assets/30090331/d9189c5f-9b50-4adf-94ca-3bed228f0291)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by EmEiBee** [comment] 2024-07-02 14:17
Update:

Same with `FreeCAD_weekly-builds-38001-conda-Windows-x86_64-py311`

**Comment by maxwxyz** [comment] 2024-07-03 06:45
I cannot reproduce on Windows

**Comment by maxwxyz** [comment] 2024-07-03 07:12
Ah I can reproduce now! It displays normally until I hover over the planes for the first time. Then it is broken. Also only with Smooth Lines setting.
The bug is also present in the current stable 0.21.2

**Comment by EmEiBee** [comment] 2024-07-03 07:14
> The bug is also present in the current stable 0.21.2

hmmm... I never noticed this in 21.2...

**Comment by maxwxyz** [comment] 2024-07-03 07:15
And it also affects the normal origin planes. I've updated the title.

**Comment by maxwxyz** [comment] 2024-07-03 07:16
Duplicate of https://github.com/FreeCAD/FreeCAD/issues/11444

**Closed by maxwxyz** 2024-07-03 07:16 UTC
Labels: Bug, Core, UI/UX
