### ISSUE TITLE
Measurment: Can't measure center to center

### ISSUE THREAD

**Issue by macdroid53** [FreeCAD/FreeCAD#15916] opened 2024-08-17 14:35 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Can't measure the center to center distance of circles/shafts, or center to edge, etc

### Full version info

```shell
0.22
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment] 2024-08-17 18:49
Also kind of a duplicate of https://github.com/FreeCAD/FreeCAD/issues/13708
Maybe add all relevant modes there in the comment.

**Closed by maxwxyz** 2024-08-17 18:49 UTC
Labels: Type: Feature, Topic: Measurement
